<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html>
<head>
<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
<script type="text/javascript" src="/js/common.js"></script>
<script src="/js/validate.js" type="text/javascript"></script>
<script src="/js/validate.js" type="text/javascript"></script>
<script type="text/javascript" src=<?php echo $this->baseUrl()."/js/Json/Base64.js"?>></script>
<script type="text/javascript" src=<?php echo $this->baseUrl()."/js/Json/json2.js"?>></script>
<script type="text/javascript" src=<?php echo $this->baseUrl()."/js/Json/json_parse.js"?>></script>
<script type="text/javascript" src=<?php echo $this->baseUrl()."/js/Ajax/AjaxEngine.js"?>></script>
<link rel="stylesheet" type="text/css" href="/styles/general.css" />
</head>
<body style="background-color:transparent">
<form  name=frmUpload enctype="multipart/form-data" action="/hscv/phienbanduthao/save" method="post" 
target= <?php 
if($this->is_new==0) echo '"PBDuThao_CapNhatFrame'.$this->idPBDuthao.'"' ; 
if($this->is_new==1) echo '"PBDuThao_ThemMoiDiv'. $this->idDuthao .'"';
?> >
<input type="hidden" name="MAX_FILE_SIZE" value="100000000" />
	
	<div class="required">
	<label>Phiên bản</label>
	<input type="text" name="version" value="<?php echo $this->sophienban ?>">
	<span class="box_erro_area" id="ERRversion"></span>
	</div>	
	<div class=clr></div>
	<div class="required">
	<label>File đính kèm</label>
	<input name="uploadedfile" type="file" />
	</div>        
        <?php
        if($this->user->ISLEADER == 1 || TRUE ){
        ?>
		<div>
		<label nowrap class=key>Tệp đính kèm (Chữ kí số)</label>
			<input type="button"  id="_SignOfflineFile"  onclick="exc_sign_file('', '', '');return false;" value="Chọn file ký số"/>
			<input type='hidden' name='idFileCKS' id="idFileCKS" value="0"/>
			<span id=filename></span>
	</div>
	<script language="javascript" type="text/javascript" src="/js/vgca/base64.js"></script>
	<script language="javascript" type="text/javascript" src="/js/vgca/vgcaplugin.js"></script>
	<script>
		function SignFileCallBack(rv) {
                // alert(1)
                var received_msg = JSON.parse(rv);
            
                if (received_msg.Status == 0) {
                    document.frmUpload.submit();

					// console.log(received_msg)
                    
                } else {
                   // document.frmUpload.submit();
                //console.log(received_msg);
                    //document.getElementById("_signature").value = received_msg.Message;
                }
            }
		function exc_sign_file(sessionid, filename, metadata) {
                var prms = {};
				<?php $myAuth = Zend_Registry::get('auth');?>
				var id_user = <?php echo $myAuth->getIdentity()->ID_U?>;
				// console.log(data)	
                prms["SessionId"] = sessionid;
                prms["FileName"] = filename;
                prms["MetaData"] = metadata;
                prms["FileUploadHandler"] = '<?php echo  (isset($_SERVER['HTTPS']) ? "https" : "http") . "://$_SERVER[HTTP_HOST]";?>/chukyso/chukyso/saveduthao?idHSCV=<?php echo $this->idHSCV?>&version=<?php echo $this->sophienban ?>&idPBDuthao=<?php echo $this->idPBDuthao?>&isTemp=1&year=<?php echo $this->year?>&idOldFile=<?php echo $this->idOldFile?>&type=2&vgca=1&idDuthao=<?php echo $this->idDuthao?>';
                
                var json_prms = JSON.stringify(prms);
                 console.log(json_prms);
              
                vgca_sign_file(json_prms, SignFileCallBack);
                // alert(vgca_sign_file);
            }
		
	</script>
        <?php
        }
        ?>	
        <div>
	<label>Chú thích </label>
	<textarea name="comment" cols="50" rows="5" id="comment"></textarea>
	</div>
	
	<!-- 
	<table class="admintable" >
		<tr>
			<td nowrap class=key>Phiên bản</td>
			<td><input type="text" name="version" value="<?php //echo $this->version ?>"> </td>
		</tr>
		<tr> <td colspan=2><span class="box_erro_area" id="ERRversion"></span> </td></tr>
		<tr>
			<td nowrap class=key>File đính kèm</td>
			<td ><input name="uploadedfile" type="file" /> </td>
		</tr>
	</table>  -->
	<input type="hidden" name="idHSCV" value=<?php echo $this->idHSCV?> >
	<input type="hidden" name="idObject" value=<?php echo $this->idPBDuthao?> >
	<input type="hidden" name="idPBDuthao" value=<?php echo $this->idPBDuthao?> >
	<input type="hidden" name="isTemp" value=<?php if($this->is_new==0) echo 0 ; if($this->is_new==1) echo 1; //cho id tam?>>
	<input type="hidden" name="year" value=<?php echo $this->year?>>
	<input type="hidden" name="idOldFile" value=<?php echo $this->idOldFile?>>
	<input type="hidden" name="type" value=2 >
	<input type="hidden" name="idDuthao" value=<?php echo $this->idDuthao?>>
</form> 

<a  onclick="checkFormDataAndSubmit(); return false;
			//window.parent.document.getElementById('PBDuThao_CapNhatFrame<?php echo $this->idPBDuthao ?>').style.display = 'none';
			//var version = document.frmUpload.version =
			//window.parent.document.sendRequestToServer('/hscv/phienbanduthao/update?version=&year=<?php echo $this->year?>&idPBDuthao=<?php $this->idPBDuthao ?>');
			//window.parent.loadDivFromUrl('PhienBanDiv<?php echo $this->idDuthao ?>','/hscv/PhienBanDuThao?year=<?php echo $this->year?>&idDuthao=<?php echo $this->idDuthao?>',1);
" href="#"  >[ Lưu ]</a>
<?php if($this->is_new==1){ ?>
<a href="#" onclick="window.parent.document.getElementById('PBDuThao_ThemMoiDiv<?php echo $this->idDuthao ?>').style.display = 'none';">[ Hủy ]</a>
<?php }else{ ?>
<a href="javascript:;" onclick="window.parent.document.getElementById('PBDuThao_CapNhatFrame<?php echo $this->idPBDuthao ?>').style.display = 'none';">[ Hủy ]</a>
<?php } ?>
<p id=lasttext></p>
</body>
</html>
<script>

function checkFormDataAndSubmit(){

	var str = "Bạn phải nhập tên phiên bản";
	var strerr = validateInput("required",document.frmUpload.version,str);
	if(!strerr){
		document.frmUpload.version.focus();
		return false;
	}
	str="Tên phiên bản có định dạng xx.xx (ví dụ 2.0) ";
	strerr = validateInput("dec",document.frmUpload.version,str);
	if(!strerr){
		document.frmUpload.version.focus();
		return false;
	}
	
	document.frmUpload.submit();
	return true;
}

function SaveButtonClick(){
	
}
<?php if($this->is_new==1){ ?>
var iframeElement = window.parent.document.getElementById('PBDuThao_ThemMoiDiv<?php echo $this->idDuthao ?>');
iframeElement.style.height = ""+(document.getElementById("lasttext").offsetTop)+"px";
iframeElement.width = "100%"; 
<?php }else{ ?>
var iframeElement = window.parent.document.getElementById('PBDuThao_CapNhatFrame<?php echo $this->idPBDuthao ?>');
iframeElement.style.height = ""+(document.getElementById("lasttext").offsetTop)+"px";
iframeElement.width = "100%"; 
<?php } ?>

</script>