<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html>
<head>
<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
<script type="text/javascript" src="/js/common.js"></script>
<script src="/js/validate.js" type="text/javascript"></script>
<script src="/js/validate.js" type="text/javascript"></script>
<script type="text/javascript" src="/js/ajax/AjaxEngine.js"></script>
<link rel="stylesheet" type="text/css" href="/styles/general.css" />
</head>
<body style="background-color:transparent">
<form name="frm" method=post action="/hscv/phoihop/addphanhoi">
<table class=admintable>
	<tr>
		<td class=key>
			Nội dung phản hồi
		</td>
		<td>
			<textarea rows="4" cols="100" name="NOIDUNG"></textarea>
		</td>
	</tr>    
	<tr>
		<td colspan="2">
			<input type="button" value="Phản hồi" onclick="document.frm.submit();" />
		</td>
	</tr>
</table>
<input type=hidden name=idgopy value="<?=$this->idgopy?>">
<input type=hidden name=idhscv value="<?=$this->idhscv?>">
<input type=hidden name=code value="save">
</form>
</body>
</html>
