<?php
$this->dojo()->enable();
?>
<script type="text/javascript">
var ischecked = 0;
</script>
<form action="/qtht/Danhmucnhomnguoidung/Save" enctype="multipart/form-data" name="frm"  method="post">
<fieldset>
	<div class="required clearfix">
		<label><?php echo MSG11009005 ?>(*)</label>
		<input type=text class=inputbox name=NAME value="<?=$this->data->NAME?>" class="inputText" size="50" maxlength="100">
    	<span class="box_erro_area" id="ERRNAME">
        	
        </span>
	</div>
	<div class="required clearfix">
		<label>Thứ tự(*)</label>
		<input type=text class=inputbox name=ORDERS value="<?=$this->data->ORDERS?>" class="inputText" size="2" maxlength="2">
    	<span class="box_erro_area" id="ERRORDERS">
        	
        </span>
	</div>
	<div class="clr"></div>
	<div class="optional">
		<label for="ID_U_DAIDIEN" id="lblTextIput">Người đại diện</label>
		<select name=ID_U_DAIDIEN>
			<option value=0>--Chọn người đại diện--</option>
<?php
	foreach($this->user as $useritem){
?>			<option value=<?=$useritem['ID_U']?>><?=$useritem['NAME']?></option>
<?php
	}
?>
		</select>
		<script>
			document.frm.ID_U_DAIDIEN.value='<?=$this->data->ID_U_DAIDIEN?>';
		</script>
        <span class="box_erro_area" id="ERRID_U_DAIDIEN">
        </span>
	</div>
	<div class="clr"></div>
	<div class="required clearfix">
		<label>Có sử dụng</label>
		<input size=50 name="ACTIVE" class="inputCheckbox" type="checkbox" id="ACTIVE" value="1" <?php echo $this->data->ACTIVE==1?"checked":""; ?> />
	</div>
	<div class="clr"></div>
    <div class="optional clearfix">
    	<span>(*) Bắt buộc nhập liệu.</span>
    </div>
 
</fieldset>
<fieldset>
	<legend>Danh sách người trong nhóm</legend>
		<table class="adminlist">
            <thead>
                <tr>
                    <th nowrap width=60>STT</th>
                    <th width=100%>Họ và Tên </th>
               </tr>
            </thead>
		</table>
		<?php 
            foreach($this->datagr as $it_dep){
        ?>
        <div id="content-pane" class="pane-sliders">
            <div class="panel">
				 <h3 class="jpane-toggler title">
                 <span><?php echo 'Phòng Ban : '.$it_dep["DEP_NAME"]?></span>
                </h3>
                 <div class="jpane-slider content">
                    <table class="adminlist">
                        
                        <tbody>
                            <?php
                            $stt=0;
                            $i=0;
                           
                            foreach ($it_dep as $row ){
                           		if((int)$row["ID_U"]){
								$stt++;
                            ?>
                                    <tr class="row<?php echo $i; ?>">
                                        <td nowrap width=30 align="right"><?php echo $stt ?></td>
                                        <td nowrap width=30 align="center">
                                            <input type=checkbox name=SEL_EMP[] value='<?php echo $row["ID_U"] ?>' <?php if($row['SEL'] == 1) echo 'checked' ?> onclick=OnChangeCheck()>
                                        </td>
                                        <td width=100%>
                                            <? echo htmlspecialchars($row["FIRSTNAME"].' '.$row["LASTNAME"]) ?>
                                        </td>
                                                                                
                                    </tr>
                            <?php
                                $i = (-1+$i)*-1;
                            }}
                            ?>	
                        </tbody>
                    </table>
                </div>
            </div>
        </div>
	<?php }?>
       
</fieldset>
<input type=hidden name=ID_G value="<?php echo $this->data->ID_G; ?>">
<input type=hidden name=page value="<?php echo $this->page; ?>">
<input type=hidden name=limit value="<?php echo $this->limit; ?>">
<input type=hidden name=search value="<?php echo $this->search; ?>">
<input type=hidden name=filter_object value="<?php echo $this->filter_object; ?>">
</form>

<script>
    function SaveButtonClick(){
        var err = true;
        err = err & validateInput("req",document.frm.NAME,"<?php echo ERR11009003 ?>");
        err = err & err==true?validateInput("maxlen=50",document.frm.NAME,"<?php echo ERR11009004 ?>"):false;
        if(err==true){
            document.frm.submit();
        }
    }
    function BackButtonClick(){
        document.frm.action = "/qtht/Danhmucnhomnguoidung";
        document.frm.submit();
    }
	function OnChangeCheck(){
		ischecked = 1;
	}
</script>