<form id="containerID" action="/qtht/DanhMucCongViecNoiBo/save" method="post" enctype="multipart/form-data" name="datacdform" >
<fieldset>
	<div style="float: right;">
             Trường có dấu <font color="red">*</font> là bắt buộc nhập
	</div>
     
	<div class="required clearfix">
		<label>Tên<font color="red">*</font></label>
        <input type="text" name="name" maxlength="128" value="<?php echo htmlspecialchars($this->namebefore);?>" class="inputText" size="10" >
    	<span class="box_erro_area" id="ERRname"></span>
	</div>
        <div class="required clearfix">
        <label>Hạn xử lý</label>                       
        <input type="text" name="HANXULY" value="<?php echo htmlspecialchars($this->hanxulybefore);?>" size="10" > 
        <input type="radio" name="TYPEHANXULY" value=8 <?php if($this->typehanxulybefore ==8) echo " checked " ?> /> Giờ
        <input type="radio" name="TYPEHANXULY" value=1 <?php if($this->typehanxulybefore ==1) echo " checked " ?> /> Ngày
        <span class="box_erro_area" id="ERRHANXULY"></span>
	</div>
	
	<div class="required clearfix">
		<label>Đã được sử dụng</label>
        <?php
            if($this->activeselect == 1){
                echo '<input type="checkbox" value=1 class="inputCheckbox" name="active" checked=checked>';
            }
            else {
                echo '<input type="checkbox" value=1 class="inputCheckbox" name="active">';
            }
        ?>
	</div>
</fieldset>
<input type=hidden name="InputIDDMNB" value=<?php echo $this->id?> >
<input type=hidden name="limit" value=<?php echo $this->limit?> >
<input type=hidden name="filter_object" value=<?php echo $this->filter_object?> >
<input type=hidden name="search" value=<?php echo $this->search?> >
<input type=hidden name="page" value=<?php echo $this->page?> >
</form>
<script>
function checkFormData(){
	var str = "Bạn phải nhập tên danh mục công việc nội bộ";
	var strerr = validateInput("required",document.datacdform.name,str);
	if(!strerr){
		document.datacdform.name.focus();
		return false;
	}
	str="Tên danh mục công việc nội bộ không được quá 128 ký tự";
	strerr = validateInput("maxlen=128",document.datacdform.name,str);
	if(!strerr){		
		document.datacdform.name.focus();
		return false;
	}	  
		document.datacdform.submit();

}



function SaveButtonClick(){
    checkFormData();
}

function BackButtonClick(){
	document.datacdform.action = '/qtht/danhmuccongviecnoibo/index';
	document.datacdform.submit();
}

</script>