<script type="text/javascript" src="/js/validate.js"></script>
<script type="text/javascript" src="/js/Ajax/AjaxEngine.js"></script>
<script type="text/javascript" src="/js/autocomplete.js"></script>
<script type="text/javascript" src="/js/json/json_parse.js"></script>
<form id="containerID" action="/taphscv/thumuc/save" method="post" enctype="multipart/form-data" name="frm" >
<table>
    <tr>
	   <td> <font color="Blue">Tên thư mục</font></td>
	   <td>
	       <div class="required clearfix">		
             <input type="text" name="name" maxlength="128" value="<?php echo htmlspecialchars($this->namebefore);?>" class="inputText" size="10" >
    	     <span class="box_erro_area" id="ERRname"></span>
	       </div>
	  </td>
  </tr>  
   <tr>
   <td> <font color="Blue">Thuộc thư mục cha </font></td>
   <td>
	 <select name="choiceLVCha" >
	<option value="1">Không có thư mục cha</option>
	<?php 
		//in ra cac gia tri cua combobox
		$count = count($this->data);		
		for($i = 0 ; $i<$count  ;$i++){
			if($this->data[$i]["ID_THUMUC"] != $this->id && $this->data[$i]["ID_THUMUC_PARENT"] != $this->id)
			echo '<option value='.$this->data[$i]["ID_THUMUC"].'>'.htmlspecialchars(str_repeat("--",$this->data[$i]["LEVEL"]-1).$this->data[$i]["NAME"]). '</option>';
		}
	?>   		
	</select>
	<script>
		document.frm.choiceLVCha.value ="<?=$this->ID_THUMUC_PARENT?>";
		
	</script>
	</td>			
  </tr>  
  </tr>  
   <tr>
   <td> <font color="Blue">Độ quan trọng</font></td>
   <td>
	 <select name="choiceDoQuanTrong" >
	<option value="0" selected>Bình thường</option>		
	<option value="1">Quan trọng</option>		
	<option value="2">Rất quan trọng</option>				
	</select>
	<script>
		document.frm.choiceDoQuanTrong.value ="<?=$this->DOQUANTRONG?>";
		
	</script>
	</td>			
  </tr> 
  <tr>
	  <td> <font color="Blue">Đã được sử dụng</font></td>
	  <td>
	<div class="required clearfix">
		
        <?php
            if($this->activeselect == 1){
                echo '<input type="checkbox" value=1  class="inputCheckbox" name="active" checked=checked>';
            }
            else {
                echo '<input type="checkbox" value=1  class="inputCheckbox" name="active">';
            }
        ?>
	</div>
	</td>
	</tr>
</table>
<input type=hidden name="InputidTHUMUC" value=<?php echo $this->id?> >
<input type=hidden name="limit" value=<?php echo $this->limit?> >
<input type=hidden name="filter_object" value=<?php echo $this->filter_object?> >
<input type=hidden name="search" value=<?php echo $this->search?> >
<input type=hidden name="page" value=<?php echo $this->page?> >
</form>
<script>

function checkFormData(){
	var str = "Bạn phải nhập tên thư mục văn bản";
	var strerr = validateInput("required",document.frm.name,str);
	if(!strerr){
		document.frm.name.focus();
		return false;
	}
	str="Tên thư mục không được quá 128 ký tự";
	strerr = validateInput("maxlen=128",document.frm.name,str);
	if(!strerr){
		
		document.frm.name.focus();
		return false;
	}
  
	return true;
}

function SaveButtonClick(){
	
	if(checkFormData())
		document.frm.submit();
}

function BackButtonClick(){
	document.frm.action = '/taphscv/thumuc/index';
	document.frm.submit();
}

</script>