<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html>
<head>
<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
<script type="text/javascript" src="/js/common.js"></script>
<script src="/js/validate.js" type="text/javascript"></script>
<script src="/js/validate.js" type="text/javascript"></script>
<script type="text/javascript" src=<?php echo $this->baseUrl()."/js/Json/Base64.js"?>></script>
<script type="text/javascript" src=<?php echo $this->baseUrl()."/js/Json/json2.js"?>></script>
<script type="text/javascript" src=<?php echo $this->baseUrl()."/js/Json/json_parse.js"?>></script>
<script type="text/javascript" src=<?php echo $this->baseUrl()."/js/Ajax/AjaxEngine.js"?>></script>
<link rel="stylesheet" type="text/css" href="/styles/general.css" />
<link rel=Stylesheet href=stylesheet.css>
</head>
<body style="background-color:transparent">

    <? $num = count($this->data); 

       if ($num>0) {?>
    <br>
    <div style="color: blue; font-weight: bold">
        SỐ LƯỢNG VĂN BẢN ĐẾN CÓ TRONG DANH SÁCH : <?=$num?>
    </div>
    <br>
    <? } ?>
    
    
<table class=adminlist width="100%" >
 <thead>
 	<tr>
	    <th nowrap rowspan=2>STT</th> 
 		<th nowrap rowspan=2>Ký Hiệu VB</th>
		<th nowrap rowspan=2>Trích yếu VB</th>
 		<th  rowspan=2>Loại VB</th>
 		<th  rowspan=2 style="text-align:center">Cơ quan ban hành</th>
 		<th  rowspan=2 >Ngày ban hành</th>
		<th  rowspan=2 >Ngày đến</th>
		<th  rowspan=2 >Kết quả xử lý</th>
		<th  rowspan=2 >Gửi liên thông</th>
		<th  rowspan=2 >Có file đính kèm</th>
		<th  rowspan=2 >Dòng luân chuyển</th>
		<th  rowspan=2 >Người lưu kết thúc</th>
		<th  rowspan=2 >Hình thức lưu</th>
		<th  rowspan=2 >Trạng Thái</th>
		<th  rowspan=2 >Số Văn Bản</th>
 		<th  rowspan=2 >Ghi chú</th>
		<!--<th  rowspan=2>Ghi chú</th> -->
 	</tr>

 </thead>
 <tbody>
<?php require_once 'qtht/models/LoaiVanBanModel.php';
require_once 'qtht/models/CoquanModel.php'; 
require_once 'qtht/models/DepartmentsModel.php';
require_once 'qtht/models/UsersModel.php';
?>
<?php $nguoixuly ; $phongban; $stt=1; 
$num = count($this->data);
foreach($this->data as $row){ 
	
             
 //dem so cot gion nhau
 //if($stt == 1 || $row['ID_HSCV'] != $this->data[$stt-2]['ID_HSCV']){
 $ten= VanbandenreportModel::getNguoiXuly();
 ?>
	
	<tr>
     <td  align="center" ><?=$stt?></td> 
	<?php  {?>
 	<td width="5%" valign=top ><?=$row["SOKYHIEU"]?></td>
	<?php } ?>
     <?php  {?>
 	<td  width="10%" valign=top ><?= $row["TRICHYEU"] ?></td>
	<?php } ?>
     <?php {?>
	<td width="5%" align="center" valign=top > <?php echo LoaiVanBanModel::getArrNameById($row["ID_LVB"]) ?></td>
    <?php } ?>
 	<td width="7%"  valign=top ><?php echo $row["COQUANBANHANH_TEXT"] ?></td>
 	<td width="4%"  valign=top ><?php echo QLVBDHCommon::MysqlDateToVnDate($row["NGAYBANHANH"]) ?></td>
	<?php  {?>
	<td  valign=top ><?php echo QLVBDHCommon::MysqlDateToVnDate($row["NGAYDEN"]) ?></td>
 	<?php } ?>
 	<?php  {?>
	<td valign=top width="10%">
	<?php 
	if($row["ID_HSCV"] != ""){		
		$arr_file_maso = explode(",",$row["FILE_MASO"]);	
         foreach($arr_file_maso as $arr_file_maso_item){
		 
		    if($arr_file_maso_item){
				$arr_maso = explode('~', $arr_file_maso_item);
				if($arr_maso[0] != "")
				{
					echo "<a href='/hscv/File/download?year=".$row['NAM']."&maso=".$arr_maso[0]."'>".$arr_maso[1]." - (".$arr_maso[2].")<br/>";	
				} else {
					echo $arr_maso[1]."<br/>";	
				}
		    } else {
				echo $row["KQ_DEXUAT"];
			}	
		}				
		}
	?>
	</td>
	<?php } ?>
 	<?php  {?>
	<td width="5%" align="center"  ><?php if ($row['IS_LIENTHONG'] ==1) {
		echo "Có";
	}
	else echo "Không"; ?></td>
 	<?php } ?>
	<?php {?>
	<td  width="5%" align="center"  ><?php if(!empty($row['TEP_DINHKEM'])){echo "Có";}else{echo "Không";} ?></td>
 	<?php } ?>
	<!--<td nowrap valign=top rowspan=<?php echo $d ?>><?php echo LoaiVanBanModel::getArrNameById($row["ID_LVB"]) ?></td>
 	<td nowrap valign=top rowspan=<?php echo $d ?>><?php echo UsersModel::getEmloyeeNameByIdUser($row["NGUOITAO"]) ?></td>-->
   <!--	<td nowrap ><i><?php echo $row["SOBAN"] ?></i></td>-->  
   	<?php  {?>
 	<td valign="top" width="18%">
 	<i><?php 
 	if($row["IS_KHONGXULY"] == 1)
 		echo "Văn bản không xử lý";
 	else{ 	
            $xl= WFEngine::GetProcessLogByObjectId((int)$row['ID_HSCV']);
            // echo "<pre>";print_r($xl[0]['EMPNCNAME']);
            $rowsend = $xl[0]['EMPNCNAME'];
            for($j=0;$j<count($xl);$j++){
                if($j==10){
	                $rowsend .="<br/>" ;
	                $rowsend .=" <br> " ;
	                $rowsend .= $xl[$j]['EMPNCNAME'];

                }else{
                    if($rowsend != $xl[$j]['EMPNNNAME'])
                    {
                		// echo "<pre>";print_r($xl[$j]);
                        $rowsend .=" <br> " ;
                        if($xl[$j]["ID_U_EXECUTE"]>0 && $xl[$j]["ID_U_EXECUTE"]!=$xl[$j]["ID_U_NC"]){
                            $rowsend .= "(". $xl[$j]["EMPEXNAME"]." chuyển giúp) <br>" ;
                        }
                        if($xl[$j]['NAME'] == "Chuyển xử lý")
                              $rowsend .= "<font color=blue>";
                        $rowsend .= $xl[$j]['EMPNNNAME']."<br/>";
                        
                        
                        if($xl[$j]['NAME'] == "Chuyển xử lý" )
                          	$rowsend .= "</font>";
                          

                        $rowsend .= "[".$xl[$j]['NAME']." &ndash; ".date('d/m/Y', strtotime($xl[$j]['DATESEND']))."]";
                    }
                }
            }
            $rowsend .=" <br> " ;
            //$rowsend .= $xl[$j-1]['EMPNNNAME'];
						
            ?>
            <i> <?					
                echo $rowsend;
            ?></i> 
            
            <?php
          
	} 
	?>
 		
 	</i></td>
	
 	<?php } ?>
 	<?php  {?>
	<td width="7%" align="center"  ><?php 
		echo UsersModel::getEmloyeeNameByIdUser($row['NGUOILUUKETTHUC']);
	 ?></td>
 	<?php } ?>
 	<?php {?>
	<td  valign=top  ><?php if ($row['THEODOI']==0)
			echo 'Lưu Kết Thúc';
			if ($row['THEODOI']==1)
			echo 'Lưu Tham Khảo';
	 ?></td>
 	<?php } ?>
	<?php {?>
  	<td width="5%" nowrap valign=top ><?php
    if ( $row['NGAYHETHAN'] !='' && (int)$row['HANXULYTOANBO']>0 && $row['IS_FINISH']==0 ){
					echo QLVBDHCommon::trehantostr(QLVBDHCommon::countdateswitch(strtotime($row["NGAYHETHAN"]),null));
				}elseif($row['IS_FINISH']==1) {
					if($row['TRE']>0){
						echo "<font color=red> <i>Đã xử lý xong - Trễ hạn</i></font>";
					}else if($row['TRE']==0){
						echo "<font color=blue> <i>Đã xử lý xong - Đúng hạn</i></font>";
					}else{
						echo "<font color=blue> <i>Đã xử lý xong - Sớm hạn</i></font>";
					}
				}


   ?></td>
    <?php }?>
	<td  width="8%" valign=top   ><?php echo LoaiVanBanModel::getArrNameSVBById($row["ID_SVB"]) ?></td>
	 <td  nowrap valign=top rowspan  ><?= $row["GHICHU"] ?></td>
	</tr> 
	
	
	

<?php 
 /*	
 }
 $nguoixuly .= "<br/>".$row["U_SEND"]."(".$row["NAME_DEP"].")"."--".$row['TR_NAME'];
 //$phongban .="<br/>".$row["NAME_DEP"];
 	
 if($row['ID_HSCV'] != $this->data[$stt]['ID_HSCV']){
 	echo "<td>".$nguoixuly."</td>";
 	//echo "<td>".$phongban."</td>";
 	echo "</tr>";
 	$nguoixuly ="";
 	$phongban = "";
 }

 */
  $stt++ ; } ?>
 </tbody>
 <tfoot >
 </tfoot>
</table>
<p id=lasttext></p>
</body>
</html>
<script>
function resize(){
	try{
	var iframeElement = window.parent.document.getElementById('reportview');
	iframeElement.style.height = ""+(document.getElementById("lasttext").offsetTop)+"px";
	iframeElement.width = "100%";
	setTimeout("resize()",1000);
	}catch(ex){
 }
 }
resize();
</script>