<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html>
<head>
<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />

<style>
td{
	border-color: black;
}
th{
	border-color: black;
}
</style>

</head>
<body style="background-color:transparent">
<table  width=100% >
<tr >
  <td align=center ><?= mb_strtoupper($this->config->sys_info->unit,"utf-8") ?></td>

  <td align=center>CỘNG HÒA XÃ HỘI CHỦ
  NGHĨA VIỆT NAM</td>
 </tr>
 <tr >
  <td align=center ><b><?=mb_strtoupper($this->config->sys_info->company,"utf-8") ?></b></td>
  <td align=center >Ðộc lập - Tự do - Hạnh phúc</td>
 </tr>
 <tr >

 
  <td ></td>
  <td align=right><?=$this->config->sys_info->city?>, ngày <?=date("d")?> tháng <?=date("m")?> năm <?=date("Y")?></td>
 </tr>

 
</table>
<p align=center><b>BÁO CÁO VĂN BẢN ĐẾN 11 </b> </br>

<?php echo $this->thu;?> năm <?=QLVBDHCommon::getYear()?></p>

<table border="1" style="border: 1px solid black; border-collapse: collapse;">
 <thead>
 	<tr>
		<th nowrap rowspan=2>STT</th> 
		<?php  {?>
 		<th nowrap rowspan=2>Ký Hiệu VB</th>
		<?php } ?>
		<?php if(count($this->ngayden) >0) {?>
		<th nowrap rowspan=2>Trích yếu VB</th>
		<?php } ?>
        <?php if(count($this->coquanbh) >0) {?>
 		<th  rowspan=2>Loại VB</th>
		<?php } ?>
 		<th  rowspan=2 style="text-align:center">Cơ quan ban hành</th>
		<?php if(count($this->trichyeund) >0) {?>
 		<th  rowspan=2 >Ngày ban hành</th>
		<?php } ?>
		<th  rowspan=2 >Ngày đến</th>
		<?php  { ?>
		<th  rowspan=2 >Kết quả xử lý</th>
		<?php } ?>
		<th  rowspan=2 >Gửi liên thông</th>
		<?php  { ?>
		<th  rowspan=2 >Có file đính kèm</th>
		<?php } ?>
		
		<th  rowspan=2 >Dòng luân chuyển</th>
		
		<?php  { ?>
		<th  rowspan=2 >Người lưu kết thúc</th>
		<?php } ?>
		<?php  { ?>
		<th  rowspan=2 >Hình thức lưu</th>
		<?php } ?>	
		<th  rowspan=2 >Trạng Thái</th>
		<th  rowspan=2 >Số Văn Bản</th>
 		<th  rowspan=2 >Ghi chú</th>
 		
 	</tr>
 </thead>
 <tbody>
<?php require_once 'qtht/models/LoaiVanBanModel.php';
require_once 'qtht/models/CoquanModel.php'; 
require_once 'qtht/models/DepartmentsModel.php';
require_once 'qtht/models/UsersModel.php';
?>
<?php $nguoixuly ; $phongban; $stt=1; 
$num = count($this->data); $ten= VanbandenreportModel::getNguoiXuly();

foreach($this->data as $row){ 
 
 ?>
	
	<tr>   
	 <td  align="center" ><?=$stt?></td> 
	<?php if(count($this->soden) >0) {?>
 	<td width="5%" valign=top ><?=$row["SOKYHIEU"]?></td>
	<?php } ?>
     <?php if(count($this->ngayden) >0) {?>
 	<td  width="10%" valign=top ><?= ($row["TRICHYEU"]) ?></td>
	<?php } ?>
     <?php if(count($this->coquanbh) >0) {?>
	<td width="5%" align="center" valign=top > <?php echo LoaiVanBanModel::getArrNameById($row["ID_LVB"]) ?></td>
    <?php } ?>
 	<td width="7%"  valign=top ><?php echo $row["COQUANBANHANH_TEXT"] ?></td>
 	<td width="4%"  valign=top ><?php echo QLVBDHCommon::MysqlDateToVnDate($row["NGAYBANHANH"]) ?></td>
	<?php if(count($this->trichyeund) >0) {?>
	<td  valign=top ><?php echo QLVBDHCommon::MysqlDateToVnDate($row["NGAYDEN"]) ?></td>
 	<?php } ?>
 	<?php if(count($this->ketqua) >0) {?>
	<td valign=top width="13%">
	<?php 
	if($row["ID_HSCV"] != ""){		
		$arr_file_maso = explode(",",$row["FILE_MASO"]);	
         foreach($arr_file_maso as $arr_file_maso_item){
		 
		    if($arr_file_maso_item){
				$arr_maso = explode('~', $arr_file_maso_item);
				if($arr_maso[0] != "")
				{
					echo "<a href='/hscv/File/download?year=".$row['NAM']."&maso=".$arr_maso[0]."'>".$arr_maso[1]." - (".$arr_maso[2].")<br/>";	
				} else {
					echo $arr_maso[1]."<br/>";	
				}
		    } else {
				echo $row["KQ_DEXUAT"];
			}	
		}				
		}
	?>
	</td>
	<?php } ?>
 	<?php  {?>
	<td width="5%" valign=top  ><?php if ($row['IS_LIENTHONG'] ==1) {
		echo "Có";
	}
	else echo "Không"; ?></td>
 	<?php } ?>
	<?php {?>
	<td  width="5%" valign=top  ><?php echo "Có"; ?></td>
 	<?php } ?>
	<!--<td nowrap valign=top rowspan=<?php echo $d ?>><?php echo LoaiVanBanModel::getArrNameById($row["ID_LVB"]) ?></td>
 	<td nowrap valign=top rowspan=<?php echo $d ?>><?php echo UsersModel::getEmloyeeNameByIdUser($row["NGUOITAO"]) ?></td>-->
   <!--	<td nowrap ><i><?php echo $row["SOBAN"] ?></i></td>-->  
   	<?php if(count($this->chuyenchoai) >0) {?>
 	<td valign="top" width="12%">
 	<i><?php 
 	if($row["IS_KHONGXULY"] == 1)
 		echo "Văn bản không xử lý";
 	else{ 	
            $xl= WFEngine::GetProcessLogByObjectId((int)$row['ID_HSCV']);
            $rowsend = $xl[0]['EMPNCNAME'];
            for($j=0;$j<count($xl);$j++){
                    if($j==10){
                    $rowsend .="<br/>" ;
                    $rowsend .=" <br> " ;
                    $rowsend .= $xl[$j]['EMPNCNAME'];

                    }else{
                            if($rowsend != $xl[$j]['EMPNNNAME'])
                            {
                                    //var_dump($xl[$j]);
                                    //exit;
                                    $rowsend .=" <br> " ;
                                    if($xl[$j]["ID_U_EXECUTE"]>0 && $xl[$j]["ID_U_EXECUTE"]!=$xl[$j]["ID_U_NC"]){
                                        $rowsend .= "(". $xl[$j]["EMPEXNAME"]." chuyển giúp) <br>" ;
                                    }
                                    if($xl[$j]['NAME'] == "Chuyển xử lý")
                                          $rowsend .= "<font color=blue>";
                                    $rowsend .= $xl[$j]['EMPNNNAME'];  
                                    
                                    if($xl[$j]['NAME'] == "Chuyển xử lý" )
                                      $rowsend .= "</font>";
                            }
                    }
            }
            $rowsend .=" <br> " ;
            //$rowsend .= $xl[$j-1]['EMPNNNAME'];
						
            ?>
            <i> <?					
                    echo $rowsend;
            ?></i> 
            
            <?php
          
	} 
		 ?>
 		
 	</i></td>
	
 	<?php } ?>
 	<?php  {?>
	<td width="7%" valign=top  ><?php 
		echo UsersModel::getEmloyeeNameByIdUser($row['NGUOILUUKETTHUC']);
	 ?></td>
 	<?php } ?>
 	<?php {?>
	<td  valign=top  ><?php if ($row['THEODOI']==0)
			echo 'Lưu Kết Thúc';
			if ($row['THEODOI']==1)
			echo 'Lưu Tham Khảo';
	 ?></td>
 	<?php } ?>
	<?php {?>
  	<td width="5%" nowrap valign=top ><?php
    if ( $row['NGAYHETHAN'] != NULL && $row['NGAYHETHAN'] != '' ) {
                                $minusTime = strtotime($row['NGAYBANHANH']) - strtotime($row['NGAYHETHAN']);
                                if ( $minusTime > 0 ) {
                                    echo 'Trễ hạn';
                                }
                                if ( $minusTime == 0 ) {
                                    echo 'Đúng hạn';
                                }
                                if ( $minusTime < 0 ) {
                                    echo 'Sớm hạn';
                                }
                            }

   ?></td>
    <?php }?>
	<td  width="8%" valign=top   ><?php echo LoaiVanBanModel::getArrNameSVBById($row["ID_SVB"]) ?></td>
	 <td  nowrap valign=top rowspan  ><?= $row["GHICHU"] ?></td>
	</tr>
 

<?php  	

  $stt++ ; } ?>
 </tbody>

</table>
</body>
<script>print();</script>
</html>
