<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html>
<head>
<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />

<style>
td{
	border-color: black;
}
th{
	border-color: black;
}
</style>

</head>
<body style="background-color:transparent">
<table  width=100% >
<tr >
  <td align=center ><b><?= mb_strtoupper($this->config->sys_info->unit,"utf-8") ?></b></td>

  <td align=center><b>CỘNG HÒA XÃ HỘI CHỦ
  NGHĨA VIỆT NAM</b></td>
 </tr>
 <tr >
  <td align=center ><b><?=mb_strtoupper($this->config->sys_info->company,"utf-8") ?></b></td>
  <td align=center ><b>Ðộc lập - Tự do - Hạnh phúc</b></td>
 </tr>
 <tr >

 
  <td ></td>
  <td align=right><?=$this->config->sys_info->city?>, ngày <?=date("d")?> tháng <?=date("m")?> năm <?=date("Y")?></td>
 </tr> 
</table>

<p align=center><b>THỐNG KÊ CÔNG VIỆC CUỘC HỌP</b></p>
<p align=center><?php echo $this->thu;?></p>

<table border="1" style="border: 1px solid black; border-collapse: collapse;" width=100%>
	
	<thead>
		<tr>
                    <th>Số cuộc họp</th>
                    <th>Tổng số công việc</th>
                    <th>Đã hoàn thành</th>
                    <th>Chưa hoàn thành</th>
		</tr>
	</thead>

	<tbody>
   <td style="text-align: center">              
                    <?php
                        echo baocaocuochopModel::CountgetReportData($this->fromdate, $this->todate, 2);
                     ?>
            </td>

            <td style="text-align: center">                
                    <?php
                        echo baocaocuochopModel::CountgetReportData($this->fromdate, $this->todate, 1);
                     ?>          
            </td>

            <td style="text-align: center">                
                    <?php
                        echo baocaocuochopModel::CountgetReportData($this->fromdate, $this->todate, 3);
                     ?>               
            </td>

            <td style="text-align: center">                
                    <?php
                        echo baocaocuochopModel::CountgetReportData($this->fromdate, $this->todate, 4);
                     ?>
            </td>
	</tbody>
</table>
</body>
<script>print();</script>
</html>



















