<?php 
require_once('qtht/models/UsersModel.php');
?>
<form action="" name="frmEditDepartment"  method="<?php echo $this->form->getAttrib('method');?>">
<fieldset>
	<div style="text-align:right;width:100%">
		 Trường có dấu <font color="red">*</font> là bắt buộc nhập
	</div>
	<div align="center"><span class="box_erro_area"><?php echo $this->error; ?></span></div>
	<div class="clr"></div>
	<div class="required">
		<label id="lblTextIput">Mã phòng ban<font color="red">*</font></label>
		<?php echo $this->form->getElement('CODE_DEP');?>
    	<span class="box_erro_area">
        	<?php 
                echo QLVBDHCommon::getTopErrorMessage($this->form->getElement('CODE_DEP'));
            ?>
        </span>
	</div>

   <div class="clr"></div>	
	<div class="required">
		<label  id="lblTextIput">Cơ quan trực thuộc</label>
		<select name=ID_CQ>
			<option value=0>--Chọn cơ quan--</option>
		<?php
			  $this->cq = UsersModel::getAllcoquannoibo();
			foreach($this->cq as $cqitem){
		?>			<option value=<?=$cqitem['ID_CQ']?>><?=$cqitem['NAME']?></option>
		<?php
			}
		?>
		</select>
		<script>		
			document.frmEditDepartment.ID_CQ.value='<?=$this->ID_CQnb?>';
		</script>
        <span class="box_erro_area">		 
        </span>
	</div>



	<div class="clr"></div>
	<div class="required">
		<label id="lblTextIput">Tên phòng ban<font color="red">*</font></label>
		<?php echo $this->form->getElement('NAME');?>
    	<span class="box_erro_area">
        	<?php 
                echo QLVBDHCommon::getTopErrorMessage($this->form->getElement('NAME'));			
            ?>
        </span>
	</div>
	<div class="clr"></div>
	<div class="required">
	    <label id="lblTextkh">Ký hiệu<font color="red">*</font></label>
	    <?php echo $this->form->getElement('KYHIEU_PB');?>
	    <span class="box_erro_area" id="ERRKIHIEU_PB">
        	<?php 
                echo QLVBDHCommon::getTopErrorMessage($this->form->getElement('KYHIEU_PB'));	
            ?>
        </span>
	 </div>
        <div class="clr"></div>
	<div class="required">
	    <label id="lblphonedep">Số điện thoại phòng</label>
	    <?php echo $this->form->getElement('PHONE_DEP');?>
	    <span class="box_erro_area" id="ERRPHONE_DEP">
        	<?php 
                echo QLVBDHCommon::getTopErrorMessage($this->form->getElement('PHONE_DEP'));	
            ?>
        </span>
	 </div>
	<div class="clr"></div>
	<div class="required">
		<label for="ID_DEP_PARENT" id="lblTextIput">Phòng cấp trên</label>
		<?php echo $this->form->getElement('ID_DEP_PARENT');?>
        <span class="box_erro_area">
        	<?php 
                echo QLVBDHCommon::getTopErrorMessage($this->form->getElement('ID_DEP_PARENT'));			
            ?>
        </span>
	</div>
	<div class="clr"></div>
	<div class="required">
		<label for="ID_U_DAIDIEN" id="lblTextIput">Người đại diện</label>
		<select name=ID_U_DAIDIEN>
			<option value=0>--Chọn người đại diện--</option>
<?php
	foreach($this->user as $useritem){
?>			<option value=<?=$useritem['ID_U']?>><?=$useritem['NAME']?></option>
<?php
	}
?>
		</select>
		<script>
			document.frmEditDepartment.ID_U_DAIDIEN.value='<?=$this->ID_U_DAIDIEN?>';
		</script>
        <span class="box_erro_area">
        </span>
	</div>
	<div class="clr"></div>
	<div class="required">
		<label for="ACTIVE" id="lblTextIput">Kích hoạt</label>
		<?php echo $this->form->getElement('ACTIVE');?>
	</div>
	<div class="clr"></div>
	<div class="required">
		<label for="ISLEADER" id="lblTextIput">Là phòng lãnh đạo</label>
		<?php echo $this->form->getElement('ISLEADER');?>
	</div>
	<div class="clr"></div>
	<input type=hidden name="id" value=<?php echo $this->id?> >
</fieldset>
</form>

<script>
	function SaveButtonClick()
	{
		document.frmEditDepartment.submit();
	}
	function BackButtonClick()
	{
		document.frmEditDepartment.action = "/qtht/departments/";
		document.frmEditDepartment.submit();
	}
</script>