<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html>
<head>
<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
<script type="text/javascript" src="/js/jquery-1.3.2.js"></script>
<script type="text/javascript" src="/js/common.js"></script>
<script src="/js/validate.js" type="text/javascript"></script>
<script type="text/javascript" src="/js/Ajax/AjaxEngine.js"></script>
<link rel="stylesheet" type="text/css" href="/styles/general.css" />
</head>
<body style="background-color:transparent">
<form name="frm" action="/hscv/hosoluutheodoi/luutheodoi">
<table class=admintable width=100%>
	<tr style="display:none">
		<td nowrap><b style="margin-left: 5px">Lưu thư mục cá nhân</b>
			
		</td>
		<td width=100%>
			<select name=FOLDER>
				<option value=0>--Lưu thư mục--</option>
				<?php
				foreach($this->datafolder as $folderitem){
				?>
				<option value="<?=$folderitem["ID_TMCN"]?>"><?=$folderitem["NAME"]?></option>
				<?php
				}
				?>
			</select>
		</td>
	</tr>
	 <tr>	
                <td nowrap><b style="margin-left: 5px">Nội dung</b>
			
		</td>
		<td width=50%>
			<textarea rows="2" cols="80" name='comment' id='comment'><?=htmlspecialchars($this->data['COMMENT'])?></textarea>
		</td>                    
                     
	</tr>
    <?php 
        if(isset($this->dataTapHSCV)){
    ?>
	<tr>		
		<td nowrap><b style="margin-left: 5px">Lưu vào hồ sơ công việc điện tử</b></td>
		<td width=100%>
            <select name="idtaphoso" value="" onchange="changeDir(this.value);checkInTapHHSCVDT(<?=$this->ID_HSCV?>,this.value);">
			<option value="">-Chọn thư mục HSCV điện tử-</option>
            <?php
                $countTapHSCV = count($this->dataTapHSCV); 
                if($countTapHSCV <= 0){
                    //echo " <option value=''>Không tìm thấy tập hồ sơ công việc nào</option>";
                }else{
                    $arrDir = array();
                    foreach($this->dataTapHSCV as $row){
                    $array = array();
                    QLVBDHCommon::getDirThuMucTapHSCV(&$array, $row['ID_THUMUC']);
                    $arrDir[$row['ID_TAPHOSO']] = implode(">>", array_reverse($array));
                    ?>
                    <option value="<?=$row['ID_TAPHOSO']?>"><?=$row['TEN']?></option>
            <?php
                    }
                }
            ?>
            </select>
            <?php 
				$tenThuMuc = $arrDir[$this->dataTapHSCV[0]['ID_TAPHOSO']];
				if($arrDir[$this->dataTapHSCV[0]['ID_TAPHOSO']] == ""){
					$tenThuMuc = "Không có ? <a href='/taphscv/taphscv/list' target='_blank'>Quản lý và tạo ở đây</a> ";
				}
			?>
                    <b>Thư mục </b> :  <span id="dirThuMucHSCV"><?=$tenThuMuc?></span><span></span><span id="err_dirThuMucHSCV" style=" margin-left: 20px;color: red"></span>
		</td>
	</tr>
    <?php 
        echo "<script>\n";
        echo "var listDir = new Array();\n";
        $i = 0;
        $arrkeys = array_keys($arrDir);
        foreach($arrkeys as $key){
           echo "listDir[".$key."] = '".$arrDir[$key]."';\n";
        }
        echo '</script>';
        echo ' <input type="hidden" name="vbdi" value="'.$this->vbdi.'" /> ';
        echo ' <input type="hidden" name="vbden" value="'.$this->vbden.'" /> ';
        echo ' <input type="hidden" name="duthao" value="'.$this->duthao.'" /> ';
    } ?>
	<tr>
		<td><input type=button value="Lưu" onclick="luutheodoi();"></td>
		<td align="right" width="200px">   </td>
	</tr>
	
</table>
<input type=hidden id=TRICHYEU value="<?=$this->vanbanden["TRICHYEU"]?>"> 
<input type=hidden id=SOKYHIEU value="<?=$this->vanbanden["SOKYHIEU"]?>">     
<input type=hidden name=id_hscv value="<?=$this->ID_HSCV?>" >
</form>
<p id=lasttext></p>
</body>
</html>
<script>
function changeDir(key){
    if(listDir[key]){
        document.getElementById('dirThuMucHSCV').innerHTML = listDir[key];
    }else{
        document.getElementById('dirThuMucHSCV').innerHTML ='';
    }
}
function luutheodoi(){
//document.frm.submit();
  <?php 
     if(QLVBDHCommon::TabHscv(8,33)==1){ ?>
     var comment = document.getElementById("comment").value;
	var is_giaoviec= <?=$this->vanbanden['IS_GIAOVIEC']?>;	
    var trichyeu = document.getElementById("TRICHYEU").value;
    var sokyhieu = document.getElementById('SOKYHIEU').value;
    var submitAjax = new AjaxEngine();
    var oXmlHttp = submitAjax.createXMLHttp();
    oXmlHttp.open("get", "/vbden/vbden/kiemtravanbanden?TRICHYEU="+trichyeu+"&SOKYHIEU="+sokyhieu , true); 
    oXmlHttp.setRequestHeader("Content-Type", "application/x-www-form-urlencoded");

    oXmlHttp.onreadystatechange = function () { 
        if (oXmlHttp.readyState == 4 && oXmlHttp.status == 200) { 
                   if(comment == "" && (oXmlHttp.responseText == 1 || is_giaoviec==1)){                         
                         alert('Văn bản này bắt buộc xử lý. Nếu muốn tiếp tục lưu tham khảo, cần nhập nội dung giải trình lưu theo dõi!.');

                   } else
                   {
                       document.frm.submit();
                   }
        } 
    };       
    oXmlHttp.send(null);
    <?php } else { ?>
        document.frm.submit();
      <?php }   ?>  
}
function checkInTapHHSCVDT(id,idTapHoSo){
    document.getElementById('err_dirThuMucHSCV').innerHTML = 'Đang kiểm tra .....';
    jQuery.ajax({
        url: '/hscv/hosoluutheodoi/checkintaphscvdt/id/'+id+'/idtaphoso/'+idTapHoSo,
        type: 'POST',
        cache: false,
        success: function(data)
        {
            document.getElementById('err_dirThuMucHSCV').innerHTML = data;
        }
    });
}
function resize(){
	var iframeElement = parent.document.getElementById('iframebutphe<?=$this->ID_HSCV?>');
	iframeElement.style.height = "" + document.getElementById("lasttext").offsetTop + "px";
	iframeElement.width = "100%";
}
resize();
</script>