<form id="containerID" action="/giaoviec/danhsachguimail/save" method="post" enctype="multipart/form-data" name="datacdform" >
    <div style="float: right;"><font color="red">(*) Bắt buộc nhập liệu </font></div>
    <div class="clr"></div>
    <fieldset>
        <div class="required clearfix">
            <label>Tên người nhận<font color="red">*</font></label>
            <input type="text" name="tennguoinhan" maxlength="200" value="<?php echo htmlspecialchars($this->tennguoinhanbefore); ?>" class="inputText" size="100" >
            <span class="box_erro_area" id="ERRtennguoinhan"></span>
        </div>
        <div class="required clearfix">
            
            <label>Đơn vị<font color="red">*</font></label>
            
            <select name="madonvi" id="madonvi" class="inputbox" size="1">
                <?php
                    echo DanhSachGuiMailModel::WriteDonVi((int)$this->madonvibefore, "-- Chọn tất cả  --");
                ?>
            </select>
        
        </div>
       
        <div class="required clearfix">
            <label>Điện thoại<font color="red">*</font></label>
            <input type="text" name="sodienthoai" maxlength="100" value="<?php echo htmlspecialchars($this->sodienthoaibefore); ?>" class="inputText" size="50" >
        </div>
        <div class="required clearfix">
            <label>Email</label>
            <input type="text" name="email" maxlength="100" value="<?php echo htmlspecialchars($this->emailbefore); ?>" class="inputText" size="50" >
        </div>
         <div class="required clearfix">
            <label>Email 2</label>
            <input type="text" name="email2" maxlength="100" value="<?php echo htmlspecialchars($this->email2before); ?>" class="inputText" size="50" >
        </div>
        <div class="optional clearfix">
            <label>Gửi email</label>
            <?php
            if ($this->activeselect == 1) {
                echo '<input type="checkbox" value=1 class="inputCheckbox" name="active" checked="checked">';
            } else {
                echo '<input type="checkbox" value=1 class="inputCheckbox" name="active">';
            }
            ?>
        </div>
    </fieldset>
    <input type=hidden name="InputID" value=<?php echo $this->id ?> >
    <input type=hidden name="limit" value=<?php echo $this->limit ?> >
    <input type=hidden name="filter_object" value=<?php echo $this->filter_object ?> >
    <input type=hidden name="search" value=<?php echo $this->search ?> >
    <input type=hidden name="page" value=<?php echo $this->page ?> >
</form>
<script type="text/javascript">

    function SaveButtonClick() {
        var flag = true;
        var errname = true;
        var errcode = true;

        if (errcode) {
            var AE = new AjaxEngine();
            var oXmlHttp = AE.createXMLHttp();
            oXmlHttp.open("post", "/giaoviec/danhsachguimail/checkexist/code/" + document.datacdform.madonvi.value + "/id/" + document.datacdform.InputID.value, true);
            oXmlHttp.setRequestHeader("Content-Type", "application/x-www-form-urlencoded");
            oXmlHttp.onreadystatechange = function () {
                if (oXmlHttp.readyState == 4) {
                    if (oXmlHttp.status == 200) {
                        if ('<?= $this->madonvibefore ?>' != ''){   //cập nhật
                            if (document.datacdform.madonvi.value != '<?= $this->madonvibefore ?>') {
                                if (oXmlHttp.responseText == 1) {
                                    document.getElementById('ERRcode').innerHTML = 'Mã đơn vị đã tồn tại';
                                    flag = false;
                                }
                            }
                            if (flag == true) {
                                if (errcode && errname) {
                                    document.datacdform.submit();
                                }
                            }
                        }
                        if ('<?= $this->madonvibefore ?>' == '') {
                            if (oXmlHttp.responseText == 1) {
                                document.getElementById('ERRcode').innerHTML = 'Mã đơn vị đã tồn tại';
                            }
                            else {
                                if (errcode && errname) {
                                    document.datacdform.submit();
                                }
                            }
                        }
                    }
                }
            };
            oXmlHttp.send(null);
        }
    }

    function BackButtonClick() {
        document.datacdform.action = '/giaoviec/danhsachguimail/index';
        document.datacdform.submit();
    }

</script>