<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html>

<head>
<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />


</head>

<body lang=EN-US style='tab-interval:.5in'>
<?php if(!$this->print){ ;?>
<div align=right>
	<a href="#" onclick='window.open("/motcua/dongbohsmc/viewdon/print/1/id/<?=$this->ID_MC_HSW?>");' class="toolbar"><span class="icon-PrintButton" title="In phiếu"></span>In phiếu</a>
</div>
<?php }?>


<p class="MsoNormal" style="text-align: center;" align="center"><b><span style="font-size: 12.5pt;">CỘNG HÒA XÃ HỘI CHỦ NGHĨA
VIỆT <st1:place w:st="on"><st1:country-region w:st="on">NAM</st1:country-region></st1:place><o:p></o:p></span></b></p>

<p class="MsoNormal" style="text-align: center;" align="center"><b><span style="font-size: 12.5pt;">Độc lập - Tự do - Hạnh
phúc</span></b><span style="font-size: 12.5pt;"><o:p></o:p></span></p>

<p class="MsoNormal"><span style="">

<table align="left" cellpadding="0" cellspacing="0">
 <tbody><tr>
  <td width="222" height="0"></td>
 </tr>
 <tr>
  <td></td>
  <td><img src="dungdo_files/image001.gif" v:shapes="_x0000_s1026" width="198" height="2"></td>
 </tr>
</tbody></table>

</span><span style="font-size: 6pt;"><o:p>&nbsp;</o:p></span></p>

<p class="MsoNormal"><span style="font-size: 6pt;"><o:p>&nbsp;</o:p></span></p>

<br style="" clear="ALL">

<h4 style="text-align: center;" align="center">ĐƠN ĐỀ
NGHỊ CẤP GIẤY PHÉP </h4>

<h4 style="text-align: center;" align="center">PHƯƠNG TIỆN
VẬN TẢI VÀO ĐƯỜNG CẤM;<span style=""> DỪNG, ĐỖ XE TẠI KHU VỰC CẤM<o:p></o:p></span></h4>

<p class="MsoNormal" style="margin-left: 0.5in; text-align: center; text-indent: -0.5in;" align="center"><b><span style="font-size: 9pt;"><o:p>&nbsp;</o:p></span></b></p>

<p class="MsoNormal" style="margin: 0in 0in 6pt 0.5in; text-align: center; text-indent: -0.5in;" align="center"><span style="font-size: 12.5pt;">Kính gửi:</span><span style="font-size: 12.5pt;"> Sở Giao thông vận tải thành
phố Đà Nẵng <o:p></o:p></span></p>

<p class="MsoNormal" style="margin-top: 9pt; text-align: justify;"><span style="font-size: 12.5pt;">- Cá nhân, tổ chức đề
nghị: </span><span style="font-size: 10pt;"><?=" ".htmlspecialchars($this->data["TENTOCHUCCANHAN"])." "?><o:p></o:p></span></p>

<p class="MsoNormal" style="text-align: justify;"><span style="font-size: 12.5pt;">-
Địa chỉ: </span><span style="font-size: 10pt;"><?=" ".htmlspecialchars($this->data["DIACHI"])." "?></span><span style="font-size: 12.5pt;">Điện thoại: </span><span style="font-size: 10pt;"><?=" ".htmlspecialchars($this->data["DIENTHOAI"])." "?></span><span style="font-size: 12.5pt;"><o:p></o:p></span></p>

<p class="MsoNormal" style="text-align: justify;"><span style="font-size: 12.5pt;">Đề
nghị cấp giấy phép cho phương tiện vào
đường cấm; dừng, đỗ xe tại khu
vực cấm với các thông số sau:<o:p></o:p></span></p>

<p class="MsoNormal" style="margin-top: 6pt;"><b style=""><span style="font-size: 12.5pt;">1. PHƯƠNG TIỆN VẬN
CHUYỂN:<o:p></o:p></span></b></p>

<p class="MsoNormal" style="text-align: justify;"><span style="font-size: 12.5pt;">-
Loại xe: </span><span style="font-size: 10pt;"><?=htmlspecialchars($this->data["LOAI_XE"])?></span><span style="font-size: 12.5pt;"><o:p></o:p></span></p>

<p class="MsoNormal" style="text-align: justify;"><span style="font-size: 12.5pt;">-
Nhãn hiệu xe: </span><span style="font-size: 10pt;"><?=htmlspecialchars($this->data["NHAN_HIEU"])." "?></span><span style="font-size: 12.5pt;">Biển số đăng ký: </span><span style="font-size: 10pt;"><?=htmlspecialchars($this->data["BIEN_SO"])?></span><span style="font-size: 12.5pt;"><o:p></o:p></span></p>

<p class="MsoNormal" style="text-align: justify;"><span style="font-size: 12.5pt;">-
Kích thước xe (dài x rộng x cao):</span><span style="font-size: 10pt;"><?=htmlspecialchars($this->data["KT_XE_DAI"])?></span><span style="font-size: 12.5pt;">x</span><span style="font-size: 10pt;"><?=htmlspecialchars($this->data["KT_XE_RONG"])?></span><span style="font-size: 12.5pt;">x</span><span style="font-size: 10pt;"><?=htmlspecialchars($this->data["KT_XE_CAO"])?></span><span style="font-size: 12.5pt;">(m).<o:p></o:p></span></p>

<p class="MsoNormal" style="text-align: justify;"><span style="font-size: 12.5pt;">-
Trọng tải thiết kế của xe: </span><span style="font-size: 10pt;"><?=htmlspecialchars($this->data["TL_XE_TK"])?></span><span style="font-size: 12.5pt;">(tấn).<o:p></o:p></span></p>

<p class="MsoNormal" style="text-align: justify;"><span style="font-size: 12.5pt;">-
Trọng lượng bản thân xe: .</span><span style="font-size: 10pt;"><?=htmlspecialchars($this->data["TL_XE"])?></span><span style="font-size: 12.5pt;">(tấn).<o:p></o:p></span></p>

<p class="MsoNormal" style="text-align: justify;"><span style="font-size: 12.5pt;">-
Số trục của xe:</span><span style="font-size: 10pt;"></span><span style="font-size: 12.5pt;"><?=htmlspecialchars($this->data["SO_TRUCXE"])?><o:p></o:p></span></p>

<p class="MsoNormal" style="text-align: justify;"><span style="font-size: 12.5pt;">-
Ngày kiểm định lần
tới: <?=" ".implode("/",array_reverse(explode("-",$this->data["NGAY_KIEMDINH_LT"])))?><o:p></o:p></span></p>

<p class="MsoNormal" style="margin-top: 6pt;"><b style=""><span style="font-size: 12.5pt;">2. HÀNG HÓA VẬN CHUYỂN:<o:p></o:p></span></b></p>

<p class="MsoNormal" style="text-align: justify;"><span style="font-size: 12.5pt;">-
Loại hàng: </span><span style="font-size: 10pt;"><?=htmlspecialchars($this->data["LOAI_HANG"])?></span><span style="font-size: 12.5pt;"><o:p></o:p></span></p>

<p class="MsoNormal" style="text-align: justify;"><span style="font-size: 12.5pt;">-
Trọng lượng hàng xin chở: </span><span style="font-size: 10pt;"><?=htmlspecialchars($this->data["TL_HANG"])?></span><span style="font-size: 12.5pt;">(tấn).<o:p></o:p></span></p>

<p class="MsoNormal" style="margin-top: 6pt;"><b style=""><span style="font-size: 12.5pt;">3. TUYẾN ĐƯỜNG VÀ
THỜI GIAN VẬN CHUYỂN:<o:p></o:p></span></b></p>

<p class="MsoNormal" style="text-align: justify;"><span style="font-size: 12.5pt;">- Địa
điểm đi (lấy hàng):</span><span style="font-size: 10pt;"><?=htmlspecialchars($this->data["DD_DI"])?><o:p></o:p></span></p>

<p class="MsoNormal" style="text-align: justify;"><span style="font-size: 12.5pt;">- Địa
điểm đến (lấy hàng):</span><span style="font-size: 10pt;"><?=htmlspecialchars($this->data["DD_DEN"])?><o:p></o:p></span></p>

<p class="MsoNormal" style="text-align: justify;"><span style="font-size: 12.5pt;">-
Tuyến đường vận chuyển:</span><span style="font-size: 10pt;">…… </span><span style="font-size: 12.5pt; color: rgb(51, 102, 255);">
</span><span style="font-size: 10pt;"><?=htmlspecialchars($this->data->TUYEN_DUONG)?></span><span style="font-size: 12.5pt;"><o:p></o:p></span></p>

<p class="MsoNormal" style="text-align: justify;"><span style="font-size: 12.5pt;">
<span style="font-size: 10pt;"></span><span style="font-size: 12.5pt;"><o:p></o:p></span></p>

<p class="MsoNormal" style="text-align: justify;"><span style="font-size: 12.5pt;">- Thời
gian vận chuyển trong ngày: <span style="">&nbsp;</span>


<?php $stt_tg_dd = 3;
for($i = 1; $i <= $stt_tg_dd ;$i++){
	$value_t = "";
	eval( '$value_t = ($this->data["TG_VC_TU_'.$i.'"]'. ");");
	if($value_t){
		$arr_t_tu = explode(":",$value_t);
		//var_dump($arr_t);
	}else{
		$arr_t_tu = array();
	}

	$value_t = "";
	eval( '$value_t = ($this->data["TG_VC_DEN_'.$i.'"]' .");");
	if($value_t){
		$arr_t_den = explode(":",$value_t);
		
	}else{
		$arr_t_den= array();
	}

?>

<b style="">Từ</b></span><span style="font-size: 10pt;"><?=htmlspecialchars($arr_t_tu[0])?></span><span style="font-size: 12.5pt;">giờ</span><span style="font-size: 10pt;"><?=htmlspecialchars($arr_t_tu[1])?></span><span style="font-size: 12.5pt;">phút</span><span style="font-size: 10pt;">.....…..</span><span style="font-size: 12.5pt;"> <b style="">đến</b> </span><span style="font-size: 10pt;"><?=htmlspecialchars($arr_t_den[0])?></span><span style="font-size: 12.5pt;">giờ</span><span style="font-size: 10pt;"><?=htmlspecialchars($arr_t_den[1])?></span><span style="font-size: 12.5pt;">phút</span><span style="font-size: 10pt;">.....…..</span><span style="font-size: 12.5pt;"> <o:p></o:p></span></p>

<p class="MsoNormal" style="text-align: justify;"><span style="font-size: 12.5pt;"><span style="">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; 

<?php } ?>

<p class="MsoNormal" style="margin-top: 6pt;"><b style=""><span style="font-size: 12.5pt;">4. ĐỊA ĐIỂM VÀ
THỜI GIAN DỪNG, ĐỖ XE:<o:p></o:p></span></b></p>

<p class="MsoNormal" style=""><span style="font-size: 12.5pt;">-
Địa điểm dừng, đỗ xe (số nhà, tên
đường hoặc trong phạm vi công trình):<?=htmlspecialchars($this->data["DD_DUNGDO"])?><o:p></o:p></span></p>

<p class="MsoNormal" style=""><span style="font-size: 12.5pt;"><o:p></o:p></span></p>

<p class="MsoNormal" style="text-align: justify;"><span style="font-size: 12.5pt;">-
Thời gian dừng, đỗ xe trong ngày:<span style="">&nbsp; </span>

<?php $stt_tg_dd = 3;
for($i = 1; $i <= $stt_tg_dd ;$i++){
	$value_t = "";
	eval( '$value_t = ($this->data["TG_DD_TU_'.$i.'"]'.");");
	if($value_t){
		$arr_t_tu = explode(":",$value_t);
		//var_dump($arr_t);
	}else{
		$arr_t_tu = array();
	}

	$value_t = "";
	eval( '$value_t = ($this->data["TG_DD_DEN_'.$i.'"]'.");");
	if($value_t){
		$arr_t_den = explode(":",$value_t);
		
	}else{
		$arr_t_den= array();
	}

?>

<b style="">Từ</b></span><span style="font-size: 10pt;"><?=htmlspecialchars($arr_t_tu[0])?></span><span style="font-size: 12.5pt;">giờ</span><span style="font-size: 10pt;"><?=htmlspecialchars($arr_t_tu[1])?></span><span style="font-size: 12.5pt;">phút</span><span style="font-size: 10pt;">.....…..</span><span style="font-size: 12.5pt;"> <b style="">đến</b> </span><span style="font-size: 10pt;"><?=htmlspecialchars($arr_t_den[0])?></span><span style="font-size: 12.5pt;">giờ</span><span style="font-size: 10pt;"><?=htmlspecialchars($arr_t_den[1])?></span><span style="font-size: 12.5pt;">phút</span><span style="font-size: 10pt;"></span><span style="font-size: 12.5pt;"> <o:p></o:p></span></p>

<p class="MsoNormal" style="text-align: justify;"><span style="font-size: 12.5pt;"><span style="">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; 

<?php } ?>
<p class="MsoNormal" style="margin-top: 6pt; text-align: justify;"><b style=""><span style="font-size: 12.5pt;">5. THỜI
GIAN ĐỀ NGHỊ CẤP PHÉP: Từ ngày<?=" ".implode("/",array_reverse(explode("-",$this->data["TU_NGAY"])))." "?>đến
hết ngày<?=" ".implode("/",array_reverse(explode("-",$this->data["DEN_NGAY"])))?><o:p></o:p></span></b></p>

<p class="MsoNormal" style="text-align: center;" align="center"><span style="font-size: 12.5pt; color: rgb(51, 102, 255);"><o:p></o:p></span></p>

<p class="MsoNormal" style="margin-top: 6pt; text-indent: 17.85pt;"><b><i><span style="font-size: 12.5pt;">Sau khi được cấp phép hoạt
động, tôi xin cam kết:<o:p></o:p></span></i></b></p>

<p class="MsoNormal" style="text-align: justify; text-indent: 0.25in;"><span style="font-size: 12.5pt;">Chấp hành các quy định hiện
hành của Nhà nước và của UBND thành phố Đà
Nẵng về đảm bảo an toàn giao thông, trật
tự đô thị và vệ sinh môi trường.<o:p></o:p></span></p>

<p class="MsoNormal" style="text-align: justify; text-indent: 0.25in;"><span style="font-size: 12.5pt;">Nếu không thực hiện đúng các
nội dung trên, tôi xin chịu hoàn toàn trách nhiệm
trước Pháp luật./.<o:p></o:p></span></p>

<p class="MsoNormal"><span style="font-size: 12.5pt;"><o:p>&nbsp;</o:p></span></p>

<table class="MsoNormalTable" style="margin-left: 5.4pt; border-collapse: collapse;" border="0" cellpadding="0" cellspacing="0">
 <tbody><tr style="">
  <td style="padding: 0in 5.4pt; width: 3.25in;" valign="top" width="312">
  <p class="MsoNormal"><b><u><span style="font-size: 10pt;">Ghi chú:</span></u></b><b><span style="font-size: 10pt;"> Người làm đơn khi đến nhận
  kết quả phải mang theo đầy đủ các
  nội dung sau:<o:p></o:p></span></b></p>
  <p class="MsoNormal"><span style="font-size: 10pt;">1. Bản chụp CMND (hoặc GPLX)
  người làm đơn;<o:p></o:p></span></p>
  <p class="MsoNormal"><span style="font-size: 10pt;">2. Bản chụp </span><span style="font-size: 10pt;">giấy chứng nhận đăng ký
  xe;<o:p></o:p></span></p>
  <p class="MsoNormal"><span style="font-size: 10pt;">3. Bản chụp sổ chứng
  nhận kiểm định xe.<o:p></o:p></span></p>
  <p class="MsoNormal"><i><span style="font-size: 10pt;">(Có bản chính để đối chiếu trả
  lại ngay)<b><o:p></o:p></b></span></i></p>
  </td>
  <td style="padding: 0in 5.4pt; width: 243pt;" valign="top" width="324">
  <p class="MsoNormal" style="text-align: center;" align="center"><i><span style="font-size: 12pt;">Đà Nẵng, ngày.....tháng.......năm
  200....</span></i><span style="font-size: 12pt;"><o:p></o:p></span></p>
  <p class="MsoNormal" style="margin: 0in 0in 6pt 0.25in; text-align: center;" align="center"><b><span style="font-size: 12pt;">Người làm đơn<o:p></o:p></span></b></p>
  <p class="MsoNormal" style="margin: 0in 0in 6pt 0.25in; text-align: center;" align="center"><i style=""><span style="font-size: 12pt; color: rgb(51, 102, 255);">(Ký tên; ghi rõ họ
  tên)</span></i><b><i><span style="font-size: 8pt; color: rgb(51, 102, 255);"><o:p></o:p></span></i></b></p>
  </td>
 </tr>
</tbody></table>

<p class="MsoNormal"><o:p>&nbsp;</o:p></p>

<p class="MsoNormal"><o:p>&nbsp;</o:p></p>

<p id=lasttext1></p>

</body>

</html>
<script>
function resize(){
	try{
		//alert("aa");
	var iframeElement = parent.document.getElementById('iframebutphe<?=$this->ID_FR?>');
	iframeElement.style.height = ""+ (document.getElementById("lasttext1").offsetTop) +"px";
	iframeElement.width = "100%"; 
	setTimeout("resize()",1000);
	}catch(ex){
	}
}

setTimeout("resize()",1000);
<?php if($this->print){?>
window.print();
<?php }?>
</script>