<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<head>
<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
<meta name=ProgId content=Word.Document>
<meta name=Generator content="Microsoft Word 12">
<meta name=Originator content="Microsoft Word 12">
<style>
<!--
 /* Font Definitions */
 @font-face
	{font-family:Wingdings;
	panose-1:5 0 0 0 0 0 0 0 0 0;
	mso-font-charset:2;
	mso-generic-font-family:auto;
	mso-font-pitch:variable;
	mso-font-signature:0 268435456 0 0 -2147483648 0;}
@font-face
	{font-family:"Cambria Math";
	panose-1:2 4 5 3 5 4 6 3 2 4;
	mso-font-charset:0;
	mso-generic-font-family:roman;
	mso-font-pitch:variable;
	mso-font-signature:-1610611985 1107304683 0 0 159 0;}
@font-face
	{font-family:Calibri;
	panose-1:2 15 5 2 2 2 4 3 2 4;
	mso-font-charset:0;
	mso-generic-font-family:swiss;
	mso-font-pitch:variable;
	mso-font-signature:-1610611985 1073750139 0 0 159 0;}
 /* Style Definitions */
 p.MsoNormal, li.MsoNormal, div.MsoNormal
	{mso-style-unhide:no;
	mso-style-qformat:yes;
	mso-style-parent:"";
	margin-top:0in;
	margin-right:0in;
	margin-bottom:10.0pt;
	margin-left:20pt;
	line-height:115%;
	mso-pagination:widow-orphan;
	font-size:11.0pt;
	font-family:"Calibri","sans-serif";
	mso-fareast-font-family:"Times New Roman";
	mso-bidi-font-family:"Times New Roman";}
h1
	{mso-style-unhide:no;
	mso-style-qformat:yes;
	mso-style-link:"Heading 1 Char";
	mso-style-next:Normal;
	margin:0in;
	margin-bottom:.0001pt;
	text-align:center;
	mso-pagination:widow-orphan;
	page-break-after:avoid;
	mso-outline-level:1;
	font-size:14.0pt;
	mso-bidi-font-size:12.0pt;
	font-family:"Times New Roman","serif";
	mso-font-kerning:0pt;}
h2
	{mso-style-name:"Heading 2\,BVI2\,Heading 2-BVI\,RepHead2\,MyHeading2\,Mystyle2\,Mystyle21\,Mystyle22\,Mystyle23\,Mystyle211\,Mystyle221";
	mso-style-unhide:no;
	mso-style-qformat:yes;
	mso-style-link:"Heading 2 Char\,BVI2 Char\,Heading 2-BVI Char\,RepHead2 Char\,MyHeading2 Char\,Mystyle2 Char\,Mystyle21 Char\,Mystyle22 Char\,Mystyle23 Char\,Mystyle211 Char\,Mystyle221 Char";
	mso-style-next:Normal;
	margin:0in;
	margin-bottom:.0001pt;
	text-align:center;
	mso-pagination:widow-orphan;
	page-break-after:avoid;
	mso-outline-level:2;
	font-size:12.0pt;
	font-family:"Times New Roman","serif";}
h3
	{mso-style-unhide:no;
	mso-style-qformat:yes;
	mso-style-link:"Heading 3 Char";
	mso-style-next:Normal;
	margin:0in;
	margin-bottom:.0001pt;
	text-align:right;
	mso-pagination:widow-orphan;
	page-break-after:avoid;
	mso-outline-level:3;
	font-size:14.0pt;
	mso-bidi-font-size:12.0pt;
	font-family:"Times New Roman","serif";
	font-weight:normal;
	font-style:italic;}
h4
	{mso-style-unhide:no;
	mso-style-qformat:yes;
	mso-style-link:"Heading 4 Char";
	mso-style-next:Normal;
	margin:0in;
	margin-bottom:.0001pt;
	text-align:justify;
	text-indent:.5in;
	mso-pagination:widow-orphan;
	page-break-after:avoid;
	mso-outline-level:4;
	font-size:14.0pt;
	font-family:"Times New Roman","serif";}
h5
	{mso-style-unhide:no;
	mso-style-qformat:yes;
	mso-style-link:"Heading 5 Char";
	mso-style-next:Normal;
	margin-top:0in;
	margin-right:-9.45pt;
	margin-bottom:0in;
	margin-left:0in;
	margin-bottom:.0001pt;
	mso-pagination:widow-orphan;
	page-break-after:avoid;
	mso-outline-level:5;
	font-size:14.0pt;
	font-family:"Times New Roman","serif";
	color:black;
	text-decoration:underline;
	text-underline:single;}
p.MsoFootnoteText, li.MsoFootnoteText, div.MsoFootnoteText
	{mso-style-noshow:yes;
	mso-style-unhide:no;
	mso-style-link:"Footnote Text Char";
	margin:0in;
	margin-bottom:.0001pt;
	mso-pagination:widow-orphan;
	font-size:10.0pt;
	font-family:"Times New Roman","serif";
	mso-fareast-font-family:"Times New Roman";}
span.MsoFootnoteReference
	{mso-style-noshow:yes;
	mso-style-unhide:no;
	vertical-align:super;}
span.Heading1Char
	{mso-style-name:"Heading 1 Char";
	mso-style-unhide:no;
	mso-style-locked:yes;
	mso-style-link:"Heading 1";
	mso-ansi-font-size:14.0pt;
	mso-bidi-font-size:12.0pt;
	font-family:"Times New Roman","serif";
	mso-ascii-font-family:"Times New Roman";
	mso-fareast-font-family:"Times New Roman";
	mso-hansi-font-family:"Times New Roman";
	mso-bidi-font-family:"Times New Roman";
	font-weight:bold;}
span.Heading2Char
	{mso-style-name:"Heading 2 Char\,BVI2 Char\,Heading 2-BVI Char\,RepHead2 Char\,MyHeading2 Char\,Mystyle2 Char\,Mystyle21 Char\,Mystyle22 Char\,Mystyle23 Char\,Mystyle211 Char\,Mystyle221 Char";
	mso-style-unhide:no;
	mso-style-locked:yes;
	mso-style-link:"Heading 2\,BVI2\,Heading 2-BVI\,RepHead2\,MyHeading2\,Mystyle2\,Mystyle21\,Mystyle22\,Mystyle23\,Mystyle211\,Mystyle221";
	mso-ansi-font-size:12.0pt;
	mso-bidi-font-size:12.0pt;
	font-family:"Times New Roman","serif";
	mso-ascii-font-family:"Times New Roman";
	mso-fareast-font-family:"Times New Roman";
	mso-hansi-font-family:"Times New Roman";
	mso-bidi-font-family:"Times New Roman";
	font-weight:bold;}
span.Heading3Char
	{mso-style-name:"Heading 3 Char";
	mso-style-unhide:no;
	mso-style-locked:yes;
	mso-style-link:"Heading 3";
	mso-ansi-font-size:14.0pt;
	mso-bidi-font-size:12.0pt;
	font-family:"Times New Roman","serif";
	mso-ascii-font-family:"Times New Roman";
	mso-fareast-font-family:"Times New Roman";
	mso-hansi-font-family:"Times New Roman";
	mso-bidi-font-family:"Times New Roman";
	font-style:italic;}
span.Heading4Char
	{mso-style-name:"Heading 4 Char";
	mso-style-unhide:no;
	mso-style-locked:yes;
	mso-style-link:"Heading 4";
	mso-ansi-font-size:14.0pt;
	mso-bidi-font-size:14.0pt;
	font-family:"Times New Roman","serif";
	mso-ascii-font-family:"Times New Roman";
	mso-fareast-font-family:"Times New Roman";
	mso-hansi-font-family:"Times New Roman";
	mso-bidi-font-family:"Times New Roman";
	font-weight:bold;}
span.Heading5Char
	{mso-style-name:"Heading 5 Char";
	mso-style-unhide:no;
	mso-style-locked:yes;
	mso-style-link:"Heading 5";
	mso-ansi-font-size:14.0pt;
	mso-bidi-font-size:14.0pt;
	font-family:"Times New Roman","serif";
	mso-ascii-font-family:"Times New Roman";
	mso-fareast-font-family:"Times New Roman";
	mso-hansi-font-family:"Times New Roman";
	mso-bidi-font-family:"Times New Roman";
	color:black;
	font-weight:bold;
	text-decoration:underline;
	text-underline:single;}
span.FootnoteTextChar
	{mso-style-name:"Footnote Text Char";
	mso-style-noshow:yes;
	mso-style-unhide:no;
	mso-style-locked:yes;
	mso-style-link:"Footnote Text";
	mso-ansi-font-size:10.0pt;
	mso-bidi-font-size:10.0pt;
	font-family:"Times New Roman","serif";
	mso-ascii-font-family:"Times New Roman";
	mso-fareast-font-family:"Times New Roman";
	mso-hansi-font-family:"Times New Roman";
	mso-bidi-font-family:"Times New Roman";}
.MsoChpDefault
	{mso-style-type:export-only;
	mso-default-props:yes;
	mso-ascii-font-family:Calibri;
	mso-hansi-font-family:Calibri;}
 /* Page Definitions */
 @page
	{mso-footnote-separator:url("tuyencodinh_files/header.html") fs;
	mso-footnote-continuation-separator:url("tuyencodinh_files/header.html") fcs;
	mso-endnote-separator:url("tuyencodinh_files/header.html") es;
	mso-endnote-continuation-separator:url("tuyencodinh_files/header.html") ecs;}
@page Section1
	{size:11.0in 8.5in;
	mso-page-orientation:landscape;
	margin:1.0in 1.0in 1.0in 1.0in;
	mso-header-margin:.5in;
	mso-footer-margin:.5in;
	mso-paper-source:0;}
div.Section1
	{page:Section1;}
 /* List Definitions */
 @list l0
	{mso-list-id:53892441;
	mso-list-type:hybrid;
	mso-list-template-ids:70255880 -393192000 67698691 67698693 67698689 67698691 67698693 67698689 67698691 67698693;}
@list l0:level1
	{mso-level-start-at:0;
	mso-level-number-format:bullet;
	mso-level-text:-;
	mso-level-tab-stop:74.25pt;
	mso-level-number-position:left;
	margin-left:74.25pt;
	text-indent:-.25in;
	font-family:"Times New Roman","serif";
	mso-fareast-font-family:"Times New Roman";}
ol
	{margin-bottom:0in;}
ul
	{margin-bottom:0in;}
-->
</style>


</head>

<body >
<?php if(!$this->print){ ;?>
<div align=right>
	<a href="#" onclick='window.open("/motcua/dongbohsmc/viewdon/print/1/id/<?=$this->ID_MC_HSW?>");' class="toolbar"><span class="icon-PrintButton" title="In phiếu"></span>In phiếu</a>
</div>
<?php }?>

<div id="block-news-content">

<table class="" style="margin-left: 5.4pt; border-collapse: collapse;" border="0" cellpadding="0" cellspacing="0">
 <tbody>
	<tr style="">
		  <td style="padding: 0in 5.4pt; width: 177.2pt;" valign="top" width="236">
		  <p class="MsoNormal" style="margin: 2pt -9.35pt 10pt 0in; text-align: center;" align="center"><?=htmlspecialchars($this->data["TEN_DOANHNGHIEP"])?></p>
		  </td>
		  <td style="padding: 0in 5.4pt; width: 600.3pt;" valign="top" >
		  <p class="MsoNormal" style="margin: 2pt -9.35pt 10pt 0in; text-align: center;" align="center">
		  <b><span style="font-size: 12pt; line-height: 115%; font-family: &quot;Times New Roman&quot;,&quot;serif&quot;;">CỘNG HOÀ XÃ HỘI CHỦ
		  NGHĨA VIỆT <st1:place w:st="on"><st1:country-region w:st="on">NAM</st1:country-region></st1:place><o:p></o:p></span></b></p>
		  </td>
	 </tr>
	 <tr style="">
		  <td style="padding: 0in 5.4pt; width: 177.2pt;" valign="top" >
			<p class="MsoNormal" style="margin: 2pt -9.35pt 10pt 0in; text-align: center;" align="center"><span class="SpellE"><span style="font-size: 12pt; line-height: 115%; font-family: &quot;Times New Roman&quot;,&quot;serif&quot;;">Số</span></span><span style="font-size: 12pt; line-height: 115%; font-family: &quot;Times New Roman&quot;,&quot;serif&quot;;">: <?=htmlspecialchars($this->data["MASODON"])?><o:p></o:p></span></p>
		  </td>
		  <td style="padding: 0in 5.4pt; width: 600.3pt;" valign="top" width="100%">
			  <p class="MsoNormal" style="margin: 2pt -9.35pt 10pt 0in; text-align: center;" align="center"><span class="SpellE"><b><u><span style="font-size: 12pt; line-height: 115%; font-family: &quot;Times New Roman&quot;,&quot;serif&quot;;">Độc</span></u></b></span><b><u><span style="font-size: 12pt; line-height: 115%; font-family: &quot;Times New Roman&quot;,&quot;serif&quot;;"> <span class="SpellE">lập</span> -
			  <span class="SpellE">Tự</span> do - <span class="SpellE">Hạnh</span> <span class="SpellE">phúc</span></span></u></b><b><span style="font-size: 12pt; line-height: 115%; font-family: &quot;Times New Roman&quot;,&quot;serif&quot;;"><o:p></o:p></span></b></p>
		  </td>
	</tr>
</tbody></table>
<p class="MsoNormal" style="margin-right: -9.45pt; text-align: right;" align="right"><b><span style="font-size: 3pt; line-height: 115%; font-family: &quot;Times New Roman&quot;,&quot;serif&quot;;"><o:p>&nbsp;</o:p></span></b></p>
<?php $date =strtotime($this->data["NGAYDON"]);?>
<p class="MsoNormal" style="margin-left: 2.5in; text-align: center; text-indent: 0.5in;" align="center"><i><span style="font-size: 13pt; line-height: 115%; font-family: &quot;Times New Roman&quot;,&quot;serif&quot;;">Đà Nẵng, <span class="SpellE">ngày</span><span style=""><?=" ".date("d",$date)." "?></span><span class="SpellE">tháng</span><span style=""><?=" ".date("m",$date)." "?></span><span class="SpellE">năm</span> <span style=""><?=" ".date("Y",$date)." "?></span><o:p></o:p></span></i></p>

<p class="MsoNormal" style="text-align: center;" align="center"><span style="font-size: 8pt; line-height: 115%; font-family: &quot;Times New Roman&quot;,&quot;serif&quot;;"><o:p>&nbsp;</o:p></span></p>

<h1><span style="font-size: 12pt;">GIẤY ĐỀ NGHỊ <o:p></o:p></span></h1>

<h1><span style="font-size: 12pt;">VẬN TẢI KHÁCH DU LỊCH
BẰNG ÔTÔ</span><span style="font-size: 11pt; font-weight: normal;"><o:p></o:p></span></h1>

<p class="MsoNormal" style="text-align: center;" align="center"><span style="font-size: 12pt; line-height: 115%; font-family: &quot;Times New Roman&quot;,&quot;serif&quot;;"><o:p>&nbsp;</o:p></span></p>

<p class="MsoNormal" style="margin-left: 1.5in;"><span style="font-size: 12pt; line-height: 115%; font-family: &quot;Times New Roman&quot;,&quot;serif&quot;;"><o:p>&nbsp;</o:p></span></p>

<p class="MsoNormal" style="text-align: center;"><span class="SpellE"><span style="font-size: 12pt; line-height: 115%; font-family: &quot;Times New Roman&quot;,&quot;serif&quot;;">Kính gửi: Sở Giao thông Vận tải thành phố Đà Nẵng</span></p>

<p class="MsoNormal" style="text-align: justify;"><span style="font-size: 12pt; line-height: 115%; font-family: &quot;Times New Roman&quot;,&quot;serif&quot;;"><o:p>&nbsp;</o:p></span></p>


<p class="MsoNormal" style="line-height: 17pt;"><span style="font-size: 12pt; font-family: &quot;Times New Roman&quot;,&quot;serif&quot;;">1.
<span class="SpellE">Tên</span> <span class="SpellE">doanh</span> <span class="SpellE">nghiệp</span> <span class="SpellE">hoặc</span> <span class="SpellE">cá</span> <span class="SpellE">nhân</span>:
<?=htmlspecialchars($this->data["TEN_DOANHNGHIEP"])?><o:p></o:p></span></p>

<p class="MsoNormal" style="text-align: justify; line-height: 17pt;"><span style="font-size: 12pt; font-family: &quot;Times New Roman&quot;,&quot;serif&quot;;">2. <span class="SpellE">Tên</span> <span class="SpellE">giao</span> <span class="SpellE">dịch</span>
<span class="SpellE">quốc</span> <span class="SpellE">tế</span> (<span class="SpellE">nếu</span> <span class="SpellE">có</span>): <?=htmlspecialchars($this->data["TEN_QUOCTE"])?><o:p></o:p></span></p>

<p class="MsoNormal" style="text-align: justify; line-height: 17pt;"><span style="font-size: 12pt; font-family: &quot;Times New Roman&quot;,&quot;serif&quot;;">3. <span class="SpellE">Trụ</span> <span class="SpellE">sở</span> <span class="SpellE">doanh</span> <span class="SpellE">nghiệp</span>:
<?=htmlspecialchars($this->data["DIACHI_TRUSO"])?><o:p></o:p></span></p>

<p class="MsoNormal" style="text-align: justify; line-height: 17pt;"><span style="font-size: 12pt; font-family: &quot;Times New Roman&quot;,&quot;serif&quot;;">4. <span class="SpellE">Số</span> <span class="SpellE">điện</span> <span class="SpellE">thoại</span> (Fax): <?=htmlspecialchars($this->data["DIENTHOAI"])?>/<?=htmlspecialchars($this->data["FAX"])?><o:p></o:p></span></p>

<p class="MsoNormal" style="text-align: justify; line-height: 17pt;"><span style="font-size: 12pt; font-family: &quot;Times New Roman&quot;,&quot;serif&quot;;">5. <span class="SpellE">Giấy</span> <span class="SpellE">chứng</span> <span class="SpellE">nhận</span> <span class="SpellE">đăng</span> <span class="SpellE">ký</span> <span class="SpellE">kinh</span> <span class="SpellE">doanh</span>
<span class="SpellE">số</span><?=" ".htmlspecialchars($this->data["DKKD_SO"])." "?>do<span class="GramE"><?=htmlspecialchars($this->data["DKKD_NOICAP"])?>
<span class="SpellE">cấp</span></span>
<span class="SpellE">ngày</span>
<?php $date =strtotime($this->data["DKKD_NGAY"]);?>
<?=date("d",$date)?><span style="">&nbsp;&nbsp;
</span><span class="SpellE"> tháng</span><?=" ".date("m",$date)." "?> <span class="SpellE">năm</span>
<?=date("Y",$date)?><o:p></o:p></span></p>

<p class="MsoNormal" style="text-align: justify; line-height: 17pt;"><span style="font-size: 12pt; font-family: &quot;Times New Roman&quot;,&quot;serif&quot;;">6. <span class="SpellE">Phạm</span> <span class="GramE">vi</span> <span class="SpellE">đăng</span>
<span class="SpellE">ký</span> <span class="SpellE">hoạt</span> <span class="SpellE">động</span>:<?=htmlspecialchars($this->data["PHAMVI_HOATDONG"])?><o:p></o:p></span></p>

<p class="MsoNormal" style="text-align: justify; line-height: 17pt;"><span style="font-size: 12pt; font-family: &quot;Times New Roman&quot;,&quot;serif&quot;;">7. <span class="SpellE">Số</span> <span class="SpellE"><span class="GramE">xe</span></span>
<span class="SpellE">đăng</span> <span class="SpellE">ký</span>:
<?php 
			echo "<b>" .count($this->danhsach) ."</b>";
	  
?>

<span class="SpellE"><span class="GramE">xe</span></span> (<span class="SpellE">danh</span> <span class="SpellE">sách</span> <span class="SpellE">xe</span>
<span class="SpellE">kèm</span> <span class="SpellE">theo</span>)<o:p></o:p></span></p>

<p class="MsoNormal" style="text-align: justify; line-height: 17pt;"><span style="font-size: 12pt; font-family: &quot;Times New Roman&quot;,&quot;serif&quot;;"><o:p>&nbsp;</o:p></span></p>


<p class="MsoNormal" style="text-align: justify; text-indent: 0.5in; line-height: 17pt;"><span class="SpellE"><span style="font-size: 12pt; font-family: &quot;Times New Roman&quot;,&quot;serif&quot;;">Doanh</span></span><span style="font-size: 12pt; font-family: &quot;Times New Roman&quot;,&quot;serif&quot;;">
<span class="SpellE">nghiệp</span> cam <span class="SpellE">kết</span> <span class="SpellE">những</span> <span class="SpellE">nội</span> dung <span class="SpellE">đã</span> <span class="SpellE">đăng</span> <span class="SpellE">ký</span> <span class="SpellE">đúng</span> <span class="SpellE">với</span>
<span class="SpellE">thực</span> <span class="SpellE">tế</span> <span class="SpellE">tại</span> <span class="SpellE">doanh</span> <span class="SpellE">nghiệp</span>.<o:p></o:p></span></p>

<p class="MsoNormal" style="text-align: justify;"><span style="font-size: 12pt; line-height: 115%; font-family: &quot;Times New Roman&quot;,&quot;serif&quot;;"><o:p>&nbsp;</o:p></span></p>


<table  style="  margin-left: 0pt; border-collapse: collapse;" border="1" cellpadding="0" cellspacing="0" width=100%>
	<thead>
		<tr>
			<td nowrap  width=30px align=center >TT</td>
			<td nowrap  align=center>Biển số xe</td>
			<td nowrap  align=center>Loại xe</td>
			<td nowrap align=center>Số ghế<br> xe</td>
			<td nowrap  align=center>Năm sx</td>
			<td nowrap  align=center>Hạn <br> kiểm định</td>
			<td align=center>Ghi chú</td>
			
		</tr>
	</thead>
	<tbody>
		<?php 
		
		
		$stt = 1;
		foreach($this->danhsach as $it){
		?>
		
		<tr>
			<td><?=$stt?></td>
			<td><?=htmlspecialchars($it["BIEN_SO"])?></td>
			<td><?=htmlspecialchars($it["LOAI_XE"])?></td>
			<td><?=htmlspecialchars($it["SO_GHE"])?></td>
			<td><?=htmlspecialchars($it["NAM_SX"])?></td>
			<td><?=htmlspecialchars($it["HAN_KD"])?></td>
			<td><?=htmlspecialchars($it["GHICHU"])?></td>
		

		</tr>
		<?php $stt++;} ?>
		
		
	</tbody>
	<tfoot>
	
	</tfoot>
</table>

<p class="MsoNormal" style="text-align: justify; text-indent: 0.5in; line-height: 17pt;"><span style="font-size: 12pt; font-family: &quot;Times New Roman&quot;,&quot;serif&quot;;"><o:p>&nbsp;</o:p></span></p>

<p class="MsoNormal" style="text-align: justify; text-indent: 0.5in; line-height: 17pt;"><span class="SpellE"><span style="font-size: 12pt; font-family: &quot;Times New Roman&quot;,&quot;serif&quot;;">Doanh</span></span><span style="font-size: 12pt; font-family: &quot;Times New Roman&quot;,&quot;serif&quot;;">
<span class="SpellE">nghiệp</span> cam <span class="SpellE">kết</span> <span class="SpellE">những</span> <span class="SpellE">nội</span> dung <span class="SpellE">đã</span> <span class="SpellE">đăng</span> <span class="SpellE">ký</span> <span class="SpellE">đúng</span> <span class="SpellE">với</span>
<span class="SpellE">thực</span> <span class="SpellE">tế</span> <span class="SpellE">tại</span> <span class="SpellE">doanh</span> <span class="SpellE">nghiệp</span>.<o:p></o:p></span></p>
<p class="MsoNormal" style="text-align: justify;"><span style="font-size: 12pt; line-height: 115%; font-family: &quot;Times New Roman&quot;,&quot;serif&quot;;"><o:p>&nbsp;</o:p></span></p>

<table class="MsoNormalTable" style="margin-left: 250.65pt; border-collapse: collapse;" border="0" cellpadding="0" cellspacing="0">
 <tbody><tr style="">
  <td style="padding: 0in 5.4pt; width: 600.3pt;" valign="top" width="308">
  <p class="MsoNormal" style="margin-left: 291.75pt; text-align: center; text-indent: -291.75pt;" align="center"><span class="SpellE"><b><span style="font-size: 12pt; line-height: 115%; font-family: &quot;Times New Roman&quot;,&quot;serif&quot;;">Chủ</span></b></span><b><span style="font-size: 12pt; line-height: 115%; font-family: &quot;Times New Roman&quot;,&quot;serif&quot;;"> <span class="SpellE">doanh</span> <span class="SpellE">nghiệp</span><o:p></o:p></span></b></p>
<br><br><br>
  <p class="MsoNormal" style="margin-left: 291.75pt; text-align: center; text-indent: -291.75pt;" align="center"><i style=""><span style="font-size: 12pt; line-height: 115%; font-family: &quot;Times New Roman&quot;,&quot;serif&quot;;">(<span class="SpellE">Ký</span> <span class="SpellE">tên</span> <span class="SpellE">đóng</span>
  <span class="SpellE">dấu</span>)<o:p></o:p></span></i></p>
  <p class="MsoNormal" style="text-align: center;" align="center"><b><span style="font-size: 12pt; line-height: 115%; font-family: &quot;Times New Roman&quot;,&quot;serif&quot;;"><o:p>&nbsp;</o:p></span></b></p>
  </td>
 </tr>
</tbody></table>

<p class="MsoNormal" style="text-align: justify; line-height: 110%;"><span class="SpellE"><b style=""><i style=""><span style="font-size: 12pt; line-height: 110%; font-family: &quot;Times New Roman&quot;,&quot;serif&quot;;">Nơi</span></i></b></span><b style=""><i style=""><span style="font-size: 12pt; line-height: 110%; font-family: &quot;Times New Roman&quot;,&quot;serif&quot;;"> <span class="SpellE">nhận</span>:<o:p></o:p></span></i></b></p>

<p class="MsoNormal" style="text-align: justify; line-height: 110%;"><span style="font-family: &quot;Times New Roman&quot;,&quot;serif&quot;;">- <span class="SpellE">Như</span> <span class="SpellE">trên</span>;<o:p></o:p></span></p>

<p class="MsoNormal" style="text-align: justify; line-height: 110%;"><span style="font-family: &quot;Times New Roman&quot;,&quot;serif&quot;;">- <span class="SpellE">Lưu</span>.<o:p></o:p></span></p>

<p class="MsoNormal"><span style="font-size: 8pt; line-height: 115%; font-family: &quot;Times New Roman&quot;,&quot;serif&quot;;"><o:p>&nbsp;</o:p></span></p>

<p class="MsoNormal"><span style="font-family: &quot;Times New Roman&quot;,&quot;serif&quot;;"><o:p>&nbsp;</o:p></span></p>
</div>
<p id=lasttext1></p>
</body>
</html>
<script>
function resize(){
	try{
		//alert("aa");
	var iframeElement = parent.document.getElementById('iframebutphe<?=$this->ID_FR?>');
	iframeElement.style.height = ""+ (document.getElementById("lasttext1").offsetTop) +"px";
	iframeElement.width = "100%"; 
	setTimeout("resize()",1000);
	}catch(ex){
	}
}

setTimeout("resize()",1000);

<?php if($this->print){?>
window.print();
<?php }?>
</script>