<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html>
<head>
<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
<script type="text/javascript" src="/js/common.js"></script>
<script src="/js/validate.js" type="text/javascript"></script>
<script src="/js/validate.js" type="text/javascript"></script>
<script type="text/javascript" src=<?php echo $this->baseUrl()."/js/Json/Base64.js"?>></script>
<script type="text/javascript" src=<?php echo $this->baseUrl()."/js/Json/json2.js"?>></script>
<script type="text/javascript" src=<?php echo $this->baseUrl()."/js/Json/json_parse.js"?>></script>
<script type="text/javascript" src=<?php echo $this->baseUrl()."/js/Ajax/AjaxEngine.js"?>></script>
<link rel="stylesheet" type="text/css" href="/styles/general.css" />
</head>
<body style="background-color:transparent">
<form name=frmUpload enctype="multipart/form-data" action="/hscv/quanlyphieutrinh/inphieu" method="post">
<table width="100%">
	<tr>
		<td nowrap class=key>File đính kèm<font color=red>*</font></td>
		<td width="100%"><input type=file name=uploadedfile onchange="CheckValue();"><span class="box_erro_area" id="ERRuploadedfile"></td>
	</tr>
</table>
<input type=hidden name=idhscv value="<?php echo $this->idhscv?>">
<input type=hidden name=idpt value="<?php echo $this->idpt?>">
</form>
<p id=lasttext></p>
</body>
</html>
<script>
var iframeElement = window.parent.document.getElementById("addPhieuTrinhFrm<?php echo $this->idhscv?>");
iframeElement.style.height = "" +(document.getElementById("lasttext").offsetTop+30)+ "px";
iframeElement.width = "100%";
function CheckValue(){
	str="File đính kèm không được để trống.";
	strerr = validateInput("req",document.frmUpload.uploadedfile,str);

	if(!strerr){
		return false;
	}
	document.frmUpload.submit();
}
</script>