<?=QLVBDHCommon::useDlgConfirm()?>
<?php 
require_once 'qtht/models/LoaiVanBanModel.php';
echo('<script>');
$status = $this->synchronousStatus;
if($status==1 || $status==0){
    $message = "Đồng bộ thành công".'\n';
    if($status==0){
        $message .= "Không có dữ liệu nào.";
    }else{
        $message .= "Thêm mới ".$this->insert." loại văn bản ".'\n';
        $message .= "Cập nhật ".$this->update." loại văn bản ".'\n';
    }
    echo 'alert("'.$message.'");';
}
else if($status==2)
{
    $message = "Đồng bộ không thành công".'\n';
    echo 'alert("'.$message.'");';
}
echo('</script>');
?>
<form name="frm" action="<?echo $this->baseUrl()?>/qtht/DanhMucLoaiVanBan" method="post"> 
<table>
		<tr>
			<td align="left" width="100%">
				Lọc:
				<input type="text" name="search" id="search" value="<?php echo htmlspecialchars($this->search); ?>" class="text_area" onchange="document.frm.page.value=1;document.frm.submit();" />
                                <input type="button" style="background: url(/images/hscv-input-bg.png) repeat-x;" onclick="document.frm.submit();" value="Tìm" />
                                <input type="button" style="background: url(/images/hscv-input-bg.png) repeat-x;" onclick="document.getElementById('search').value='';document.frm.submit();" value="Làm lại"/>
                                <input type="button" style="background: url(/images/hscv-input-bg.png) repeat-x;" value="Đồng bộ" onclick="DongBo();"/>
                                <span class="box_erro_area" id="infodb"></span>
			</td>
			<td nowrap="nowrap">
				<select name="filter_object" id="filter_object" class="inputbox" size="1" onchange="document.frm.submit();">
					<?php 
						echo LoaiVanBanModel::toComboFilter($this->filter_object);
						//echo ClassModel::ToCombo($this->class,$this->filter_object); 
					?>
				</select>
			</td>
		</tr>
</table>


<table class="adminlist">
	<thead>
		<tr>
			<th nowrap>STT</th>
			<th nowrap><input type=checkbox name=DELALL onclick="SelectAll(this,'DEL')"></th>
			<th nowrap>Ký hiệu</th>
			<th nowrap>Tên loại văn bản</th>
<!--                        tuanpp hanxuly-->
                        <th nowrap>Hạn xử lý</th>
			<th nowrap>Mã số</th>
			<th nowrap>Đã được sử dụng</th>
		</tr>
	</thead>
	
	<tbody>
<?php
$stt=0;
$i=0;

foreach ($this->data as $row ){
	$stt++;
?>
		<tr class="row<?php echo $i; ?>">
			<td nowrap align="right"><?php echo $stt ?></td>
			<td nowrap align="center">
				<input type=checkbox name=DEL[] value='<?php echo $row->ID_LVB ?>'>
			</td>
			<td nowrap>
				<?php echo htmlspecialchars($row->KYHIEU) ?>
				
			</td>
			<td width=100%>
				<a href="#" onclick = "ItemClick(<?php echo $row->ID_LVB?>);">
				<?php echo htmlspecialchars($row->NAME) ?>
				</a>
			</td>
<!--                        tuanpp cot hanxuly-->
                        <td nowrap> <?php echo QLVBDHCommon::createTextHanXuLy($row->HANXULY) ?></td>
<!--                        tuanpp End-->
			<td nowrap> <?php echo htmlspecialchars($row->CODE) ?></td>
			<td nowrap>
<?php
	$active = $row->ACTIVE;
	if($active == 1)
		echo "Có";
	else 
		echo "Không";
	echo '</td>';
?>
			
		</tr>
<?php
	$i = (-1+$i)*-1;
}
?>	
	</tbody>
		
	<tfoot>
		<tr>
			<td colspan="7">
					<div class="pagination">
						<div class="limit">Hiển thị #
							<select name="limit" id="limit" class="inputbox" size="1" onchange="document.frm.page.value = 1;document.frm.submit();" style="width:60px;">
								<option value="5">5</option>
								<option value="10">10</option>
								<option value="15">15</option>
								<option value="20">20</option>
								<option value="25">25</option>
								<option value="30">30</option>
								<option value="35">35</option>
								<option value="40">40</option>
								<script>
									document.frm.limit.value='<?php echo $this->limit ?>';
								</script>
							</select>
						</div>
						<div style="float:right"><?php echo $this->showPage; ?></div>
					</div>
			</td>
		</tr>
	</tfoot>
</table>					
<input type="hidden" name="page" value="<?php echo $this->page; ?>">
</form>

<script>
function DeleteButtonClick()
{
	var ln = 0;
	var arr = document.getElementsByName('DEL[]');
	for(var i = 0 ; i < arr.length ;i++ )
	{
		
		if(arr[i].checked == true)
		{
			ln = 1;
		}
	}
	if(ln == 1)
	{
		var func_ok = "document.frm.action='/qtht/DanhMucLoaiVanBan/delete';document.frm.method='post';document.frm.submit();";
		var func_cancel = "";
		displayConfirm("Bạn có muốn xóa không?","","",func_ok,func_cancel);
		
	}
	else
	{
		alert("Bạn phải một dòng chọn để xóa");
	}
}

function AddNewButtonClick(){
	//document.URL = "/qtht/DanhMucCoQuan/input";
	document.frm.action="/qtht/DanhMucLoaiVanBan/input";
	document.frm.method="post";
	document.frm.submit();
	
}
function ItemClick(id){
	//document.URL = "/qtht/DanhMucCoQuan/input/idCoQuan/"+id;
	document.frm.action="/qtht/DanhMucLoaiVanBan/input/idLVB/"+id;;
	document.frm.method="post";
	document.frm.submit();
}
function DongBo(){

	document.frm.action="/qtht/DanhMucLoaiVanBan/dongboloaivanban";
	document.frm.method="post";
	document.frm.submit();

}

</script>
<script>
    var ftext = document.getElementById('search');
    ftext.focus();
</script>