<form id="containerID" action="/qtht/DanhMucLoaiVanBan/save" method="post" enctype="multipart/form-data" name="datacdform" >
<fieldset>
	<div style="float: right;">
             Trường có dấu <font color="red">*</font> là bắt buộc nhập
	</div>
     <div class="required clearfix">
		<label>Ký hiệu</label>
        <input type="text" name="kyhieu" maxlength="128" value="<?php echo htmlspecialchars($this->kyhieu);?>" class="inputText" size="10" >
    	<span class="box_erro_area" id="ERRkyhieu"></span>
	</div>
	<div class="required clearfix">
		<label>Tên<font color="red">*</font></label>
        <input type="text" name="name" maxlength="128" value="<?php echo htmlspecialchars($this->namebefore);?>" class="inputText" size="10" >
    	<span class="box_erro_area" id="ERRname"></span>
	</div>
        <div class="required clearfix">
        <label>Hạn xử lý</label>                       
        <input type="text" name="HANXULY" value="<?php echo htmlspecialchars($this->hanxulybefore);?>" size="10" > ngày
        <span class="box_erro_area" id="ERRHANXULY"></span>
	</div>
	<div class="required clearfix" style="display: none">
		<label>Mã số</label>
        <input type="text" name="code" maxlength="2" value="<?php echo htmlspecialchars($this->codebefore);?>" class="inputText" size="10">
    	<span class="box_erro_area" id="ERRcode"></span>
        <span id='re_cdb'></span>
	</div>
	<div class="required clearfix">
		<label>Đã được sử dụng</label>
        <?php
            if($this->activeselect == 1){
                echo '<input type="checkbox" value=1 class="inputCheckbox" name="active" checked=checked>';
            }
            else {
                echo '<input type="checkbox" value=1 class="inputCheckbox" name="active">';
            }
        ?>
	</div>
</fieldset>
<input type=hidden name="InputIDLVB" value=<?php echo $this->id?> >
<input type=hidden name="limit" value=<?php echo $this->limit?> >
<input type=hidden name="filter_object" value=<?php echo $this->filter_object?> >
<input type=hidden name="search" value=<?php echo $this->search?> >
<input type=hidden name="page" value=<?php echo $this->page?> >
</form>
<script>
function checkFormData(){
	var str = "Bạn phải nhập tên lĩnh vực văn bản";
	var strerr = validateInput("required",document.datacdform.name,str);
	if(!strerr){
		document.datacdform.name.focus();
		return false;
	}
	str="Tên lĩnh vực không được quá 128 ký tự";
	strerr = validateInput("maxlen=128",document.datacdform.name,str);
	if(!strerr){		
		document.datacdform.name.focus();
		return false;
	}	  
		document.datacdform.submit();
        //checkmaso();

}

//function changhan(){
//	var typeValue ="1";
//	if(document.getElementById('type_1_id_HANXULY').checked){
//		typeValue = "1";
//	}
//	if(document.getElementById('type_8_id_HANXULY').checked){
//		typeValue = "8";
//	}
//	document.getElementById('type_real_id_HANXULY').value = typeValue;
//}

function SaveButtonClick(){
	//window.showModalDialog( '/DialogTemplate/QueryDialog.html',document);
    checkFormData();
}

function BackButtonClick(){
	document.datacdform.action = '/qtht/danhmucloaivanban/index';
	document.datacdform.submit();
}
// function checkmaso()
  // {
        // var loaitru = <?=$this->id!=''?$this->id:0?>;
    	// var maso = document.datacdform.code.value;        
        
        // var jx = new Jx();
        // jx.setParameter('maso',maso);
        // jx.setParameter('loaitru',loaitru);
        // jx.success('checkSuccess');
        // jx.request('/qtht/danhmucloaivanban/checkmaso','POST');
  // }
  // function checkSuccess(){
      // var re_dis = document.getElementById('ERRcode');
      // if(rs === true){
          // re_dis.innerHTML = "<div style='color : red;'>Mã số đã tồn tại</div>";
          // document.datacdform.code.focus();
      // }else{
          // re_dis.innerHTML = " ";
          // document.datacdform.submit();
      // }
      
  // }
</script>