<!DOCTYPE html>
<html>
    <head>
        <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
        <script type="text/javascript" src="/js/common.js"></script>
        <script src="/js/validate.js" type="text/javascript"></script>
        <script src="/js/validate.js" type="text/javascript"></script>
        <script type="text/javascript" src="/js/Json/Base64.js"?>></script>
        <script type="text/javascript" src="/js/Json/json2.js"?>></script>
        <script type="text/javascript" src="/js/Json/json_parse.js"?>></script>
        <script type="text/javascript" src="/js/Ajax/AjaxEngine.js"?>></script>
        <link rel="stylesheet" type="text/css" href="/styles/general.css" />
        <link rel=Stylesheet href=stylesheet.css>
    </head>
    <body style="background-color:transparent">
        <form name="frmThongKe" target="_blank" id="frmThongKe" action="/giamsatgiaoviec/baocao/thongkedetailview" enctype="multipart/form-data" method="post">
            <table class=adminlist>
                <tr>
                    <td align=center style="font-weight:bold;border: none;">Từ ngày <?= $this->fromdate ?> đến ngày <?= $this->todate ?></td>
                </tr>

            </table>

            <table class=adminlist1>
                <thead>
                    <tr>
                        <th rowspan=2>TT</th>
                        <th rowspan="2">Cơ quan thực hiện nhiệm vụ</th>
                        <th rowspan="2" style="text-align:center">Nhiệm vụ trong tháng</th>
                        <th style="text-align:center" colspan=3>Đã hoàn thành</th>
                        <th style="text-align:center" colspan=3>Chưa hoàn thành</th>
                    </tr>
                    <tr>
                        <th style="text-align:center">Trong hạn</th>
                        <th style="text-align:center">Quá hạn</th>
                        <th style="text-align:center">Tổng</th>
                        <th style="text-align:center">Trong hạn</th>
                        <th style="text-align:center">Quá hạn</th>
                        <th style="text-align:center">Tổng</th>
                    </tr>

                </thead>
                <tbody>
                    <?php
                    $stt = 0;
                    foreach ($this->dataReport as $itemreport) {
                        ?>
                        <tr>
                            <td align=center><?php echo ++$stt ?></td>
                            <td><?php echo $itemreport->TENDONVI ?></td>
                            <td align=center><a href="#" onclick="window.parent.document.frm.target = '_blank';
                                window.parent.document.frm.action = '/giaoviec/index/baocaogiaoviecdetail/REPORTTYPE/1/DONVINHAN/<?php echo $itemreport->DONVINHAN ?>';
                                window.parent.document.frm.submit();
                                window.parent.document.frm.action = '/giaoviec/index/baocaogiaoviecview';
                                window.parent.document.frm.target = '_self';
                                return false;"><?php echo $itemreport->CNTCONGVIEC ?></a></td>
                            <td align=center>
                                <?php
                                if ((int) $itemreport->CNTXONGDUNGHAN > 0) {
                                    ?>
                                    <a href="#" onclick="window.parent.document.frm.target = '_blank';
                                         window.parent.document.frm.action = '/giaoviec/index/baocaogiaoviecdetail/REPORTTYPE/2/DONVINHAN/<?php echo $itemreport->DONVINHAN ?>';
                                         window.parent.document.frm.submit();
                                         window.parent.document.frm.action = '/giaoviec/index/baocaogiaoviecview';
                                        window.parent.document.frm.target = '_self';
                                         return false;"><?php echo $itemreport->CNTXONGDUNGHAN ?></a>
                                       <?php
                                   } else
                                       echo $itemreport->CNTXONGDUNGHAN;
                                   ?>
                            </td>

                            <td align=center >
                                <?php
                                if ((int) $itemreport->CNTXONGTREHAN > 0) {
                                    ?>
                                    <a href="#" style="color: #f00;font-weight: bold" onclick="window.parent.document.frm.target = '_blank';
                                        window.parent.document.frm.action = '/giaoviec/index/baocaogiaoviecdetail/REPORTTYPE/3/DONVINHAN/<?php echo $itemreport->DONVINHAN ?>';
                                        window.parent.document.frm.submit();
                                        window.parent.document.frm.action = '/giaoviec/index/baocaogiaoviecview';
                                        window.parent.document.frm.target = '_self';
                                        return false;"><?php echo $itemreport->CNTXONGTREHAN ?></a>
                                       <?php
                                   } else
                                       echo $itemreport->CNTXONGTREHAN;
                                   ?>
                            </td>
                            <td align=center>
                                <?php
                                if ((int) $itemreport->CNTTONGDUNGHAN> 0) {
                                    ?>
                                    <a href="#" style="color: #f00;font-weight: bold" onclick="window.parent.document.frm.target = '_blank';
                                        window.parent.document.frm.action = '/giaoviec/index/baocaogiaoviecdetail/REPORTTYPE/4/DONVINHAN/<?php echo $itemreport->DONVINHAN ?>';
                                        window.parent.document.frm.submit();
                                        window.parent.document.frm.action = '/giaoviec/index/baocaogiaoviecview';
                                        window.parent.document.frm.target = '_self';
                                        return false;"><?php echo $itemreport->CNTTONGDUNGHAN ?></a>
                                       <?php
                                   } else
                                       echo $itemreport->CNTTONGDUNGHAN;
                                   ?>
                            </td>
                            <td align=center>
                                <?php
                                if ((int) $itemreport->CNTDANGTRIENKHAI > 0) {
                                    ?>
                                    <a href="#" onclick="window.parent.document.frm.target = '_blank';
                                        window.parent.document.frm.action = '/giaoviec/index/baocaogiaoviecdetail/REPORTTYPE/5/DONVINHAN/<?php echo $itemreport->DONVINHAN ?>';
                                        window.parent.document.frm.submit();
                                        window.parent.document.frm.action = '/giaoviec/index/baocaogiaoviecview';
                                        window.parent.document.frm.target = '_self';
                                        return false;"><?php echo $itemreport->CNTDANGTRIENKHAI ?></a>
                                       <?php
                                   } else
                                       echo $itemreport->CNTDANGTRIENKHAI;
                                   ?>
                            </td>

                            <td align=center>
                                <?php
                                if ((int) $itemreport->CNTDANGTRIENKHAITREHAN > 0) {
                                    ?>
                                    <a href="#" style="color: #f00;font-weight: bold" onclick="window.parent.document.frm.target = '_blank';
                                        window.parent.document.frm.action = '/giaoviec/index/baocaogiaoviecdetail/REPORTTYPE/6/DONVINHAN/<?php echo $itemreport->DONVINHAN ?>';
                                        window.parent.document.frm.submit();
                                        window.parent.document.frm.action = '/giaoviec/index/baocaogiaoviecview';
                                        window.parent.document.frm.target = '_self';
                                        return false;"><?php echo $itemreport->CNTDANGTRIENKHAITREHAN ?></a>
                                       <?php
                                   } else
                                       echo $itemreport->CNTDANGTRIENKHAITREHAN;
                                   ?>


                            </td>
                            <td align=center>
                                <?php
                                if ((int) $itemreport->CNTTONGTREHAN> 0) {
                                    ?>
                                    <a href="#" style="color: #f00;font-weight: bold" onclick="window.parent.document.frm.target = '_blank';
                                        window.parent.document.frm.action = '/giaoviec/index/baocaogiaoviecdetail/REPORTTYPE/7/DONVINHAN/<?php echo $itemreport->DONVINHAN ?>';
                                        window.parent.document.frm.submit();
                                        window.parent.document.frm.action = '/giaoviec/index/baocaogiaoviecview';
                                        window.parent.document.frm.target = '_self';
                                        return false;"><?php echo $itemreport->CNTTONGTREHAN ?></a>
                                       <?php
                                   } else
                                       echo $itemreport->CNTTONGTREHAN;
                                   ?>
                            </td>
                        </tr>
                        <?php
                    }
                    ?>
                    
                    </body>
                <tfoot>
                </tfoot>
            </table>
        </form>
        <p id="lasttext"></p>
        <script>
            function resize() {
                try {
                    var iframeElement = window.parent.document.getElementById('reportview');
                    iframeElement.style.height = "" + (document.getElementById("lasttext").offsetTop) + "px";
                    iframeElement.width = "100%";
                    setTimeout("resize()", 1000);
                } catch (ex) {
                }
            }
            resize();
        </script>
    </body>
</html>