<?php 
require_once('qtht/models/DepartmentsModel.php');
require_once 'qtht/models/Vb_nguoikyModel.php';
require_once 'qtht/models/UsersModel.php';
$data_departs = DepartmentsModel::getAll();

?>
<script type="text/javascript" src="/js/calendar.js"></script>
<script src="/jquery/jquery-1.10.2.js" type="text/javascript" ></script>
<script type="text/javascript" src="/js/validate.js"></script>
<script type="text/javascript" src="/js/Ajax/AjaxEngine.js"></script>
<script type="text/javascript" src="/js/autocomplete.js"></script>
<script type="text/javascript" src="/js/json/json_parse.js"></script>
<script language="javascript" type="text/javascript" src="/js/mail/mailautocomplete_actb.js"></script>
<script language="javascript" type="text/javascript" src="/js/mail/mailautocomplete_common.js"></script>
<link rel="stylesheet" type="text/css" href="/chosen/chosen.custom.css" />
<script src="/chosen/chosen.jquery.custom.js"></script>
<form name=frm action="/giaoviec/index/baocaogiaoviecview" method="POST">
    <div class=clr></div>
    <div>
        <select name="selectBaoCao" id="selectBaoCao" onchange="checkBaoCao()" style="width:135px">
            <option value="0">Ngày giao nhiệm vụ</option>
            <option value="1">Ngày hoàn thành</option>
            <option value="2">Ngày xác nhận hoàn thành</option>
        </select>
        <?= QLVBDHCommon::calendarFull($this->fromdate, "fromdate", "fromdate") ?>
        >>
        <?= QLVBDHCommon::calendarFull($this->todate, "todate", "todate") ?>
    </div>

    <div class=clr></div>
    <div>
        <div>
            <?php
            $year = QLVBDHCommon::getYear();
            $d = strtotime($year . "-3-1");
            $d = $d - 86400;
            $str_cuoi2 = date('d/m', $d);
            ?>            
			<label><b>Tháng:</b></label>
            <input type="radio" name='sel_timedis' onclick="setvalueDateD('1/1/<?php echo $year ?>', '31/1/<?php echo $year ?>')">1

            <input type="radio" name='sel_timedis' onclick="setvalueDateD('1/2/<?php echo $year ?>', '<?php echo $str_cuoi2 ?>/<?php echo $year ?>')" >2
            <input type="radio" name='sel_timedis' onclick="setvalueDateD('1/3/<?php echo $year ?>', '31/3/<?php echo $year ?>')">3
            <input type="radio" name='sel_timedis'onclick="setvalueDateD('1/4/<?php echo $year ?>', '30/4/<?php echo $year ?>')" >4
            <input type="radio" name='sel_timedis'onclick="setvalueDateD('1/5/<?php echo $year ?>', '31/5/<?php echo $year ?>')">5
            <input type="radio" name='sel_timedis' onclick="setvalueDateD('1/6/<?php echo $year ?>', '30/6/<?php echo $year ?>')">6
            <input type="radio" name='sel_timedis'onclick="setvalueDateD('1/7/<?php echo $year ?>', '31/7/<?php echo $year ?>')" >7
            <input type="radio" name='sel_timedis'onclick="setvalueDateD('1/8/<?php echo $year ?>', '31/8/<?php echo $year ?>')" >8
            <input type="radio" name='sel_timedis'onclick="setvalueDateD('1/9/<?php echo $year ?>', '30/9/<?php echo $year ?>')">9
            <input type="radio" name='sel_timedis'onclick="setvalueDateD('1/10/<?php echo $year ?>', '31/10/<?php echo $year ?>')">10
            <input type="radio" name='sel_timedis'onclick="setvalueDateD('1/11/<?php echo $year ?>', '30/11/<?php echo $year ?>')">11
            <input type="radio" name='sel_timedis'onclick="setvalueDateD('1/12/<?php echo $year ?>', '31/12/<?php echo $year ?>')">12
        </div>
        <div class=clr></div>
        <div>
            <label><b>Quí:</b></label>
            <input type="radio" name='sel_timedis' onclick="setvalueDateD('1/1/<?php echo $year ?>', '31/3/<?php echo $year ?>')">I
            <input type="radio" name='sel_timedis' onclick="setvalueDateD('1/4/<?php echo $year ?>', '30/6/<?php echo $year ?>')">II
            <input type="radio" name='sel_timedis'onclick="setvalueDateD('1/7/<?php echo $year ?>', '30/9/<?php echo $year ?>')">III
            <input type="radio" name='sel_timedis'onclick="setvalueDateD('1/10/<?php echo $year ?>', '31/12/<?php echo $year ?>')">IV
        </div>
        <div class=clr></div>
        <div>
            <label><b>Năm:</b></label>
            <input type="radio" name='sel_timedis' onclick="setvalueDateD('1/1/<?php echo $year ?>', '31/12/<?php echo $year ?>')">
        </div>
    </div>
    <div class=clr></div>
    <div id="trangthai" >
        <label><b>Trạng thái:</b></label>
        <select name="sel_trangthai" id="sel_trangthai">
            <option value="-1">--Chọn trạng thái--</option>
            <option value="3">Đã hoàn thành</option>
            <option value="4">Chưa hoàn thành</option>
        </select>              
    </div>
    <div class=clr></div>
    <div id="xacnhantrangthai" style="display:none">
        <label><b>Xác nhận trạng thái:</b></label>
        <select name="xacnhantrangthai" id="xacnhantrangthai">
            <option value="-1">--Chọn trạng thái--</option>
            <option value="1">Hoàn thành</option>
            <option value="2">Hoàn thành trễ hạn</option>
            <option value="3">Chưa hoàn thành</option>
        </select>              
    </div>
    <div class=clr></div>
    <div id="" >
        <label><b>Người xử lý:</b></label>
        <select name="sel_nguoisoan" id="sel_nguoisoan" onchange="">
            <option value="0">--Chọn người theo dõi--</option>
            <?php
            $data_nguoisoan = UsersModel::getAllNameAndId(1);
            foreach($data_nguoisoan as $itemnguoisoan){
            ?>
                <option value="<?=$itemnguoisoan['ID_U']?>"><?=$itemnguoisoan['NAME']?></option>
            <?php
            }
            ?>
                
        </select>              
    </div>    
    <div class="clr"></div>
    <input type=hidden id=h_isexel name=h_isexel value=0>
    <div>
        <br/>
        <input type="button" title="Hiển thị báo cáo" value="Hiển thị" onclick="document.frm.target = 'reportview';
                document.frm.h_isexel.value = 0;
                document.frm.action = '/giaoviec/index/baocaogiaoviecview';
                document.frm.submit();
                return false;" style="background: url(/images/hscv-input-bg.png) repeat-x;" >
        <input type="button" title="Xuất excel" value="Xuất Excel" onclick="document.frm.target = 'reportview';
                document.frm.h_isexel.value = 1;
                document.frm.action = '/giaoviec/index/baocaogiaoviecview/is_in/1';
                document.frm.submit();
                return false;" style="background: url(/images/hscv-input-bg.png) repeat-x;" >
        <input type="button" title="In báo cáo" value="In báo cáo" onclick="document.frm.target = '_blank';
                document.frm.h_isexel.value = 0;
                document.frm.action = '/giaoviec/index/baocaogiaoviecview/is_in/1';
                document.frm.submit();
                return false;" style="background: url(/images/hscv-input-bg.png) repeat-x;" >
    </div>
    <div class=clr></div>
</form>
<iframe  style="overflow-x:visible" allowTransparency=true BORDER=0 scrolling=no FRAMEBORDER=no 
         id="reportview" 
         name="reportview" >
</iframe>
<script>
function setvalueDateD(value_from, value_to) {
	document.frm.fromdate.value = value_from;
	document.frm.todate.value = value_to;
}
setvalueDateD('1/1/<?php echo $year ?>', '31/12/<?php echo $year ?>');
function checkBaoCao(){
    var e = document.getElementById("selectBaoCao");
    var val = $("#selectBaoCao").val();
    if(val== '2'){
        $("#trangthai").hide();
        $("#xacnhantrangthai").show();
    }else{
        $("#trangthai").show();
        $("#xacnhantrangthai").hide();
    }
}
</script>