<html xmlns:v="urn:schemas-microsoft-com:vml"
xmlns:o="urn:schemas-microsoft-com:office:office"
xmlns:x="urn:schemas-microsoft-com:office:excel"
xmlns="http://www.w3.org/TR/REC-html40">

<head>
<meta http-equiv=Content-Type content="text/html; charset=utf-8">
<meta name=ProgId content=Excel.Sheet>
<meta name=Generator content="Microsoft Excel 12">
<link id=Main-File rel=Main-File href="../baocaotkcongviec.htm">
<link rel=File-List href=filelist.xml>
<link rel=Stylesheet href=stylesheet.css>
<style>
tr
	{mso-height-source:auto;}
col
	{mso-width-source:auto;}
br
	{mso-data-placement:same-cell;}
.style0
	{mso-number-format:General;
	text-align:general;
	vertical-align:bottom;
	white-space:nowrap;
	mso-rotate:0;
	mso-background-source:auto;
	mso-pattern:auto;
	color:black;
	font-size:11.0pt;
	font-weight:400;
	font-style:normal;
	text-decoration:none;
	font-family:Calibri, sans-serif;
	mso-font-charset:0;
	border:none;
	mso-protection:locked visible;
	mso-style-name:Normal;
	mso-style-id:0;}
td
	{mso-style-parent:style0;
	padding-top:1px;
	padding-right:1px;
	padding-left:1px;
	mso-ignore:padding;
	color:black;
	font-size:11.0pt;
	font-weight:400;
	font-style:normal;
	text-decoration:none;
	font-family:Calibri, sans-serif;
	mso-font-charset:0;
	mso-number-format:General;
	text-align:general;
	vertical-align:bottom;
	border:none;
	mso-background-source:auto;
	mso-pattern:auto;
	mso-protection:locked visible;
	white-space:nowrap;
	mso-rotate:0;}
.xl65
	{mso-style-parent:style0;
	font-size:14.0pt;
	font-family:"Times New Roman", serif;
	mso-font-charset:0;}
.xl66
	{mso-style-parent:style0;
	font-size:14.0pt;
	font-family:"Times New Roman", serif;
	mso-font-charset:0;
	white-space:normal;}
.xl67
	{mso-style-parent:style0;
	font-size:18.0pt;
	font-weight:700;
	font-family:"Times New Roman", serif;
	mso-font-charset:0;
	text-align:center;}
.xl68
	{mso-style-parent:style0;
	font-size:14.0pt;
	font-family:"Times New Roman", serif;
	mso-font-charset:0;
	text-align:center;
	border-top:none;
	border-right:.5pt solid windowtext;
	border-bottom:.5pt solid windowtext;
	border-left:none;
	background:#BFBFBF;
	mso-pattern:black none;
	white-space:normal;}
.xl69
	{mso-style-parent:style0;
	font-size:14.0pt;
	font-family:"Times New Roman", serif;
	mso-font-charset:0;
	text-align:center;
	vertical-align:middle;
	border-top:none;
	border-right:.5pt solid windowtext;
	border-bottom:.5pt solid windowtext;
	border-left:none;
	background:#BFBFBF;
	mso-pattern:black none;
	white-space:normal;}
.xl70
	{mso-style-parent:style0;
	font-size:14.0pt;
	font-family:"Times New Roman", serif;
	mso-font-charset:0;
	text-align:center;
	vertical-align:middle;
	border-top:none;
	border-right:.5pt solid windowtext;
	border-bottom:.5pt solid windowtext;
	border-left:.5pt solid windowtext;
	white-space:normal;}
.xl71
	{mso-style-parent:style0;
	font-size:14.0pt;
	font-family:"Times New Roman", serif;
	mso-font-charset:0;
	text-align:left;
	vertical-align:middle;
	border-top:none;
	border-right:.5pt solid windowtext;
	border-bottom:.5pt solid windowtext;
	border-left:none;
	white-space:normal;}
.xl72
	{mso-style-parent:style0;
	font-size:14.0pt;
	font-family:"Times New Roman", serif;
	mso-font-charset:0;
	text-align:center;
	border-top:none;
	border-right:.5pt solid windowtext;
	border-bottom:.5pt solid windowtext;
	border-left:none;
	white-space:normal;}
.xl73
	{mso-style-parent:style0;
	font-size:14.0pt;
	font-weight:700;
	font-family:"Times New Roman", serif;
	mso-font-charset:0;
	text-align:center;
	white-space:normal;}
.xl74
	{mso-style-parent:style0;
	font-size:14.0pt;
	font-family:"Times New Roman", serif;
	mso-font-charset:0;
	text-align:center;
	vertical-align:middle;
	border-top:.5pt solid windowtext;
	border-right:.5pt solid windowtext;
	border-bottom:none;
	border-left:.5pt solid windowtext;
	background:#BFBFBF;
	mso-pattern:black none;
	white-space:normal;}
.xl75
	{mso-style-parent:style0;
	font-size:14.0pt;
	font-family:"Times New Roman", serif;
	mso-font-charset:0;
	text-align:center;
	vertical-align:middle;
	border-top:none;
	border-right:.5pt solid windowtext;
	border-bottom:.5pt solid windowtext;
	border-left:.5pt solid windowtext;
	background:#BFBFBF;
	mso-pattern:black none;
	white-space:normal;}
.xl76
	{mso-style-parent:style0;
	font-size:14.0pt;
	font-family:"Times New Roman", serif;
	mso-font-charset:0;
	text-align:center;
	border-top:.5pt solid windowtext;
	border-right:none;
	border-bottom:.5pt solid windowtext;
	border-left:none;
	background:#BFBFBF;
	mso-pattern:black none;
	white-space:normal;}
.xl77
	{mso-style-parent:style0;
	font-size:14.0pt;
	font-family:"Times New Roman", serif;
	mso-font-charset:0;
	text-align:center;
	border-top:.5pt solid windowtext;
	border-right:none;
	border-bottom:.5pt solid windowtext;
	border-left:.5pt solid windowtext;
	background:#BFBFBF;
	mso-pattern:black none;
	white-space:normal;}
.xl78
	{mso-style-parent:style0;
	font-size:14.0pt;
	font-family:"Times New Roman", serif;
	mso-font-charset:0;
	text-align:center;
	border-top:.5pt solid windowtext;
	border-right:.5pt solid windowtext;
	border-bottom:.5pt solid windowtext;
	border-left:none;
	background:#BFBFBF;
	mso-pattern:black none;
	white-space:normal;}
.xl79
	{mso-style-parent:style0;
	font-size:14.0pt;
	font-family:"Times New Roman", serif;
	mso-font-charset:0;
	border-top:none;
	border-right:none;
	border-bottom:none;
	border-left:.5pt solid windowtext;}
.xl80
	{mso-style-parent:style0;
	font-size:14.0pt;
	font-family:"Times New Roman", serif;
	mso-font-charset:0;
	border-top:none;
	border-right:.5pt solid windowtext;
	border-bottom:none;
	border-left:none;}
.xl81
	{mso-style-parent:style0;
	border-top:none;
	border-right:.5pt solid windowtext;
	border-bottom:none;
	border-left:none;}
.xl82
	{mso-style-parent:style0;
	font-size:14.0pt;
	font-family:"Times New Roman", serif;
	mso-font-charset:0;
	border-top:none;
	border-right:none;
	border-bottom:.5pt solid windowtext;
	border-left:.5pt solid windowtext;}
.xl83
	{mso-style-parent:style0;
	font-size:14.0pt;
	font-family:"Times New Roman", serif;
	mso-font-charset:0;
	border-top:none;
	border-right:none;
	border-bottom:.5pt solid windowtext;
	border-left:none;}
.xl84
	{mso-style-parent:style0;
	font-size:14.0pt;
	font-family:"Times New Roman", serif;
	mso-font-charset:0;
	border-top:none;
	border-right:.5pt solid windowtext;
	border-bottom:.5pt solid windowtext;
	border-left:none;}
.xl85
	{mso-style-parent:style0;
	border-top:none;
	border-right:none;
	border-bottom:.5pt solid windowtext;
	border-left:none;}
.xl86
	{mso-style-parent:style0;
	border-top:none;
	border-right:.5pt solid windowtext;
	border-bottom:.5pt solid windowtext;
	border-left:none;}
.xl87
	{mso-style-parent:style0;
	font-size:14.0pt;
	font-family:"Times New Roman", serif;
	mso-font-charset:0;
	text-align:center;
	vertical-align:middle;
	border-top:.5pt solid windowtext;
	border-right:none;
	border-bottom:none;
	border-left:.5pt solid windowtext;
	white-space:normal;}
.xl88
	{mso-style-parent:style0;
	font-size:14.0pt;
	font-family:"Times New Roman", serif;
	mso-font-charset:0;
	text-align:center;
	vertical-align:middle;
	border-top:.5pt solid windowtext;
	border-right:none;
	border-bottom:none;
	border-left:none;
	white-space:normal;}
.xl89
	{mso-style-parent:style0;
	font-size:14.0pt;
	font-family:"Times New Roman", serif;
	mso-font-charset:0;
	text-align:center;
	vertical-align:middle;
	border-top:.5pt solid windowtext;
	border-right:.5pt solid windowtext;
	border-bottom:none;
	border-left:none;
	white-space:normal;}
.xl90
	{mso-style-parent:style0;
	font-size:14.0pt;
	font-family:"Times New Roman", serif;
	mso-font-charset:0;
	text-align:center;
	vertical-align:middle;
	border-top:none;
	border-right:none;
	border-bottom:none;
	border-left:.5pt solid windowtext;
	white-space:normal;}
.xl91
	{mso-style-parent:style0;
	font-size:14.0pt;
	font-family:"Times New Roman", serif;
	mso-font-charset:0;
	text-align:center;
	vertical-align:middle;
	white-space:normal;}
.xl92
	{mso-style-parent:style0;
	font-size:14.0pt;
	font-family:"Times New Roman", serif;
	mso-font-charset:0;
	text-align:center;
	vertical-align:middle;
	border-top:none;
	border-right:.5pt solid windowtext;
	border-bottom:none;
	border-left:none;
	white-space:normal;}
.xl93
	{mso-style-parent:style0;
	font-size:14.0pt;
	font-family:"Times New Roman", serif;
	mso-font-charset:0;
	text-align:center;
	vertical-align:middle;
	border-top:.5pt solid windowtext;
	border-right:none;
	border-bottom:none;
	border-left:.5pt solid windowtext;}
.xl94
	{mso-style-parent:style0;
	font-size:14.0pt;
	font-family:"Times New Roman", serif;
	mso-font-charset:0;
	text-align:center;
	vertical-align:middle;
	border-top:.5pt solid windowtext;
	border-right:none;
	border-bottom:none;
	border-left:none;}
.xl95
	{mso-style-parent:style0;
	font-size:14.0pt;
	font-family:"Times New Roman", serif;
	mso-font-charset:0;
	text-align:center;
	vertical-align:middle;
	border-top:.5pt solid windowtext;
	border-right:.5pt solid black;
	border-bottom:none;
	border-left:none;}
.xl96
	{mso-style-parent:style0;
	font-size:14.0pt;
	font-family:"Times New Roman", serif;
	mso-font-charset:0;
	text-align:center;
	vertical-align:middle;
	border-top:none;
	border-right:none;
	border-bottom:none;
	border-left:.5pt solid windowtext;}
.xl97
	{mso-style-parent:style0;
	font-size:14.0pt;
	font-family:"Times New Roman", serif;
	mso-font-charset:0;
	text-align:center;
	vertical-align:middle;}
.xl98
	{mso-style-parent:style0;
	font-size:14.0pt;
	font-family:"Times New Roman", serif;
	mso-font-charset:0;
	text-align:center;
	vertical-align:middle;
	border-top:none;
	border-right:.5pt solid black;
	border-bottom:none;
	border-left:none;}

</style>
</head>

<body link=blue vlink=purple>

<table border=0 cellpadding=0 cellspacing=0 width=1139 style='table-layout:fixed;width:855pt'>
 <col width=44 style='mso-width-source:userset;mso-width-alt:1408;width:33pt'>
 <col width=267 style='mso-width-source:userset;mso-width-alt:8544;width:200pt'>
 <col width=106 style='mso-width-source:userset;mso-width-alt:3392;width:80pt'>
 <col width=92 style='mso-width-source:userset;mso-width-alt:2944;width:69pt'>
 <col width=81 style='mso-width-source:userset;mso-width-alt:2592;width:61pt'>
 <col width=87 style='mso-width-source:userset;mso-width-alt:2784;width:65pt'>
 <col width=81 style='mso-width-source:userset;mso-width-alt:2592;width:61pt'>
 <col width=71 style='mso-width-source:userset;mso-width-alt:2272;width:53pt'>
 <col width=86 style='mso-width-source:userset;mso-width-alt:2752;width:65pt'>
 <col width=71 style='mso-width-source:userset;mso-width-alt:2272;width:53pt'>
 <col width=84 style='mso-width-source:userset;mso-width-alt:2688;width:63pt'>
 <col width=69 style='mso-width-source:userset;mso-width-alt:2208;width:52pt'>
 <tr height=25 style='mso-height-source:userset;height:18.75pt'>
  <td height=25 class=xl66 width=44 style='height:18.75pt;width:33pt'></td>
  <td class=xl66 width=267 style='width:200pt'></td>
  <td class=xl66 width=106 style='width:80pt'></td>
  <td class=xl66 width=92 style='width:69pt'></td>
  <td class=xl66 width=81 style='width:61pt'></td>
  <td class=xl66 width=87 style='width:65pt'></td>
  <td class=xl66 width=81 style='width:61pt'></td>
  <td class=xl65 width=71 style='width:53pt'></td>
  <td class=xl65 width=86 style='width:65pt'></td>
  <td class=xl65 width=71 style='width:53pt'></td>
  <td class=xl65 width=84 style='width:63pt'></td>
  <td class=xl65 width=69 style='width:52pt'></td>
 </tr>
 <tr height=30 style='mso-height-source:userset;height:22.5pt'>
  <td colspan=12 height=30 class=xl67 style='height:22.5pt'>BÁO CÁO KẾT QUẢ
  THỰC HIỆN NHIỆM VỤ UBND TỈNH, CHỦ TÍCH, PHÓ CHỦ TỊCH</td>
 </tr>
 <tr height=30 style='mso-height-source:userset;height:22.5pt'>
  <td colspan=12 height=30 class=xl67 style='height:22.5pt'>GIAO CHO CÁC CƠ
  QUAN, ĐƠN VỊ TRỰC THUỘC</td>
 </tr>
 <tr height=30 style='mso-height-source:userset;height:22.5pt'>
  <td height=30 colspan=12 class=xl67 style='height:22.5pt;mso-ignore:colspan'></td>
 </tr>
 <tr height=25 style='mso-height-source:userset;height:18.75pt'>
  <td colspan=12 height=25 class=xl73 width=1139 style='height:18.75pt;
  width:855pt'>Từ ngày <?= $this->fromdate ?> đến ngày <?= $this->todate ?></td>
 </tr>
 <tr height=25 style='mso-height-source:userset;height:18.75pt'>
  <td colspan=12 height=25 class=xl73 width=1139 style='height:18.75pt;
  width:855pt'>Kính gửi : ..............................................</td>
 </tr>
 <tr height=25 style='mso-height-source:userset;height:18.75pt'>
  <td height=25 colspan=7 class=xl66 style='height:18.75pt;mso-ignore:colspan'></td>
  <td colspan=5 class=xl65 style='mso-ignore:colspan'></td>
 </tr>
 <tr height=25 style='mso-height-source:userset;height:18.75pt'>
  <td rowspan=2 height=75 class=xl74 width=44 style='border-bottom:.5pt solid black;
  height:56.25pt;width:33pt'>STT</td>
  <td rowspan=2 class=xl74 width=267 style='border-bottom:.5pt solid black;
  width:200pt'>Cơ quan thực hiện nhiệm vụ</td>
  <td colspan=3 class=xl77 width=279 style='border-right:.5pt solid black;
  border-left:none;width:210pt'>Nhiệm vụ được giao trong tháng</td>
  <td colspan=3 class=xl77 width=239 style='border-right:.5pt solid black;
  border-left:none;width:179pt'>Đã thực hiện</td>
  <td colspan=2 class=xl77 width=157 style='border-right:.5pt solid black;
  border-left:none;width:118pt'>Đang thực hiện</td>
  <td colspan=2 class=xl77 width=153 style='border-right:.5pt solid black;
  border-left:none;width:115pt'>Chưa thực hiện</td>
 </tr>
 <tr height=50 style='mso-height-source:userset;height:37.5pt'>
  <td height=50 class=xl68 width=106 style='height:37.5pt;width:80pt'>Kết dư từ
  tháng trước</td>
  <td class=xl68 width=92 style='width:69pt'>Nhiệm vụ trong tháng</td>
  <td class=xl68 width=81 style='width:61pt'>Tổng nhiệm vụ được giao</td>
  <td class=xl69 width=87 style='width:65pt'>Trước hạn</td>
  <td class=xl69 width=81 style='width:61pt'>Đúng hạn</td>
  <td class=xl69 width=71 style='width:53pt'>Quá hạn</td>
  <td class=xl69 width=86 style='width:65pt'>Trong hạn</td>
  <td class=xl69 width=71 style='width:53pt'>Quá hạn</td>
  <td class=xl69 width=84 style='width:63pt'>Trong hạn</td>
  <td class=xl69 width=69 style='width:52pt'>Quá hạn</td>
 </tr>
 <?php
    $stt = 0;
    $CNTTHANGTRUOC = 0;
    $CNTCONGVIEC = 0;
    $CNTXONGTRUOCHAN= 0;
    $CNTXONGDUNGHAN = 0;
    $CNTXONGTREHAN = 0;
    $CNTDANGTRIENKHAI = 0;
    $CNTDANGTRIENKHAITREHAN = 0;
    $CNTCHUATHUCHIEN = 0;
    $CNTCHUATHUCHIENTREHAN = 0;
  foreach ($this->dataReport as $itemreport) { ?> 
 <tr height=25 style='mso-height-source:userset;height:18.75pt'>
  <td height=25 class=xl70 width=44 style='height:18.75pt;width:33pt'><?php echo ++$stt ?></td>
  <td class=xl71 width=267 style='width:200pt'><?php echo $itemreport->TENDONVI ?></td>
  <td class=xl72 width=106 style='width:80pt'><?=$itemreport->CNTTHANGTRUOC?></td>
  <td class=xl72 width=92 style='width:69pt'><?=$itemreport->CNTCONGVIEC?></td>
  <td class=xl72 width=81 style='width:61pt'><?php echo (int) $itemreport->CNTTHANGTRUOC + (int) $itemreport->CNTCONGVIEC ?></td>
  <td class=xl72 width=87 style='width:65pt'><?=$itemreport->CNTXONGTRUOCHAN?></td>
  <td class=xl72 width=81 style='width:61pt'><?=$itemreport->CNTXONGDUNGHAN?></td>
  <td class=xl72 width=71 style='width:53pt'><?=$itemreport->CNTXONGTREHAN?></td>
  <td class=xl72 width=86 style='width:65pt'><?=$itemreport->CNTDANGTRIENKHAI?></td>
  <td class=xl72 width=71 style='width:53pt'><?=$itemreport->CNTDANGTRIENKHAITREHAN?></td>
  <td class=xl72 width=84 style='width:63pt'><?=$itemreport->CNTCHUATHUCHIEN?></td>
  <td class=xl72 width=69 style='width:52pt'><?=$itemreport->CNTCHUATHUCHIENTREHAN?></td>
 </tr>
 <?php
            $CNTTHANGTRUOC = $CNTTHANGTRUOC + (int)$itemreport->CNTTHANGTRUOC;
            $CNTCONGVIEC = $CNTCONGVIEC + (int)$itemreport->CNTCONGVIEC;
            $CNTXONGTRUOCHAN= $CNTXONGTRUOCHAN + (int)$itemreport->CNTXONGTRUOCHAN;
            $CNTXONGDUNGHAN = $CNTXONGDUNGHAN + (int)$itemreport->CNTXONGDUNGHAN;
            $CNTXONGTREHAN = $CNTXONGTREHAN + (int)$itemreport->CNTXONGTREHAN;
            $CNTDANGTRIENKHAI = $CNTDANGTRIENKHAI + (int)$itemreport->CNTDANGTRIENKHAI;
            $CNTDANGTRIENKHAITREHAN = $CNTDANGTRIENKHAITREHAN + (int)$itemreport->CNTDANGTRIENKHAITREHAN;
            $CNTCHUATHUCHIEN = $CNTCHUATHUCHIEN + (int)$itemreport->CNTCHUATHUCHIEN;
            $CNTCHUATHUCHIENTREHAN = $CNTCHUATHUCHIENTREHAN + (int)$itemreport->CNTCHUATHUCHIENTREHAN;
  }
    ?>
  <tr height=25 style='mso-height-source:userset;height:18.75pt'>
  <td height=25 class=xl70 width=44 style='height:18.75pt;width:33pt'><?php echo ++$stt ?></td>
  <td class=xl71 width=267 style='width:200pt'><?php echo 'Tổng cộng' ?></td>
  <td class=xl72 width=106 style='width:80pt'><?=$CNTTHANGTRUOC?></td>
  <td class=xl72 width=92 style='width:69pt'><?=$CNTCONGVIEC?></td>
  <td class=xl72 width=81 style='width:61pt'><?php echo $CNTTHANGTRUOC + $CNTCONGVIEC ?></td>
  <td class=xl72 width=87 style='width:65pt'><?=$CNTXONGTRUOCHAN?></td>
  <td class=xl72 width=81 style='width:61pt'><?=$CNTXONGDUNGHAN?></td>
  <td class=xl72 width=71 style='width:53pt'><?=$CNTXONGTREHAN?></td>
  <td class=xl72 width=86 style='width:65pt'><?=$CNTDANGTRIENKHAI?></td>
  <td class=xl72 width=71 style='width:53pt'><?=$CNTDANGTRIENKHAITREHAN?></td>
  <td class=xl72 width=84 style='width:63pt'><?=$CNTCHUATHUCHIEN?></td>
  <td class=xl72 width=69 style='width:52pt'><?=$CNTCHUATHUCHIENTREHAN?></td>
 </tr>
 <tr height=25 style='height:18.75pt'>
  <td height=25 colspan=7 class=xl65 style='height:18.75pt;mso-ignore:colspan'></td>
  <td colspan=5 style='mso-ignore:colspan'></td>
 </tr>
 <tr height=25 style='height:18.75pt'>
  <td height=25 colspan=2 class=xl65 style='height:18.75pt;mso-ignore:colspan'></td>
  <td colspan=4 rowspan=4 class=xl87 width=366 style='border-right:.5pt solid black;
  width:275pt'>LẬP BIỂU<br>
    TỔ THEO DÕI NHIỆM VỤ<br>
    TỔ TRƯỞNG</td>
  <td colspan=5 rowspan=4 class=xl93 style='border-right:.5pt solid black'>CHÁNH
  VĂN PHÒNG</td>
  <td></td>
 </tr>
 <tr height=25 style='height:18.75pt'>
  <td height=25 colspan=2 class=xl65 style='height:18.75pt;mso-ignore:colspan'></td>
  <td></td>
 </tr>
 <tr height=25 style='height:18.75pt'>
  <td height=25 colspan=2 class=xl65 style='height:18.75pt;mso-ignore:colspan'></td>
  <td></td>
 </tr>
 <tr height=25 style='height:18.75pt'>
  <td height=25 colspan=2 class=xl65 style='height:18.75pt;mso-ignore:colspan'></td>
  <td></td>
 </tr>
 <tr height=25 style='height:18.75pt'>
  <td height=25 colspan=2 class=xl65 style='height:18.75pt;mso-ignore:colspan'></td>
  <td class=xl79>&nbsp;</td>
  <td colspan=2 class=xl65 style='mso-ignore:colspan'></td>
  <td class=xl80>&nbsp;</td>
  <td class=xl65></td>
  <td colspan=3 style='mso-ignore:colspan'></td>
  <td class=xl81>&nbsp;</td>
  <td></td>
 </tr>
 <tr height=25 style='height:18.75pt'>
  <td height=25 colspan=2 class=xl65 style='height:18.75pt;mso-ignore:colspan'></td>
  <td class=xl79>&nbsp;</td>
  <td colspan=2 class=xl65 style='mso-ignore:colspan'></td>
  <td class=xl80>&nbsp;</td>
  <td class=xl65></td>
  <td colspan=3 style='mso-ignore:colspan'></td>
  <td class=xl81>&nbsp;</td>
  <td></td>
 </tr>
 <tr height=25 style='height:18.75pt'>
  <td height=25 colspan=2 class=xl65 style='height:18.75pt;mso-ignore:colspan'></td>
  <td class=xl79>&nbsp;</td>
  <td colspan=2 class=xl65 style='mso-ignore:colspan'></td>
  <td class=xl80>&nbsp;</td>
  <td class=xl65></td>
  <td colspan=3 style='mso-ignore:colspan'></td>
  <td class=xl81>&nbsp;</td>
  <td></td>
 </tr>
 <tr height=25 style='height:18.75pt'>
  <td height=25 colspan=2 class=xl65 style='height:18.75pt;mso-ignore:colspan'></td>
  <td class=xl82>&nbsp;</td>
  <td class=xl83>&nbsp;</td>
  <td class=xl83>&nbsp;</td>
  <td class=xl84>&nbsp;</td>
  <td class=xl83>&nbsp;</td>
  <td class=xl85>&nbsp;</td>
  <td class=xl85>&nbsp;</td>
  <td class=xl85>&nbsp;</td>
  <td class=xl86>&nbsp;</td>
  <td></td>
 </tr>
 <![if supportMisalignedColumns]>
 <tr height=0 style='display:none'>
  <td width=44 style='width:33pt'></td>
  <td width=267 style='width:200pt'></td>
  <td width=106 style='width:80pt'></td>
  <td width=92 style='width:69pt'></td>
  <td width=81 style='width:61pt'></td>
  <td width=87 style='width:65pt'></td>
  <td width=81 style='width:61pt'></td>
  <td width=71 style='width:53pt'></td>
  <td width=86 style='width:65pt'></td>
  <td width=71 style='width:53pt'></td>
  <td width=84 style='width:63pt'></td>
  <td width=69 style='width:52pt'></td>
 </tr>
 <![endif]>
</table>

</body>
<?php if($this->is_in = 1) { ?>
<script>print();</script>
<?php } ?>
</html>
