<table class=adminlist1>
<thead>
    <tr>
        <th nowrap rowspan=2>STT</th>
        <th rowspan=2>Văn bản</th>
        <th rowspan=2>Trích yếu văn bản</th>
        <th rowspan=2>Cơ quan thực hiện</th>
        <th rowspan=2>Nội dung nhiệm vụ</th>
        <th rowspan=2>Người theo dõi</th>
        <th rowspan=2>Người thực hiện</th>
        <th rowspan=2>Ngày giao</th>
        <th rowspan=2>Hạn xử lý</th>
        <th rowspan=2>Ngày hoàn thành</th>
        <th rowspan=2>Văn bản kết quả</th>
        <th colspan=2 style="text-align: center;">Đã thực hiện</th>
    </tr>
    <tr>
        <th>Trong hạn</th>
        <th>Quá hạn</th>
    </tr>
</thead>
<tbody>
    <?php
        $stt=0;
        foreach($this->dataReport as $itemreport){
            if(($itemreport->CNTXONGDUNGHAN == ' ') && ($itemreport->CNTXONGTREHAN == 'X')){
    ?>
    <tr>
        <td nowrap align=right><?php echo ++$stt?></td>
        <td><a href="/vbdi/banhanh/listall/SOKYHIEU/<?= base64_encode($itemreport->SOKYHIEU) ?>/base64/1"><?php echo $itemreport->SOKYHIEU?> - <?php echo QLVBDHCommon::MysqlDateToVnDate($itemreport->NGAYBANHANH)?> - <?php echo $itemreport->DONVIGIAO?></a></td>
        <td><?php echo $itemreport->TRICHYEU?></td>
        <td><?php echo $itemreport->DONVINHAN?></td>
        <td><?php echo $itemreport->TENCONGVIEC?></td>
        <td><?php echo $itemreport->CHUYENVIENTHEODOI?></td>
        <td><?php echo $itemreport->HOTENNGUOINHAN?></td>
        <td><?= date("d/m/Y", strtotime($itemreport->NGAYBANHANH)) ?></td>
        <td><?= date("d/m/Y", strtotime($itemreport->NGAYDUKIENHOANTHANH)) ?></td>
        <td>
            <?php 
            if($itemreport->NGAYHOANTHANH)
                echo date("d/m/Y", strtotime($itemreport->NGAYHOANTHANH));
            else
                echo '';
            ?>
        </td>
        <td width=10%>
            <?php 
                require_once 'giaoviec/models/GiaoViecModel.php';
                $giaoviec = new GiaoViecModel();
                $giaoviec->ShowFileAll($this->session,$itemreport->ID_CONGVIECDETAIL,$itemreport->ID_VBLIENTHONG_VAO);
            ?>
        </td>
        <td align=center>
            <?php 
                $ngayDuKienHoanThanh = date("d/m/Y", strtotime($itemreport->NGAYDUKIENHOANTHANH));
                if($itemreport->CNTXONGDUNGHAN == ' ' || $itemreport->CNTXONGDUNGHAN == NULL) {
                    if($itemreport->TRANGTHAI == 3 && $ngayDuKienHoanThanh == "01/01/1970"){
                        echo "X";
                    }else{
                        echo '';
                    }
                }else{
                    echo "X";
                }
            ?>
            
        </td>
        <td align=center>
            <?php if($itemreport->CNTXONGTREHAN == ' ' || $itemreport->CNTXONGTREHAN == NULL) {
                    echo  '';
                }else{
                    echo "X";
                }
             
            ?>
            
        </td>
    </tr>
    <?php
        } }
    ?>
                  
</body>
<tfoot>
</tfoot>
</table>
