<form name=frm method="post" action="/qtht/goiy">
	<table class="adminlist">
	<thead>
		<tr>
			<th nowrap style="text-align: center;">#</th>
			<th nowrap style="text-align: center;"><input type=checkbox name=DELALL onclick="SelectAll(this,'DEL')"></th>
			<th width="100%">Nội dung</th>
		</tr>
	</thead>
	<tfoot>
		<tr>
			<td colspan="8">
					
			</td>
		</tr>
	</tfoot>

	<tbody>
<?php
$stt=0;
$i=0;
foreach ($this->data as $row ){
	$stt++;
?>
		<tr class="row<?php echo $i; ?>">
			<td nowrap align="center"><?php echo $stt ?></td>
			<td nowrap align="center">
				<input type=checkbox name=DEL[] value='<?php echo $row['ID_GOIY'] ?>'>
			</td>
			<td nowrap>
				<a href="#" onclick = "ItemClick(<?php echo $row['ID_GOIY'] ?>);">
				<?php echo htmlspecialchars($row['NOIDUNG']) ?>
				</a>
			</td>
		</tr>
<?php
	$i = (-1+$i)*-1;
}
?>
	</tbody>
</table>
<input type="hidden" name="page" value="<?php echo $this->page; ?>">
</form>
<script>
function DeleteButtonClick(){
	var mess = true;
	mess = validateInput("selone_check","DEL[]","Phải chọn ít nhất một câu gợi ý");
	if(mess){
		if(confirm("Bạn có muốn xoá câu gợi ý này không?")){
			document.frm.action = "/qtht/goiy/Delete";
			document.frm.submit();
		}
	}else{
		alert("Phải chọn ít nhất một câu gợi ý");
	}
}
function AddNewButtonClick(){
	document.frm.action = "/qtht/goiy/input";
	document.frm.submit();
}
function ItemClick(id){
	document.frm.action = "/qtht/goiy/input/id/"+id;
	document.frm.submit();
}

</script>