<html xmlns:o="urn:schemas-microsoft-com:office:office"
xmlns:x="urn:schemas-microsoft-com:office:excel"
xmlns="http://www.w3.org/TR/REC-html40">

<head>
<meta http-equiv=Content-Type content="text/html; charset=utf-8">
<meta name=ProgId content=Excel.Sheet>
<meta name=Generator content="Microsoft Excel 12">
<link rel=File-List href="Danh%20muc%20ho%20so%20van%20ban_files/filelist.xml">
<style id="Danh muc ho so van ban_10294_Styles">
<!--table
	{mso-displayed-decimal-separator:"\.";
	mso-displayed-thousand-separator:"\,";}
.xl6310294
	{padding-top:1px;
	padding-right:1px;
	padding-left:1px;
	mso-ignore:padding;
	color:black;
	font-size:13.0pt;
	font-weight:400;
	font-style:normal;
	text-decoration:none;
	font-family:"Times New Roman", serif;
	mso-font-charset:0;
	mso-number-format:General;
	text-align:general;
	vertical-align:bottom;
	mso-background-source:auto;
	mso-pattern:auto;
	white-space:nowrap;}
.xl6410294
	{padding-top:1px;
	padding-right:1px;
	padding-left:1px;
	mso-ignore:padding;
	color:black;
	font-size:13.0pt;
	font-weight:400;
	font-style:normal;
	text-decoration:none;
	font-family:"Times New Roman", serif;
	mso-font-charset:0;
	mso-number-format:General;
	text-align:center;
	vertical-align:middle;
	border:.5pt solid windowtext;
	mso-background-source:auto;
	mso-pattern:auto;
	white-space:nowrap;}
.xl6510294
	{padding-top:1px;
	padding-right:1px;
	padding-left:1px;
	mso-ignore:padding;
	color:black;
	font-size:13.0pt;
	font-weight:700;
	font-style:normal;
	text-decoration:none;
	font-family:"Times New Roman", serif;
	mso-font-charset:0;
	mso-number-format:General;
	text-align:center;
	vertical-align:middle;
	border:.5pt solid windowtext;
	background:#BFBFBF;
	mso-pattern:black none;
	white-space:normal;}
.xl6610294
	{padding-top:1px;
	padding-right:1px;
	padding-left:1px;
	mso-ignore:padding;
	color:black;
	font-size:13.0pt;
	font-weight:700;
	font-style:normal;
	text-decoration:none;
	font-family:"Times New Roman", serif;
	mso-font-charset:0;
	mso-number-format:General;
	text-align:general;
	vertical-align:bottom;
	mso-background-source:auto;
	mso-pattern:auto;
	white-space:nowrap;}
.xl6710294
	{padding-top:1px;
	padding-right:1px;
	padding-left:1px;
	mso-ignore:padding;
	color:black;
	font-size:13.0pt;
	font-weight:400;
	font-style:normal;
	text-decoration:none;
	font-family:"Times New Roman", serif;
	mso-font-charset:0;
	mso-number-format:General;
	text-align:left;
	vertical-align:middle;
	border:.5pt solid windowtext;
	mso-background-source:auto;
	mso-pattern:auto;
	white-space:normal;}
.xl6810294
	{padding-top:1px;
	padding-right:1px;
	padding-left:1px;
	mso-ignore:padding;
	color:black;
	font-size:13.0pt;
	font-weight:400;
	font-style:normal;
	text-decoration:none;
	font-family:"Times New Roman", serif;
	mso-font-charset:0;
	mso-number-format:General;
	text-align:center;
	vertical-align:middle;
	border:.5pt solid windowtext;
	mso-background-source:auto;
	mso-pattern:auto;
	white-space:normal;}
.xl6910294
	{padding-top:1px;
	padding-right:1px;
	padding-left:1px;
	mso-ignore:padding;
	color:black;
	font-size:14.0pt;
	font-weight:700;
	font-style:normal;
	text-decoration:none;
	font-family:"Times New Roman", serif;
	mso-font-charset:0;
	mso-number-format:General;
	text-align:center;
	vertical-align:bottom;
	mso-background-source:auto;
	mso-pattern:auto;
	white-space:nowrap;}
.xl7010294
	{padding-top:1px;
	padding-right:1px;
	padding-left:1px;
	mso-ignore:padding;
	color:black;
	font-size:13.0pt;
	font-weight:400;
	font-style:normal;
	text-decoration:none;
	font-family:"Times New Roman", serif;
	mso-font-charset:0;
	mso-number-format:General;
	text-align:center;
	vertical-align:bottom;
	mso-background-source:auto;
	mso-pattern:auto;
	white-space:nowrap;}
.xl7110294
	{padding-top:1px;
	padding-right:1px;
	padding-left:1px;
	mso-ignore:padding;
	color:black;
	font-size:13.0pt;
	font-weight:700;
	font-style:normal;
	text-decoration:none;
	font-family:"Times New Roman", serif;
	mso-font-charset:0;
	mso-number-format:General;
	text-align:center;
	vertical-align:bottom;
	mso-background-source:auto;
	mso-pattern:auto;
	white-space:nowrap;}
.xl7210294
	{padding-top:1px;
	padding-right:1px;
	padding-left:1px;
	mso-ignore:padding;
	color:black;
	font-size:13.0pt;
	font-weight:400;
	font-style:italic;
	text-decoration:none;
	font-family:"Times New Roman", serif;
	mso-font-charset:0;
	mso-number-format:General;
	text-align:right;
	vertical-align:bottom;
	mso-background-source:auto;
	mso-pattern:auto;
	white-space:nowrap;}
.xl7310294
	{padding-top:1px;
	padding-right:1px;
	padding-left:1px;
	mso-ignore:padding;
	color:black;
	font-size:13.0pt;
	font-weight:700;
	font-style:normal;
	text-decoration:none;
	font-family:"Times New Roman", serif;
	mso-font-charset:0;
	mso-number-format:General;
	text-align:left;
	vertical-align:middle;
	border-top:.5pt solid windowtext;
	border-right:none;
	border-bottom:.5pt solid windowtext;
	border-left:.5pt solid windowtext;
	mso-background-source:auto;
	mso-pattern:auto;
	white-space:nowrap;}
.xl7410294
	{padding-top:1px;
	padding-right:1px;
	padding-left:1px;
	mso-ignore:padding;
	color:black;
	font-size:13.0pt;
	font-weight:400;
	font-style:normal;
	text-decoration:none;
	font-family:"Times New Roman", serif;
	mso-font-charset:0;
	mso-number-format:General;
	text-align:left;
	vertical-align:middle;
	border-top:.5pt solid windowtext;
	border-right:none;
	border-bottom:.5pt solid windowtext;
	border-left:none;
	mso-background-source:auto;
	mso-pattern:auto;
	white-space:nowrap;}
.xl7510294
	{padding-top:1px;
	padding-right:1px;
	padding-left:1px;
	mso-ignore:padding;
	color:black;
	font-size:13.0pt;
	font-weight:400;
	font-style:normal;
	text-decoration:none;
	font-family:"Times New Roman", serif;
	mso-font-charset:0;
	mso-number-format:General;
	text-align:left;
	vertical-align:middle;
	border-top:.5pt solid windowtext;
	border-right:.5pt solid windowtext;
	border-bottom:.5pt solid windowtext;
	border-left:none;
	mso-background-source:auto;
	mso-pattern:auto;
	white-space:nowrap;}
.xl7610294
	{padding-top:1px;
	padding-right:1px;
	padding-left:1px;
	mso-ignore:padding;
	color:black;
	font-size:13.0pt;
	font-weight:400;
	font-style:normal;
	text-decoration:none;
	font-family:"Times New Roman", serif;
	mso-font-charset:0;
	mso-number-format:"\[$-1010000\]d\/m\/yyyy\;\@";
	text-align:left;
	vertical-align:middle;
	border:.5pt solid windowtext;
	mso-background-source:auto;
	mso-pattern:auto;
	white-space:normal;}
-->
</style>
</head>

<body>
<!--[if !excel]>&nbsp;&nbsp;<![endif]-->
<!--The following information was generated by Microsoft Office Excel's Publish
as Web Page wizard.-->
<!--If the same item is republished from Excel, all information between the DIV
tags will be replaced.-->
<!----------------------------->
<!--START OF OUTPUT FROM EXCEL PUBLISH AS WEB PAGE WIZARD -->
<!----------------------------->

<div id="Danh muc ho so van ban_10294" align=center x:publishsource="Excel">

<table border=0 cellpadding=0 cellspacing=0 width=1010 class=xl6310294
 style='border-collapse:collapse;table-layout:fixed;width:757pt'>
 <col class=xl6310294 width=43 style='mso-width-source:userset;mso-width-alt:
 1536;width:32pt'>
 <col class=xl6310294 width=122 style='mso-width-source:userset;mso-width-alt:
 4352;width:92pt'>
 <col class=xl6310294 width=89 style='mso-width-source:userset;mso-width-alt:
 3157;width:67pt'>
 <col class=xl6310294 width=147 style='mso-width-source:userset;mso-width-alt:
 5233;width:110pt'>
 <col class=xl6310294 width=379 style='mso-width-source:userset;mso-width-alt:
 13482;width:284pt'>
 <col class=xl6310294 width=103 style='mso-width-source:userset;mso-width-alt:
 3669;width:77pt'>
 <col class=xl6310294 width=127 style='mso-width-source:userset;mso-width-alt:
 4522;width:95pt'>
 <tr height=22 style='height:16.8pt'>
  <td colspan=3 height=22 class=xl7010294 width=254 style='height:16.8pt;
  width:191pt'><?=$this->config->sys_info->unit?></td>
  <td class=xl6310294 width=147 style='width:110pt'></td>
  <td class=xl6310294 width=379 style='width:284pt'></td>
  <td class=xl6310294 width=103 style='width:77pt'></td>
  <td class=xl6310294 width=127 style='width:95pt'></td>
 </tr>
 <tr height=22 style='height:16.8pt'>
  <td colspan=3 height=22 class=xl7110294 style='height:16.8pt'><?=$this->config->sys_info->company?></td>
  <td colspan=4 class=xl7210294><?=$this->config->sys_info->city?>, ngày <?=date('d')?> tháng <?=date('m')?> năm <?=date('Y')?> </td>
 </tr>
 <tr height=22 style='height:16.8pt'>
  <td height=22 class=xl6310294 style='height:16.8pt'></td>
  <td class=xl6310294></td>
  <td class=xl6310294></td>
  <td class=xl6310294></td>
  <td class=xl6310294></td>
  <td class=xl6310294></td>
  <td class=xl6310294></td>
 </tr>
 <tr height=23 style='height:17.4pt'>
  <td colspan=7 height=23 class=xl6910294 style='height:17.4pt'>DANH MỤC HỒ SƠ VĂN BẢN</td>
 </tr>
 <tr height=50 style='mso-height-source:userset;height:37.5pt'>
  <td height=50 class=xl6510294 width=43 style='height:37.5pt;width:32pt'>TT</td>
  <td class=xl6510294 width=122 style='border-left:none;width:92pt'>Số ký hiệu VB</td>
  <td class=xl6510294 width=89 style='border-left:none;width:67pt'>Ngày ban
  hành</td>
  <td class=xl6510294 width=147 style='border-left:none;width:110pt'>Cơ quan ban hành</td>
  <td class=xl6510294 width=379 style='border-left:none;width:284pt'>Trích yếu</td>
  <td class=xl6510294 width=103 style='border-left:none;width:77pt'>Loại</td>
  <td class=xl6510294 width=127 style='border-left:none;width:95pt'>Ghi chú</td>
 </tr>
  <?php 
$idTapHscv = 0;
$stt = 0;
$loai = array("1"=>"Văn bản đến","3"=>"Văn bản ngoài","2"=>"Văn bản đi",);
foreach($this->data as $item){
    $stt++;
    if($item['ID_TAPHOSO'] != $idTapHscv){
    $idTapHscv = $item['ID_TAPHOSO'];
 ?>
 <tr height=28 style='mso-height-source:userset;height:21.0pt'>
  <td colspan=7 height=28 class=xl7310294 style='border-right:.5pt solid black;
  height:21.0pt'>T&#7853;p h&#7891; s&#417;: <?=$item['TEN_TAPHSCV']?></td>
 </tr>
 <?php } ?>
 <tr height=46 style='mso-height-source:userset;height:34.5pt'>
  <td height=46 class=xl6410294 style='height:34.5pt;border-top:none'><?=$stt?></td>
  <td class=xl6810294 width=122 style='border-top:none;border-left:none;
  width:92pt'><?=$item['SOKYHIEU']?></td>
  <td class=xl7610294 width=89 style='border-top:none;border-left:none;
  width:67pt'><?=QLVBDHCommon::MysqlDateToVnDate($item['NGAYBANHANH'])?></td>
  <td class=xl6710294 width=147 style='border-top:none;border-left:none;
  width:110pt'><?=$item['COQUANBANHANH']?></td>
  <td class=xl6710294 width=379 style='border-top:none;border-left:none;
  width:284pt'><?=$item['TRICHYEU']?></td>
  <td class=xl6810294 width=103 style='border-top:none;border-left:none;
  width:77pt'><?=$loai[$item['LOAI']]?></td>
  <td class=xl6710294 width=127 style='border-top:none;border-left:none;
  width:95pt'>&nbsp;</td>
 </tr>
  <?php } ?>
 <tr height=22 style='height:16.8pt'>
  <td height=22 class=xl6310294 style='height:16.8pt'></td>
  <td class=xl6310294></td>
  <td class=xl6310294></td>
  <td class=xl6310294></td>
  <td class=xl6310294></td>
  <td class=xl6310294></td>
  <td class=xl6310294></td>
 </tr>
 <tr height=22 style='height:16.8pt'>
  <td height=22 class=xl6310294 style='height:16.8pt'></td>
  <td class=xl6310294></td>
  <td class=xl6310294></td>
  <td class=xl6310294></td>
  <td class=xl6310294></td>
  <td class=xl6310294></td>
  <td class=xl6310294></td>
 </tr>
 <tr height=22 style='height:16.8pt'>
  <td height=22 class=xl6310294 style='height:16.8pt'></td>
  <td class=xl6310294></td>
  <td class=xl6310294></td>
  <td class=xl6610294></td>
  <td colspan=3 class=xl7110294>Người lập</td>
 </tr>
 <tr height=22 style='height:16.8pt'>
  <td height=22 class=xl6310294 style='height:16.8pt'></td>
  <td class=xl6310294></td>
  <td class=xl6310294></td>
  <td class=xl6310294></td>
  <td class=xl6310294></td>
  <td class=xl6310294></td>
  <td class=xl6310294></td>
 </tr>
 <tr height=22 style='height:16.8pt'>
  <td height=22 class=xl6310294 style='height:16.8pt'></td>
  <td class=xl6310294></td>
  <td class=xl6310294></td>
  <td class=xl6310294></td>
  <td class=xl6310294></td>
  <td class=xl6310294></td>
  <td class=xl6310294></td>
 </tr>
 <tr height=22 style='height:16.8pt'>
  <td height=22 class=xl6310294 style='height:16.8pt'></td>
  <td class=xl6310294></td>
  <td class=xl6310294></td>
  <td class=xl6310294></td>
  <td class=xl6310294></td>
  <td class=xl6310294></td>
  <td class=xl6310294></td>
 </tr>
 <tr height=22 style='height:16.8pt'>
  <td height=22 class=xl6310294 style='height:16.8pt'></td>
  <td class=xl6310294></td>
  <td class=xl6310294></td>
  <td class=xl6310294></td>
  <td colspan=3 class=xl7010294></td>
 </tr>
 <![if supportMisalignedColumns]>
 <tr height=0 style='display:none'>
  <td width=43 style='width:32pt'></td>
  <td width=122 style='width:92pt'></td>
  <td width=89 style='width:67pt'></td>
  <td width=147 style='width:110pt'></td>
  <td width=379 style='width:284pt'></td>
  <td width=103 style='width:77pt'></td>
  <td width=127 style='width:95pt'></td>
 </tr>
 <![endif]>
</table>

</div>


<!----------------------------->
<!--END OF OUTPUT FROM EXCEL PUBLISH AS WEB PAGE WIZARD-->
<!----------------------------->
</body>

</html>
