<?php require_once('qtht/models/DepartmentsModel.php');
      require_once('hscv/models/hosocongviecModel.php');
      $data_departs = DepartmentsModel::getAll();
      require_once 'qtht/models/sovanbanModel.php'
?>

<!-- Khung lọc dữ liệu -->
<div>
<form name=frm action="/report/xulygiaoviec/reportview" method="POST" target="reportview"  >
<!--
<div>
<label><b>Theo:</b></label>
<input type="radio" name="type_date"  value=0> Ngày đến
<input type="radio" name="type_date" value=1 checked> Ngày ban hành
</div>
<div class=clr></div>
-->
<div>
<label><b>Từ:</b></label>
<?=QLVBDHCommon::calendar($this->fromdate,"fromdate","fromdate") ?>
<script> function ChangeDate(){
	document.getElementById('time').value ="";
}  </script>
>>
<?=QLVBDHCommon::calendar($this->todate,"todate","todate") ?>
<script> function ChangeDate(){
	document.getElementById('time').value ="";
	}</script>
</div>
<div class=clr></div>
<div>

<label><b>Tháng:</b></label>
<input type="radio" name='sel_timedis' onclick="setvalueDateD('1/1','31/1')">1
<?php 
$year = QLVBDHCommon::getYear();
$d = strtotime($year."-3-1") ;
$d = $d - 86400;
$str_cuoi2 =date('d/m',$d); 
 ?>
<input type="radio" name='sel_timedis' onclick="setvalueDateD('1/2','<?php echo $str_cuoi2 ?>')" >2
<input type="radio" name='sel_timedis' onclick="setvalueDateD('1/3','31/3')">3
<input type="radio" name='sel_timedis'onclick="setvalueDateD('1/4','30/4')" >4
<input type="radio" name='sel_timedis'onclick="setvalueDateD('1/5','31/5')">5
<input type="radio" name='sel_timedis' onclick="setvalueDateD('1/6','30/6')">6
<input type="radio" name='sel_timedis'onclick="setvalueDateD('1/7','31/7')" >7
<input type="radio" name='sel_timedis'onclick="setvalueDateD('1/8','31/8')" >8
<input type="radio" name='sel_timedis'onclick="setvalueDateD('1/9','30/9')">9
<input type="radio" name='sel_timedis'onclick="setvalueDateD('1/10','31/10')">10
<input type="radio" name='sel_timedis'onclick="setvalueDateD('1/11','30/11')">11
<input type="radio" name='sel_timedis'onclick="setvalueDateD('1/12','31/12')">12
</div>
<div class=clr></div>
<div>
<label><b>Quí:</b></label>
<input type="radio" name='sel_timedis' onclick="setvalueDateD('1/1','31/3')">I
<input type="radio" name='sel_timedis' onclick="setvalueDateD('1/4','30/6')">II
<input type="radio" name='sel_timedis'onclick="setvalueDateD('1/7','30/9')">III
<input type="radio" name='sel_timedis'onclick="setvalueDateD('1/10','31/12')">IV
</div>
<div class=clr></div>

<div>
<label><b>Năm:</b></label>
<input type="radio" name='sel_timedis' onclick="setvalueDateD('1/1','31/12')">
</div>
<div class=clr></div>
<!--
<div>
   <label><b>Trễ hạn tính theo:</b></label>
   <input type="radio" name='trehantheo' value="2" checked> hạn xử lý văn bản
   <input type="radio" name='trehantheo' value="1"> người xử lý
</div>
<div class=clr></div>

<?php if(hosocongviecModel::isAlowSeeAllVbDen()){?>
<div>
   <label><b>Xem hồ sơ:</b></label>
   <input type="checkbox" name='hskxly' id="hskxly" value="1" 
			<?=$this->hskxly>0?"checked":""?>  onclick="aaa()">  Hồ sơ không xử lý   
</div>
<div class=clr></div>
<?php }?>
<!--
<div>
   <label><b>Chọn kiểu xuất:</b></label>
   <input type="radio" name='xuat' value=2 > Nằm dọc
   <input type="radio" name='xuat' value=1 checked> Nằm ngang
</div>
<div class=clr></div>
-->
<div>
   <label><b>Tùy biến các cột:</b></label>   
   
   <input type="checkbox"  name="soto" value="1" <?=$this->soto>0?"checked":""?> checked> Số tờ 
   <input type="checkbox" name="soden" value="1" <?=$this->soden>0?"checked":""?> checked> Số đến
   <input type="checkbox" name="trichyeu" value="1" <?=$this->trichyeu>0?"checked":""?> checked> Trích yếu
   <input type="checkbox" name="nguoixl" value="1" <?=$this->nguoixl>0?"checked":""?> checked> Người xử lý
   <input type="checkbox" name="trangthai" value="1" <?=$this->trangthai>0?"checked":""?> checked> Trạng thái
   <input type="checkbox"  name="ketquaxl" value="1" <?=$this->ketquaxl>0?"checked":""?> checked> Kết quả xử lý  
</div>
<div class=clr></div>
<div>
   <label><b></b></label>
   <input type="checkbox" name="coquanbh" value="1" <?=$this->coquanbh>0?"checked":""?> checked> Cơ quan ban hành
   <input type="checkbox" name="sokh" value="1" <?=$this->sokh>0?"checked":""?> checked> Số ký hiệu   
   <input type="checkbox" name="ngayden" value="1" <?=$this->ngayden>0?"checked":""?> > Ngày đến   
   <input type="checkbox" name="nguoiky" value="1" <?=$this->nguoiky>0?"checked":""?> > Người ký
   
   
</div>

<div class=clr></div>
<br/>
<!--
<div>
    <label><b>Sắp xếp:</b></label>
    <select name=SORTTYPE onchange="document.frm.submit();">
        <option value="ASC">Tăng dần</option>
        <option value="DESC" >Giảm dần</option>
    </select>
    <input type="checkbox" name="trichyeu" value="TRICHYEU" onclick="order(this.value)"> Trích yếu
</div>
<div class=clr></div>
-->
<div>
<label><b>Trạng thái xử lý:<br/></label>
<select name="sel_trangthai" id="sel_trangthai">
	<option value=0>[Tất cả ]</option>
	<option value=1>Đã xử lý</option>
	<option value=2>--- Không có văn bản đi</option>
	<option value=3>--- Có văn bản đi</option>
	<option value=4>Đang xử lý</option>	
</select>
<div class=clr></div>
</div>
<!--
<div >
<label><b>Sổ văn bản:</b></label>
<select name="sel_svb" id="sel_svb" >
	<option value=0>[Chọn tất cả]</option>
	<?php sovanbanModel::getSVBByUserCqDepSmartToCombo();?>
</select>
</div>	
<div class=clr></div>
-->
<br/>
<div>
<div style="float:left;padding-left:10px">
<br/>
<select style="width:60px" name="op_lvb">
	<option value=0 >Và</option>
	<option value=1>Hoặc</option>
</select>
</div>
<div style="float:left">
<b>Loại văn bản:</b><br/>
<select name="sel_lvb[]" id="sel_lvb" multiple="multiple" size=5>
	<option value=0>[Tất cả loại văn bản]</option>
	<?php LoaiVanBanModel::toComboName(); ?>
</select>
</div>

<div style="float:left;padding-left:10px">
<br/>
<select style="width:60px" name="op_cqbh">
	<option value=0>Và</option>
	<option value=1>Hoặc</option>
</select>
</div>
<div style="float:left;padding-left:10px">
<b>Cơ quan ban hành:</b><br/>
<select name="sel_cqbh[]" id="sel_cqbh" multiple="multiple" size=5>
	<option value=0>[Tất cả loại văn bản]</option>
	<?php CoquanModel::toComboName(1); ?>
</select>
</div>
<div id="nguoixuly" style="float:left;padding-left:10px">
<b>Người xử lý:</b><br/>
 <?php 
   echo QLVBDHCommon::writeSelectDepartmentUserWithSelreport('ID_DEP','ID_U')
 ?>
</div>
</div>
<br/>
<div class="clr"></div>
<input type=hidden id=time name=time value="">
<input type=hidden id=h_isexel name=h_isexel value=0>
<input type=hidden id=page name=page value=1>
<input type=hidden id=limit1 name=limit1 value=40>
<br/>
</form>
<input type="button" title="Hiện thị báo cáo" style="background: url(/images/hscv-input-bg.png) repeat-x;" 
onclick="
document.frm.target='reportview';
document.frm.h_isexel.value = 0;
document.frm.action = '/report/Xulygiaoviec/reportview';
document.frm.submit();
return false;" value="Hiển thị">

<input type="button" title="Xuất excel" style="background: url(/images/hscv-input-bg.png) repeat-x;" 
onclick="
document.frm.target='reportview';
document.frm.h_isexel.value = 1;
document.frm.action = '/report/Xulygiaoviec/reportviewexcel';
document.frm.submit();
return false;" value="Xuất ra Exel">

<input type="button" title="In báo cáo" style="background: url(/images/hscv-input-bg.png) repeat-x;" 
onclick="
document.frm.target='_blank';
document.frm.h_isexel.value = 0;
document.frm.action = '/report/Xulygiaoviec/reportview/is_in/1';
document.frm.submit();
return false;" value="In báo cáo">

</div>
<div class="clr"></div>

<iframe style="overflow-x:visible" allowTransparency=true BORDER=0 scrolling=no FRAMEBORDER=no id="reportview" name="reportview" >
</iframe>

<script>
var arr_user = new Array();
function setvalueDateD(value_from,value_to){
	document.frm.fromdate.value = value_from;
	document.frm.todate.value = value_to;
}
function aaa(){   
  if(document.getElementById('hskxly').checked==true ){
    document.getElementById('nguoixuly').style.display="none";
	
   }else{
    document.getElementById('nguoixuly').style.display ="";
	

   }
 }
 function order(sxtrichyeu)
 {
     document.frm.submit();
 }
</script>