
<form name="frm">
    <ul style="margin: 0; padding: 0; ">
        <li style="float: left; display: inline-block;">&nbsp;Từ: &nbsp;</li>
        <li style="float: left; display: inline-block;">
            <?php echo QLVBDHCommon::calendarFull(QLVBDHCommon::MysqlDateToVnDate($this->fromsearch),"fromsearch","fromsearch") ?>
            	
        </li>
        <li style="float: left; display: inline-block;">&nbsp; Đến: &nbsp; </li>
        <li style="float: left; display: inline-block;">
            <?php echo QLVBDHCommon::calendarFull(QLVBDHCommon::MysqlDateToVnDate($this->tosearch),"tosearch","tosearch") ?>
            
        </li>
        <li style="float: left; display: inline-block;">&nbsp;<input onclick="search();" type="button" value="Tìm"/></li>
        <li style="float: left; display: inline-block;"><input onclick="clearInput();" type="button" value="Nhập lại"/></li>
    </ul>
    <div style="clear: both"></div> 
<table class="adminlist">
<thead>
	<th style="width:20px; text-align: center">STT</th>
        <th style="text-align: center">Ngày yêu cầu sao lưu</th>
	<th  style="text-align: center">Nội dung</th>
        <th></th>
</thead>
<tbody>
	<?php $stt = 1 ;foreach ($this->data as $data){?>
	<tr>
	<td style="text-align: center"><?php echo $stt?></td>
	
        <td style="text-align: center"><b><?php echo date('H:i:s d/m/Y',strtotime($data["REQUEST_DATE"]))?></b></td>
        <td style="text-align: right;"><?php echo $data["CONTENT"]?></td>
        <td style="text-align: right;"><?php echo $data["DISMISS"]==0?'<a href="javascript:dismiss(\''.$data['ID'].'\')">Ngừng nhắc nhở</a>':''?></td>
	</tr>
	<?php $stt++;}?>
        <tfoot>
		<tr>
			<td colspan="7">
					<div class="pagination">
						<div class="limit">Hiển thị #
							<select name="limit" id="limit" class="inputbox" size="1" onchange="selectLimit();" style="width:60px;">
                                                                <option value="10" <?php echo $this->limit==10?'selected="selected"':''?>>10</option>
								<option value="20" <?php echo $this->limit==20?'selected="selected"':''?>>20</option>
								<option value="30" <?php echo $this->limit==30?'selected="selected"':''?>>30</option>
								<option value="40" <?php echo $this->limit==40?'selected="selected"':''?>>40</option>
								<option value="50" <?php echo $this->limit==50?'selected="selected"':''?>>50</option>
								<option value="100" <?php echo $this->limit==100?'selected="selected"':''?>>100</option>
							</select>
							
						</div>
						<div style="float:right"><?php echo $this->showPage; ?></div>
					</div>
			</td>
		</tr>
	</tfoot>
</tbody>
</table>
    
    <input hidden="hidden" name="page" value="<?php echo $this->page;?>"/>
    <input hidden="hidden" name="dismiss"/> 
   
</form>
<script>
   
    function selectLimit(){
        //alert(document.getElementById('limit').value);
        document.frm.action='/qtht/saoluu/miss';
        document.frm.limit.value= document.getElementById('limit').value;
        document.frm.method="post";
        document.frm.submit();
    }
    function search(){
        document.frm.action='/qtht/saoluu/miss';
        document.frm.fromsearch.value= document.getElementById('fromsearch').value;;
        document.frm.tosearch.value= document.getElementById('tosearch').value;;
        document.frm.method="post";
        document.frm.submit();
    }
    function clearInput(){
        document.getElementById('fromsearch').value = '';
        document.getElementById('tosearch').value = '';
    }
    function dismiss(id){
        document.frm.action='/qtht/saoluu/miss';
        document.frm.dismiss.value= id;
        document.frm.method="post";
        document.frm.submit();
    }
    
</script>

