<?php
$hscv = vbdenModel::GetAllHSCV($this->id);
$userbp = WFEngine::GetAccessUserFromTransitionNoGroup(WFEngine::GetBPTransition($hscv[0]["ID_HSCV"]));
$xltrans = WFEngine::GetNextTransitionsByTransition(WFEngine::GetBPTransition($hscv[0]["ID_HSCV"]));
$bpinfo = WFEngine::GetBPInfo($hscv[0]["ID_HSCV"]);
$bpdata = vbdenModel::GetLastBP($this->id,$bpinfo["ID_U_RECEIVE"]);

// detect chưa có hscv
if(count($hscv)==0){
	//echo "chưa có hscv";
	global $auth;
	$user = $auth->getIdentity();
	$this->wf_id_t = WFEngine::GetBeginTransition('VBD',$user->ID_DEP);//$this->parameter["wf_id_t"];
	$userbp = WFEngine::GetAccessUserFromTransitionNoGroup($this->wf_id_t);
	$xltrans = WFEngine::GetAllNextTransitionsByTransition($this->wf_id_t);
	foreach($xltrans as $xltransitem){
		if($xltransitem["ALIAS"]=="BUTPHE" && $xltransitem["ID_A_BEGIN"] != $xltransitem["ID_A_END"]){
			$this->wf_id_t=$xltransitem["ID_T"];
			break;
		}
	}
	foreach($xltrans as $xltransitem){
		if($xltransitem["ALIAS"]=="BUTPHE" && $xltransitem["ID_A_BEGIN"] == $xltransitem["ID_A_END"]){
			$this->wf_id_t_butphe=$xltransitem["ID_T"];
			break;
		}
	}
}

?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html>
<head>
<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
<script type="text/javascript" src="/js/common.js"></script>
<script src="/js/validate.js" type="text/javascript"></script>
<script src="/js/validate.js" type="text/javascript"></script>
<script type="text/javascript" src="/js/Json/Base64.js"></script>
<script type="text/javascript" src="/js/Json/json2.js"></script>
<script type="text/javascript" src="/js/Json/json_parse.js"></script>
<script type="text/javascript" src="/js/Json/json_parse_state.js"></script>
<script type="text/javascript" src="/js/Ajax/AjaxEngine.js"></script>
<link rel="stylesheet" type="text/css" href="/styles/general.css" />
</head>
<body style="background-color:transparent">
<form name="frm" method=post action="/vbden/vbden/savechuyenxllaivtbp">
<fieldset>
<legend style="color:#0066CC;">
	Chuyển xử lý
</legend>
</fieldset>
<table class=admintable width=100%>
	<tr>
		<td colspan="3"><b style="margin-left: 5px">Người BP</b>
			<select name=ID_U_BP>
				<?php foreach($userbp as $itemubp){?>
				<option value='<?=$itemubp["ID_U"]?>'><?=$itemubp["NAME"]?></option>
				<?php } ?>
			</select>
			<script>document.frm.ID_U_BP.value='<?=$bpinfo["ID_U_RECEIVE"]?>'</script>
		</td>
	</tr>
	<tr>
		<td colspan="3"><b style="margin-left: 5px">Nội dung</b>
			<textarea rows="2" cols="80" name=NOIDUNG><?=$bpdata["NOIDUNG"]?></textarea>
		</td>
	</tr>
	<tr>
		<td valign="top" nowrap="nowrap">
			<?php echo QLVBDHCommon::writeMultiSelectDepartmentUser('DEP_NGUOIGUI','NGUOIGUI')?>
		</td>
		<td valign="top"><input type="button" value="&gt;&gt;" onclick="InsertIntoArr()" style="margin-top:50px;"/></td>
		<td valign="top" width=100%><div id="listuser"></div></td>
	</tr>
</table>
<input type=button name=SEND value="Chuyển" onclick="SaveButtonClick();" class="butphe">
<input type=hidden name=id value="<?=$this->id?>">
<input type=hidden name=wf_id_t value="<?=$this->wf_id_t?>">
<?php
if(count($hscv)==0){
?>
<input type=hidden name=wf_id_t_butphe value="<?=$this->wf_id_t_butphe?>">
<input type=hidden name=ishscvnull value="1">
<?php
}
?>
<input type=hidden name=istheodoi value="1">

<p id=lasttext></p>
</form>
</body>
</html>

<script>
var retvalue;
var arr_user = new Array();
var arr_user_temp = new Array();
var arr1 = new Array();
var curcombo = null;
<?php
	foreach($hscv as $hscvitem){
		if(WFEngine::CanChuyenLaiForVTBP($hscvitem["ID_HSCV"])){
			$lastlc = WFEngine::GetCurrentTransitionInfoByIdHscv($hscvitem["ID_HSCV"]);
?>
arr_user[arr_user.length] = new Array(document.frm.DEP_NGUOIGUI.value,<?=$lastlc["ID_U_NK"]?>,'<?=$lastlc["EMPNKNAME"]?>',2,<?=$lastlc["HANXULY"]?>);
arr_user_temp[arr_user_temp.length] = new Array('<?=$lastlc["ID_U_NK"]?>');
<?php
		}
	}
?>
InsertIntoArr();
function SaveButtonClick(){
	var err = true;
	if(err==true){
		var alltype = document.getElementsByName("TYPE[]");
		for(var i=0;i<alltype.length;i++){
			if(alltype[i].value==2){
				document.frm.istheodoi.value=0;
				break;
			}else{
				document.frm.istheodoi.value=1;
			}
		}
		document.frm.submit();
	}
}
function InsertIntoArr(){
	var opt = document.frm.NGUOIGUI.options;
	for(var i=0;i<opt.length;i++){
		if(opt[i].selected){
			arr_user[arr_user.length] = new Array(document.frm.DEP_NGUOIGUI.value,opt[i].value,opt[i].text,1,'<?=$xltrans["HANXULY"]?>');
			arr_user_temp[arr_user_temp.length] = new Array(opt[i].value);
		}
	}
    //arr_user[arr_user.length] = new Array(document.frm.DEP_NGUOIGUI.value,document.frm.NGUOIGUI.value,document.frm.NGUOIGUI[document.frm.NGUOIGUI.selectedIndex].innerHTML);
    arr1[0] = new Array(100,'Tên');
    arr1[1] = new Array(0,'Chức năng');
    arr1[2] = new Array(0,'Hạn XL');
    arr1[3] = new Array(0,'Xóa');
    ShowArr('listuser',arr1,arr_user);
    FillComboBy2Combo(document.getElementById("GDEP_NGUOIGUI"),document.getElementById("DEP_NGUOIGUI"),document.getElementById("NGUOIGUI"),ARR_NGUOIGUI,arr_user_temp);
}
/**
 * Tạo lưới từ 2 mảng
 * 
 * @param String idDiv id div hoặc khung chứa lưới
 * @param int Arr1 mảng chứa tên trường và độ rộng tính theo % của trường
 * @param int Arr2 mảng chứa dữ liệu của các trường trên
 * @return html code
 */
function ShowArr(idDiv,Arr1,Arr2){
    var html;
    html = '<table class="adminlist" width=100%>';
    html += '<thead>';
    html += '<tr>';
    html += '<th nowrap>#</td>';
    for(i=0;i<Arr1.length;i++){
        if(Arr1[i][0]==0){
    		html += '<th nowrap>' + Arr1[i][1] + '</td>';
        }else{
        	html += '<th width="' + Arr1[i][0] + '%">' + Arr1[i][1] + '</td>';
        }
    }
    html += '</tr>';
    html += '</thead>';    
    html += '<tfoot><tr><th colspan=3 align=left>';
    html += '</th></tr></tfoot>';
    html += '<tbody>';
    	for(i=0;i<Arr2.length;i++){
    		html += '<tr>';
    		html += '<td nowrap align="right">' + (i + 1) + '</td>';
    		html += '<td>';
    		html += Arr2[i][2];
    		html += "<input type=hidden name=ID_U[] value="+Arr2[i][1]+">";
    		html += '</td>';
    		html += '<td nowrap>';
    		html += '<select onchange="UpdateType(this,'+i+')" name=TYPE[] style="width:80px">';
    		html += '<option value=1 '+(Arr2[i][3]==1?"selected":"")+'>Để biết</option>';
    		html += '<option value=2 '+(Arr2[i][3]==2?"selected":"")+'>Xử lý</option>';
    		html += '<option value=3 '+(Arr2[i][3]==3?"selected":"")+'>Phối hợp</option>';
    		html += '</select>';
    		html += '</td>';
    		html += '<td nowrap>';
    		html += '<input style="display:'+(Arr2[i][3]==1||Arr2[i][3]==3?"none":"")+'" id=HANXULY'+i+' onchange="UpdateHanXuLy(this,'+i+')" name=HANXULY[] type=text size=2 value="'+Arr2[i][4]+'">';
    		html += '</td>';
    		html += '<td nowrap>';
    		html += '<a href="javascript:;" onclick="arr_user_temp.splice('+i+',1);arr_user.splice('+i+',1);ShowArr(\'listuser\',arr1,arr_user);FastReload();return false;">Xóa</a>';
    		html += '</td>';
    		html += '</tr>';
        }
    	html += '</tbody>';
    	html += '</table>';
    //
	    //alert(html);
    document.getElementById(idDiv).innerHTML = html;
    resize();    	
}
function FastReload(){
	FillComboBy2Combo(document.getElementById("GDEP_NGUOIGUI"),document.getElementById("DEP_NGUOIGUI"),document.getElementById("NGUOIGUI"),ARR_NGUOIGUI,arr_user_temp);
}
function resize(){
	var iframeElement = parent.document.getElementById('iframebutphe<?=$this->id?>');
	iframeElement.style.height = "" + document.getElementById("lasttext").offsetTop + "px";
	iframeElement.width = "100%";
}
function UpdateHanXuLy(obj,i){
	arr_user[i][4] = obj.value;
}
function UpdateType(obj,i){
	curcombo = obj;
	arr_user[i][3] = obj.value;
	if(obj.value==1 || obj.value==3){
		document.getElementById("HANXULY"+i).style.display="none";
	}else{
		document.getElementById("HANXULY"+i).style.display="";
		getvalue("auth","user","checksendable","wf_id_t=<?=count($hscv)>0?$xltrans["ID_T"]:$this->wf_id_t?>&idu="+arr_user[i][1]);
	}
}
function UpdateRet(){
	if(retvalue=="0"){
		alert("Người được chọn không có quyền xử lý.");
		curcombo.value = 1;
		curcombo.onchange();
		
	}
}
resize();
</script>