<?php
	require_once 'Common/FileDinhKem.php';
	require_once('auth/models/ResourceUserModel.php');
	$disable="/isreadonly/1";
?>
<script type="text/javascript" src=<?php echo $this->baseUrl()."/js/Json/Base64.js"?>></script>
<script type="text/javascript" src=<?php echo $this->baseUrl()."/js/Json/json2.js"?>></script>

<script type="text/javascript" src=<?php echo $this->baseUrl()."/js/Json/json_parse.js"?>></script>
<script type="text/javascript" src=<?php echo $this->baseUrl()."/js/Json/json_parse_state.js"?>></script>
<script type="text/javascript" src="/js/autocomplete.js"></script>
<script type="text/javascript" src=<?php echo $this->baseUrl()."/js/Ajax/AjaxEngine.js"?>></script>
<form name=frm method=post action='/vbden/vbden/index' onclick="
if(at_container){ at_Hide(false);}" onsubmit="document.frm.page.value = 1;document.frm.action = '/vbden/vbden/index';return true;">

<div>
	<table>
	<?php if(hosocongviecModel::isAlowSeeAllVbDen()){?>
		<tr> 
			<td colspan="5"><input type="checkbox" name="IS_SEE_ALL" value="1" 
			<?=$this->IS_SEE_ALL>0?"checked":""?>
			onclick="document.frm.submit();"> 
			<b><i>Xem danh sách văn bản toàn cơ quan</i></b></td>
		</tr>
	<?php }?>

	<tr>
		<td colspan="5"><input type="checkbox" name="IS_PHOBIEN" value="1" 
			<?=$this->IS_PHOBIEN>0?"checked":""?>
			onclick="document.frm.submit();"> 
			<b><i>Xem danh sách văn bản phổ biến</i></b></td>
	</tr>

		<tr>
			<td nowrap="nowrap">Sổ văn bản</td>
			<td nowrap="nowrap">
				<select name="ID_SVB" id="ID_SVB" class="inputbox" size="1" onchange="document.frm.submit();">
            	<?php 
            		echo vbdenModel::WriteSVB((int)$this->ID_SVB,"-- Chọn tất cả  --", true);
            	?> 
        		</select>
			</td>
			<td width="10" nowrap="nowrap"></td>
			<td nowrap="nowrap">Loại văn bản</td>
			<td nowrap="nowrap">
				<select name="ID_LVB" id="ID_LVB" class="inputbox" size="1" onchange="document.frm.submit();">
            	<?php 
            		echo vbdenModel::WriteLVB((int)$this->ID_LVB,"-- Chọn tất cả  --");
            	?> 
        		</select>
			</td>
			<td width="100%"></td>
		</tr>
		<tr>
			<td nowrap="nowrap" valign=top>Nội dung</td>
			<td nowrap="nowrap" colspan="3">
				<input type=text class=inputbox name=TRICHYEU value="<?=$this->TRICHYEU?>" size=50>
				<br>
				<input type="checkbox" name=INNAME value=1 <?=$this->INNAME==1?"checked":""?>>Trong trích yếu
				<input type="checkbox" name=INFILE value=1 <?=$this->INFILE==1?"checked":""?>>Trong nội dung văn bản
			</td>
			<td width="100%"></td>
		</tr>
		
		<tr>
			<td nowrap="nowrap">Số đến</td>
			<td nowrap="nowrap"><input type=text class=inputbox name=SODEN value="<?=$this->SODEN?>" size=10>
			<input name=SODEN_ISLIKE value=1 type=checkbox <?=$this->SODEN_ISLIKE==1?"checked":""?> > Tìm gần đúng
			</td>
			
			<td width="10" nowrap="nowrap"></td>
		
			<td nowrap="nowrap">Số ký hiệu</td>
			<td nowrap="nowrap" ><input type=text class=inputbox name=SOKYHIEU value="<?=$this->SOKYHIEU?>" size=20></td>
			
		</tr>
		
		<tr>
			<td nowrap="nowrap"></td>
			<td><input type=checkbox onclick="doAdvance();">Tìm kiếm nâng cao</td>
			<td></td>
		</tr>
		<tr id=FindAdvanced2>
			<td nowrap="nowrap">Ngày đến</td>
			<td nowrap="nowrap" colspan="3">
				<?=QLVBDHCommon::calendar($this->NGAYDEN_BD,"NGAYDEN_BD","NGAYDEN_BD") ?>
				<span style="font-weight:bold;padding-left:10px;"> >> </span>
				<?=QLVBDHCommon::calendar($this->NGAYDEN_KT,"NGAYDEN_KT","NGAYDEN_KT") ?>
			</td>
			<td width="100%"></td>
		</tr>
		<tr id=FindAdvanced3>
			<td nowrap="nowrap">Ngày ban hành</td>
			<td nowrap="nowrap" colspan="3">
				<?=QLVBDHCommon::calendar($this->NGAYBANHANH_BD,"NGAYBANHANH_BD","NGAYBANHANH_BD") ?>
				<span style="font-weight:bold;padding-left:10px;"> >> </span>
				<?=QLVBDHCommon::calendar($this->NGAYBANHANH_KT,"NGAYBANHANH_KT","NGAYBANHANH_KT") ?>
			</td>
			<td width="100%"></td>
		</tr>
		<tr id=FindAdvanced4>
			<td nowrap="nowrap">Cơ quan</td>
			<td nowrap="nowrap">
				<?php
					echo QLVBDHCommon::AutoComplete(
					vbdenModel::GetDataCQ((int)$this->ID_CQ),
					"ID_CQ",
					"NAME",
					"ID_CQ",
					"COQUANBANHANH_TEXT",
					false,
					"width:200px",
					"",
					(int)$this->ID_CQ,
					'');
				?>
			</td>
			<td width="10" nowrap="nowrap"></td>
			<td nowrap="nowrap"></td>
			<td nowrap="nowrap"></td>
			<td width="100%"></td>
		</tr>
		<tr>
			<td nowrap="nowrap"></td>
			<td nowrap="nowrap">
				<input type=hidden name=advanced>
				<input type=submit value="Tìm kiếm">
				<input type=hidden name=ADVANCEDVALUE value="<?=$this->ADVANCED?>">
			</td>
			<td width="10" nowrap="nowrap"></td>
			<td nowrap="nowrap"></td>
			<td nowrap="nowrap"></td>
			<td width="100%"></td>
		</tr>
	</table>
</div>

<table class=adminlist>
	<thead>
		<tr>
			<th colspan="4">
				<div>
					<div class="limit" style="float:left;">Hiển thị #
						<select name="limit1"  style="width:60px;" id="limit1" class="inputbox" size="1" onchange="
							document.frm.page.value = 1;
							document.frm.limit2.value = document.frm.limit1.value;
							document.frm.action = '/vbden/vbden/index';
							document.frm.submit();
						">
							<option value="5" <?php if($this->limit==5){echo "selected";} ?>>5</option>
							<option value="10" <?php if($this->limit==10){echo "selected";} ?>>10</option>
							<option value="15" <?php if($this->limit==15){echo "selected";} ?>>15</option>
							<option value="20" <?php if($this->limit==20){echo "selected";} ?>>20</option>
							<option value="25" <?php if($this->limit==25){echo "selected";} ?>>25</option>
							<option value="30" <?php if($this->limit==30){echo "selected";} ?>>30</option>
							<option value="35" <?php if($this->limit==35){echo "selected";} ?>>35</option>
							<option value="40" <?php if($this->limit==40){echo "selected";} ?>>40</option>
							<option value="50" <?php if($this->limit==50){echo "selected";} ?>>50</option>
							<option value="100" <?php if($this->limit==100){echo "selected";} ?>>100</option>
						</select>
					</div>
					<div class="limit" style="float:right;"><?php echo $this->showPage; ?></div>
				</div>
			</th>
		</tr>
		<tr>
			<th nowrap="nowrap">
				#
			</th>
			<th width="100%">
				Sắp xếp theo 
				<select name=SORTBY onchange="document.frm.submit();">
					
					<option value="NGAYDEN" <?=($this->SORTBY?"":"selected")?> >Ngày đến</option>
				</select>
				<script>
					document.frm.SORTBY.value="<?=$this->SORTBY?>";
					
				</script>
				<?php
					if( $this->SORTBY != "DA_XEM" ){
				?>
				
				<select name=SORTTYPE onchange="document.frm.submit();">
					<option value="ASC">Tăng dần</option>
					<option value="DESC" >Giảm dần</option>
				</select>
				<input type=checkbox name=CHUA_DOC value=1 <?=$this->CHUA_DOC==1?"checked":""?> onclick="document.frm.submit();" > Chưa đọc
				<script>
					document.frm.SORTTYPE.value="<?=$this->SORTTYPE?>";
				</script>
				<?php } ?>
				
				
			</th>
			<th nowrap="nowrap">
				&nbsp;
			</th>
		</tr>
	</thead>
	<tfoot>
		<tr>
			<th colspan="3">
				<div class="pagination">
					<div class="limit">Hiển thị #
						<select name="limit2" style="width:60px;" id="limit2" class="inputbox" size="1" onchange="
							document.frm.page.value = 1;
							document.frm.limit1.value = document.frm.limit2.value;
							document.frm.action = '/vbden/vbden/index';
							document.frm.submit();
						">
							<option value="5" <?php if($this->limit==5){echo "selected";} ?>>5</option>
							<option value="10" <?php if($this->limit==10){echo "selected";} ?>>10</option>
							<option value="15" <?php if($this->limit==15){echo "selected";} ?>>15</option>
							<option value="20" <?php if($this->limit==20){echo "selected";} ?>>20</option>
							<option value="25" <?php if($this->limit==25){echo "selected";} ?>>25</option>
							<option value="30" <?php if($this->limit==30){echo "selected";} ?>>30</option>
							<option value="35" <?php if($this->limit==35){echo "selected";} ?>>35</option>
							<option value="40" <?php if($this->limit==40){echo "selected";} ?>>40</option>
							<option value="50" <?php if($this->limit==50){echo "selected";} ?>>50</option>
							<option value="100" <?php if($this->limit==100){echo "selected";} ?>>100</option>
						</select>
					</div>
					<div style="float:right"><?php echo $this->showPage; ?></div>
				</div>
			</th>
		</tr>
	</tfoot>
	<tbody>
<?php
	if(count($this->data)<=0){
		echo "<tr><td colspan='3'>Không tìm thấy hồ sơ công việc nào<td></tr>";
	}else{
	$stt=($this->page-1)*$this->limit;
	$i=0;
	foreach($this->data as $row){
		//var_dump($row);
		$stt++;
		$row['TRICHYEU'] = $this->INNAME==1?QLVBDHCommon::highlightWords($row['TRICHYEU'],$this->TRICHYEU):$row['TRICHYEU'];
?>
		<tr class="row<?=$this->ID_VBD==$row['ID_VBD']?"2":$i?>">
			<td valign="top"><a name="vbden<?=$row['ID_VBD']?>"></a><?=$stt?></td>
			<td><?php
				$vbdeninfo = $this->vbden->find($row["ID_VBD"])->current();
				echo "<b>".$vbdeninfo->SOKYHIEU." - ".QLVBDHCommon::MysqlDateToVnDate($vbdeninfo->NGAYBANHANH)." - ".$vbdeninfo->COQUANBANHANH_TEXT."</b><br>";
				?>
				<?=$row['TRICHYEU']?>
				<?php
					if($this->INFILE==1){
						$dt = PhienBanDuThaoModel::getFileContentFromVBD($row['ID_VBD']);
						foreach($dt as $itemdt){
							$rfind = QLVBDHCommon::highlightString($itemdt['CONTENT'],$this->TRICHYEU);
							if($rfind!=""){
				?>
				<br><a href="/hscv/File/download?year=&maso=<?=$itemdt['MASO']?>"><B><?=$itemdt['FILENAME']?>:</B> <?=$rfind?></a>
				<?php 
							}
						}
					}
				?>
				<?php //if(isset()){
					//$key = array_search($row["ID_VBD"],$this->arr_idnews);
					//echo $row['DA_XEM'];
					 
					if($row['DA_XEM']>1){
						echo "
						<img id='image_new_".$row['ID_VBD']. "' src='/images/moi.gif'>
						";
					}
					$id_url = "/id/".$row["ID_HSCV"];
					$isidvbden = "/isidvbden=0";
					//if($row["IS_KHONGXULY"] || QLVBDHCommon::getYear()==2008){
						$id_url = "/id/".$row["ID_VBD"];
						$isidvbden = "/isidvbden/1";
					//}
				?>
				<div>
					<ul class="chitiethscv">					
						<li id=groupicon1_<?=$row["ID_VBD"]?>>
							<img src="/images/icon_chitiet.jpg" border="0" hspace="5" >
							<a href='javascript:
					{	SwapDiv(<?=$row["ID_VBD"]?>,"/vbden/vbden/detail/type/1<?=$id_url?><?=$isidvbden?>/year/<?=$this->realyear?><?=$disable?>",1);  
						updateImageNew(<?php echo '"image_new_'.$row["ID_VBD"].'"'?>,<?=$row["ID_VBD"]?>);
					}
					'>Chi tiết</a>
						</li>						
					<?php if(!$row["IS_KHONGXULY"]){?>
					<li id=groupicon2_<?=$row["ID_VBD"]?>>
						<img src="/images/icon_butphe.jpg" border="0" hspace="5" >
						<a href='javascript:{SwapDiv(<?=$row["ID_VBD"]?>,"/hscv/hscv/viewbutphe/id/<?=$row["ID_HSCV"]?>/id_vbd/<?=$row["ID_VBD"]?>/year/<?=$this->realyear?><?=$disable?>",2); updateImageNew(<?php echo '"image_new_'.$row["ID_VBD"].'"'?>,<?=$row["ID_VBD"]?>);}'>Bút phê</a>
					</li>
					
					<?php /*
					<li id=groupicon4_<?=$row["ID_VBD"]?>>
						<img src="/images/icon_files.jpg" border="0" hspace="5" >
						<a href='javascript:SwapDiv(<?=$row["ID_HSCV"]?>,"/hscv/file/index/iddiv/groupcontent<?=$row["ID_HSCV"]?>/idObject/<?=$row["ID_VBD"]?>/is_new/0/year/<?=$this->realyear?>/type/3<?=$disable?>",4)'>File đính kèm</a>
					</li>
					*/?>
					<?php }?>
					<li id=groupicon6_<?=$row["ID_VBD"]?>>
						<img src="/images/icon_luanchuyen.jpg" border="0" hspace="5" >
						<a href='javascript:{ SwapDiv(<?=$row["ID_VBD"]?>,"/vbden/vbden/way/id_vbd/<?=$row["ID_VBD"]?>/id/<?=$row["ARR_HSCV"]?>/year/<?=$this->realyear?>/type/1/code/vbd",6);updateImageNew(<?php echo '"image_new_'.$row["ID_VBD"].'"'?>,<?=$row["ID_VBD"]?>);}'>Luân chuyển</a>
					</li>
					
					<li id=groupicon7_<?=$row["ID_VBD"]?>>
						<img src="/images/icon_vbden.jpg" border="0" hspace="5" >
						<a href='javascript:{SwapDiv(<?=$row["ID_VBD"]?>,"/vbden/vbden/vbdilienquan/id_vbd/<?=$row["ID_VBD"]?>/id/<?=$row["ARR_HSCV"]?>/year/<?=$this->realyear?>/type/1/code/vbd",6);updateImageNew(<?php echo '"image_new_'.$row["ID_VBD"].'"'?>,<?=$row["ID_VBD"]?>);}'>Văn bản đi</a>
					</li>
			
					<li>
						<?php echo $row["IS_KHONGXULY"]==0?"":"<font color='blue' ><b>(Văn bản không chuyển xử lý) </b></font>" ?>
					</li>
					</ul>
					
					<div class="clr"></div>
					<div class="groupcontent" id="groupcontent<?=$row["ID_VBD"]?>" style="display:none"></div>
				</div>
				
			</td>
			
			<?php 
			
			$actionid = ResourceUserModel::getActionByUrl('vbden','vbden','inputvbden');
			$auth = Zend_Registry::get('auth');
			if($ln = ResourceUserModel::isAcionAlowed($auth->getIdentity()->USERNAME,$actionid[0]) && vbdenModel::CanEdit($row['ID_VBD'])){
			?>
			<td nowrap="nowrap" valign="top">		
			<a href="/vbden/vbden/inputvbden?id_vbd=<?php echo $row['ID_VBD']?>">Cập nhật</a>
			<?php 
				if($row['IS_KHONGXULY'] == 1){ 
			?>
					<br>
					<a href="/vbden/vbden/delete?id=<?php echo $row['ID_VBD']?>">Xóa</a>
			<?php 
				}else{
					if($this->config->hscv->vtbp==1){
			?>
					<br>
					<a href="#" onclick="SwapIframe(<?=$row["ID_VBD"]?>,'/vbden/vbden/chuyenxllaivtbp/id/<?=$row["ID_VBD"]?>');return false;">Chuyển xử lý</a>
			<?php 
					}
				}
			?>
			</td>
			<?php 
			}else{
			?>
			<td nowrap="nowrap" valign="top">&nbsp;</td>
			<?php }?>
		</tr>
<?php
		$i = (-1+$i)*-1;	
	}
}
?>
	</tbody>
</table>
<input type="hidden" name="page" value="<?php echo $this->page; ?>">
</form>
<script>
	function CreateButtonClick(url){
		document.frm.action = url;
		document.frm.submit();
	}
	function SwapDiv(id,url,tab){
		for(var i=1;i<11;i++){
			if(document.getElementById("groupicon"+i+"_"+id)){
				if(tab!=i){
					if(document.getElementById("groupicon"+i+"_"+id).className=="groupiconopen"){
						document.getElementById("groupcontent"+id).style.display="none";
						document.getElementById("groupicon"+i+"_"+id).className = "groupicon";
						break;
					}
				}
			}
		}
		if(document.getElementById("groupcontent"+id).style.display==""){
			document.getElementById("groupcontent"+id).style.display="none";
			document.getElementById("groupicon"+tab+"_"+id).className = "groupicon";
		}else{
			document.getElementById("groupcontent"+id).style.display="";
			document.getElementById("groupicon"+tab+"_"+id).className = "groupiconopen";
			document.getElementById("groupcontent"+id).innerHTML="<img src='/images/loading.gif' width='16' height='16' border='0'></img<img src='/images/loading.gif' width='16' height='16' border='0'></img><img src='/images/loading.gif' width='16' height='16' border='0'></img><img src='/images/loading.gif' width='16' height='16' border='0'></img>";
			loadDivFromUrl("groupcontent"+id,url,1);

		}
	}
	function SwapIframe(id,url){
		for(var i=1;i<11;i++){
			if(document.getElementById("groupicon"+i+"_"+id)){
				if(document.getElementById("groupicon"+i+"_"+id).className=="groupiconopen"){
					document.getElementById("groupcontent"+id).style.display="none";
					document.getElementById("groupicon"+i+"_"+id).className = "groupicon";
					break;
				}
			}
		}
		if(document.getElementById('groupcontent'+id).style.display == ''){
			document.getElementById('groupcontent'+id).style.display = 'none';
		}else{
			document.getElementById('groupcontent'+id).innerHTML = '<iframe style="overflow-x:visible" height=0 id=iframebutphe'+id+' allowTransparency=true BORDER=0 scrolling=no FRAMEBORDER=no src="'+url+'"></iframe>';
			document.getElementById('groupcontent'+id).style.display = '';
		}
	}
	function Swap(id,url){
		if(document.getElementById(id).style.display==""){
			document.getElementById(id).style.display="none";
			document.getElementById("groupicon"+id).className = "groupicon";
		}else{
			document.getElementById(id).style.display="";
			document.getElementById("groupicon"+id).className = "groupiconopen";
			loadDivFromUrl(id,url,1);
		}
	}	
	// Sự kiện khi thay đổi text box cơ quan
    function CQClick(){
       if(document.frm.ID_CQ.value==0){
    	   document.getElementById('COQUANBANHANH_TEXT').style.display="block";
    	   document.frm.COQUANBANHANH_TEXT.value="<?php echo (!isset($this->data->COQUANBANHANH_TEXT) || $this->data->COQUANBANHANH_TEXT=='')?MSG11001017:$this->data->COQUANBANHANH_TEXT ?>"; 
       }
       else{
    	   document.getElementById('COQUANBANHANH_TEXT').style.display="none";    	   
       }
    }
    //
    //CQClick();
    function updateImageNew(iddiv,id){
    	var oimg = document.getElementById(iddiv);
    	if(oimg != null){
    		if(oimg.style.display != 'none'){
	    	oimg.style.display = 'none';
	    	
	    	var AE = new AjaxEngine();
			var oXmlHttp = AE.createXMLHttp(); 	
		    <?php 
		    $authen = Zend_Registry::get('auth');
		    $user = $authen->getIdentity();
		    ?>
			var url = '/vbden/vbden/updatedadoc?year=<?=QLVBDHCommon::getYear()?>&id_vbd='+id+'&id_u=<?=$user->ID_U?>';
			oXmlHttp.open('post', url , true);
		    oXmlHttp.setRequestHeader("Content-Type", "application/x-www-form-urlencoded");
		    oXmlHttp.onreadystatechange = function () { 
		        if (oXmlHttp.readyState == 4) { 
		        	if (oXmlHttp.status == 200) {             	
		            	//alert(oXmlHttp.responseText);
		        	} else { 
		            	
		            }            
		        } 
		    };  
		    oXmlHttp.send(null);   
    		}
    	}
	    
    }

	function chonsapxep(){
		if(document.frm.SORTBY.value == "DAXEM")
			document.frm.SORTTYPE.style.display = 'none';
		else 
			document.frm.SORTTYPE.style.display = '';
	}
	function doAdvance(){
		for(var i=1;i<10;i++){
			if(document.getElementById("FindAdvanced"+i)){
				if(document.getElementById("FindAdvanced"+i).style.display==""){
					document.getElementById("FindAdvanced"+i).style.display="none";
					document.frm.advanced.value="Nâng cao";
					document.frm.ADVANCEDVALUE.value=0;

				}else{
					document.getElementById("FindAdvanced"+i).style.display="";
					document.frm.advanced.value="Cơ bản";
					document.frm.ADVANCEDVALUE.value=1;
				}
			}
		}
	}
	<?php
		if($this->ADVANCED==0){
			echo "doAdvance();";
		}
	?>
</script>
<?php
$end = (float) array_sum(explode(' ',microtime())); 
 
//echo "Processing time: ". sprintf("%.4f", ($end-$this->start))." seconds"
?>