<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html>
<head>
<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
<script type="text/javascript" src="/js/common.js"></script>
<script src="/js/validate.js" type="text/javascript"></script>
<script src="/js/validate.js" type="text/javascript"></script>
<script type="text/javascript" src="/js/Json/Base64.js"></script>
<script type="text/javascript" src="/js/Json/json2.js"></script>
<script type="text/javascript" src="/js/Json/json_parse.js"></script>
<script type="text/javascript" src="/js/Json/json_parse_state.js"></script>
<script type="text/javascript" src="/js/Ajax/AjaxEngine.js"></script>
<link rel="stylesheet" type="text/css" href="/styles/general.css" />
</head>
<body style="background-color:transparent">
<form name="frm" method=post action="/vbden/vbden/savechuyenxulylanhdao">
<table width=100%>
	<tr><td nowrap valign=top><font size="2" color="#0000ff">Dòng luân chuyển</font></td><td valign=top width=100%>
<?  $xl= WFEngine::GetProcessLogByObjectId((int)$this->idhscv);
			   
				/*phuongpt them CHUCDANH*/
			$rowsend = $xl[0]['EMPNCNAME'];
//                                                        $rowsend1 = $xl[0]['EMPNNNAME'];
		for($j=0;$j<count($xl);$j++){
			if($j==10){
			$rowsend .="<br/>" ;
			$rowsend .=" -> " ;
			$rowsend .= $xl[$j]['EMPNCNAME'];
										
//                                                        $rowsend1 .="->" ;
//                                                        $rowsend1 .= $xl[$j]['NAME'];
			}else{
				if($rowsend != $xl[$j]['EMPNCNAME'])
				{
					$rowsend .=" -> " ;
					$rowsend .= $xl[$j]['EMPNCNAME'];
				}
//                                                                if($rowsend1 != $xl[$j]['EMPNNNAME'])
//                                                                {
//                                                                    $rowsend1 .= $xl[$j]['EMPNNNAME'];
//                                                                }
			}
		}
		$rowsend .=" -> " ;
		$rowsend .= $xl[$j-1]['EMPNNNAME'];
		echo $rowsend;
?>	
	</td></tr>
	<tr><td valign=top nowrap><font size="2" color="#0000ff">Lãnh đạo bút phê</font></td><td valign=top width=100%>
		<?php
				// Lấy người có quyền bút phê từ workflow
					$userbp = WFEngine::GetAccessUserFromTransitionNoGroup($this->wf_id_t);
					$xltrans = WFEngine::GetAllNextTransitionsByTransition($this->wf_id_t);
					$stringoptionuserbp = "";
					foreach($userbp as $userbpitem){
						$stringoptionuserbp.="<option value=".$userbpitem["ID_U"].">".htmlspecialchars($userbpitem["NAME"])."</option>";
					}
		?>
		<table width=100% class=adminlist1>
			<thead>
				<tr>
					<th nowrap>STT</th>
					<th nowrap>Người bút phê</th>
					<th nowrap>Ngày bút phê</th>
					<th width=100%>Nội dung bút phê</th>
					<th nowrap>Xoá</th>
				</tr>
			</thead>
			<tbody>
	<?php
				for($loopbp = 1;$loopbp<20;$loopbp++){
	?>
				<tr class=row<?=$loopbp%2?> <?=$loopbp>2?"style='display:none'":""?> id=rowbutphe<?=$loopbp?>>
					<td nowrap align=right><?=$loopbp?></td>
					<td nowrap>
						<select id=rowbutphe_nguoibutphe<?=$loopbp?> name=ID_U_BP[] onchange="if(this.value>-1){document.getElementById('rowbutphe<?=$loopbp+1?>').style.display='';resize();}">
							<?php if($loopbp>1){?>
							<option value=-1>--Chọn lãnh đạo--</option>
							<?php } ?>
							<?php if($loopbp==1){
								foreach($userbp as $userbpitem){
									if($userbpitem["ID_U"]==$this->currenttrans["ID_U_NK"]){
									echo "<option value=".$userbpitem["ID_U"].">".htmlspecialchars($userbpitem["NAME"])."</option>";
									}
								}
							} else { ?>
							<?=$stringoptionuserbp?>
							<?php } ?>
						</select>
					</td>
					<td nowrap><?=QLVBDHCommon::calendarFullWithNoEvent(date("d/m/Y"),"NGAYBUTPHE[]","rowbutphe_ngaybutphe".$loopbp) ?></td>
					<td width=100%><textarea id=rowbutphe_noidungbp<?=$loopbp?> style="width:98%" name=NOIDUNG_BP[]></textarea></td>
					<td nowrap><?php if($loopbp>1){?><a href="#" onclick="Delete(<?=$loopbp?>); return false;">Xoá</a><?php } ?></td>
				</tr>
	<?php
				}
	?>
			</tbody>
			<tfoot>
				<tr>
					<td colspan=5>
					<?php
						foreach($xltrans as $xltransitem){
							if($xltransitem["ALIAS"]=="BUTPHE" && $xltransitem["ID_A_BEGIN"] != $xltransitem["ID_A_END"]){
					?>
					<input type=hidden name=wf_id_t value="<?=$xltransitem["ID_T"]?>">
					<?php
								break;
							}
						}
					?>
					<?php
						foreach($xltrans as $xltransitem){
							if($xltransitem["ALIAS"]=="BUTPHE" && $xltransitem["ID_A_BEGIN"] == $xltransitem["ID_A_END"]){
					?>
					<input type=hidden name=wf_id_t_butphe value="<?=$xltransitem["ID_T"]?>">
					<?php
								break;
							}
						}
					?>
					</td>
				</tr>
			</tfoot>
		</table>
	</td></tr>
	<tr><td valign=top nowrap><font size="2" color="#0000ff">Chuyển phòng xử lý</font></td><td valign=top width=100%>
		<table width=100%>
			<tr>
				<td valign=top><?php echo QLVBDHCommon::writeMultiSelectDepartmentUser('DEP_NGUOIGUI','NGUOIGUI',true)?></td>
				<td id="listuser" valign=top width=100%></td>
			</tr>
		</table>
	</td></tr>
</table>

<input type=button name=SEND value="Chuyển" onclick="SaveButtonClick();" class="chuyenxuly">
<input type=hidden name=idvbd value=<?=$this->id?>>
<input type=hidden name=idhscv value=<?=$this->idhscv?>>
<p id=lasttext></p>
</form>
</body>
</html>
<script>
function SaveButtonClick(){
	document.frm.submit();
}
function resize(){
	var iframeElement = parent.document.getElementById('iframebutphe<?=$this->id?>');
	iframeElement.style.height = "" + document.getElementById("lasttext").offsetTop + "px";
	iframeElement.width = "100%";
}
resize();
function Delete(rownum){
	for(var i=rownum;i<19;i++){
		document.getElementById("rowbutphe_nguoibutphe"+i).value=document.getElementById("rowbutphe_nguoibutphe"+(i+1)).value;
		document.getElementById("rowbutphe_noidungbp"+i).value=document.getElementById("rowbutphe_noidungbp"+(i+1)).value;
		document.getElementById("rowbutphe_ngaybutphe"+i).value=document.getElementById("rowbutphe_ngaybutphe"+(i+1)).value;
	}

	for(var i=19;i>2;i--){
		if(document.getElementById("rowbutphe"+i).style.display==""){
			document.getElementById("rowbutphe"+i).style.display="none";
			break;
		}
	}
	resize();
}
     var arr_user = new Array();
    var arr_user_temp = new Array();
	var arr_user_smsemail = new Array();
    var arr1 = new Array();
    var curcombo = null;
  function InsertIntoArr(){
	var op_chuyen = 1;
	if(arr_user.length==0){
		op_chuyen = 2;
	}
	var opt = document.frm.NGUOIGUI.options;
	for(var i=0;i<opt.length;i++){
		if(opt[i].selected){
			arr_user[arr_user.length] = new Array(document.frm.DEP_NGUOIGUI.value,opt[i].value,opt[i].text,op_chuyen,'<?=$this->hanxuly?>',1,"","","","","");
			arr_user_temp[arr_user_temp.length] = new Array(opt[i].value);
			for(j=0;j<ARR_NGUOIGUI.length;j++){
				if(ARR_NGUOIGUI[j][2]==opt[i].value){
					arr_user_smsemail[arr_user_smsemail.length] = ARR_NGUOIGUIsmsemail[j];
					break;
				}
			}
		}
	}
    //arr_user[arr_user.length] = new Array(document.frm.DEP_NGUOIGUI.value,document.frm.NGUOIGUI.value,document.frm.NGUOIGUI[document.frm.NGUOIGUI.selectedIndex].innerHTML);
    arr1[0] = new Array(100,'Tên');
    arr1[1] = new Array(0,'Chức năng');
    arr1[2] = new Array(0,'Hạn XL');
    arr1[3] = new Array(0,'Xóa');
    ShowArr('listuser',arr1,arr_user);
    FillComboBy2Combo(document.getElementById("GDEP_NGUOIGUI"),document.getElementById("DEP_NGUOIGUI"),document.getElementById("NGUOIGUI"),ARR_NGUOIGUI,arr_user_temp);
}
    /**
     * Tạo lưới từ 2 mảng
     * 
     * @param String idDiv id div hoặc khung chứa lưới
     * @param int Arr1 mảng chứa tên trường và độ rộng tính theo % của trường
     * @param int Arr2 mảng chứa dữ liệu của các trường trên
     * @return html code
     */
    function ShowArr(idDiv,Arr1,Arr2){
        var html="";

		if(Arr2.length!=0){
        html = '<table class="adminlist1" width=100%>';
        html += '<thead>';
        html += '<tr>';
        html += '<th nowrap>#</td>';
        for(i=0;i<Arr1.length;i++){
            if(Arr1[i][0]==0){
        		html += '<th nowrap>' + Arr1[i][1] + '</td>';
            }else{
            	html += '<th width="' + Arr1[i][0] + '%">' + Arr1[i][1] + '</td>';
            }
        }
        html += '</tr>';
        html += '</thead>';    
        html += '<tfoot><tr><th colspan=5 align=left>';
        html += '</th></tr></tfoot>';
        html += '<tbody>';
        	for(i=0;i<Arr2.length;i++){
html += '<tr>';
html += '<td nowrap align="right">' + (i + 1) + '</td>';
html += '<td>';
html += ''+(Arr2[i][2]);
html += "<input type=hidden name=ID_U_XL[] value="+Arr2[i][1]+">";
html += '</td>';
html += '<td nowrap>';
html += '<select onchange="UpdateType(this,'+i+')" name=TYPE_XL[] style="width:80px">';
html += '<option value=1 '+(Arr2[i][3]==1?"selected":"")+'>Để biết</option>';
html += '<option value=2 '+(Arr2[i][3]==2?"selected":"")+'>Xử lý</option>';
html += '<option value=3 '+(Arr2[i][3]==3?"selected":"")+'>Phối hợp</option>';
html += '</select>';
html += '<span id=wf_smsemail'+i+' '+(arr_user_smsemail[i]>0?"":"style='display:none'")+'><br><span '+((arr_user_smsemail[i]==3 || arr_user_smsemail[i]==1)?"":"style='display:none'")+'> SMS<input type=checkbox onclick="document.getElementById(\'SMS'+i+'\').value=(this.checked?1:0);arr_user['+i+'][6]=(this.checked?1:0);" '+(Arr2[i][6]==1?"checked":"")+'> </span><span '+((arr_user_smsemail[i]==3 || arr_user_smsemail[i]==2)?"":"style='display:none'")+'> Email<input type=checkbox onclick="document.getElementById(\'EMAIL'+i+'\').value=(this.checked?1:0);arr_user['+i+'][7]=(this.checked?1:0);" '+(Arr2[i][7]==1?"checked":"")+'></span></span>';
html += '<input type=hidden name=SMS[] value='+(Arr2[i][6]==1?"1":"0")+' id=SMS'+i+'><input type=hidden name=EMAIL[] value='+(Arr2[i][7]==1?"1":"0")+' id=EMAIL'+i+'>';
html += '</td>';
html += '<td nowrap>';
html += '<span id=SPANHANXULY'+i+' style="display:'+(Arr2[i][3]==1||Arr2[i][3]==3?"none":"")+'">'+calendarFull(Arr2[i][8],'NGAY_KETTHUC'+i,'ChangeDate','ChangeDate('+i+')')+createInputHanxuly('HANXULY'+i,'HANXULY[]',Arr2[i][4],'UpdateHanXuLy('+i+')',(Arr2[i][3]==1||Arr2[i][3]==3?"none":""),Arr2[i][5])+"</span>";
//html += '<input style="display:'+(Arr2[i][3]==1||Arr2[i][3]==3?"none":"")+'" id=HANXULY'+i+' onchange="UpdateHanXuLy(this,'+i+')" name=HANXULY_XL[] type=text size=2 value="'+Arr2[i][4]+'">';
html += '</td>';
html += '<td nowrap>';
html += '<a href="javascript:;" onclick="arr_user_temp.splice('+i+',1);arr_user.splice('+i+',1);arr_user_smsemail.splice('+i+',1);ShowArr(\'listuser\',arr1,arr_user);FastReload();return false;">Xóa</a>';
html += '</td>';
html += '</tr>';
            }
        	html += '</tbody>';
        	html += '</table>';
        }
        document.getElementById(idDiv).innerHTML = html;
		for(i=0;i<Arr2.length;i++){
			if(document.getElementById("NGAY_KETTHUC"+i).value=="")UpdateHanXuLy(i);
		} 
		resize();
    }
    function FastReload(){
    	FillComboBy2Combo(document.getElementById("GDEP_NGUOIGUI"),document.getElementById("DEP_NGUOIGUI"),document.getElementById("NGUOIGUI"),ARR_NGUOIGUI,arr_user_temp);
    }
    function UpdateHanXuLy(i){
    	arr_user[i][4] = document.getElementById("HANXULY"+i).value;
		arr_user[i][5] = document.getElementById("type_real_HANXULY"+i).value;
    }
    function UpdateType(obj,i){
    	curcombo = obj;
    	arr_user[i][3] = obj.value;
    	if(obj.value==1 || obj.value==3){
    		document.getElementById("span_HANXULY"+i).style.display="none";
			document.getElementById("SPANHANXULY"+i).style.display="none";
    	}else{
			document.getElementById("span_HANXULY"+i).style.display="";
			document.getElementById("SPANHANXULY"+i).style.display="";
    		getvalue("auth","user","checksendable","wf_id_t="+document.frm.wf_id_t.value+"?>&idu="+arr_user[i][1]);
    	}
    }
    function UpdateRet(){
    	if(retvalue=="0"){
    		alert("Người được chọn không có quyền xử lý.");
    		curcombo.value = 1;
    		curcombo.onchange();
    		
    	}
    }
	var stthan = 0;
	function UpdateRethanxuly(){
		document.getElementById("HANXULY"+stthan).value=retvalue;
		arr_user[stthan][4] = document.getElementById("HANXULY"+stthan).value;
    }
	function UpdateRetntthuc(){
		document.getElementById("NGAY_KETTHUC"+stthan).value=retvalue;
		arr_user[stthan][4] = document.getElementById("HANXULY"+stthan).value;
		arr_user[stthan][5] = document.getElementById("type_real_HANXULY"+stthan).value;
		arr_user[stthan][8] = retvalue;
    }
	function ChangeDate(i){
		stthan = i;
		//alert(i);
        getvalue("auth","user","adddatehanxuly","date="+document.getElementById("NGAY_KETTHUC"+stthan).value+"&all="+document.getElementById("type_real_HANXULY"+stthan).value+"","UpdateRethanxuly");
    }
	function UpdateHanXuLy(i){
		stthan = i;
		getvalue("auth","user","adddate","all="+document.getElementById("type_real_HANXULY"+stthan).value+"&value="+(parseInt(document.getElementById("HANXULY"+stthan).value,10)),"UpdateRetntthuc");
	}

</script>