<?php require_once 'Common/FileDinhKem.php';?>
<?php 

	$actid = ResourceUserModel::getActionByUrl('hscv','chuyennoibo','chuyennoiboinput');
	$is_cnb = ResourceUserModel::isAcionAlowed($this->user->USERNAME,$actid[0]);

$arr_col = Common_Sovanban::getColumNameGroup(1);
$len_arr = count($arr_col);

if($len_arr==0){
	$year=QLVBDHCommon::getYear();
	$cur_soden = Common_Sovanban::getCurrentSoden($year,array());
}
$url = "";$is_new = 1;$type = -1;$id_f_object = 0; $is_nogetcontent = 1;
if($this->id_vbnhan){
	if($this->count_files_vbnhan > 0){
		$id_f_object = $this->id_vbnhan;
		$is_new = 0;
		$type =13;
	}
}else if($this->data->ID_VBDNB){
	
		if($this->count_files_vbnhannobo > 0){
		//foreach($this->files_vbnhannobo as $file_vbnb){
			$gen_temp = new gen_tempModel();
			$new_object = $gen_temp->getIdTemp();			
			filedinhkemModel::copyFile(QLVBDHCommon::getYear(),$this->id_vbnhannoibo,$new_object,15,-1);
		//}
		
		$id_f_object = $new_object;
		$is_new = 0;
		$type =-1;
	}
}
if ($this->id_object != '') {
    $id_f_object = $this->id_object;
    $is_new = 0;
}
$url ="'/hscv/file/index/enableDragAndDrop/1/?iddiv=idFileDinhKem&idObject=$id_f_object&is_new=".$is_new."&type=".$type."&is_nogetcontent=".$is_nogetcontent."'" ;
?>

<script type="text/javascript" src="/js/Ajax/AjaxEngine.js"></script>
<script type="text/javascript" src="/js/json/json_parse.js"></script>
<script type="text/javascript" src="/js/autocomplete.js"></script>
<form name=frm method="post" action="/vbden/vbden/SaveDraft" target="submitfrm" >

<div id="checkdata_err" align="left" style="display:none;">
<font color="Red">Văn bản này đã có trong hệ thống</font>
</div>

<div id="load_checkdata_all" align="right" style="display:none;">
<img src='/images/loading.gif'> <font color="Blue">Đang kiểm tra dữ liệu nhập, xin chờ ...</font>
</div>
<table width="100%"  onclick="if(at_container){ if(at_container.style.display!='none')at_Hide(false);}" >
	<?php 
	$cqnhan = vbdenModel::GetDataCQN((int)$this->data->COQUANNHAN,true);
	if( count($cqnhan) > 1){?>
	<tr>
		<td nowrap="nowrap" valign="top">
			<font color="Blue">Cơ quan nhận</font>
			<font color="Red" size="3">*</font>
		</td>
		<td nowrap="nowrap" valign="top">
			
			<select name="COQUANNHAN" onchange="changeCQNHAN(true)" >
				<?php foreach($cqnhan as $cq ){?>
					<option value="<?=$cq["ID_CQ"]?>"><?=$cq["NAME"]?></option>
				<?php } ?>
			</select>
			
			<?php
				
				/*echo QLVBDHCommon::AutoComplete(
				$cqnhan,
				"ID_CQ",
				"NAME",
				"COQUANNHAN",
				"COQUANNHAN_TEXT",
				true,
				"width:200px",
				"changeCQNHAN();",
				(int)$cqnhan[0]["ID_CQ"],
				'');*/
			?>
			<script></script>
			<div class="clr"></div>
			<span class="box_erro_area" id="ERRCOQUANNHAN_TEXT"></span>	
		</td>
	   
	</tr>
	<?php } else {?>
	<input type=hidden name="COQUANNHAN" value=<?=(int)$cqnhan[0]["ID_CQ"]?>>
	
	<?php }?>
	<tr>
		<td nowrap="nowrap" valign="top">
			<font color="Blue"><?php echo MSG11001005 ?></font>
			<font color="Red" size="3">*</font>
		</td>
		<td nowrap="nowrap" valign="top">
			<?php
				foreach($arr_col as $col)
				$onok = "";
				if($col == 'ID_SVB')
     				$onok = 'checkData(4,document.frm.ID_SVB.value)';
				echo QLVBDHCommon::AutoComplete(
				vbdenModel::GetDataSVB((int)$this->data->ID_SVB),
				"ID_SVB",
				"NAME",
				"ID_SVB",
				"ID_SVB_TEXT",
				true,
				"width:200px",
				"$onok;selectloaivb();selecthanxulytoanbo();",
				(int)$this->data->ID_SVB,
				'');
			?>
			<div class="clr"></div>            
			<span class="box_erro_area" id="ERRID_SVB"></span> 			
		</td>
		<td width=20 nowrap="nowrap"></td>
		<td nowrap="nowrap" valign="top">
			<font color="Blue"><?php echo MSG11001008 ?></font>
			<font color="Red" size="3">*</font>
		</td>
		<td nowrap="nowrap" valign="top">
			<?php
				$onok = "";
				foreach($arr_col as $col)
					if($col == 'ID_LVB')
	     				$onok = 'checkData(4,document.frm.ID_LVB.value)';
				echo QLVBDHCommon::AutoComplete(
				vbdenModel::GetDataLVB((int)$this->data->ID_LVB),
				"ID_LVB",
				"NAME",
				"ID_LVB",
				"ID_LVB_TEXT",
				true,
				"width:200px",
				"$onok;if (document.frm.ID_LVB.value!=0) {checkData(5,document.frm.ID_LVB.value)};selecthanxulytoanbo();",
				(int)$this->data->ID_LVB,
				$this->data->ID_LVB_TEXT);
			?>
			<div class="clr"></div>            
			<span class="box_erro_area" id="ERRID_LVB"></span>
		</td>
		<td width="100%"></td>
	</tr>
	<tr>
		<td nowrap="nowrap" valign="top">
			<font color="Blue">Số, ký hiệu VB</font>
			<font color="Red" size="3">*</font>	
		</td>
		<td nowrap="nowrap" valign="top">
                    <input type=text style="width: 200px;" class=inputbox name=SOKYHIEU value="<?=$this->data->SOKYHIEU?>"  
			onchange="checkData(1,document.frm.SOKYHIEU.value);return true;"
			>
			<div class="clr"></div>
			<span class="box_erro_area" id="ERRSOKYHIEU"></span>		
		</td>
		<td width=20 nowrap="nowrap"></td>
		<td nowrap="nowrap" valign="top">
			<font color="Blue"><?php echo MSG11001010 ?></font>
			<font color="Red" size="3">*</font>
		</td>
		<td nowrap="nowrap" valign="top">
			<input type=text class=inputbox size="4" name=SODEN value="<?php
				if($this->data->SODEN==0){
					echo $cur_soden+1;
				}else{
					echo $this->data->SODEN;
				}
				?>" size=50 onchange="checkData(2,this.value); return true;">
			<img id="id_img_den" src='/images/loading.gif' style="display:none;"/>
			<div class="clr"></div>
			<span class="box_erro_area" id="ERRSODEN"></span>	
		</td>
		<td width="100%"></td>
	</tr>
	<tr>
		<td nowrap="nowrap" valign="top">
			<font color="Blue"><?php echo MSG11001012 ?></font>
			<font color="Red" size="3">*</font>
		</td>
		<td nowrap="nowrap" valign="top">
			<?=QLVBDHCommon::calendarFullWithNoEvent(QLVBDHCommon::MysqlDateToVnDate($this->data->NGAYBANHANH),"NGAYBANHANH","NGAYBANHANH") ?>
			<div class="clr"></div>
			<span class="box_erro_area" id="ERRNGAYBANHANH"></span>	
		</td>
		<td width=20 nowrap="nowrap"></td>
		<td nowrap="nowrap" valign="top">
			<font color="Blue"><?php echo MSG11001011 ?></font>
			<font color="Red" size="3">*</font>
		</td>
		<td nowrap="nowrap" valign="top">
			<?=QLVBDHCommon::calendarFullWithNoEvent(QLVBDHCommon::MysqlDateToVnDate($this->data->NGAYDEN),"NGAYDEN","NGAYDEN") ?>
			<div class="clr"></div>
			<span class="box_erro_area" id="ERRNGAYDEN"></span> 
		</td>
		<td width="100%"></td>
	</tr>
	
	
	<tr>
		<td nowrap="nowrap" valign="top">
			<font color="Blue"><?php echo MSG11001007 ?></font>
			<font color="Red" size="3">*</font>
		</td>
		<td nowrap="nowrap" valign="top">
			<?php
				echo QLVBDHCommon::AutoComplete(
				vbdenModel::GetDataCQ((int)$this->data->ID_CQ),
				"ID_CQ",
				"LONGNAME",
				"ID_CQ",
				"COQUANBANHANH_TEXT",
				false,
				"width:400px",
				"",
				(int)$this->data->ID_CQ,
				$this->data->COQUANBANHANH_TEXT);
			?>
			<div class="clr"></div>
			<span class="box_erro_area" id="ERRCOQUANBANHANH_TEXT"></span>	
		</td>
		<td width=20 nowrap="nowrap"></td>
		<td nowrap="nowrap" valign="top">
			<font color="Blue">Người ký</font>
		</td>
		<td nowrap="nowrap" valign="top">
			<?=QLVBDHCommon::AutoComplete(
				vbdenModel::GetDataNguoiKy(),
				"NGUOIKY_ID",
				"NGUOIKY",
				"NGUOIKY_ID",
				"NGUOIKY",
				false,
				"width:300px",
				"",
				(int)$this->data->NGUOIKY,
				$this->data->NGUOIKY);
			?>
			<div class="clr"></div>
			<span class="box_erro_area" id="ERRNGUOIKY"></span>
		</td>
		
	</tr>
	

	<tr>
		<td nowrap="nowrap" valign="top">
			<font color="Blue"><?php echo MSG11001004 ?></font>
			<font color="Red" size="3">*</font>
		</td>
		<td nowrap="nowrap" valign="top" colspan="4">
			<TEXTAREA NAME="TRICHYEU" ROWS="2" style="width:99%;"><?=$this->data->TRICHYEU?></TEXTAREA>
			<div class="clr"></div>
			<span class="box_erro_area" id="ERRTRICHYEU"></span>
		</td>
		<td width="100%"></td>
	</tr>

	<tr style="display:none">
		<td nowrap="nowrap" valign="top">
			<font color="Blue">Hạn xử lý toàn bộ</font>
			<font color="Red" size="3">*</font>
		</td>
		<td nowrap="nowrap" valign="top" colspan="4">
			<input NAME="HANXULYTOANBO" value='<?=$this->data->HANXULYTOANBO?>' type=text size=4> ngày
			<div class="clr"></div>
			<span class="box_erro_area" id="ERRHANXULYTOANBO"></span>
		</td>
		<td width="100%"></td>
	</tr>
	
	<tr style="display:none">
		<td nowrap="nowrap" valign="top">
			
		</td>
		<td nowrap="nowrap" valign="top" colspan="4">
			<input type="checkbox" name='is_kcxl' value="1" id='is_kcxl' onclick="is_cxlChange()"> Văn bản không chuyển xử lý
		</td>
		<td width="100%"></td>
	</tr>

	
	<tr style="display:none">
		<td nowrap="nowrap" valign="top">
			
		</td>
		<td nowrap="nowrap" valign="top" colspan="4">
			<input type="checkbox" name='IS_PHOBIEN' value="1" id='IS_PHOBIEN' > Là văn bản phổ biến
		</td>
		<td width="100%"></td>
	</tr>

	<tr>
		<td nowrap="nowrap" valign="top">
			<font color="Blue">File đính kèm</font>
		</td>
		<td nowrap="nowrap" valign="top" colspan="4" id="idFileDinhKem"></td>
		<td width="100%"></td>
	</tr>
	<tr>
		<td nowrap="nowrap" valign="top">
			<font color="Blue">Số bản</font>
		</td>
		<td nowrap="nowrap" valign="top">
			<input type=text class=inputbox name=SOBAN value="<?=$this->data->SOBAN==""?1:$this->data->SOBAN?>" size='3'>
			<div class="clr"></div>
			<span class="box_erro_area" id="ERRSOBAN"></span>	
		</td>
		<td width=20 nowrap="nowrap"></td>
		<td nowrap="nowrap" valign="top">
			<font color="Blue"><?php echo MSG11001015 ?></font>
		</td>
		<td nowrap="nowrap" valign="top">
			<select name="DOMAT" id="DOMAT" class="inputbox" >
            	<option value="1" selected><?php echo 'Bình thường' ?></option>
            	<option value="2"><?php echo 'Mật' ?></option>
            	<option value="3"><?php echo 'Tối mật' ?></option>
            	<option value="4"><?php echo 'Tuyệt mật' ?></option>                                
             </select>
            
			<div class="clr"></div>
			<span class="box_erro_area" id="ERRDOMAT"></span> 
		</td>
		<td width="100%"></td>
	</tr>
	<tr>
		<td nowrap="nowrap" valign="top">
			<font color="Blue">Số trang</font>
		</td>
		<td nowrap="nowrap" valign="top">
			<input type=text class=inputbox name=SOTO value="<?=$this->data->SOTO==""?1:$this->data->SOTO?>" size=3>
			<div class="clr"></div>
			<span class="box_erro_area" id="ERRSOTO"></span>	
		</td>
		<td width=20 nowrap="nowrap"></td>
		<td nowrap="nowrap" valign="top">
			<font color="Blue"><?php echo MSG11001016 ?></font>
		</td>
		<td nowrap="nowrap" valign="top">
			<select name="DOKHAN" id="DOKHAN" class="inputbox"  >
            	<option value="1" selected><?php echo 'Bình thường' ?></option>
            	<option value="2"><?php echo 'Khẩn' ?></option>
            	<option value="3"><?php echo 'Hỏa tốc' ?></option>                                
            </select>
			<div class="clr"></div>
			<span class="box_erro_area" id="ERRDOKHAN"></span>  
		</td>
		<td width="100%"></td>
	</tr>
	
	
	<tr>
		<td nowrap="nowrap" valign="top">
			<font color="Blue"><?php echo MSG11001006 ?></font>
		</td>
		<td nowrap="nowrap" valign="top">
			<select name="ID_LVVB" id="ID_LVVB"   >
			<option value='0'> -- Chọn lĩnh vực văn bản --</option>	
            	<?php             					 			
			    $count = count($this->datalvvb);		
				for($i = 0 ; $i<$count  ;$i++){					
					echo '<option '.($this->data->ID_LVVB==$this->datalvvb[$i]["ID_LVVB"]?'selected':'').' value='.$this->datalvvb[$i]["ID_LVVB"].'>'.htmlspecialchars(str_repeat("--",$this->datalvvb[$i]["LEVEL"]-1).$this->datalvvb[$i]["NAME"]). '</option>';
				}			 
            	?> 
            </select> 
		</td>
		<td width=20 nowrap="nowrap"></td>
                <td nowrap="nowrap" valign="top">
<!--			<font color="Blue">Thư mục <br>hồ sơ công việc:</font>
			<font color="Red" size="3"></font>-->
		</td>
		<td nowrap="nowrap" valign="top">
			<?php //echo thumucModel::toComboboxThumucHSCV();?>
		</td>
		
		<td width="100%"></td>
	</tr>
    <?php
        if($this->idvbdraft == 0){
    ?>   
    <tr>
        <td nowrap="nowrap" valign="top">
			<font color="Blue">Sao chép</font>
		</td>
        <td colspan="5"><input type="checkbox" name="copyNoiDung" value="" title="Click vào đây để sao chép nội dung" />  </td>
    </tr>
    <?php } ?>
</table>
<input type=hidden name=username value="<?=$this->user->USERNAME; ?>">
<input type=hidden name=password value="<?=$this->user->PASSWORD; ?>">
<input type=hidden name=id_vbnhan value="<?php echo $this->id_vbnhan; ?>">
<input type=hidden name=year value="<?php echo $this->year; ?>">
<input type=hidden name=ID_VBD value="<?php echo $this->data->ID_VBD; ?>">
<input type=hidden name=ID_VBDNB value="<?php echo $this->data->ID_VBDNB; ?>">
<input type=hidden name=ID_VBDI value="<?php echo $this->ID_VBDI; ?>">
<input type=hidden name=id_hscv value="<?php echo $this->data->ID_HSCV; ?>">
<input type=hidden name=TYPE value="">
<input type=hidden name=VALUECHECKED value="">
<input type="hidden" name="SODEN_IN" value="0">
<input type="hidden" name="SOKYHIEU_IN" value="0">
<input type=hidden name=istheodoi value="1">
<input type="hidden" name="id_loaihscv" value="<?=$this->id_loaihscv?>">
<input type="hidden" name="islienthong" value="<?=$this->islienthong?>">
<input type="hidden" name="MASOLIENTHONG" value="<?=$this->data->MASOLIENTHONG?>">
<input type="hidden" name="DLCLIENTHONG" value="<?=$this->data->DLCLIENTHONG?>">
<input type="hidden" name="idvbdraft" value="<?=$this->idvbdraft?>">
<input type=hidden name=NGAYCHUYENLIENTHONG value="<?=$this->data->NGAYCHUYENLIENTHONG ?>">
</form>
<script>
//    tuanpp getdefaulthxl
<?php if($this->data->DOMAT){ ?>
document.frm.DOMAT.value='<?php echo $this->data->DOMAT ?>';
document.frm.DOKHAN.value='<?php echo $this->data->DOKHAN ?>';
<?php } ?>
function getdefaulthxl(msg){
		document.frm.temp_wf_hanxuly_user.value = msg;
                document.getElementById("real_wf_hanxuly_user").value = msg;
		var fade = function (node) {
	        var level = 1;
	        var step = function (  ) {
	            var hex = level.toString(16);
	            node.style.backgroundColor = '#FFFF' + hex + hex;
	            if (level < 15) {
	                level += 1;
	                setTimeout(step, 100);
	            }
	        };
	        setTimeout(step, 100);
	    };
	    fade(document.frm.temp_wf_hanxuly_user);            
    }
//tuanpp end
	/* Doi co quan nhan */
function changeCQNHAN(resetall){
	if(resetall){
	document.frm.ID_SVB.value = 0;
	document.frm.ID_SVB_TEXT.value = "";
	}
	DATA_ID_SVB = new Array();
	var submitAjax = new AjaxEngine(); 
			var cqn = document.frm.COQUANNHAN.value;
			if(cqn == "")
				cqn = 0;	
			var oXmlHttp = submitAjax.createXMLHttp();
			oXmlHttp.open("get", "/vbden/vbden/getsvbbycoquannhan?COQUANNHAN="+cqn , true); 
			oXmlHttp.setRequestHeader("Content-Type", "application/x-www-form-urlencoded"); 
			
			oXmlHttp.onreadystatechange = function () { 
				
			if (oXmlHttp.readyState == 4) { 
				//alert(oXmlHttp.responseText);
				if (oXmlHttp.status == 200) { 
					var lnc = 0;
					var id_svb = 0;
					var name = "";
					myData = json_parse(oXmlHttp.responseText, function (key, value) {
						var is_valid = 0;
						if(key =="ID_SVB"){
							id_svb = value;
							lnc ++;
						}
						if(key =="NAME"){
							is_valid = 1;
							name = value;
							lnc ++;
						}
						if(lnc%2==0 && is_valid==1)
							DATA_ID_SVB[DATA_ID_SVB.length]= new Array(id_svb,name);
					}	
					);
				
				
            } else { 
               
            } 
        } 
       }; 
   		
		oXmlHttp.send(null);
}
	changeCQNHAN(false);
	/* Load khung file dinh kem*/
	loadDivFromUrl('idFileDinhKem',<?=$url?>,0);
	
	var is_check_sokyhieu=false;
    var is_check_soden=true;
    
    var as_sokyhieu = 0;
    var as_soden = 0;
    var is_sokyhieu_valid = true;
    var is_soden_valid = true;
    var as_checkdata_all = 0;
    function check_sokyhieu(msg){
		//alert(msg);
    	if(msg=='0'){	
			document.getElementById('ERRSOKYHIEU').innerHTML = "Số ký hiệu, cơ quan, ngày ban hành trùng";
    		is_check_sokyhieu=false;
    		is_sokyhieu_valid = false;
		}
		else{
			document.getElementById('ERRSOKYHIEU').innerHTML = "";
		    is_check_sokyhieu=true;
		    is_sokyhieu_valid = true;
		}
		as_sokyhieu = 1;
		//return true;
    }
    
    // Hàm thực hiện khi việc lấy số đến tăng tự động thành công
    function get_soden(msg){	
		document.frm.SODEN.value = msg;
		var fade = function (node) {
	        var level = 1;
	        var step = function (  ) {
	            var hex = level.toString(16);
	            node.style.backgroundColor = '#FFFF' + hex + hex;
	            if (level < 15) {
	                level += 1;
	                setTimeout(step, 100);
	            }
	        };
	        setTimeout(step, 100);
	    };
	    fade(document.frm.SODEN);
	    oimgsoden = document.getElementById("id_img_den");
	    oimgsoden.style.display = "none";
	    		
    }
    // Hàm gọi khi thực hiện check dữ liệu trên server không thành công
    function checkFail(msg){
        waitingIcon('fail');
		oimgsoden = document.getElementById("id_img_den");
	    oimgsoden.style.display = "none";
	    as_soden =1;
	    		
    }
    function check_all(msg){
    	if(msg == 0){
    		//do something
    		var odiv_checkdata_err = document.getElementById('checkdata_err');
    		odiv_checkdata_err.style.display = "";
    	}else{
    		var odiv_checkdata_err = document.getElementById('checkdata_err');
    		odiv_checkdata_err.style.display = "none";
    		sendEndDataToServer();
    	}
    	var odiv_checkdata_all = document.getElementById('load_checkdata_all');
    	odiv_checkdata_all.style.display = "none";
        
    	
    }
    
    function waitingIcon(status){
        var saveDiv = document.getElementsByClassName('icon-SaveButton')[0];
        if(status == "on"){
            saveDiv.setAttribute("onclick","");
            saveDiv.innerHTML = '<a href="#" title="Lưu">Lưu <img src="/images/loading.gif"> </a>';
        }else if(status == "off"){
            saveDiv.setAttribute("onclick","SaveButtonClick();");
            saveDiv.innerHTML = '<a href="#" title="Lưu">Lưu <img src="/images/ok.gif"> </a>';
        }else if(status == "fail"){
            saveDiv.setAttribute("onclick","SaveButtonClick();");
            saveDiv.innerHTML = '<a href="#" title="Lưu">Lưu <img src="/images/error.gif"> </a>';
        }
    }
    
    // Hàm thực hiện check dữ liệu trên server
    function checkData(type,value){
    	var checkAjax = new AjaxEngine();
    		if(document.frm.SODEN.value != "")
    			document.frm.SODEN_IN.value = checkdinhdangsoden();
    		if(document.frm.SODEN_IN.value != -1){
    		}
			else
			{
				document.getElementById('ERRSODEN').innerHTML = "Số đến sai định dạng";
				return ;
			}
    		
			var url="/vbden/vbden/check";
    		url=url+"/TYPE/"+type;
    		url=url+"/SODEN_IN/"+document.frm.SODEN_IN.value;
    		url=url+"/VALUECHECKED/"+value;
    		url=url+"/ID_SVB/"+document.frm.ID_SVB.value;    		    		
    		url=url+"/SODEN/"+document.frm.SODEN.value;
			url=url+"/ID_LVB/"+document.frm.ID_LVB.value;
    		url=url+"/ID_CQ/"+document.frm.ID_CQ.value;    		
    		//if(document.frm.ID_CQ.value==0)
    			//url=url+"/COQUANBANHANH_TEXT/"+document.frm.COQUANBANHANH_TEXT.value;
    		url=url+"?SOKYHIEU="+document.frm.SOKYHIEU.value;
    		url=url+"&NGAYBANHANH="+document.frm.NGAYBANHANH.value;
    	var type_request = "GET";
    	
    	switch (type) {	    	
	    	//SOKYHIEU
	    	case 1: 
	    	{
					    	
	    		sendRequestToServer(url,type_request,check_sokyhieu,checkFail); 
	    	
	    	break;
	    	}
	    	case 3:
	    	{
	    		var odiv_checkdata_all = document.getElementById('load_checkdata_all');
    			odiv_checkdata_all.style.display = "";
                waitingIcon('on');
	    		//alert(url);
	    		sendRequestToServer(url,type_request,check_all,checkFail); 
	    		break;
	    	}
	    	// SODEN
	    	case 2: {
	    		oimgsoden = document.getElementById("id_img_den");
	    		oimgsoden.style.display = "";
	    		sendRequestToServer(url,type_request,check_soden,checkFail); 
	    		break;
	    	}
	    	// get SODEN
	    	case 4: 
	    	{
	    		oimgsoden = document.getElementById("id_img_den");
	    		oimgsoden.style.display = "";
	    		sendRequestToServer(url,type_request,get_soden,checkFail); 
	    		break;
	    	}
                // Tuanpp get HANXULY MAC DINH
	    	case 5:
	    	{	    		
	    		//sendRequestToServer(url,type_request,getdefaulthxl,checkFail);
	    		break;
	    	}
    		// Tuanpp end
	    	default: result = 'unknown';    		
    	}
    }
    function check_soden(msg){
		
    	if(msg == 0){		
			document.getElementById('ERRSODEN').innerHTML = "<?php echo ERR11001022 ?>";
		    is_check_soden=false;
		    is_soden_valid = false;
		}
		else{
			document.getElementById('ERRSODEN').innerHTML = "";
		    is_check_soden=true;
		    is_soden_valid = true;
		}		
		oimgsoden = document.getElementById("id_img_den");
	    oimgsoden.style.display = "none";
	    as_soden = 1;
	    
    }
</script>
<script>
	var arrSVB = Array();
	var arrLVB = Array();
	<?php 
		foreach($this->svb as $item){
	?>
			arrSVB[arrSVB.length] = Array('<?=$item->ID_SVB?>','<?=$item->ID_LVB?>');
	<?php
		}
	?>
	<?php
	$loaivanban = vbdenModel::GetDataLVB(0);
	foreach($loaivanban as $item){
	?>
		arrLVB[arrLVB.length] = Array('<?=$item['ID_LVB']?>','<?=(float)$item['HANXULY']?>');
	<?php
	}
	?>
	function SaveButtonClick(){
        var err = true;
        err = err & validateInput("gt=0",document.frm.ID_SVB,"<?php echo ERR11001003 ?>");
        err = err & validateInput("req",document.frm.SOKYHIEU,"<?php echo ERR11001007 ?>");
        err = err & validateInput("req",document.frm.NGAYBANHANH,"<?php echo ERR11001013 ?>");
        
        if(document.frm.idvbdraft == ""){
            err = err & err==true?validateInput("nequ=''",document.frm.NGAYBANHANH,"<?php echo ERR11001013 ?>"):false;
        }
        err = err & err==true?validateInput("date",document.frm.NGAYBANHANH,"<?php echo ERR11001014 ?>"):false;
        err = err & validateInput("req",document.frm.COQUANBANHANH_TEXT,"<?php echo ERR11001004 ?>");
        err = err & err==true?validateInput("maxlen=1024",document.frm.COQUANBANHANH_TEXT,"<?php echo ERR11001005 ?>"):false;
        err = err & validateInput("req",document.frm.TRICHYEU,"<?php echo ERR11001001 ?>");
        err = err & err==true?validateInput("maxlen=1024",document.frm.TRICHYEU,"<?php echo ERR11001002 ?>"):false;
        err = err & validateInput("gt=0",document.frm.ID_LVB,"<?php echo ERR11001006 ?>");
              
        err = err & validateInput("req",document.frm.SODEN,"<?php echo ERR11001009 ?>");
        
        if(!is_check_soden && err==true){
        	document.getElementById('ERRSODEN').innerHTML = "<?php echo ERR11001022 ?>";
        	err = false;
        }
        err = err & validateInput("req",document.frm.NGAYDEN,"<?php echo ERR11001011 ?>");
        if(document.frm.idvbdraft == ""){
            err = err & err==true?validateInput("nequ=''",document.frm.NGAYDEN,"<?php echo ERR11001011 ?>"):false;
        }
        
        err = err & err==true?validateInput("date",document.frm.NGAYDEN,"<?php echo ERR11001012 ?>"):false; 
        err = err & validateInput("num",document.frm.SOBAN,"<?php echo ERR11001017 ?>");
        err = err & err==true?validateInput("maxlen=2",document.frm.SOBAN,"<?php echo ERR11001017 ?>"):false;
        err = err & validateInput("num",document.frm.SOTO,"<?php echo ERR11001019 ?>"); 
        err = err & err==true?validateInput("maxlen=3",document.frm.SOTO,"<?php echo ERR11001019 ?>"):false; 
        if(err==true){
        if(CompareDate(
				document.frm.NGAYDEN.value + " 00:00",
				document.frm.NGAYBANHANH.value + " 00:00")==1){
			document.getElementById('ERRNGAYDEN').innerHTML = "Ngày đến phải sau ngày ban hành";
			err=false;
		}
		}
        document.frm.SOKYHIEU_IN.value = getSokyhieuIn();
        if(document.frm.SOKYHIEU_IN.value == -1)
        	document.frm.SOKYHIEU_IN.value = "";
		if(err==true){
		document.frm.SODEN_IN.value = checkdinhdangsoden();
		if(document.frm.SODEN_IN.value != -1){
			
		}
			//do nothing
		else
		{
			document.getElementById('ERRSODEN').innerHTML = "Số đến sai định dạng";
			return ;
		}
		}
        
        if(err==true){
           	//kiem tra lai du lieu mot lan nua
           	<?php if($this->config->hscv->vtbp==1 && ResourceUserModel::isAcionAlowed($this->user->USERNAME,$actid[0])){?>
        	var alltype = document.getElementsByName("TYPE_XL[]");
    		for(var i=0;i<alltype.length;i++){
    			if(alltype[i].value==2){
    				document.frm.istheodoi.value=0;
    				break;
    			}else{
    				document.frm.istheodoi.value=1;
    			}
    		}
    		<?php }
                if($this->idvbdraft == 0){
            ?>            
                checkData(3,0);
            <?php }else{ ?>
                waitingIcon('on');
                sendEndDataToServer();
                <?php } ?>
       }else{
       	
       }
    }
    
    function sendEndDataToServer(){
    		var submitAjax = new AjaxEngine(); 
			var oXmlHttp = submitAjax.createXMLHttp();
			oXmlHttp.open("post", "/vbden/vbden/save/draft/1" , true); 
			oXmlHttp.setRequestHeader("Content-Type", "application/x-www-form-urlencoded"); 
			document.frm.SODEN_IN.value = checkdinhdangsoden();
			if(document.frm.SODEN_IN.value != -1){
				
			}
				//do nothing
			else
			{
				document.getElementById('ERRSODEN').innerHTML = "Số đến sai định dạng";
				return ;
			}
			var post = submitAjax.getDataFromFrm(document.frm);
			oXmlHttp.onreadystatechange = function () { 
				
			if (oXmlHttp.readyState == 4) {
				if (oXmlHttp.status == 200) {
				if(oXmlHttp.responseText == 1){
				<?php if($this->data->ID_VBDNB){?>
					window.location = "/vbden/vbdennhan/list";
				
				<?php } else {?>
                    waitingIcon('off');
					//alert("Đã lưu văn bản thành công.");
                    if(document.frm.copyNoiDung.checked == false){                        
                        document.frm.TRICHYEU.value = "";
                        document.frm.SOKYHIEU.value = "";
                        document.frm.NGAYBANHANH.value = "";
                        document.frm.NGUOIKY.value = "";
                        document.frm.SOBAN.value = "1";
                        document.frm.SOTO.value = "1";
                        document.frm.DOMAT.value = "0";
                        document.frm.DOKHAN.value = "0";
                        document.frm.ID_CQ.value = "0";
                        document.frm.ID_LVVB.value = "0";
                        document.frm.COQUANBANHANH_TEXT.value = "";
                        document.frm.IS_PHOBIEN.checked = false;                        
                        document.frm.MASOLIENTHONG.value = "";
                        document.frm.DLCLIENTHONG.value = "";
                        document.frm.islienthong.value = "";
                        document.frm.id_hscv.value = "";
                        document.frm.ID_VBDI.value = "";
                        document.frm.ID_VBDNB.value = "";
                        document.frm.ID_VBD.value = "";
                        document.frm.id_vbnhan.value = "";
                    }
                    checkData(4,0);
					loadDivFromUrl('idFileDinhKem',<?=$url?>,1);
				<?php }?>	
					
				}
				else{
					if(oXmlHttp.responseText == 2){
						//loi so den khong hop le
						document.getElementById('ERRSODEN').innerHTML = "<?php echo ERR11001022 ?>";
						//as_checkdata_all = 1;
					}
				}
				
            } else { 
                //as_checkdata_all = 1;
            } 
        } 
       }; 
   		
		oXmlHttp.send(post);
    }
    
    function BackButtonClick(){
        
		<?php if($this->data->ID_VBDNB){?>
					window.location = "/vbden/vbdennhan/list";
				
		<?php } else {?>
		window.location = "/vbden/vbden/listdraft";
		<?php }?>
    	//document.frm.action = "/vbden/vbden";
        //document.frm.submit();
        
    }
    document.location.href = "#atitle";
    function PressCtrlS(){
    	SaveButtonClick();
    }
    
	function selectloaivb(){
        var idsvb = document.frm.ID_SVB.value;
        //alert(idsvb);
        //alert(arrSVB.length);
        for(var i=0;i<arrSVB.length;i++){
        	//DATA_ID_LVB
        	//alert(arrSVB[i][0]);
        	if(arrSVB[i][0]==idsvb){
            	
            	for(var j=0;j<DATA_ID_LVB.length;j++){
                	if(DATA_ID_LVB[j][0]==arrSVB[i][1]){
                		document.frm.ID_LVB_TEXT.value = DATA_ID_LVB[j][1];
                		document.frm.ID_LVB.value = DATA_ID_LVB[j][0];
                	}
            	}
				if (document.frm.ID_LVB.value!=0) {checkData(4,document.frm.ID_LVB.value)};
            	return;
        	}
        }
    }

	function selecthanxulytoanbo(){
        var idlvb = document.frm.ID_LVB.value;
        //alert(idsvb);
        //alert(arrSVB.length);
        for(var i=0;i<arrLVB.length;i++){
        	//DATA_ID_LVB
        	//alert(arrSVB[i][0]);
        	if(arrLVB[i][0]==idlvb){
            	document.frm.HANXULYTOANBO.value=arrLVB[i][1];
            	return;
        	}
        }
    }
    
    function getSokyhieuIn(){
    	var sokyhieu_text = document.frm.SOKYHIEU.value;
    	var sokyhieu_in = "";
    	
    	for(var i = 0 ; i < sokyhieu_text.length ;i++){
    		c = sokyhieu_text.charAt(i);
    		
    		
    		if(isInteger(sokyhieu_text.charAt(i))){
    			//alert(i);
    			sokyhieu_in += c  ; 
    		}
    		else{
    			break;
    		}
    	}
    	
    	
    	return sokyhieu_in;
    }
    
    
    function checkdinhdangsoden(){
    	var soden_text = document.frm.SODEN.value;
    	var soden_in = "";
    	
    	for(var i = 0 ; i < soden_text.length ;i++){
    		c = soden_text.charAt(i);
    		
    		
    		if(isInteger(soden_text.charAt(i))){
    			//alert(i);
    			soden_in += c  ; 
    		}
    		else{
    			break;
    		}
    	}
    	
    	if(i>5)
    		return -1;
    	if(i==0)
    		return -1;
    	//var endstr = substring(i,soden_text.length-1);
    	
    	return soden_in;
    	
    }
    
    function is_cxlChange(){
    	var tr_cxl = document.getElementById('tr_cxl');
    	var is_kcxl = document.frm.is_kcxl;
    	
    	//alert(is_cxl.checked);
    	if(is_kcxl.checked == true)
    		tr_cxl.style.display ="none";
    	else
    		tr_cxl.style.display ="";
    }

	

    var retvalue;    
	<?php if($this->config->hscv->vtbp==1 && ResourceUserModel::isAcionAlowed($this->user->USERNAME,$actid[0])){?>
    var arr_user = new Array();
    var arr_user_temp = new Array();
	var arr_user_smsemail = new Array();
    var arr1 = new Array();
    var curcombo = null;
  function InsertIntoArr(){
	var op_chuyen = 1;
	if(arr_user.length==0){
		op_chuyen = 2;
	}
	var opt = document.frm.NGUOIGUI.options;
	for(var i=0;i<opt.length;i++){
		if(opt[i].selected){
			arr_user[arr_user.length] = new Array(document.frm.DEP_NGUOIGUI.value,opt[i].value,opt[i].text,op_chuyen,'<?=$this->hanxuly?>',1,"","","","","");
			arr_user_temp[arr_user_temp.length] = new Array(opt[i].value);
			for(j=0;j<ARR_NGUOIGUI.length;j++){
				if(ARR_NGUOIGUI[j][2]==opt[i].value){
					arr_user_smsemail[arr_user_smsemail.length] = ARR_NGUOIGUIsmsemail[j];
					break;
				}
			}
		}
	}
    //arr_user[arr_user.length] = new Array(document.frm.DEP_NGUOIGUI.value,document.frm.NGUOIGUI.value,document.frm.NGUOIGUI[document.frm.NGUOIGUI.selectedIndex].innerHTML);
    arr1[0] = new Array(100,'Tên');
    arr1[1] = new Array(0,'Chức năng');
    arr1[2] = new Array(0,'Hạn XL');
    arr1[3] = new Array(0,'Xóa');
    ShowArr('listuser',arr1,arr_user);
    FillComboBy2Combo(document.getElementById("GDEP_NGUOIGUI"),document.getElementById("DEP_NGUOIGUI"),document.getElementById("NGUOIGUI"),ARR_NGUOIGUI,arr_user_temp);
}
    /**
     * Tạo lưới từ 2 mảng
     * 
     * @param String idDiv id div hoặc khung chứa lưới
     * @param int Arr1 mảng chứa tên trường và độ rộng tính theo % của trường
     * @param int Arr2 mảng chứa dữ liệu của các trường trên
     * @return html code
     */
    function ShowArr(idDiv,Arr1,Arr2){
        var html="";

		if(Arr2.length!=0){
        html = '<table class="adminlist" width=100%>';
        html += '<thead>';
        html += '<tr>';
        html += '<th nowrap>#</td>';
        for(i=0;i<Arr1.length;i++){
            if(Arr1[i][0]==0){
        		html += '<th nowrap>' + Arr1[i][1] + '</td>';
            }else{
            	html += '<th width="' + Arr1[i][0] + '%">' + Arr1[i][1] + '</td>';
            }
        }
        html += '</tr>';
        html += '</thead>';    
        html += '<tfoot><tr><th colspan=5 align=left>';
        html += '</th></tr></tfoot>';
        html += '<tbody>';
        	for(i=0;i<Arr2.length;i++){
html += '<tr>';
html += '<td nowrap align="right">' + (i + 1) + '</td>';
html += '<td>';
html += ''+(Arr2[i][2]);
html += "<input type=hidden name=ID_U_XL[] value="+Arr2[i][1]+">";
html += '</td>';
html += '<td nowrap>';
html += '<select onchange="UpdateType(this,'+i+')" name=TYPE_XL[] style="width:80px">';
html += '<option value=1 '+(Arr2[i][3]==1?"selected":"")+'>Để biết</option>';
html += '<option value=2 '+(Arr2[i][3]==2?"selected":"")+'>Xử lý</option>';
html += '<option value=3 '+(Arr2[i][3]==3?"selected":"")+'>Phối hợp</option>';
html += '</select>';
html += '<span id=wf_smsemail'+i+' '+(arr_user_smsemail[i]>0?"":"style='display:none'")+'><br><span '+((arr_user_smsemail[i]==3 || arr_user_smsemail[i]==1)?"":"style='display:none'")+'> SMS<input type=checkbox onclick="document.getElementById(\'SMS'+i+'\').value=(this.checked?1:0);arr_user['+i+'][6]=(this.checked?1:0);" '+(Arr2[i][6]==1?"checked":"")+'> </span><span '+((arr_user_smsemail[i]==3 || arr_user_smsemail[i]==2)?"":"style='display:none'")+'> Email<input type=checkbox onclick="document.getElementById(\'EMAIL'+i+'\').value=(this.checked?1:0);arr_user['+i+'][7]=(this.checked?1:0);" '+(Arr2[i][7]==1?"checked":"")+'></span></span>';
html += '<input type=hidden name=SMS[] value='+(Arr2[i][6]==1?"1":"0")+' id=SMS'+i+'><input type=hidden name=EMAIL[] value='+(Arr2[i][7]==1?"1":"0")+' id=EMAIL'+i+'>';
html += '</td>';
html += '<td nowrap>';
html += '<span id=SPANHANXULY'+i+' style="display:'+(Arr2[i][3]==1||Arr2[i][3]==3?"none":"")+'">'+calendarFull(Arr2[i][8],'NGAY_KETTHUC'+i,'ChangeDate','ChangeDate('+i+')')+createInputHanxuly('HANXULY'+i,'HANXULY[]',Arr2[i][4],'UpdateHanXuLy('+i+')',(Arr2[i][3]==1||Arr2[i][3]==3?"none":""),Arr2[i][5])+"</span>";
//html += '<input style="display:'+(Arr2[i][3]==1||Arr2[i][3]==3?"none":"")+'" id=HANXULY'+i+' onchange="UpdateHanXuLy(this,'+i+')" name=HANXULY_XL[] type=text size=2 value="'+Arr2[i][4]+'">';
html += '</td>';
html += '<td nowrap>';
html += '<a href="javascript:;" onclick="arr_user_temp.splice('+i+',1);arr_user.splice('+i+',1);arr_user_smsemail.splice('+i+',1);ShowArr(\'listuser\',arr1,arr_user);FastReload();return false;">Xóa</a>';
html += '</td>';
html += '</tr>';
            }
        	html += '</tbody>';
        	html += '</table>';
        }
        document.getElementById(idDiv).innerHTML = html;
		for(i=0;i<Arr2.length;i++){
			if(document.getElementById("NGAY_KETTHUC"+i).value=="")UpdateHanXuLy(i);
		} 
    }
    function FastReload(){
    	FillComboBy2Combo(document.getElementById("GDEP_NGUOIGUI"),document.getElementById("DEP_NGUOIGUI"),document.getElementById("NGUOIGUI"),ARR_NGUOIGUI,arr_user_temp);
    }
    function UpdateHanXuLy(i){
    	arr_user[i][4] = document.getElementById("HANXULY"+i).value;
		arr_user[i][5] = document.getElementById("type_real_HANXULY"+i).value;
    }
    function UpdateType(obj,i){
    	curcombo = obj;
    	arr_user[i][3] = obj.value;
    	if(obj.value==1 || obj.value==3){
    		document.getElementById("span_HANXULY"+i).style.display="none";
			document.getElementById("SPANHANXULY"+i).style.display="none";
    	}else{
			document.getElementById("span_HANXULY"+i).style.display="";
			document.getElementById("SPANHANXULY"+i).style.display="";
    		getvalue("auth","user","checksendable","wf_id_t="+document.frm.wf_id_t.value+"?>&idu="+arr_user[i][1]);
    	}
    }
    function UpdateRet(){
    	if(retvalue=="0"){
    		alert("Người được chọn không có quyền xử lý.");
    		curcombo.value = 1;
    		curcombo.onchange();
    		
    	}
    }
	var stthan = 0;
	function UpdateRethanxuly(){
		document.getElementById("HANXULY"+stthan).value=retvalue;
		arr_user[stthan][4] = document.getElementById("HANXULY"+stthan).value;
    }
	function UpdateRetntthuc(){
		document.getElementById("NGAY_KETTHUC"+stthan).value=retvalue;
		arr_user[stthan][4] = document.getElementById("HANXULY"+stthan).value;
		arr_user[stthan][5] = document.getElementById("type_real_HANXULY"+stthan).value;
		arr_user[stthan][8] = retvalue;
    }
	function ChangeDate(i){
		stthan = i;
		//alert(i);
        getvalue("auth","user","adddatehanxuly","date="+document.getElementById("NGAY_KETTHUC"+stthan).value+"&all="+document.getElementById("type_real_HANXULY"+stthan).value+"","UpdateRethanxuly");
    }
	function UpdateHanXuLy(i){
		stthan = i;
		getvalue("auth","user","adddate","all="+document.getElementById("type_real_HANXULY"+stthan).value+"&value="+(parseInt(document.getElementById("HANXULY"+stthan).value,10)),"UpdateRetntthuc");
	}

    <?php }else{ ?>
	function UpdateRet(){
		document.frm.wf_sms.checked=false;
		document.frm.wf_email.checked=false;    	
		if(parseInt(retvalue,10) > 0){
			//chi co sms
    		if(parseInt(retvalue,10)==1){
				document.getElementById("wf_sms").style.display='';
				document.getElementById("wf_email").style.display='none';
			}
			if(parseInt(retvalue,10)==2){
				document.getElementById("wf_sms").style.display='none';
				document.getElementById("wf_email").style.display='';
			}
			if(parseInt(retvalue,10)==3){
				document.getElementById("wf_sms").style.display='';
				document.getElementById("wf_email").style.display='';
			}
			document.getElementById("wf_smsemail").style.display='';
    	}else{
			document.getElementById("wf_smsemail").style.display='none';
		}
    }
	<?php } ?>
	
	<?php
	if($is_cnb){
	?>
			
		function fillcomboCqnb(id_combo,arr,arr_exp){
			var objdesc = document.getElementById(id_combo);
			
			
			for (i = objdesc.length - 1; i>=0; i--) {
				objdesc.removeChild(objdesc.options[i]);
			}
			for(var i=0;i<arr.length;i++){
				var ln = 0;
				for(var j= 0;j < arr_exp.length ; j++){
					//alert(arr_exp[j]);
					if(arr_exp[j] == arr[i][0] ){
						ln =1;
						
						break;
						
					}
				}
				if(ln == 0 ){
					var elOptNew = document.createElement('option');
					elOptNew.text = arr[i][1];
					elOptNew.value = arr[i][0];
					try {
					  objdesc.add(elOptNew, null); // standards compliant; doesn't work in IE
					}
					catch(ex) {
					  objdesc.add(elOptNew); // IE only
					}
				}
			}
			if(objdesc.length)
				objdesc.style.display = 'block';
			else
				objdesc.style.display = 'none';
			//objdesc.value = sel;
		}
		
		var arr_cqselect = new Array();
		var arr_cqselect_temp = new Array();

		var arr_cqnb = new Array();
		<?php $stt = 0 ;foreach ($data_cqnb as $cqnb){ ?>
		
		arr_cqnb[<?=$stt?>] =  new Array("<?=$cqnb['ID_CQ']?>", "<?=$cqnb['NAME']?>");
		<?php $stt++; } ?>
		
		
		
<?php } ?>

</script>
