<?=QLVBDHCommon::useDlgConfirm()?>
<?php
	require_once 'Common/FileDinhKem.php';
	if(strtoupper($this->code)!=''){
		$disable="/isreadonly/1";
		$disablefile="/isreadonly/1";
	}else{
		$actid = ResourceUserModel::getActionByUrl("hscv","file","vanthu");
		//var_dump($actid);
		//echo "ss".ResourceUserModel::isAcionAlowed($this->user->USERNAME,$actid[0]);
		if(!ResourceUserModel::isAcionAlowed($this->user->USERNAME,$actid[0])){
			$disablefile="/isreadonly/1";
		}
	}
	$script="";
?>
<script type="text/javascript" src=<?php echo $this->baseUrl()."/js/Json/Base64.js"?>></script>
<script type="text/javascript" src=<?php echo $this->baseUrl()."/js/Json/json2.js"?>></script>
<script type="text/javascript" src=<?php echo $this->baseUrl()."/js/Json/json_parse.js"?>></script>
<script type="text/javascript" src=<?php echo $this->baseUrl()."/js/Json/json_parse_state.js"?>></script>
<script type="text/javascript" src=<?php echo $this->baseUrl()."/js/Ajax/AjaxEngine.js"?>></script>
<form name=frm method=post onsubmit="document.frm.page.value = 1;document.frm.action = '/hscv/hscv/listchobanhanh/id_thumuc/<?=$this->id_thumuc?>/code/<?=$this->code?>';return true;">
<?php
if(strtoupper($this->code)=="ZIP"){
?>
<table><tr><td nowrap="nowrap" valign="top" style="border-right: 1px solid">
<ul class=treeview id=treemenu2>
<li>Thư mục lưu trữ
<?php 
$html = "";
echo ThuMucModel::ToTree($this->thumuc,1,"treemenu2",$html,$this->id_thumuc);
?>
</li>
</ul>
<script type="text/javascript" src="/js/simpletreemenu.js">

/***********************************************
* Simple Tree Menu- © Dynamic Drive DHTML code library (www.dynamicdrive.com)
* This notice MUST stay intact for legal use
* Visit Dynamic Drive at http://www.dynamicdrive.com/ for full source code
***********************************************/

</script>

<link rel="stylesheet" type="text/css" href="/styles/simpletree.css" />
<script type="text/javascript">

//ddtreemenu.createTree(treeid, enablepersist, opt_persist_in_days (default is 1))
ddtreemenu.createTree("treemenu2", true, 5)
ddtreemenu.flatten('treemenu2', 'expand');

</script>

</td>
<td width="100%" valign="top">
<?php } ?>
<div style=" padding-top:20px; ">
	<table>
		<tr>
			<td nowrap="nowrap">Loại công việc</td>
			<td nowrap="nowrap"><select name="OBJECT" onchange="
						document.frm.page.value = 1;
						if(document.frm.TRANGTHAI!=null)document.frm.TRANGTHAI.value = 0;
						document.frm.action = '/hscv/hscv/listchobanhanh/id_thumuc/<?=$this->id_thumuc?>/code/<?=$this->code?>';
						document.frm.submit();
				">
						<option value="">--Chọn loại công việc--</option>
						<option value="VBD">Xử lý văn bản đến</option>
						<option value="VBSOANTHAO">Công việc</option>
						<!--<option value="MOTCUA">Hồ sơ một cửa</option>-->
				</select>
				<script>document.frm.OBJECT.value="<?=$this->OBJECT?>";</script>
				</td>
			<td width="10" nowrap="nowrap"></td>
			<td nowrap="nowrap"></td>
			<td nowrap="nowrap"></td>
			<td width="100%"></td>
		</tr>
		<?php
			if(strtoupper($this->code)!="ZIP"){
		?>
		<tr style="display:none">
			<td nowrap="nowrap">Trạng thái</td>
			<td nowrap="nowrap"><select name="TRANGTHAI" onchange="
						document.frm.page.value = 1;
						document.frm.action = '/hscv/hscv/listchobanhanh/id_thumuc/<?=$this->id_thumuc?>/code/<?=$this->code?>';
						document.frm.submit();
					">
						<option value=0>--Chọn trang thái--</option>
						<?=WFEngine::ToCombo($this->datatrangthai,$this->TRANGTHAI)?>
				</select></td>
			<td width="10" nowrap="nowrap"></td>
			<td nowrap="nowrap"></td>
			<td nowrap="nowrap"></td>
			<td width="100%"></td>
		</tr>
		<?php } ?>
		
		<tr>
			<td nowrap="nowrap" valign=top>
			
			Nội dung
			</td>
			<td nowrap="nowrap" colspan="3"><input type=text class=inputbox name=NAMECV value="<?=$this->NAME?>" size=50><br>
			<input type="checkbox" name=INNAME value=1 style="display:none" checked><!--
			<?php switch($this->OBJECT){
				case "VBD":
					echo "Trong trích yếu";
				break;
				case "MOTCUA":
					echo "Trong tên hồ sơ";
				break;
				default:
					echo "Trong tên công việc";
				}
			?>-->
			<input type="checkbox" name=INFILE value=1 style="display:none"><!--Trong nội dung dự thảo-->
			</td>
			<td width="100%"></td>
		</tr>
		<?php if($this->OBJECT == "VBD"){ ?>
		<tr>
			<td nowrap="nowrap">Sổ văn bản</td>
			<td nowrap="nowrap">
				<select name="ID_SVB" id="ID_SVB" class="inputbox" size="1" onchange="document.frm.submit();">
            	<?php 
            		echo vbdenModel::WriteSVB((int)$this->ID_SVB,"-- Chọn tất cả  --", true);
            	?> 
        		</select>
			</td>
			<td width="10" nowrap="nowrap"></td>
			<td nowrap="nowrap">Loại văn bản</td>
			<td nowrap="nowrap">
				<select name="ID_LVB" id="ID_LVB" class="inputbox" size="1" onchange="document.frm.submit();">
            	<?php 
            		echo vbdenModel::WriteLVB((int)$this->ID_LVB,"-- Chọn tất cả  --");
            	?> 
        		</select>
			</td>
			<td width="100%"></td>
		</tr>
		
		<tr>
			<td nowrap="nowrap">Số đến</td>
			<td nowrap="nowrap"><input type=text class=inputbox name=SODEN value="<?=$this->SODEN?>" size=10>
			<input name=SODEN_ISLIKE value=1 type=checkbox <?=$this->SODEN_ISLIKE==1?"checked":""?> > Tìm gần đúng
			</td>
			
			<td width="10" nowrap="nowrap"></td>
		
			<td nowrap="nowrap">Số ký hiệu</td>
			<td nowrap="nowrap" ><input type=text class=inputbox name=SOKYHIEU value="<?=$this->SOKYHIEU?>" size=20></td>
			
		</tr>
		<tr id=FindAdvanced2>
			<td nowrap="nowrap">Ngày đến</td>
			<td nowrap="nowrap" colspan="3">
				<?=QLVBDHCommon::calendar($this->NGAYDEN_BD,"NGAYDEN_BD","NGAYDEN_BD") ?>
				<span style="font-weight:bold;padding-left:10px;"> >> </span>
				<?=QLVBDHCommon::calendar($this->NGAYDEN_KT,"NGAYDEN_KT","NGAYDEN_KT") ?>
			</td>
			<td width="100%"></td>
		</tr>
		<tr id=FindAdvanced3>
			<td nowrap="nowrap">Ngày ban hành</td>
			<td nowrap="nowrap" colspan="3">
				<?=QLVBDHCommon::calendar($this->NGAYBANHANH_BD,"NGAYBANHANH_BD","NGAYBANHANH_BD") ?>
				<span style="font-weight:bold;padding-left:10px;"> >> </span>
				<?=QLVBDHCommon::calendar($this->NGAYBANHANH_KT,"NGAYBANHANH_KT","NGAYBANHANH_KT") ?>
			</td>
			<td width="100%"></td>
		</tr>
		
		<?php }?>
		<?php if($this->OBJECT == "MOTCUA"){ ?>

	
		<tr>
			<td nowrap="nowrap">Mã hồ sơ một cửa</td>
			<td nowrap="nowrap">
				<input type=text class=inputbox name=MASOHOSO value="<?=$this->MASOHOSO?>">
			</td>
			<td width="10" nowrap="nowrap"></td>
			<td nowrap="nowrap">Tên tổ chức công dân</td>
			<td nowrap="nowrap">
				<input type=text class=inputbox name=TENTOCHUCCANHAN value="<?=$this->TENTOCHUCCANHAN?>" >
			</td>
			<td width="100%"></td>


			
			
		</tr>
		
		<tr id=FindAdvanced2>
			<td nowrap="nowrap">Ngày tiếp nhận</td>
			<td nowrap="nowrap" colspan="3">
				<?=QLVBDHCommon::calendar($this->NHAN_NGAY_BD,"NHAN_NGAY_BD","NHAN_NGAY_BD") ?>
				<span style="font-weight:bold;padding-left:10px;"> >> </span>
				<?=QLVBDHCommon::calendar($this->NHAN_NGAY_KT,"NHAN_NGAY_KT","NHAN_NGAY_KT") ?>
			</td>
			<td width="100%"></td>
		</tr>
		<?php } ?>
		<?php if($this->OBJECT == "VBSOANTHAO"){ ?>
		<tr>
			<td nowrap="nowrap">Từ ngày</td>
			<td nowrap="nowrap"><?=QLVBDHCommon::calendar($this->NGAY_BD,"NGAY_BD","NGAY_BD") ?> Đến ngày <?=QLVBDHCommon::calendar($this->NGAY_KT,"NGAY_KT","NGAY_KT") ?></td>
			<td width="10" nowrap="nowrap"></td>
			<td nowrap="nowrap"></td>
			<td nowrap="nowrap"></td>
			<td width="100%"></td>
		</tr>
		
		<?php } ?>
		<tr>
			<td nowrap="nowrap"></td>
			<td nowrap="nowrap" colspan="3"><input type=submit value="Tìm kiếm"></td>
			<td width="100%"></td>
		</tr>
	</table>
	</div>
	
	



<table class=adminlist>
	<thead>
		<tr>
			<th colspan="4">
				<div>
					<div class="limit" style="float:left;">Hiển thị #
						<select name="limit1"  style="width:60px;" id="limit1" class="inputbox" size="1" onchange="
							document.frm.page.value = 1;
							document.frm.limit2.value = document.frm.limit1.value;
							document.frm.action = '/hscv/hscv/listchobanhanh/id_thumuc/<?=$this->id_thumuc?>/code/<?=$this->code?>';
							document.frm.submit();
						">
							<option value="5" <?php if($this->limit==5){echo "selected";} ?>>5</option>
							<option value="10" <?php if($this->limit==10){echo "selected";} ?>>10</option>
							<option value="15" <?php if($this->limit==15){echo "selected";} ?>>15</option>
							<option value="20" <?php if($this->limit==20){echo "selected";} ?>>20</option>
							<option value="25" <?php if($this->limit==25){echo "selected";} ?>>25</option>
							<option value="30" <?php if($this->limit==30){echo "selected";} ?>>30</option>
							<option value="35" <?php if($this->limit==35){echo "selected";} ?>>35</option>
							<option value="40" <?php if($this->limit==40){echo "selected";} ?>>40</option>
							<option value="50" <?php if($this->limit==50){echo "selected";} ?>>50</option>
							<option value="100" <?php if($this->limit==100){echo "selected";} ?>>100</option>
						</select>
					</div>
					<div class="limit" style="float:right;"><?php echo $this->showPage; ?></div>
				</div>
			</th>
		</tr>
		<tr>
			<th nowrap="nowrap">
				#
			</th>
			<th width="100%">
				Tên công việc
			</th>
			<th nowrap="nowrap">
				&nbsp;
			</th>
		</tr>
	</thead>
	<tfoot>
		<tr>
			<th colspan="3">
				<div class="pagination">
					<div class="limit">Hiển thị #
						<select name="limit2" style="width:60px;" id="limit2" class="inputbox" size="1" onchange="
							document.frm.page.value = 1;
							document.frm.limit1.value = document.frm.limit2.value;
							document.frm.action = '/hscv/hscv/listchobanhanh/id_thumuc/<?=$this->id_thumuc?>/code/<?=$this->code?>';
							document.frm.submit();
						">
							<option value="5" <?php if($this->limit==5){echo "selected";} ?>>5</option>
							<option value="10" <?php if($this->limit==10){echo "selected";} ?>>10</option>
							<option value="15" <?php if($this->limit==15){echo "selected";} ?>>15</option>
							<option value="20" <?php if($this->limit==20){echo "selected";} ?>>20</option>
							<option value="25" <?php if($this->limit==25){echo "selected";} ?>>25</option>
							<option value="30" <?php if($this->limit==30){echo "selected";} ?>>30</option>
							<option value="35" <?php if($this->limit==35){echo "selected";} ?>>35</option>
							<option value="40" <?php if($this->limit==40){echo "selected";} ?>>40</option>
							<option value="50" <?php if($this->limit==50){echo "selected";} ?>>50</option>
							<option value="100" <?php if($this->limit==100){echo "selected";} ?>>100</option>
						</select>
					</div>
					<div style="float:right"><?php echo $this->showPage; ?></div>
				</div>
			</th>
		</tr>
	</tfoot>
	<tbody>
<?php
	if(count($this->data)<=0){
		echo "<tr><td colspan='3'>Không tìm thấy hồ sơ công việc nào<td></tr>";
	}else{
	$stt=($this->page-1)*$this->limit;
	$i=0;
	$datatre = "";
	foreach($this->data as $row){
		//var_dump(explode(" ",$this->NAME));
		$row['NAME'] = $this->INNAME==1?QLVBDHCommon::highlightText($row['NAME'],$this->NAME):$row['NAME'];
		if(strtoupper($this->code)!="ZIP"){
			if($row['IS_THEODOI']!=1){
				$tt = hosocongviecModel::getlastlog($row['ID_PI']);
				//var_dump($tt);
				$datatre .= $row['ID_HSCV'].",".urlencode($tt['DATESEND']).",".$tt['HANXULY'].",".$tt['ID_U_RECEIVE'].",";
				$parentlog = WFEngine::GetStartLogIdByProcessItem($row['ID_PI'],$tt['ID_T']);
				//var_dump($parentlog);
				if(is_array($parentlog)){
					foreach($parentlog as $itemparent){
						if($itemparent['ID_PL']!=$tt['ID_PL']){
							$datatre .= $row['ID_HSCV'].",".urlencode($itemparent['DATESEND']).",".$itemparent['HANXULY'].",".$itemparent['ID_U_RECEIVE'].",";
						}
					}
				}
			}
			//$script .= "loadDivFromUrl('TREHAN".$row['ID_HSCV']."','/auth/user/delay/date/".urlencode($tt['DATESEND'])."/hanxuly/".$tt['HANXULY']."',1);";
		}
		$stt++;
?>
		<tr class="row<?=$this->idhscv==$row['ID_HSCV']?"2":$i?>">
			<td valign="top" rowspan="2"><a name="hscv<?=$row['ID_HSCV']?>"></a><?=$stt?></td>
			<td valign="top">
				<?php
					if($row["ALIAS"]=="VBD"){
						echo "<img src='/images/icon_vbden.jpg'>";
						$vbden = $this->vbden->findByHscv($row['ID_HSCV']);
						//var_dump($vbden);
					}else if($row["ALIAS"]=="VBSOANTHAO"){
						echo "<img src='/images/icon_soanthaovb.jpg'>";
					}else if($row["ALIAS"]=="MOTCUA"){
						echo "<img src='/images/icon_motcua.jpg'>";
					}
				?>
				<?php if($row["ALIAS"]=="VBD"){
					$vbdeninfo = $this->vbden->find($vbden['ID_VBD'])->current();
					echo "<b>".$vbdeninfo->SOKYHIEU." - ".QLVBDHCommon::MysqlDateToVnDate($vbdeninfo->NGAYBANHANH)." - ".$vbdeninfo->COQUANBANHANH_TEXT."</b><br>";
				}?>
				<?=$row['NAME']?><?=$row['EXTRA']!=""?" - ".$row['EXTRA']:""?> <span id="TREHAN<?=$row['ID_HSCV']?>"></span>
				<?php
					if($this->INFILE==1){
						$dt = PhienBanDuThaoModel::getFileContent($row['ID_HSCV']);
						foreach($dt as $itemdt){
							$rfind = QLVBDHCommon::highlightString($itemdt['CONTENT'],$this->NAME);
							if($rfind!=""){
				?>
				<br><a href="/hscv/File/download?year=&maso=<?=$itemdt['MASO']?>"><B><?=$itemdt['FILENAME']?>:</B> <?=$rfind?></a>
				<?php 
							}
						}
					}
				?>
				<?php if(strtoupper($this->code)=="PHOIHOP"){
						
						if($row["IS_NEW_PH"] == 0){
							
				?>		
					<img id='img_new_ph_<?=$row["ID_HSCV"]?>' src='/images/moi.gif'></img>
				<?php		}}
				?> 
			</td>
<?php
		if(strtoupper($this->code)!="PHOIHOP"){
?>
			<td nowrap="nowrap" valign="top" id="NEXTSTEP<?=$row["ID_HSCV"]?>">
				
				<?php
					$datanextstep .= $row['ID_HSCV'].",".$this->code.",".$row['CNTPL'].",".$row["ID_LOAIHSCV"].",".$row["ID_PI"].",";
				?>
			</td>
<?php
		}
?>
		</tr>
		<tr class="row<?=$this->idhscv==$row['ID_HSCV']?"2":$i?>">
			<td colspan="2">
				<div>
					<ul class="chitiethscv">
					<?php if(QLVBDHCommon::TabHscv(1,$row["ID_LOAIHSCV"])==1){ ?>
						<li id=groupicon1_<?=$row["ID_HSCV"]?>>
							<img src="/images/icon_chitiet.jpg" border="0" hspace="5" >
							<a href='javascript:SwapDiv(<?=$row["ID_HSCV"]?>,"/vbden/vbden/detail/type/<?=$row["ID_LOAIHSCV"]?>/id/<?=$row["ID_HSCV"]?>/year/<?=$this->realyear?><?=$disable?>",1);
							<?php if(strtoupper($this->code)=="PHOIHOP"){
						
								if($row["IS_NEW_PH"] == 0){?>
							updateImageNew("img_new_ph_<?=$row["ID_HSCV"]?>",<?=$row["ID_HSCV"]?>);
							<?php }}?>
							'>Chi tiết</a>
						</li>
					<?php } ?>
					<?php if(QLVBDHCommon::TabHscv(6,$row["ID_LOAIHSCV"])==1){ ?>
					<li id=groupicon6_<?=$row["ID_HSCV"]?>>
						<img src="/images/icon_luanchuyen.jpg" border="0" hspace="5" >
						<a href='javascript:SwapDiv(<?=$row["ID_HSCV"]?>,"/hscv/hscv/way/id/<?=$row["ID_HSCV"]?>/year/<?=$this->realyear?>/type/<?=$row["ID_LOAIHSCV"]?>",6);
						<?php if(strtoupper($this->code)=="PHOIHOP"){
						
								if($row["IS_NEW_PH"] == 0){?>
							updateImageNew("img_new_ph_<?=$row["ID_HSCV"]?>",<?=$row["ID_HSCV"]?>);
							<?php }}?>
						'>Luân chuyển</a>
					</li>
					<?php } ?>
					<?php if(QLVBDHCommon::TabHscv(5,$row["ID_LOAIHSCV"])==1){ ?>
					<li id=groupicon5_<?=$row["ID_HSCV"]?>>
						<img src="/images/icon_duthao.jpg" border="0" hspace="5" >
						<a href='javascript:SwapDiv(<?=$row["ID_HSCV"]?>,"/hscv/VanBanDuThao/index/year/<?=$this->realyear?>/iddivParent/groupcontent<?=$row["ID_HSCV"]?>/idHSCV/<?=$row["ID_HSCV"]?><?=$disable?>",5);
						<?php if(strtoupper($this->code)=="PHOIHOP"){
						
								if($row["IS_NEW_PH"] == 0){?>
							updateImageNew("img_new_ph_<?=$row["ID_HSCV"]?>",<?=$row["ID_HSCV"]?>);
							<?php }}?>
						'>Dự thảo</a>
					</li>
					<?php } ?>
					
					<?php if(QLVBDHCommon::TabHscv(8,$row["ID_LOAIHSCV"])==1){ ?>
					<li id=groupicon8_<?=$row["ID_HSCV"]?>>
						<img src="/images/icon_vanbanlienquan.jpg" border="0" hspace="5" >
						<a href='javascript:SwapDiv(<?=$row["ID_HSCV"]?>,"/hscv/hscv/bosung/year/<?=$this->realyear?>/iddivParent/groupcontent<?=$row["ID_HSCV"]?>/id/<?=$row["ID_HSCV"]?><?=$disable?>",8);
						<?php if(strtoupper($this->code)=="PHOIHOP"){
						
								if($row["IS_NEW_PH"] == 0){?>
							updateImageNew("img_new_ph_<?=$row["ID_HSCV"]?>",<?=$row["ID_HSCV"]?>);
							<?php }}?>
						'>Bổ sung hồ sơ</a>
					</li>
					<?php } ?>
					<?php 
					if(QLVBDHCommon::TabHscv(2,$row["ID_LOAIHSCV"])==1){ ?>
					<li id=groupicon2_<?=$row["ID_HSCV"]?>>
						<img src="/images/icon_butphe.jpg" border="0" hspace="5" >
						<a href='javascript:SwapDiv(<?=$row["ID_HSCV"]?>,"/hscv/hscv/viewbutphe/id/<?=$row["ID_HSCV"]?>/year/<?=$this->realyear?><?=$disable?>",2);
						<?php if(strtoupper($this->code)=="PHOIHOP"){
						
								if($row["IS_NEW_PH"] == 0){?>
							updateImageNew("img_new_ph_<?=$row["ID_HSCV"]?>",<?=$row["ID_HSCV"]?>);
							<?php }}?>
						'>Bút phê</a>
					</li>
					<?php } ?>
					<?php if(QLVBDHCommon::TabHscv(3,$row["ID_LOAIHSCV"])==1){ ?>
					<li id=groupicon3_<?=$row["ID_HSCV"]?>>
						<img src="/images/icon_phoihop.gif" border="0" hspace="5" >
						<a href='javascript:SwapDiv(<?=$row["ID_HSCV"]?>,"/hscv/phoihop/index/idhscv/<?=$row["ID_HSCV"]?>/year/<?=$this->realyear?><?=strtoupper($this->code)=="PHOIHOP"?"":$disable?>",3);
						<?php if(strtoupper($this->code)=="PHOIHOP"){
						
								if($row["IS_NEW_PH"] == 0){?>
							updateImageNew("img_new_ph_<?=$row["ID_HSCV"]?>",<?=$row["ID_HSCV"]?>);
							<?php }}?>
						'>Phối hợp</a>
					</li>
					<?php } ?>
					<?php if(QLVBDHCommon::TabHscv(4,$row["ID_LOAIHSCV"])==1){ ?>
					<li id=groupicon4_<?=$row["ID_HSCV"]?>>
						<img src="/images/icon_files.jpg" border="0" hspace="5" >
						<a href='javascript:SwapDiv(<?=$row["ID_HSCV"]?>,"/hscv/file/index/iddiv/groupcontent<?=$row["ID_HSCV"]?>/idObject/<?=$row["ID_LOAIHSCV"]==1?$vbden['ID_VBD']:$row["ID_HSCV"]?>/is_new/0/year/<?=$this->realyear?>/type/<?=$row["ID_LOAIHSCV"]==1?"3":"1"?><?=$disablefile?>",4);
						<?php if(strtoupper($this->code)=="PHOIHOP"){
						
								if($row["IS_NEW_PH"] == 0){?>
							updateImageNew("img_new_ph_<?=$row["ID_HSCV"]?>",<?=$row["ID_HSCV"]?>);
							<?php }}?>
						'>Đính kèm</a>
					</li>
					<?php } ?>
					<?php if(QLVBDHCommon::TabHscv(7,$row["ID_LOAIHSCV"])==1){ ?>
					<li id=groupicon7_<?=$row["ID_HSCV"]?>>
						<img src="/images/icon_vanbanlienquan.jpg" border="0" hspace="5" >
						<a href='javascript:SwapDiv(<?=$row["ID_HSCV"]?>,"/hscv/vanbanlienquan/index/year/<?=$this->realyear?>/iddivParent/groupcontent<?=$row["ID_HSCV"]?>/idHSCV/<?=$row["ID_HSCV"]?><?=$disable?>",7);
						<?php if(strtoupper($this->code)=="PHOIHOP"){
						
								if($row["IS_NEW_PH"] == 0){?>
							updateImageNew("img_new_ph_<?=$row["ID_HSCV"]?>",<?=$row["ID_HSCV"]?>);
							<?php }}?>
						'>VB liên quan</a>
					</li>
					<?php } ?>
					<?php if($this->id_thumuc>1 || $row["ALIAS"]=="MOTCUA"){ ?>
					<li id=groupicon9_<?=$row["ID_HSCV"]?>>
						<img src="/images/icon_vanbanlienquan.jpg" border="0" hspace="5" >
						<a href='javascript:SwapIframe(<?=$row["ID_HSCV"]?>,"/hscv/hscv/viewresult/iddivParent/groupcontent<?=$row["ID_HSCV"]?>/id/<?=$row["ID_HSCV"]?><?=$disable?>",9);
						<?php if(strtoupper($this->code)=="PHOIHOP"){
						
								if($row["IS_NEW_PH"] == 0){?>
							updateImageNew("img_new_ph_<?=$row["ID_HSCV"]?>",<?=$row["ID_HSCV"]?>);
							<?php }}?>
						'>Kết quả</a>
					</li>
					<?php } ?>
					<?php if($this->id_thumuc>1 || $row["ALIAS"]=="MOTCUA"){ 
						require_once('motcua/models/dkwebModel.php');
						$data_maso = dkwebModel::GetMasodkquamangByIDHSCV($row["ID_HSCV"]);		
						
						if($data_maso){
					?>
					<li id=groupicon9_<?=$row["ID_HSCV"]?>>
						<img src="/images/icon_vanbanlienquan.jpg" border="0" hspace="5" >
						<a href='javascript:SwapIframe(<?=$row["ID_HSCV"]?>,"/motcua/dongbohsmc/viewdon/mahoso/<?=$data_maso?>/iddivParent/groupcontent<?=$row["ID_HSCV"]?>/id_hscv/<?=$row["ID_HSCV"]?><?=$disable?>",9);
						<?php if(strtoupper($this->code)=="PHOIHOP"){
						
								if($row["IS_NEW_PH"] == 0){?>
							updateImageNew("img_new_ph_<?=$row["ID_HSCV"]?>",<?=$row["ID_HSCV"]?>);
							<?php }}?>
						'>Đơn xin cấp phép</a>
					</li>
					<?php } }?>
					</ul>
				</div>
				<div class="groupcontent" id="groupcontent<?=$row["ID_HSCV"]?>" style="display:none;background: #ffffff"></div>
			</td>
		</tr>
<?php
		$i = (-1+$i)*-1;	
	}
}
?>
	</tbody>
</table>
<input type="hidden" name="page" value="<?php echo $this->page; ?>">
<?php if(strtoupper($this->code)=="ZIP"){?>
</td></tr></table>
<?php } ?>
</form>
<script>
	function DeleteHscv(id,type){
		if(confirm("Bạn có muốn xóa công việc này không?")){
			document.location.href = "/hscv/hscv/delete/id_hscv/"+id+"/type/"+type;
		}
	}
	function DeleteHscvForVTBP(id){
		if(confirm("Bạn có muốn xóa công việc này không?")){
			document.location.href = "/hscv/hscv/deletevtbp/id_hscv/"+id;
		}
	}
	function CreateButtonClick(url){
		document.frm.action = url;
		document.frm.submit();
	}
	function SwapDiv(id,url,tab){
		for(var i=1;i<11;i++){
			if(document.getElementById("groupicon"+i+"_"+id)){
				if(tab!=i){
					if(document.getElementById("groupicon"+i+"_"+id).className=="groupiconopen"){
						document.getElementById("groupcontent"+id).style.display="none";
						document.getElementById("groupicon"+i+"_"+id).className = "groupicon";
						break;
					}
				}
			}
		}
		if(document.getElementById("groupcontent"+id).style.display==""){
			document.getElementById("groupcontent"+id).style.display="none";
			document.getElementById("groupicon"+tab+"_"+id).className = "groupicon";
		}else{
			document.getElementById("groupcontent"+id).style.display="";
			document.getElementById("groupicon"+tab+"_"+id).className = "groupiconopen";
			document.getElementById("groupcontent"+id).innerHTML="<img src='/images/loading.gif' width='16' height='16' border='0'></img<img src='/images/loading.gif' width='16' height='16' border='0'></img><img src='/images/loading.gif' width='16' height='16' border='0'></img><img src='/images/loading.gif' width='16' height='16' border='0'></img>";
			loadDivFromUrl("groupcontent"+id,url,1);

	}
	}
	function SwapIframe(id,url){
		for(var i=1;i<11;i++){
			if(document.getElementById("groupicon"+i+"_"+id)){
				if(document.getElementById("groupicon"+i+"_"+id).className=="groupiconopen"){
					document.getElementById("groupcontent"+id).style.display="none";
					document.getElementById("groupicon"+i+"_"+id).className = "groupicon";
					break;
				}
			}
		}
		if(document.getElementById('groupcontent'+id).style.display == ''){
			document.getElementById('groupcontent'+id).style.display = 'none';
		}else{
			document.getElementById('groupcontent'+id).innerHTML = '<iframe style="overflow-x:visible" height=0 id=iframebutphe'+id+' allowTransparency=true BORDER=0 scrolling=no FRAMEBORDER=no></iframe>';
			document.getElementById('iframebutphe'+id).src = url; 
			document.getElementById('groupcontent'+id).style.display = '';
			
		}
	}
	function Swap(id,url){
		if(document.getElementById(id).style.display==""){
			document.getElementById(id).style.display="none";
			document.getElementById("groupicon"+id).className = "groupicon";
		}else{
			document.getElementById(id).style.display="";
			document.getElementById("groupicon"+id).className = "groupiconopen";
			loadDivFromUrl(id,url,1);
		}
	}
	<?php if(count($this->data)>0){ ?>
	//execfunction("auth","user","getnextstep","data/<?=$datanextstep?>");
	execfunction("auth","user","delay","data/<?=$datatre?>");
	<?php
	}
	?>	

	function updateImageNew(iddiv,id){
    	var oimg = document.getElementById(iddiv);
    	if(oimg != null){
    		if(oimg.style.display != 'none'){
	    	oimg.style.display = 'none';
	    
	    	var AE = new AjaxEngine();
			var oXmlHttp = AE.createXMLHttp(); 	
		    <?php 
		    $authen = Zend_Registry::get('auth');
		    $user = $authen->getIdentity();
		    ?>
			var url = '/hscv/hscv/updatedaxemphoihop?id_hscv='+id+'&id_u=<?=$user->ID_U?>';
			oXmlHttp.open('post', url , true);
		    oXmlHttp.setRequestHeader("Content-Type", "application/x-www-form-urlencoded");
		    oXmlHttp.onreadystatechange = function () { 
		        if (oXmlHttp.readyState == 4) { 
		        	if (oXmlHttp.status == 200) {             	
		            	//alert(oXmlHttp.responseText);
		        	} else { 
		            	
		            }            
		        } 
		    };  
		    oXmlHttp.send(null);   
    		
    		
	    	}
    	}
	    
    }
	function thuhoi(id_hscv){
		
		var func_ok = 'SwapIframe('+id_hscv+',"/hscv/hscv/thuhoi/year/<?=$this->realyear?>/id/'+ id_hscv+ '");';
		
		var func_cancel = "";
		displayConfirm("Bạn có muốn thu hồi công việc vừa chuyển không?","","",func_ok,func_cancel);
	}
</script>