<?php
	require_once 'Common/FileDinhKem.php';
	
	$disable="/isreadonly/1";
?>
<script type="text/javascript" src=<?php echo $this->baseUrl()."/js/Json/Base64.js"?>></script>
<script type="text/javascript" src=<?php echo $this->baseUrl()."/js/Json/json2.js"?>></script>
<script type="text/javascript" src=<?php echo $this->baseUrl()."/js/Json/json_parse.js"?>></script>
<script type="text/javascript" src=<?php echo $this->baseUrl()."/js/Json/json_parse_state.js"?>></script>
<script type="text/javascript" src=<?php echo $this->baseUrl()."/js/Ajax/AjaxEngine.js"?>></script>
<link rel="stylesheet" href="/styles/jquery.treeview.css" type="text/css" />
<script type="text/javascript" src="/js/jquery.treeview.js"></script>
<script type="text/javascript" src="/js/jquery.cookie.js"></script>
<script type="text/javascript">
    $(document).ready(function(){
        $("#browser").treeview({
            persist: "cookie",
            cookieId: "navigationtree",
            collapsed: true,
            toggle: function() {
            //console.log("%s was toggled.", $(this).find(">span").text());
            }
        });
    });
</script>
    <div class="hscv_left">
        <div class="tree-menu">
            <ul id="browser" class="filetree treeview-famfamfam">
                <li><a class="folder" onclick="
                document.frm.action = '/hscv/hscv/listthumuchscv';document.frm.id_thumuc.value='';document.frm.submit();">Thư mục hồ sơ công việc</a>
                    <?php 
                        $html = "";
                        //echo vbdenModel::ToTree($this->datalvvb,1,"treemenu2",$html,$this->id_lvvb);
                        echo ThuMucModel::ToTreeThumucHSCV($this->thumuc,1,"treemenu2",$html,$this->id_thumuc);
                    ?>    
                </li>
            </ul>
        </div>
    </div>
    <div class="hscv_right">
        <form name=frm method=post onsubmit="document.frm.page.value = 1;document.frm.action = '/hscv/hscv/listthumuchscv/id_thumuc/<?=$this->id_thumuc?>/code/<?=$this->code?>';return true;" style="padding-left: 10px;">
	<table>
		<tr>
			<td nowrap="nowrap">Loại công việc</td>
			<td nowrap="nowrap"><select name="OBJECT" onchange="
						document.frm.page.value = 1;
						if(document.frm.TRANGTHAI!=null)document.frm.TRANGTHAI.value = 0;
						document.frm.action = '/hscv/hscv/listthumuchscv/id_thumuc/<?=$this->id_thumuc?>';
						document.frm.submit();
				">
						<option value="">--Chọn loại công việc--</option>
						<option value="VBD">Xử lý văn bản đến</option>
						<option value="VBSOANTHAO">Công việc</option>
						<!--<option value="MOTCUA">Hồ sơ một cửa</option>-->
				</select>
				<script>document.frm.OBJECT.value="<?=$this->OBJECT?>";</script>
				</td>
			<td width="10" nowrap="nowrap"></td>
			<td nowrap="nowrap"></td>
			<td nowrap="nowrap"></td>
			<td width="100%"></td>
		</tr>
		<?php
			if(strtoupper($this->code)!="ZIP"){
		?>
		<tr style="display:none">
			<td nowrap="nowrap">Trạng thái</td>
			<td nowrap="nowrap"><select name="TRANGTHAI" onchange="
						document.frm.page.value = 1;
						document.frm.action = '/hscv/hscv/listthumuchscv/id_thumuc/<?=$this->id_thumuc?>';
						document.frm.submit();
					">
						<option value=0>--Chọn trang thái--</option>
						<?=WFEngine::ToCombo($this->datatrangthai,$this->TRANGTHAI)?>
				</select></td>
			<td width="10" nowrap="nowrap"></td>
			<td nowrap="nowrap"></td>
			<td nowrap="nowrap"></td>
			<td width="100%"></td>
		</tr>
		<?php } ?>
		<tr>
			<td nowrap="nowrap" valign=top>Nội dung</td>
			<td nowrap="nowrap" colspan="3"><input type=text class=inputbox name=NAMECV value="<?=$this->NAME?>" size=50><br>
			<input type="checkbox" name=INNAME value=1 style="display:none" checked><!--Trong tên công việc -->
			<input type="checkbox" name=INFILE value=1 style="display:none"><!--Trong nội dung dự thảo-->
			</td>
			<td width="100%"></td>
		</tr>
		
		<?php 
			try{
				$config = Zend_Registry::get('config');
				if($config->is_motcua == 1){
		?>
		<tr>
			<td nowrap="nowrap" valign=top>Mã hồ sơ một cửa</td>
			<td nowrap="nowrap" colspan="3"><input type=text class=inputbox name=MASOHOSO value="<?=$this->MASOHOSO?>" size=50><br>
			</td>
			<td width="100%"></td>
		</tr>
		<?php
				
				}
			}catch(Exception $e){
				$e->__toString();
			}
		?>
		<tr>
			<td nowrap="nowrap">Từ ngày</td>
			<td nowrap="nowrap"><?=QLVBDHCommon::calendar($this->NGAY_BD,"NGAY_BD","NGAY_BD") ?> Đến ngày <?=QLVBDHCommon::calendar($this->NGAY_KT,"NGAY_KT","NGAY_KT") ?></td>
			<td width="10" nowrap="nowrap"></td>
			<td nowrap="nowrap"></td>
			<td nowrap="nowrap"></td>
			<td width="100%"></td>
		</tr>
		<tr>
			<td nowrap="nowrap"></td>
			<td nowrap="nowrap" colspan="3"><input type=submit value="Tìm kiếm"></td>
			<td width="100%"></td>
		</tr>
	</table>

<table class=adminlist>
	<thead>
		<tr>
			<th colspan="4">
				<div>
					<div class="limit" style="float:left;">Hiển thị #
						<select name="limit1"  style="width:60px;" id="limit1" class="inputbox" size="1" onchange="
							document.frm.page.value = 1;
							document.frm.limit2.value = document.frm.limit1.value;
							document.frm.action = '/hscv/hscv/listthumuchscv/id_thumuc/<?=$this->id_thumuc?>/code/<?=$this->code?>';
							document.frm.submit();
						">
							<option value="5" <?php if($this->limit==5){echo "selected";} ?>>5</option>
							<option value="10" <?php if($this->limit==10){echo "selected";} ?>>10</option>
							<option value="15" <?php if($this->limit==15){echo "selected";} ?>>15</option>
							<option value="20" <?php if($this->limit==20){echo "selected";} ?>>20</option>
							<option value="25" <?php if($this->limit==25){echo "selected";} ?>>25</option>
							<option value="30" <?php if($this->limit==30){echo "selected";} ?>>30</option>
							<option value="35" <?php if($this->limit==35){echo "selected";} ?>>35</option>
							<option value="40" <?php if($this->limit==40){echo "selected";} ?>>40</option>
							<option value="50" <?php if($this->limit==50){echo "selected";} ?>>50</option>
							<option value="100" <?php if($this->limit==100){echo "selected";} ?>>100</option>
						</select>
					</div>
					<div class="limit" style="float:right;"><?php echo $this->showPage; ?></div>
				</div>
			</th>
		</tr>
		<tr>
			<th nowrap="nowrap">
				#
			</th>
			<th width="100%">
				Tên công việc
			</th>	
                        <th></th>
		</tr>
	</thead>
	<tfoot>
		<tr>
			<th colspan="3">
				<div class="pagination">
					<div class="limit">Hiển thị #
						<select name="limit2" style="width:60px;" id="limit2" class="inputbox" size="1" onchange="
							document.frm.page.value = 1;
							document.frm.limit1.value = document.frm.limit2.value;
							document.frm.action = '/hscv/hscv/listthumuchscv/id_thumuc/<?=$this->id_thumuc?>/code/<?=$this->code?>';
							document.frm.submit();
						">
							<option value="5" <?php if($this->limit==5){echo "selected";} ?>>5</option>
							<option value="10" <?php if($this->limit==10){echo "selected";} ?>>10</option>
							<option value="15" <?php if($this->limit==15){echo "selected";} ?>>15</option>
							<option value="20" <?php if($this->limit==20){echo "selected";} ?>>20</option>
							<option value="25" <?php if($this->limit==25){echo "selected";} ?>>25</option>
							<option value="30" <?php if($this->limit==30){echo "selected";} ?>>30</option>
							<option value="35" <?php if($this->limit==35){echo "selected";} ?>>35</option>
							<option value="40" <?php if($this->limit==40){echo "selected";} ?>>40</option>
							<option value="50" <?php if($this->limit==50){echo "selected";} ?>>50</option>
							<option value="100" <?php if($this->limit==100){echo "selected";} ?>>100</option>
						</select>
					</div>
					<div style="float:right"><?php echo $this->showPage; ?></div>
				</div>
			</th>
		</tr>
	</tfoot>
	<tbody>
<?php
	if(count($this->data)<=0){
		echo "<tr><td colspan='4'>Không tìm thấy hồ sơ công việc nào</td></tr>";
	}else{
	$stt=($this->page-1)*$this->limit;
	$i=0;
	$datatre = "";
	foreach($this->data as $row){
		$row['NAME'] = $this->INNAME==1?QLVBDHCommon::highlightText($row['NAME'],$this->NAME):$row['NAME'];
		if(strtoupper($this->code)!="ZIP"){
			if($row['IS_THEODOI']!=1){
				$tt = hosocongviecModel::getlastlog($row['ID_PI']);
				$datatre .= $row['ID_HSCV'].",".urlencode($tt['DATESEND']).",".$tt['HANXULY'].",".$tt['ID_U_RECEIVE'].",";
				$parentlog = WFEngine::GetStartLogIdByProcessItem($row['ID_PI'],$tt['ID_T']);
				if(is_array($parentlog)){
					foreach($parentlog as $itemparent){
						if($itemparent['ID_PL']!=$tt['ID_PL']){
							$datatre .= $row['ID_HSCV'].",".urlencode($itemparent['DATESEND']).",".$itemparent['HANXULY'].",".$itemparent['ID_U_RECEIVE'].",";
						}
					}
				}
			}
			
		}
		$stt++;
?>
		<tr class="row<?=$this->idhscv==$row['ID_HSCV']?"2":$i?>">
			<td valign="top" rowspan="2"><a name="hscv<?=$row['ID_HSCV']?>"></a><?=$stt?></td>
			<td valign="top">
				<?php
					if($row["ALIAS"]=="VBD"){
						echo "<img src='/images/icon_vbden.jpg'>";
						$vbden = $this->vbden->findByHscv($row['ID_HSCV']);
						
					}else if($row["ALIAS"]=="VBSOANTHAO"){
						echo "<img src='/images/icon_soanthaovb.jpg'>";
					}else if($row["ALIAS"]=="MOTCUA"){
						echo "<img src='/images/icon_motcua.jpg'>";
					}
				?>
				<?php if($row["ALIAS"]=="VBD"){
					$vbdeninfo = $this->vbden->find($vbden['ID_VBD'])->current();
					echo "<b>".$vbdeninfo->SOKYHIEU." - ".QLVBDHCommon::MysqlDateToVnDate($vbdeninfo->NGAYBANHANH)." - ".$vbdeninfo->COQUANBANHANH_TEXT."</b><br>";
				}?>
				<?=$row['NAME']?><?=$row['EXTRA']!=""?" - ".$row['EXTRA']:""?> <span id="TREHAN<?=$row['ID_HSCV']?>"></span>
				<?php
					if($this->INFILE==1){
						$dt = PhienBanDuThaoModel::getFileContent($row['ID_HSCV']);
						foreach($dt as $itemdt){
							$rfind = QLVBDHCommon::highlightString($itemdt['CONTENT'],$this->NAME);
							if($rfind!=""){
				?>
				<br><a href="/hscv/File/download?year=&maso=<?=$itemdt['MASO']?>"><B><?=$itemdt['FILENAME']?>:</B> <?=$rfind?></a>
				<?php 
							}
						}
					}
				?>
				<?php if(strtoupper($this->code)=="PHOIHOP"){
						
						if($row["IS_NEW_PH"] == 0){
							
				?>		
					<img id='img_new_ph_<?=$row["ID_HSCV"]?>' src='/images/moi.gif'></img>
				<?php		}}
				?> 
			</td>

			<td nowrap="nowrap" valign="top" id="NEXTSTEP<?=$row["ID_HSCV"]?>">
			<?php
				 
				 $actid = ResourceUserModel::getActionByUrl('hscv','hscv','inputthumuchscv');
				  if(ResourceUserModel::isAcionAlowed($this->user->USERNAME,$actid[0])){
					
				
			?>
			<a href='javascript:SwapIframe(<?=$row["ID_HSCV"]?>,"/hscv/hscv/inputthumuchscv/id/<?=$row['ID_HSCV']?>/idtmhscv/<?=$row["ID_THUMUC_HSCV"]?>",1);'>Đổi thư mục HSCV</a>
			<?php
				}
			?>
			</td>
		</tr>
		<tr class="row<?=$this->idhscv==$row['ID_HSCV']?"2":$i?>">
			<td colspan="2">
				<div>
					<ul class="chitiethscv">
					<?php if(QLVBDHCommon::TabHscv(1,$row["ID_LOAIHSCV"])==1){ ?>
						<li id=groupicon1_<?=$row["ID_HSCV"]?>>
							<img src="/images/icon_chitiet.jpg" border="0" hspace="5" >
							<a href='javascript:SwapDiv(<?=$row["ID_HSCV"]?>,"/vbden/vbden/detail/type/<?=$row["ID_LOAIHSCV"]?>/id/<?=$row["ID_HSCV"]?>/year/<?=$this->realyear?><?=$disable?>",1);
							<?php if(strtoupper($this->code)=="PHOIHOP"){
						
								if($row["IS_NEW_PH"] == 0){?>
							updateImageNew("img_new_ph_<?=$row["ID_HSCV"]?>",<?=$row["ID_HSCV"]?>);
							<?php }}?>
							'>Chi tiết</a>
						</li>
					<?php } ?>
					<?php if(QLVBDHCommon::TabHscv(6,$row["ID_LOAIHSCV"])==1){ ?>
					<li id=groupicon6_<?=$row["ID_HSCV"]?>>
						<img src="/images/icon_luanchuyen.jpg" border="0" hspace="5" >
						<a href='javascript:SwapDiv(<?=$row["ID_HSCV"]?>,"/hscv/hscv/way/id/<?=$row["ID_HSCV"]?>/year/<?=$this->realyear?>/type/<?=$row["ID_LOAIHSCV"]?>",6);
						<?php if(strtoupper($this->code)=="PHOIHOP"){
						
								if($row["IS_NEW_PH"] == 0){?>
							updateImageNew("img_new_ph_<?=$row["ID_HSCV"]?>",<?=$row["ID_HSCV"]?>);
							<?php }}?>
						'>Luân chuyển</a>
					</li>
					<?php } ?>
					<?php if(QLVBDHCommon::TabHscv(5,$row["ID_LOAIHSCV"])==1){ ?>
					<li id=groupicon5_<?=$row["ID_HSCV"]?>>
						<img src="/images/icon_duthao.jpg" border="0" hspace="5" >
						<a href='javascript:SwapDiv(<?=$row["ID_HSCV"]?>,"/hscv/VanBanDuThao/index/year/<?=$this->realyear?>/iddivParent/groupcontent<?=$row["ID_HSCV"]?>/idHSCV/<?=$row["ID_HSCV"]?><?=$disable?>",5);
						<?php if(strtoupper($this->code)=="PHOIHOP"){
						
								if($row["IS_NEW_PH"] == 0){?>
							updateImageNew("img_new_ph_<?=$row["ID_HSCV"]?>",<?=$row["ID_HSCV"]?>);
							<?php }}?>
						'>Dự thảo</a>
					</li>
					<?php } ?>
					
					<?php if(QLVBDHCommon::TabHscv(8,$row["ID_LOAIHSCV"])==1){ ?>
					<li id=groupicon8_<?=$row["ID_HSCV"]?>>
						<img src="/images/icon_vanbanlienquan.jpg" border="0" hspace="5" >
						<a href='javascript:SwapDiv(<?=$row["ID_HSCV"]?>,"/hscv/hscv/bosung/year/<?=$this->realyear?>/iddivParent/groupcontent<?=$row["ID_HSCV"]?>/id/<?=$row["ID_HSCV"]?><?=$disable?>",8);
						<?php if(strtoupper($this->code)=="PHOIHOP"){
						
								if($row["IS_NEW_PH"] == 0){?>
							updateImageNew("img_new_ph_<?=$row["ID_HSCV"]?>",<?=$row["ID_HSCV"]?>);
							<?php }}?>
						'>Bổ sung hồ sơ</a>
					</li>
					<?php } ?>
					<?php 
					if(QLVBDHCommon::TabHscv(2,$row["ID_LOAIHSCV"])==1){ ?>
					<li id=groupicon2_<?=$row["ID_HSCV"]?>>
						<img src="/images/icon_butphe.jpg" border="0" hspace="5" >
						<a href='javascript:SwapDiv(<?=$row["ID_HSCV"]?>,"/hscv/hscv/viewbutphe/id/<?=$row["ID_HSCV"]?>/year/<?=$this->realyear?><?=$disable?>",2);
						<?php if(strtoupper($this->code)=="PHOIHOP"){
						
								if($row["IS_NEW_PH"] == 0){?>
							updateImageNew("img_new_ph_<?=$row["ID_HSCV"]?>",<?=$row["ID_HSCV"]?>);
							<?php }}?>
						'>Bút phê</a>
					</li>
					<?php } ?>
					<?php if(QLVBDHCommon::TabHscv(3,$row["ID_LOAIHSCV"])==1){ ?>
					<li id=groupicon3_<?=$row["ID_HSCV"]?>>
						<img src="/images/icon_phoihop.gif" border="0" hspace="5" >
						<a href='javascript:SwapDiv(<?=$row["ID_HSCV"]?>,"/hscv/phoihop/index/idhscv/<?=$row["ID_HSCV"]?>/year/<?=$this->realyear?><?=strtoupper($this->code)=="PHOIHOP"?"":$disable?>",3);
						<?php if(strtoupper($this->code)=="PHOIHOP"){
						
								if($row["IS_NEW_PH"] == 0){?>
							updateImageNew("img_new_ph_<?=$row["ID_HSCV"]?>",<?=$row["ID_HSCV"]?>);
							<?php }}?>
						'>Phối hợp</a>
					</li>
					<?php } ?>
					<?php if(QLVBDHCommon::TabHscv(4,$row["ID_LOAIHSCV"])==1){ ?>
					<li id=groupicon4_<?=$row["ID_HSCV"]?>>
						<img src="/images/icon_files.jpg" border="0" hspace="5" >
						<a href='javascript:SwapDiv(<?=$row["ID_HSCV"]?>,"/hscv/file/index/iddiv/groupcontent<?=$row["ID_HSCV"]?>/idObject/<?=$row["ID_LOAIHSCV"]==1?$vbden['ID_VBD']:$row["ID_HSCV"]?>/is_new/0/year/<?=$this->realyear?>/type/<?=$row["ID_LOAIHSCV"]==1?"3":"1"?><?=$disablefile?>",4);
						<?php if(strtoupper($this->code)=="PHOIHOP"){
						
								if($row["IS_NEW_PH"] == 0){?>
							updateImageNew("img_new_ph_<?=$row["ID_HSCV"]?>",<?=$row["ID_HSCV"]?>);
							<?php }}?>
						'>Đính kèm</a>
					</li>
					<?php } ?>
					<?php if(QLVBDHCommon::TabHscv(7,$row["ID_LOAIHSCV"])==1){ ?>
					<li id=groupicon7_<?=$row["ID_HSCV"]?>>
						<img src="/images/icon_vanbanlienquan.jpg" border="0" hspace="5" >
						<a href='javascript:SwapDiv(<?=$row["ID_HSCV"]?>,"/hscv/vanbanlienquan/index/year/<?=$this->realyear?>/iddivParent/groupcontent<?=$row["ID_HSCV"]?>/idHSCV/<?=$row["ID_HSCV"]?><?=$disable?>",7);
						<?php if(strtoupper($this->code)=="PHOIHOP"){
						
								if($row["IS_NEW_PH"] == 0){?>
							updateImageNew("img_new_ph_<?=$row["ID_HSCV"]?>",<?=$row["ID_HSCV"]?>);
							<?php }}?>
						'>VB liên quan</a>
					</li>
					<?php } ?>
					<?php if($this->id_thumuc>1 || $row["ALIAS"]=="MOTCUA"){ ?>
					<li id=groupicon9_<?=$row["ID_HSCV"]?>>
						<img src="/images/icon_vanbanlienquan.jpg" border="0" hspace="5" >
						<a href='javascript:SwapIframe(<?=$row["ID_HSCV"]?>,"/hscv/hscv/viewresult/iddivParent/groupcontent<?=$row["ID_HSCV"]?>/id/<?=$row["ID_HSCV"]?><?=$disable?>",9);
						<?php if(strtoupper($this->code)=="PHOIHOP"){
						
								if($row["IS_NEW_PH"] == 0){?>
							updateImageNew("img_new_ph_<?=$row["ID_HSCV"]?>",<?=$row["ID_HSCV"]?>);
							<?php }}?>
						'>Kết quả</a>
					</li>
					<?php } ?>
					<?php if($this->id_thumuc>1 || $row["ALIAS"]=="MOTCUA"){ 
						require_once('motcua/models/dkwebModel.php');
						$data_maso = dkwebModel::GetMasodkquamangByIDHSCV($row["ID_HSCV"]);		
						
						if($data_maso){
					?>
					<li id=groupicon9_<?=$row["ID_HSCV"]?>>
						<img src="/images/icon_vanbanlienquan.jpg" border="0" hspace="5" >
						<a href='javascript:SwapIframe(<?=$row["ID_HSCV"]?>,"/motcua/dongbohsmc/viewdon/mahoso/<?=$data_maso?>/iddivParent/groupcontent<?=$row["ID_HSCV"]?>/id_hscv/<?=$row["ID_HSCV"]?><?=$disable?>",9);
						<?php if(strtoupper($this->code)=="PHOIHOP"){
						
								if($row["IS_NEW_PH"] == 0){?>
							updateImageNew("img_new_ph_<?=$row["ID_HSCV"]?>",<?=$row["ID_HSCV"]?>);
							<?php }}?>
						'>Đơn xin cấp phép</a>
					</li>
					<?php } }?>
					</ul>
				</div>
				<div class="groupcontent" id="groupcontent<?=$row["ID_HSCV"]?>" style="display:none;background: #ffffff; border: 1px solid #ccc;"></div>
			</td>
		</tr>
<?php
		$i = (-1+$i)*-1;	
	}
}
?>
	</tbody>
</table>
<input type="hidden" name="page" value="<?php echo $this->page; ?>" />
<input type="hidden" name="id_thumuc" value="<?=$this->id_thumuc?>" />
</form>
    </div>
<script>
	
	
	function CreateButtonClick(url){
		document.frm.action = url;
		document.frm.submit();
	}
	function SwapDiv(id,url,tab){
		for(var i=1;i<11;i++){
			if(document.getElementById("groupicon"+i+"_"+id)){
				if(tab!=i){
					if(document.getElementById("groupicon"+i+"_"+id).className=="groupiconopen"){
						document.getElementById("groupcontent"+id).style.display="none";
						document.getElementById("groupicon"+i+"_"+id).className = "groupicon";
						break;
					}
				}
			}
		}
		if(document.getElementById("groupcontent"+id).style.display==""){
			document.getElementById("groupcontent"+id).style.display="none";
			document.getElementById("groupicon"+tab+"_"+id).className = "groupicon";
		}else{
			document.getElementById("groupcontent"+id).style.display="";
			document.getElementById("groupicon"+tab+"_"+id).className = "groupiconopen";
			document.getElementById("groupcontent"+id).innerHTML="<img src='/images/loading.gif' width='16' height='16' border='0'></img<img src='/images/loading.gif' width='16' height='16' border='0'></img><img src='/images/loading.gif' width='16' height='16' border='0'></img><img src='/images/loading.gif' width='16' height='16' border='0'></img>";
			loadDivFromUrl("groupcontent"+id,url,1);

	}
	}
	function SwapIframe(id,url){
		for(var i=1;i<11;i++){
			if(document.getElementById("groupicon"+i+"_"+id)){
				if(document.getElementById("groupicon"+i+"_"+id).className=="groupiconopen"){
					document.getElementById("groupcontent"+id).style.display="none";
					document.getElementById("groupicon"+i+"_"+id).className = "groupicon";
					break;
				}
			}
		}
		if(document.getElementById('groupcontent'+id).style.display == ''){
			document.getElementById('groupcontent'+id).style.display = 'none';
		}else{
			document.getElementById('groupcontent'+id).innerHTML = '<iframe style="overflow-x:visible" height=0 id=iframebutphe'+id+' allowTransparency=true BORDER=0 scrolling=no FRAMEBORDER=no></iframe>';
			document.getElementById('iframebutphe'+id).src = url; 
			document.getElementById('groupcontent'+id).style.display = '';
		}
	}
	function Swap(id,url){
		if(document.getElementById(id).style.display==""){
			document.getElementById(id).style.display="none";
			document.getElementById("groupicon"+id).className = "groupicon";
		}else{
			document.getElementById(id).style.display="";
			document.getElementById("groupicon"+id).className = "groupiconopen";
			loadDivFromUrl(id,url,1);
		}
	}
	

	
</script>