<?php require_once 'qtht/models/LoaiVanBanModel.php';
require_once 'qtht/models/CoquanModel.php'; 
require_once 'qtht/models/DepartmentsModel.php';
require_once 'qtht/models/sovanbanModel.php'
?>
<script type="text/javascript" src="/js/calendar.js"></script>
<form name=frm action="/report/Thongketaphoso/reportview" method="POST" target="reportview">
<div class=clr></div>
<div>
<label><b>Ngày nhận:</b></label>
<?=QLVBDHCommon::calendar($this->fromdate,"fromdate","fromdate") ?>
>>
<?=QLVBDHCommon::calendar($this->todate,"todate","todate") ?>

</div>

<div class=clr></div>
<div>
<div>
<label><b>Tháng:</b></label>
<?php $year = QLVBDHCommon::getYear();?>
<input type="radio" name='sel_timedis' onclick="setvalueDateD('1/1/<? echo $year?>','31/1/<? echo $year?>')">1
<?php 

$d = strtotime($year."-3-1") ;
$d = $d - 86400;
$str_cuoi2 =date('d/m/Y',$d); 
 ?>
<input type="radio" name='sel_timedis' onclick="setvalueDateD('1/2/<? echo $year?>','<?php echo $str_cuoi2 ?>')" >2
<input type="radio" name='sel_timedis' onclick="setvalueDateD('1/3/<? echo $year?>','31/3/<? echo $year?>')">3
<input type="radio" name='sel_timedis'onclick="setvalueDateD('1/4/<? echo $year?>','30/4/<? echo $year?>')" >4
<input type="radio" name='sel_timedis'onclick="setvalueDateD('1/5/<? echo $year?>','31/5/<? echo $year?>')">5
<input type="radio" name='sel_timedis' onclick="setvalueDateD('1/6/<? echo $year?>','30/6/<? echo $year?>')">6
<input type="radio" name='sel_timedis'onclick="setvalueDateD('1/7/<? echo $year?>','31/7/<? echo $year?>')" >7
<input type="radio" name='sel_timedis'onclick="setvalueDateD('1/8/<? echo $year?>','31/8/<? echo $year?>')" >8
<input type="radio" name='sel_timedis'onclick="setvalueDateD('1/9/<? echo $year?>','30/9/<? echo $year?>')">9
<input type="radio" name='sel_timedis'onclick="setvalueDateD('1/10/<? echo $year?>','31/10/<? echo $year?>')">10
<input type="radio" name='sel_timedis'onclick="setvalueDateD('1/11/<? echo $year?>','30/11/<? echo $year?>')">11
<input type="radio" name='sel_timedis'onclick="setvalueDateD('1/12/<? echo $year?>','31/12/<? echo $year?>')">12
</div>
<div class=clr></div>
<div>
<label><b>Quí:</b></label>
<input type="radio" name='sel_timedis' onclick="setvalueDateD('1/1/<? echo $year?>','31/3/<? echo $year?>')">I
<input type="radio" name='sel_timedis' onclick="setvalueDateD('1/4/<? echo $year?>','30/6/<? echo $year?>')">II
<input type="radio" name='sel_timedis'onclick="setvalueDateD('1/7/<? echo $year?>','30/9/<? echo $year?>')">III
<input type="radio" name='sel_timedis'onclick="setvalueDateD('1/10/<? echo $year?>','31/12/<? echo $year?>')">IV
</div>
<div class=clr></div>
<div>
<label><b>Năm:</b></label>
<input type="radio" name='sel_timedis' onclick="setvalueDateD('1/1/<? echo $year?>','31/12/<? echo $year?>')">
</div>
</div>

<div class="clr"></div>
<input type=hidden id=h_isexel name=h_isexel value=0>
<div>
<br/>
<input type="button" title="Hiển thị báo cáo" style="background: url(/images/hscv-input-bg.png) repeat-x;" 
onclick="
document.frm.target='reportview';
document.frm.h_isexel.value = 0;
document.frm.action = '/report/Thongketaphoso/reportview';
document.frm.submit();
return false;" value="Hiển thị báo cáo">

<input type="button" title="Xuất excel" style="background: url(/images/hscv-input-bg.png) repeat-x;" 
onclick="
document.frm.target='reportview';
document.frm.h_isexel.value = 1;
document.frm.action = '/report/Thongketaphoso/reportviewexcel';
document.frm.submit();
return false;" value="Xuất ra Exel">

<input type="button" title="In báo cáo" style="background: url(/images/hscv-input-bg.png) repeat-x;" 
onclick="
document.frm.target='_blank';
document.frm.h_isexel.value = 0;
document.frm.action = '/report/Thongketaphoso/reportview/is_in/1';
document.frm.submit();
return false;" value="In báo cáo">

</div>
</form>
<iframe style="overflow-x:visible" allowTransparency=true BORDER=0 scrolling=no FRAMEBORDER=no 
id="reportview" 
name="reportview" >
</iframe>
<script>
function setvalueDateD(value_from,value_to){
	document.frm.fromdate.value = value_from;
	document.frm.todate.value = value_to;
}
</script>
