<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html>
<head>
<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />

<style>
td{
	border-color: black;
}
th{
	border-color: black;
}
</style>

</head>
<body style="background-color:transparent">
<table  width=100% >
<tr >
  <td align=center ><?= mb_strtoupper($this->config->sys_info->unit,"utf-8") ?></td>

  <td align=center>CỘNG HÒA XÃ HỘI CHỦ
  NGHĨA VIỆT NAM</td>
 </tr>
 <tr >
  <td align=center ><b><?=mb_strtoupper($this->config->sys_info->company,"utf-8") ?></b></td>
  <td align=center style="text-decoration:underline">Ðộc lập - Tự do - Hạnh phúc</td>
 </tr>
 <tr > 
  <td ></td>
  <td align=right style="font-style:italic">
<?=$this->config->sys_info->city?>, ngày <?=date("d")?> tháng <?=date("m")?> năm <?=date("Y")?>
</td>
 </tr>

 
</table>
<p align=center><b>THỐNG KÊ TẬP HỒ SƠ </b> <br/>
<?php echo $this->thu;?> năm <?=QLVBDHCommon::getYear()?></p>

<table border="1" style="border: 1px solid black; border-collapse: collapse;">
 <thead>
 	<tr>
	     <th nowrap >Stt</th>		
 		<th nowrap>Tên hồ sơ công việc điện tử</th>		
		<th nowrap >Thuộc thư mục hồ sơ công việc điện tử </th>        
 		<th >Người tạo</th>		
 		<th nowrap>Ngày tạo</th>		
 		<th >Văn bản, tệp đính kèm</th>	
 	</tr>
 </thead>
 <tbody>
 <?php  require_once 'report/models/ThongketaphosoModel.php';
 $stt=1; foreach($this->data as $item){?>
	
	<tr>
    <td nowrap valign=top  width="5%"><?=$stt?></td>	
 	<td nowrap valign=top  width="20%"><?echo $item['TEN'];?></td>	
 	<td nowrap valign=top  width="20%"><?php ThongketaphosoModel::ToTreethumuc($this->datathumuc,$item['ID_THUMUC']); ?></td> 	
	<td valign=top width="20%"><?if($item['NGUOITAO']!=""){ echo ThongketaphosoModel::getName($item['NGUOITAO']);}?></td>
 	<td nowrap valign=top  width="20%"><?php echo QLVBDHCommon::MysqlDateToVnDate($item["NGAYTAO"]) ?></td>
 	<td nowrap valign=top align="right"  width="20%"><?php echo count(ThongketaphosoModel::Vanbantaphoso($item['ID_TAPHOSO'])); ?> </td>	
	</tr>
	<?php $stt++;}?>
 </tbody>
</table>
</body>
<script>print();</script>
</html>
