<?php 
require_once 'qtht/models/LoaiVanBanModel.php';
?>
<html xmlns:o="urn:schemas-microsoft-com:office:office"
xmlns:x="urn:schemas-microsoft-com:office:excel"
xmlns="http://www.w3.org/TR/REC-html40">

<head>
	<meta http-equiv=Content-Type content="text/html; charset=utf-8">
	<meta name=ProgId content=Excel.Sheet>
	<meta name=Generator content="Microsoft Excel 14">
	<link rel=File-List href="vanbandi_files/filelist.xml">
	<style id="baocaovanbandi (32)_5003_Styles">
	<!--table
	{mso-displayed-decimal-separator:"\.";
	mso-displayed-thousand-separator:"\,";}
	.xl155003
	{padding-top:1px;
		padding-right:1px;
		padding-left:1px;
		mso-ignore:padding;
		color:black;
		font-size:11.0pt;
		font-weight:400;
		font-style:normal;
		text-decoration:none;
		font-family:Calibri, sans-serif;
		mso-font-charset:0;
		mso-number-format:General;
		text-align:general;
		vertical-align:bottom;
		mso-background-source:auto;
		mso-pattern:auto;
		white-space:nowrap;}
		.xl635003
		{padding-top:1px;
			padding-right:1px;
			padding-left:1px;
			mso-ignore:padding;
			color:windowtext;
			font-size:12.0pt;
			font-weight:400;
			font-style:normal;
			text-decoration:none;
			font-family:"Times New Roman", serif;
			mso-font-charset:0;
			mso-number-format:General;
			text-align:general;
			vertical-align:bottom;
			mso-background-source:auto;
			mso-pattern:auto;
			white-space:nowrap;}
			.xl645003
			{padding-top:1px;
				padding-right:1px;
				padding-left:1px;
				mso-ignore:padding;
				color:windowtext;
				font-size:13.0pt;
				font-weight:400;
				font-style:normal;
				text-decoration:none;
				font-family:"Times New Roman", serif;
				mso-font-charset:0;
				mso-number-format:General;
				text-align:general;
				vertical-align:bottom;
				mso-background-source:auto;
				mso-pattern:auto;
				white-space:nowrap;}
				.xl655003
				{padding-top:1px;
					padding-right:1px;
					padding-left:1px;
					mso-ignore:padding;
					color:windowtext;
					font-size:13.0pt;
					font-weight:700;
					font-style:normal;
					text-decoration:none;
					font-family:"Times New Roman", serif;
					mso-font-charset:0;
					mso-number-format:General;
					text-align:general;
					vertical-align:bottom;
					mso-background-source:auto;
					mso-pattern:auto;
					white-space:nowrap;}
					.xl665003
					{padding-top:1px;
						padding-right:1px;
						padding-left:1px;
						mso-ignore:padding;
						color:windowtext;
						font-size:13.0pt;
						font-weight:700;
						font-style:normal;
						text-decoration:underline;
						text-underline-style:single;
						font-family:"Times New Roman", serif;
						mso-font-charset:0;
						mso-number-format:General;
						text-align:general;
						vertical-align:bottom;
						mso-background-source:auto;
						mso-pattern:auto;
						white-space:nowrap;}
						.xl675003
						{padding-top:1px;
							padding-right:1px;
							padding-left:1px;
							mso-ignore:padding;
							color:windowtext;
							font-size:12.0pt;
							font-weight:400;
							font-style:italic;
							text-decoration:none;
							font-family:"Times New Roman", serif;
							mso-font-charset:0;
							mso-number-format:General;
							text-align:general;
							vertical-align:bottom;
							mso-background-source:auto;
							mso-pattern:auto;
							white-space:nowrap;}
							.xl685003
							{padding-top:1px;
								padding-right:1px;
								padding-left:1px;
								mso-ignore:padding;
								color:windowtext;
								font-size:12.0pt;
								font-weight:400;
								font-style:normal;
								text-decoration:none;
								font-family:"Times New Roman", serif;
								mso-font-charset:0;
								mso-number-format:General;
								text-align:center;
								vertical-align:middle;
								mso-background-source:auto;
								mso-pattern:auto;
								white-space:nowrap;}
								.xl695003
								{padding-top:1px;
									padding-right:1px;
									padding-left:1px;
									mso-ignore:padding;
									color:windowtext;
									font-size:12.0pt;
									font-weight:700;
									font-style:normal;
									text-decoration:none;
									font-family:"Times New Roman", serif;
									mso-font-charset:0;
									mso-number-format:General;
									text-align:center;
									vertical-align:middle;
									border:.5pt solid windowtext;
									background:silver;
									mso-pattern:black none;
									white-space:normal;}
									.xl705003
									{padding-top:1px;
										padding-right:1px;
										padding-left:1px;
										mso-ignore:padding;
										color:windowtext;
										font-size:12.0pt;
										font-weight:700;
										font-style:normal;
										text-decoration:none;
										font-family:"Times New Roman", serif;
										mso-font-charset:0;
										mso-number-format:General;
										text-align:center;
										vertical-align:middle;
										border-top:.5pt solid windowtext;
										border-right:.5pt solid windowtext;
										border-bottom:.5pt solid windowtext;
										border-left:none;
										background:silver;
										mso-pattern:black none;
										white-space:normal;}
										.xl715003
										{padding-top:1px;
											padding-right:1px;
											padding-left:1px;
											mso-ignore:padding;
											color:windowtext;
											font-size:12.0pt;
											font-weight:400;
											font-style:normal;
											text-decoration:none;
											font-family:"Times New Roman", serif;
											mso-font-charset:0;
											mso-number-format:"\@";
											text-align:center;
											vertical-align:middle;
											border-top:none;
											border-right:.5pt solid windowtext;
											border-bottom:.5pt solid windowtext;
											border-left:.5pt solid windowtext;
											mso-background-source:auto;
											mso-pattern:auto;
											white-space:normal;}
											.xl725003
											{padding-top:1px;
												padding-right:1px;
												padding-left:1px;
												mso-ignore:padding;
												color:windowtext;
												font-size:12.0pt;
												font-weight:400;
												font-style:normal;
												text-decoration:none;
												font-family:"Times New Roman", serif;
												mso-font-charset:0;
												mso-number-format:"\@";
												text-align:center;
												vertical-align:middle;
												border-top:none;
												border-right:.5pt solid windowtext;
												border-bottom:.5pt solid windowtext;
												border-left:none;
												mso-background-source:auto;
												mso-pattern:auto;
												white-space:normal;}
												.xl735003
												{padding-top:1px;
													padding-right:1px;
													padding-left:1px;
													mso-ignore:padding;
													color:windowtext;
													font-size:12.0pt;
													font-weight:400;
													font-style:normal;
													text-decoration:none;
													font-family:"Times New Roman", serif;
													mso-font-charset:0;
													mso-number-format:"\[$-1010000\]d\/m\/yyyy\;\@";
													text-align:center;
													vertical-align:middle;
													border-top:none;
													border-right:.5pt solid windowtext;
													border-bottom:.5pt solid windowtext;
													border-left:none;
													mso-background-source:auto;
													mso-pattern:auto;
													white-space:normal;}
													.xl745003
													{padding-top:1px;
														padding-right:1px;
														padding-left:1px;
														mso-ignore:padding;
														color:windowtext;
														font-size:12.0pt;
														font-weight:400;
														font-style:italic;
														text-decoration:none;
														font-family:"Times New Roman", serif;
														mso-font-charset:0;
														mso-number-format:"\@";
														text-align:center;
														vertical-align:middle;
														border-top:none;
														border-right:.5pt solid windowtext;
														border-bottom:.5pt solid windowtext;
														border-left:none;
														mso-background-source:auto;
														mso-pattern:auto;
														white-space:normal;}
														.xl755003
														{padding-top:1px;
															padding-right:1px;
															padding-left:1px;
															mso-ignore:padding;
															color:windowtext;
															font-size:13.0pt;
															font-weight:400;
															font-style:normal;
															text-decoration:none;
															font-family:"Times New Roman", serif;
															mso-font-charset:0;
															mso-number-format:General;
															text-align:center;
															vertical-align:middle;
															mso-background-source:auto;
															mso-pattern:auto;
															white-space:nowrap;}
															.xl765003
															{padding-top:1px;
																padding-right:1px;
																padding-left:1px;
																mso-ignore:padding;
																color:windowtext;
																font-size:13.0pt;
																font-weight:700;
																font-style:normal;
																text-decoration:none;
																font-family:"Times New Roman", serif;
																mso-font-charset:0;
																mso-number-format:General;
																text-align:center;
																vertical-align:middle;
																mso-background-source:auto;
																mso-pattern:auto;
																white-space:nowrap;}
																.xl775003
																{padding-top:1px;
																	padding-right:1px;
																	padding-left:1px;
																	mso-ignore:padding;
																	color:windowtext;
																	font-size:13.0pt;
																	font-weight:400;
																	font-style:normal;
																	text-decoration:underline;
																	text-underline-style:single;
																	font-family:"Times New Roman", serif;
																	mso-font-charset:0;
																	mso-number-format:General;
																	text-align:center;
																	vertical-align:middle;
																	mso-background-source:auto;
																	mso-pattern:auto;
																	white-space:nowrap;}
																	.xl785003
																	{padding-top:1px;
																		padding-right:1px;
																		padding-left:1px;
																		mso-ignore:padding;
																		color:windowtext;
																		font-size:12.0pt;
																		font-weight:400;
																		font-style:italic;
																		text-decoration:none;
																		font-family:"Times New Roman", serif;
																		mso-font-charset:0;
																		mso-number-format:General;
																		text-align:right;
																		vertical-align:bottom;
																		mso-background-source:auto;
																		mso-pattern:auto;
																		white-space:nowrap;}
																		.xl795003
																		{padding-top:1px;
																			padding-right:1px;
																			padding-left:1px;
																			mso-ignore:padding;
																			color:windowtext;
																			font-size:12.0pt;
																			font-weight:700;
																			font-style:normal;
																			text-decoration:none;
																			font-family:"Times New Roman", serif;
																			mso-font-charset:0;
																			mso-number-format:General;
																			text-align:center;
																			vertical-align:bottom;
																			mso-background-source:auto;
																			mso-pattern:auto;
																			white-space:nowrap;}
																			.xl805003
																			{padding-top:1px;
																				padding-right:1px;
																				padding-left:1px;
																				mso-ignore:padding;
																				color:windowtext;
																				font-size:12.0pt;
																				font-weight:400;
																				font-style:italic;
																				text-decoration:none;
																				font-family:"Times New Roman", serif;
																				mso-font-charset:0;
																				mso-number-format:General;
																				text-align:center;
																				vertical-align:bottom;
																				mso-background-source:auto;
																				mso-pattern:auto;
																				white-space:nowrap;}
																				-->
																			</style>
																		</head>

																		<body>
																			<!--[if !excel]>&nbsp;&nbsp;<![endif]-->
<!--The following information was generated by Microsoft Excel's Publish as Web
	Page wizard.-->
<!--If the same item is republished from Excel, all information between the DIV
	tags will be replaced.-->
	<!----------------------------->
	<!--START OF OUTPUT FROM EXCEL PUBLISH AS WEB PAGE WIZARD -->
	<!----------------------------->

<div id="baocaovanbandi (32)_5003" align=center x:publishsource="Excel"><!--The following information was generated by Microsoft Office Excel's Publish
as Web Page wizard.--><!--If the same item is republished from Excel, all information between the DIV
tags will be replaced.--><!-----------------------------><!--START OF OUTPUT FROM EXCEL PUBLISH AS WEB PAGE WIZARD -->

<table border=0 cellpadding=0 cellspacing=0 width=1794 style='border-collapse:
collapse;table-layout:fixed;width:1347pt'>
<col class=xl635003 width=47 style='mso-width-source:userset;mso-width-alt:
1718;width:35pt'>
<col class=xl635003 width=111 style='mso-width-source:userset;mso-width-alt:
4059;width:83pt'>
<col class=xl635003 width=128 style='mso-width-source:userset;mso-width-alt:
4681;width:96pt'>
<col class=xl635003 width=107 style='mso-width-source:userset;mso-width-alt:
3913;width:80pt'>
<col class=xl635003 width=123 style='mso-width-source:userset;mso-width-alt:
4498;width:92pt'>
<col class=xl635003 width=150 style='mso-width-source:userset;mso-width-alt:
5485;width:113pt'>
<col class=xl635003 width=88 style='mso-width-source:userset;mso-width-alt:
3218;width:66pt'>
<col class=xl635003 width=78 style='mso-width-source:userset;mso-width-alt:
2852;width:59pt'>
<col class=xl635003 width=159 style='mso-width-source:userset;mso-width-alt:
5814;width:119pt'>
<col class=xl635003 width=134 style='mso-width-source:userset;mso-width-alt:
4900;width:101pt'>
<col width=186 style='mso-width-source:userset;mso-width-alt:6802;width:140pt'>
<col width=154 style='mso-width-source:userset;mso-width-alt:5632;width:116pt'>
<col width=186 style='mso-width-source:userset;mso-width-alt:6802;width:140pt'>
<col width=143 style='mso-width-source:userset;mso-width-alt:5229;width:107pt'>
<tr class=xl645003 height=23 style='mso-height-source:userset;height:17.25pt'>
	<td colspan=5 height=23 class=xl755003 width=516 style='height:17.25pt;
	width:386pt'><?= mb_strtoupper($this->config->sys_info->unit,"utf-8") ?></td>
	<td colspan=4 class=xl755003 width=475 style='width:357pt'>CỘNG HÒA XÃ HỘI
	CHỦ NGHĨA VIỆT NAM</td>
	<td class=xl655003 width=134 style='width:101pt'></td>
	<td class=xl645003 width=186 style='width:140pt'></td>
	<td class=xl645003 width=154 style='width:116pt'></td>
	<td class=xl645003 width=186 style='width:140pt'></td>
	<td class=xl645003 width=143 style='width:107pt'></td>
</tr>
<tr class=xl645003 height=23 style='mso-height-source:userset;height:17.25pt'>
	<td colspan=5 height=23 class=xl765003 style='height:17.25pt'><?=mb_strtoupper($this->config->sys_info->company,"utf-8") ?></td>
	<td colspan=4 class=xl775003>Ðộc lập - Tự do - Hạnh phúc</td>
	<td class=xl665003></td>
	<td class=xl645003></td>
	<td class=xl645003></td>
	<td class=xl645003></td>
	<td class=xl645003></td>
</tr>
<tr class=xl635003 height=21 style='mso-height-source:userset;height:15.75pt'>
	<td height=21 class=xl635003 style='height:15.75pt'></td>
	<td class=xl635003></td>
	<td class=xl635003></td>
	<td class=xl675003></td>
	<td class=xl675003></td>
	<td colspan=4 class=xl785003><?=$this->config->sys_info->city?>,ngày<?=date("d")?> tháng <?=date("m")?> năm <?=date("Y")?></td>
	<td class=xl675003></td>
	<td class=xl635003></td>
	<td class=xl635003></td>
	<td class=xl635003></td>
	<td class=xl635003></td>
</tr>
<tr class=xl635003 height=21 style='mso-height-source:userset;height:15.75pt'>
	<td height=21 class=xl635003 style='height:15.75pt'></td>
	<td class=xl635003></td>
	<td class=xl635003></td>
	<td class=xl635003></td>
	<td class=xl635003></td>
	<td class=xl635003></td>
	<td class=xl635003></td>
	<td class=xl635003></td>
	<td class=xl635003></td>
	<td class=xl635003></td>
	<td class=xl635003></td>
	<td class=xl635003></td>
	<td class=xl635003></td>
	<td class=xl635003></td>
</tr>
<tr class=xl635003 height=21 style='mso-height-source:userset;height:15.75pt'>
	<td colspan=9 height=21 class=xl795003 style='height:15.75pt'>BÁO CÁO VĂN BẢN
	ĐI</td>
	<td class=xl635003></td>
	<td class=xl635003></td>
	<td class=xl635003></td>
	<td class=xl635003></td>
	<td class=xl635003></td>
</tr>
<?php 
if(count($this->id_lvbs) > 0) 
{ 
	$lvb = htmlspecialchars(LoaiVanBanModel::getArrNameById($this->id_lvbs));
	?>
	<tr class=xl635003 height=21 style='mso-height-source:userset;height:15.75pt'>
		<td colspan=9 height=21 class=xl795003 style='height:15.75pt'>Loại Văn Bản:
			<?= $this->id_lvbs > 0 ? $lvb : 'Tất cả các loại';?></td>
			<td class=xl635003></td>
			<td class=xl635003></td>
			<td class=xl635003></td>
			<td class=xl635003></td>
			<td class=xl635003></td>
		</tr>
	<?php } ?>
	<tr class=xl635003 height=21 style='mso-height-source:userset;height:15.75pt'>
		<td colspan=9 height=21 class=xl805003 style='height:15.75pt'><?php echo $this->thu;?> năm <?=date("Y")?></td>
		<td class=xl635003></td>
		<td class=xl635003></td>
		<td class=xl635003></td>
		<td class=xl635003></td>
		<td class=xl635003></td>
	</tr>
	<tr class=xl635003 height=21 style='mso-height-source:userset;height:15.75pt'>
		<td height=21 class=xl635003 style='height:15.75pt'></td>
		<td class=xl635003></td>
		<td class=xl635003></td>
		<td class=xl635003></td>
		<td class=xl635003></td>
		<td class=xl635003></td>
		<td class=xl635003></td>
		<td class=xl635003></td>
		<td class=xl635003></td>
		<td class=xl635003></td>
		<td class=xl635003></td>
		<td class=xl635003></td>
		<td class=xl635003></td>
		<td class=xl635003></td>
	</tr>
	<tr class=xl685003 height=100 style='mso-height-source:userset;height:75.0pt'>
		<td height=100 class=xl695003 width=47 style='height:75.0pt;width:35pt'>STT</td>
		<td class=xl705003 width=111 style='width:83pt'>Ký hiệu VB</td>
		<td class=xl705003 width=128 style='width:96pt'>Trích Yếu VB</td>
		<td class=xl705003 width=107 style='width:80pt'>Cơ Quan Ban Hành</td>
		<td class=xl705003 width=123 style='width:92pt'>Ngày Ban Hành</td>
		<td class=xl705003 width=150 style='width:113pt'>Thông Tin Văn Bản Đến</td>
		<td class=xl705003 width=88 style='width:66pt'>Gửi Liên Thông</td>
		<td class=xl705003 width=78 style='width:59pt'>Có File Đính Kèm</td>
		<td class=xl705003 width=159 style='width:119pt'>Dòng Luân Chuyển</td>
		<td class=xl705003 width=134 style='width:101pt'>Phòng Xử lý</td>
		<td class=xl705003 width=186 style='width:140pt'>Người Soạn VB</td>
		<td class=xl705003 width=154 style='width:116pt'>Trạng Thái</td>
		<td class=xl705003 width=186 style='width:140pt'>Số Văn Bản</td>
		<td class=xl705003 width=143 style='width:107pt'>Ghi chú</td>
	</tr>
	<?php 
	$stt=1;
	foreach($this->data as $row){ 
		?>
		<tr class=xl635003 height=63 style='mso-height-source:userset;height:47.25pt'>
			<td height=63 class=xl715003 width=47 style='height:47.25pt;width:35pt'><?=$stt ?></td>
			<td class=xl725003 width=111 style='width:83pt'><?php echo $row["SOKYHIEU"]?></td>
			<td class=xl735003 width=128 style='width:96pt'><?=($row["TRICHYEU"]) ?></td>
			<td class=xl725003 width=107 style='width:80pt'><?=LoaiVanBanModel::getCQNameById($row["ID_CQ"])?></td>
			<td class=xl725003 width=123 style='width:92pt'><?php echo $row["NGAYBANHANH"] ?></td>
			<td class=xl725003 width=150 style='width:113pt'><?php echo VanbandireportModel::getIdHscvVBDFromIDHscvVBDi($row["ID_HSCV"]) ?></td>
			<td class=xl725003 width=88 style='width:66pt'><?php if ($row['MASOLIENTHONG'] !=0) {
				echo "Có";
			}
			else echo "Không"; ?></td>
			<td class=xl725003 width=78 style='width:59pt'><?php if(!empty($row['TEP_DINHKEM'])){echo "Có";}else{echo "Không";} ?></td>
			<td class=xl745003 width=159 style='width:119pt'><?php 

			if($row["IS_KHONGXULY"] == 1)
				echo "Văn bản không xử lý";
			else{   
				$xl= WFEngine::GetProcessLogByObjectId((int)$row['ID_HSCV']);
				$rowsend = $xl[0]['EMPNCNAME'];
				for($j=0;$j<count($xl);$j++){
					if($j==10){
						$rowsend .="" ;
						$rowsend .="" ;
						$rowsend .= $xl[$j]['EMPNCNAME'];

					}else{
						if($rowsend != $xl[$j]['EMPNNNAME'])
						{
                                    //var_dump($xl[$j]);
                                    //exit;
							$rowsend .=" - " ;
							if($xl[$j]["ID_U_EXECUTE"]>0 && $xl[$j]["ID_U_EXECUTE"]!=$xl[$j]["ID_U_NC"]){
								$rowsend .= "(". $xl[$j]["EMPEXNAME"]." chuyển giúp)" ;
							}
							if($xl[$j]['NAME'] == "Chuyển xử lý")
								$rowsend .= "<font color=blue>";
							$rowsend .= $xl[$j]['EMPNNNAME'];  
							
							if($xl[$j]['NAME'] == "Chuyển xử lý" )
								$rowsend .= "</font>";
							$rowsend .= "[".$xl[$j]['NAME']." &ndash; ".date('d/m/Y', strtotime($xl[$j]['DATESEND']))."]";
						}
					}
				}
				$rowsend .="" ;
            //$rowsend .= $xl[$j-1]['EMPNNNAME'];
				
				?>
				<i> <?          
				echo $rowsend;
				?></i> 
				
				<?php
				
			}
			
			?></td>
			<td class=xl725003 width=134 style='width:101pt'><?php
			$idemp = VanbandireportModel::getIdempFromVBDI($row["ID_VBDI"]); 
			$iddep = VanbandireportModel::getIdDepFromIDemp($idemp);
			echo $iddep;
			?></td>
			<td class=xl725003 width=186 style='width:140pt'><?php  	
			echo UsersModel::getEmloyeeNameByIdUser($row["NGUOISOAN"]);
			
                        //echo VanbandireportModel::getDonViNoiBoFromVbandi($row["ID_VBDI"]);
			?></td>
			<td class=xl725003 width=154 style='width:116pt'><?php
			$nhh = VanbandireportModel::getNhhfromIdHscv($row['ID_HSCV']); 
			if ( $nhh != NULL && $nhh != '' ) {
				$minusTime = strtotime($row['NGAYBANHANH']) - strtotime($row['NGAYHETHAN']);
				if ( $minusTime > 0 ) {
					echo 'Trễ hạn';
				}
				if ( $minusTime == 0 ) {
					echo 'Đúng hạn';
				}
				if ( $minusTime < 0 ) {
					echo 'Sớm hạn';
				}
			}
			

			?></td>
			<td class=xl725003 width=186 style='width:140pt'><?php echo LoaiVanBanModel::getArrNameSVBById($row["ID_SVB"]) ?></td>
			<td class=xl725003 width=143 style='width:107pt'><?=$row["GHICHU"]?></td>
		</tr>
		<?php $stt++;} ?>
		<![if supportMisalignedColumns]>
		<tr height=0 style='display:none'>
			<td width=47 style='width:35pt'></td>
			<td width=111 style='width:83pt'></td>
			<td width=128 style='width:96pt'></td>
			<td width=107 style='width:80pt'></td>
			<td width=123 style='width:92pt'></td>
			<td width=150 style='width:113pt'></td>
			<td width=88 style='width:66pt'></td>
			<td width=78 style='width:59pt'></td>
			<td width=159 style='width:119pt'></td>
			<td width=134 style='width:101pt'></td>
			<td width=186 style='width:140pt'></td>
			<td width=154 style='width:116pt'></td>
			<td width=186 style='width:140pt'></td>
			<td width=143 style='width:107pt'></td>
		</tr>
		<![endif]>
	</table>

</div>


<!----------------------------->
<!--END OF OUTPUT FROM EXCEL PUBLISH AS WEB PAGE WIZARD-->
<!----------------------------->
</body>

</html>
