<?php require_once 'qtht/models/LoaiVanBanModel.php';?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html>
<head>
  <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />

  <style>
  td{
    border-color: black;
  }
  th{
    border-color: black;
  }
</style>

</head>
<body style="background-color:transparent">
  <table  width=100% >
    <tr >
      <td align=center ><?= mb_strtoupper($this->config->sys_info->unit,"utf-8") ?></td>

      <td align=center>CỘNG HÒA XÃ HỘI CHỦ
      NGHĨA VIỆT NAM</td>
    </tr>
    <tr >
      <td align=center ><b><?=mb_strtoupper($this->config->sys_info->company,"utf-8") ?></b></td>
      <td align=center >Ðộc lập - Tự do - Hạnh phúc</td>
    </tr>
    <tr >

     
      <td ></td>
      <td align=right><?=$this->config->sys_info->city?>, ngày <?=date("d")?> tháng <?=date("m")?> năm <?=date("Y")?></td>
    </tr>

    
  </table>
  <p align=center><b>BÁO CÁO VĂN BẢN ĐI</b> </br>
    <?php 
    if(count($this->id_lvbs) > 0) { 
      $lvb = htmlspecialchars(LoaiVanBanModel::getArrNameById($this->id_lvbs));
      ?>
      Loại Văn Bản: <?= $this->id_lvbs > 0 ? $lvb : 'Tất cả các loại';?><br />
    <?php } ?>

    <?php echo $this->thu;?> năm <?=QLVBDHCommon::getYear()?></p>

    <table border="1" style="border: 1px solid black; border-collapse: collapse;">
     <thead>
      <tr>
        <th nowrap rowspan="2" >STT</th>
        <th nowrap rowspan="2" >Ký hiệu VB</th>
        <th nowrap rowspan="2" >Trích Yếu VB</th>
        <th nowrap rowspan="2" >Cơ Quan Ban Hành</th>
        <th nowrap rowspan="2" >Ngày Ban Hành</th>
        <th rowspan="2">Thông Tin Văn Bản Đến</th>
        <th rowspan="2">Gửi Liên Thông</th>
        <th rowspan="2">Có File Đính Kèm </th>
        <th nowrap rowspan="2" >Dòng Luân Chuyển</th>
        <th nowrap rowspan="2" >Phòng Xử lý</th>
        <th nowrap rowspan="2" >Người Soạn VB</th>
        <th nowrap rowspan="2" >Trạng Thái</th>
        <th nowrap rowspan="2" >Số Văn Bản</th>
        <th nowrap rowspan="2" >Ghi chú</th>
      </tr>
    </thead>
    <tbody>
      <?php require_once 'qtht/models/LoaiVanBanModel.php';
      require_once 'qtht/models/CoquanModel.php'; 
      require_once 'qtht/models/DepartmentsModel.php';
      require_once 'qtht/models/UsersModel.php';
      require_once 'report/models/BaocaovanbandireportModel.php';
      ?>
      <?php $nguoixuly ; $phongban; $stt=1; 
      $num = count($this->data); 
      foreach($this->data as $row){ 
       ?>
       <tr>
        <td align="center" ><?=$stt ?></td>
        <td><?php echo $row["SOKYHIEU"]?></td>
        <td width="5%" align="center" ><?php echo $row['TRICHYEU'] ?></td>
        <td width="5%" align="center" ><?php echo LoaiVanBanModel::getCQNameById($row["ID_CQ"])?></td>
        <td width="5%"  align="center" ><?php echo $row["NGAYBANHANH"] ?></td>
        <td width="10%"  align="center" ><?php echo BaocaovanbandireportModel::getIdHscvVBDFromIDHscvVBDi($row["ID_HSCV"]) ?></td>
        <td  width="5%" align="center"  ><?php if ($row['MASOLIENTHONG'] !=0) {
          echo "Có";
        }
        else echo "Không"; ?></td>
        <td width="5%" align="center" ><?php if(!empty($row['TEP_DINHKEM'])){echo "Có";}else{echo "Không";} ?></td>
        <?php  {?>
          <td valign=top>
            <i><?php 

            if($row["IS_KHONGXULY"] == 1)
              echo "Văn bản không xử lý";
            else{   
              $xl= WFEngine::GetProcessLogByObjectId((int)$row['ID_HSCV']);
              $rowsend = $xl[0]['EMPNCNAME'];
              for($j=0;$j<count($xl);$j++){
                if($j==10){
                  $rowsend .="<br/>" ;
                  $rowsend .=" <br> " ;
                  $rowsend .= $xl[$j]['EMPNCNAME'];

                }else{
                  if($rowsend != $xl[$j]['EMPNNNAME'])
                  {
                                    //var_dump($xl[$j]);
                                    //exit;
                    $rowsend .=" <br> " ;
                    if($xl[$j]["ID_U_EXECUTE"]>0 && $xl[$j]["ID_U_EXECUTE"]!=$xl[$j]["ID_U_NC"]){
                      $rowsend .= "(". $xl[$j]["EMPEXNAME"]." chuyển giúp) <br>" ;
                    }
                    if($xl[$j]['NAME'] == "Chuyển xử lý")
                      $rowsend .= "<font color=blue>";
                    $rowsend .= $xl[$j]['EMPNNNAME'];  
                    
                    if($xl[$j]['NAME'] == "Chuyển xử lý" )
                      $rowsend .= "</font>";
                    $rowsend .= "[".$xl[$j]['NAME']." &ndash; ".date('d/m/Y', strtotime($xl[$j]['DATESEND']))."]";
                  }
                }
              }
              $rowsend .=" <br> " ;
            //$rowsend .= $xl[$j-1]['EMPNNNAME'];
              
              ?>
              <i> <?          
              echo $rowsend;
              ?></i> 
              
              <?php
              
            }
            
            ?>
            
          </i></td>
        <?php } ?>
        <?php {?>
          <td align="center" ><?php
          $idemp = BaocaovanbandireportModel::getIdempFromVBDI($row["ID_VBDI"]); 
          $iddep = BaocaovanbandireportModel::getIdDepFromIDemp($idemp);
          echo $iddep;
          ?>
          
        </td>
      <?php }?>
      <?php {?>
        <td  align="center" ><?php    
        echo UsersModel::getEmloyeeNameByIdUser($row["NGUOISOAN"]);
        
                        //echo BaocaovanbandireportModel::getDonViNoiBoFromVbandi($row["ID_VBDI"]);
        ?> </td>
      <?php }?>
      <?php {?>
        <td  align="center" p ><?php
        $nhh = BaocaovanbandireportModel::getNhhfromIdHscv($row['ID_HSCV']); 
        if ( $nhh != NULL && $nhh != '' ) {
          $minusTime = strtotime($row['NGAYBANHANH']) - strtotime($row['NGAYHETHAN']);
          if ( $minusTime > 0 ) {
            echo 'Trễ hạn';
          }
          if ( $minusTime == 0 ) {
            echo 'Đúng hạn';
          }
          if ( $minusTime < 0 ) {
            echo 'Sớm hạn';
          }
        }
        

        ?></td>
      <?php }?>
      <td   align="center"   ><?php echo LoaiVanBanModel::getArrNameSVBById($row["ID_SVB"]) ?></td>
      <td   valign=top   ><?php echo $row["GHICHU"] ?></td>
    </tr>
    

    <?php   

    $stt++ ; } ?>
  </tbody>

</table>
</body>
<script>print();</script>
</html>
