<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html>
<head>
<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
<script type="text/javascript" src="/js/jquery-1.3.2.js"></script>
<script type="text/javascript" src="/js/common.js"></script>
<script src="/js/validate.js" type="text/javascript"></script>
<script src="/js/validate.js" type="text/javascript"></script>
<script type="text/javascript" src="/js/Json/Base64.js"></script>
<script type="text/javascript" src="/js/Json/json2.js"></script>
<script type="text/javascript" src="/js/Json/json_parse.js"></script>
<script type="text/javascript" src="/js/Json/json_parse_state.js"></script>
<script type="text/javascript" src="/js/Ajax/AjaxEngine.js"></script>
<script type="text/javascript" src="/js/dlg_confirm.js"></script>
<script type="text/javascript" src="/js/calendar.js"></script>
<script type="text/javascript" src="/js/autocomplete.js"></script>

<link rel="stylesheet" type="text/css" href="/styles/general.css" />
<?php global $auth; ?>
<style>
	
</style>


</head>
<body style="background-color:transparent">
<script>
<?php if($this->canBanhanh==0){
	echo "
	alert('Công việc chưa có dự thảo nào nên không thể chuyển nhiều bước được.');
	window.parent.document.getElementById('groupcontent".$this->ID_HSCV."').style.display='none';
	window.parent.SwapDiv(".$this->ID_HSCV.",'/hscv/VanBanDuThao/index/year/".QLVBDHCommon::getYear()."/iddivParent/groupcontent".$this->ID_HSCV."/idHSCV/".$this->ID_HSCV."',5);
	";
} 
?>
</script>
<?=QLVBDHCommon::useDlgConfirm()?>
<?
$lastlog = WFEngine::GetCurrentTransitionInfoByIdHscv($this->ID_HSCV);
$action = WFEngine::GetNextTransitions($lastlog['ID_PI'],$this->user->ID_U);
//echo '<pre>';
//print_r($action);
?>
<form name="frm" method=post action="/hscv/chuyenxuly/savechuyennhieubuoc">

<fieldset>
<legend style="color:#0066CC;">
	Chuyển nhiều bước
</legend>
</fieldset>
<div id="nhieubuoc">
<div id="atAutoComplete" style="position:absolute;display:none;z-index:99;"></div>
        <table class=admintable>
	<tr>
		<td nowrap>Hành động</td>
		<td nowrap>
			<select  name="hanhdong[]" onchange="changehd(this,1)">
					<option value=0>--Không thực hiện--</option>
					<?php
						foreach($action as $actionitem){							
							echo "<option value=".$actionitem['ID_T']."_".$actionitem['ID_A_END']."_".$actionitem['ISLAST'].">".$actionitem['NAME']."</option>";			
						}
						
					?>
			</select>
		</td>
	</tr>
	<tr>
		<td nowrap>Người nhận</td>
		<td nowrap>
<!--			<select  name="nguoinhan[]"  onchange="changenn(this)">
				
			</select>-->
                    <div class="nguoinhandiv"></div>
                    <input autocomplete="off" onclick="cancelEvent(event)" class="autocombobox" value="" type="text" style="width:200px" name="tempnguoinhan1" id="tempnguoinhan1" onkeydown="at_KeyDown(event)" onkeyup="at_Display(event)" onfocus="at_Load('tempnguoinhan1','nguoinhan1',DATA_nguoinhan1,true,'changenn(this,1);');" >
                    <input type="hidden" style="width:200px" name="nguoinhan[]" onchange="" id="nguoinhan1" class="realnguoinhan" value="">
		</td>
	</tr>
	<tr>
		<td nowrap>Nội dung trình</td>
		<td nowrap>
			<textarea name="noidungtrinh[]" cols=100 rows=3></textarea>
		</td>
	</tr>
	<tr>
		<td nowrap>Ngày chuyển</td>
		<td nowrap>
			<?=QLVBDHCommon::calendarFull(date('d/m/Y'),"NGAYCHUYEN[]","") ?>
		</td>
	</tr>
	<tr>
		
	</tr>
	<tr>
		<td nowrap>Lý do trễ</td>
		<td nowrap>
			<textarea name="lydotre[]" cols=100 rows=2></textarea>
		</td>
	</tr>
</table>
</div>

<script>
var idForm = 1;    
function changehd(event,id){	
	$(event).parents('.admintable').nextAll().remove();
	var str = event.value;	
	var array = str.split("_");
	var ID_T = array[0];
	//alert(ID_T);
	var ID_A = array[1];
	if (ID_T!='0' || ID_T != 0){
	$.post("/hscv/chuyenxuly/ajaxchuyennhieubuocuser", {ID_T: ID_T,ID_A: ID_A,ID_NEXT: id},
   function(data) {
   //alert("Data Loaded: " + data);
	var array_data = data.split("__");
	var html_data=array_data[0];
	var html_process=array_data[1];
	 $(event).parent().parent().next().children().children('.nguoinhandiv:last').html(html_data);
	 $(event).parent().parent().next().next().next().next().html(html_process);
   });
		/*$('#nhieubuoc').append(function(){
	});*/
	}else{
		alert("Bạn hãy chọn hành động!");
	}
	
}
//function setnguoinhan(event) {
//    var html_data = event.value;
//    $(event).next().next().html(html_data);
//}

function changenn(event,id){
//        alert(event);
	$(event).parents('.admintable').nextAll().remove();
//	var str = $(event).parent().parent().prev().children().children().val();	
        var str = $('.nguoinhandiv:last').parent().parent().prev().children().children().val();
//        console.log(str);
	var array = str.split("_");
	var ID_T = array[0];
	var ID_A = array[1];
	var ISLAST = array[2];
	//alert(ID_A);
	var user_id = $(".nguoinhandiv:last").next().next().val();
//        console.log(user_id);
	if (ID_A!='0' || ID_A != 0){
	$.post("/hscv/chuyenxuly/ajaxchuyennhieubuoc", { user_id: user_id, ID_T: ID_T,ID_A: ID_A,ISLAST: ISLAST,ID_NEXT : id},
   function(data) {
     //alert("Data Loaded: " + data);
	 $('#nhieubuoc').append(data);
   });
        idForm ++;
		/*$('#nhieubuoc').append(function(){
	});*/
	}else{
		alert("Bạn hãy chọn hành động!");
	}
}
</script>

<input type=button name=SEND value=" Chuyển " onclick="SaveButtonClick(this);" class="butphe">
<input type=hidden name=id value="<?=$this->ID_HSCV?>">
<p id=lasttext1></p>
</form>
</body>
</html>
<script>
function SaveButtonClick(obj){			
			document.frm.submit();	
}
function resize(){
	try{
	var iframeElement = parent.document.getElementById('iframebutphe<?=$this->ID_HSCV?>');
	iframeElement.style.height = "" + document.getElementById("lasttext1").offsetTop + "px";
	iframeElement.width = "100%";
	setTimeout("resize()",1000);
	}catch(ex){
	}
}

function SwapDiv(id,url){
			document.getElementById("groupcontent"+id).style.display="";
			document.getElementById("groupcontent"+id).innerHTML="<img src='/images/loading.gif' width='16' height='16' border='0'></img<img src='/images/loading.gif' width='16' height='16' border='0'></img><img src='/images/loading.gif' width='16' height='16' border='0'></img><img src='/images/loading.gif' width='16' height='16' border='0'></img>";
			loadDivFromUrl("groupcontent"+id,url,1);
}

setTimeout("resize()",10);



</script>

