<?php require_once 'qtht/models/LoaiVanBanModel.php';?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html>
<head>
<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />

<style>
td{
	border-color: black;
}
th{
	border-color: black;
}
</style>

</head>
<body style="background-color:transparent">
<table  width=100% >
<tr >
  <td align=center ><?= mb_strtoupper($this->config->sys_info->unit,"utf-8") ?></td>

  <td align=center>CỘNG HÒA XÃ HỘI CHỦ
  NGHĨA VIỆT NAM</td>
 </tr>
 <tr >
  <td align=center ><b><?=mb_strtoupper($this->config->sys_info->company,"utf-8") ?></b></td>
  <td align=center >Ðộc lập - Tự do - Hạnh phúc</td>
 </tr>
 <tr >

 
  <td ></td>
  <td align=right><?=$this->config->sys_info->city?>, ngày <?=date("d")?> tháng <?=date("m")?> năm <?=date("Y")?></td>
 </tr>

 
</table>
<p align=center><b>BÁO CÁO CÔNG VIỆC </b> </br>
<?php 
	if(count($this->id_lvbs) > 0) { 
	$lvb = htmlspecialchars(LoaiVanBanModel::getArrNameById($this->id_lvbs));
?>
Loại Văn Bản: <?= $this->id_lvbs > 0 ? $lvb : 'Tất cả các loại';?><br />
<?php } ?>

<?php echo $this->thu;?> năm <?=QLVBDHCommon::getYear()?></p>

<table border="1" style="border: 1px solid black; border-collapse: collapse;">
 <thead>
 	<tr>
	   <th nowrap rowspan=2>Stt</th> 
<!-- 		<th nowrap rowspan=2>Số đến</th>
		<th nowrap rowspan=2>Ngày đến</th>-->
 		<th  rowspan=2>Cơ quan ban hành</th>
 		<th nowrap colspan=2 style="text-align:center">Văn bản đến</th>
 		<th  rowspan=2 >Trích yếu nội dung</th>
		<th  rowspan=2>Người xử lý</th>
		<th  colspan=2>Công việc</th>
 		<th  rowspan=2 >Kết quả</th>
 	</tr>
 	<tr>
 		<th nowrap>Số</th>
 		<th nowrap>Ngày</th>
                <th nowrap>Tên công việc</th>
                <th nowrap>Trạng Thái</th>
 		
 	</tr>
 </thead>
<tbody>
<?php require_once 'qtht/models/LoaiVanBanModel.php';
require_once 'qtht/models/CoquanModel.php'; 
require_once 'qtht/models/DepartmentsModel.php';
require_once 'qtht/models/UsersModel.php';
require_once 'vbden/models/vbdenModel.php';
require_once "giaoviec/models/giaoviecservice.php";
?>
<?php $nguoixuly ; $phongban; $stt=1; 
$num = count($this->data);
$configlienthong = new Zend_Config_Ini('../application/config.ini', 'general');
$madonvi = $configlienthong->service->lienthong->username;
$password = $configlienthong->service->lienthong->password;
$giaoviecservice = new GiaoViecService();
$token = $giaoviecservice->login($madonvi,md5($password),"");
foreach($this->data as $row){ 
        $ten= VanbandenreportModel::getNguoiXuly();
 ?>
	
	<tr>
        <td nowrap valign=top ><?=$stt?></td> 
<!-- 	<td nowrap valign=top ><-?=$row["SODEN"]?></td>
 	<td nowrap valign=top ><-?php echo QLVBDHCommon::MysqlDateToVnDate($row["NGAYDEN"]) ?></td>-->
	<td  width="20%" valign=top ><?=$row["COQUANBANHANH_TEXT"]?> <?php //echo CoquanModel::getNameById($row["ID_CQ"]) ?></td>
 	<td nowrap  valign=top ><?php echo $row["SOKYHIEU"] ?></td>
 	<td nowrap valign=top ><?php echo QLVBDHCommon::MysqlDateToVnDate($row["NGAYBANHANH"]) ?></td>
	<td  valign=top width="20%" ><?php echo $row["TENLOAI"] ?> - <?php echo $row["TRICHYEU"] ?></td>
 	<td width="20%">
 	<i><?php 
 	if($row["IS_KHONGXULY"] == 1)
 		echo "Văn bản không xử lý";
 	else{ 	     
	      $arr_u_xl = explode(",",$row["NAME_U"] );			 
		  foreach($arr_u_xl as $id_user_xl){
		    if((int)$id_user_xl){
		    echo $ten[(int)$id_user_xl]."<br/>"; 
			  }
		  }
		 $arr_u_ph = explode(",",$row["NAME_PH"] );			 
		  foreach($arr_u_ph as $id_user_ph){
		    if((int)$id_user_xl){
		    echo $ten[(int)$id_user_ph]."<br/>"; 
			}
		  }
		 $arr_u_db = explode(",",$row["NAME_DB"] );			 
		  foreach($arr_u_db as $id_user_db){
		  if((int)$id_user_xl){
		    echo $ten[(int)$id_user_db]."<br/>"; 
			}
		  }
	} 
		 ?>
 		
 	</i></td>
        <td  valign=top width="30%" >
            <?php  
            $hscv = vbdenModel::GetAllHSCV($row['ID_VBD']);
            foreach($hscv as $item)
            {
                if($item['MACONGVIEC']!=NULL)
                {    
                $reCongViec = $giaoviecservice->SelectCongViecByMacongviec(
                        $token
                        ,$item['MACONGVIEC']
                );
                $this->congviec = json_decode($reCongViec);
                    if($this->congviec->data[0]->TENCONGVIEC != ''){
                        echo $this->congviec->data[0]->TENCONGVIEC.' - '.QLVBDHCommon::MysqlDateToVnDate($this->congviec->data[0]->NGAYDUKIENHOANTHANH);
                        if($this->congviec->data[0]->TRANGTHAI != 3){
                            $ngayhoanthanh = explode(' ',$this->congviec->data[0]->NGAYDUKIENHOANTHANH);
                            echo QLVBDHCommon::getTreHanNgay($ngayhoanthanh[0]).'</br>';
                        }
                    }
                }
            }
            ?>
        </td>
        <td  valign=top width="30%" >
            <?php  
            $hscv = vbdenModel::GetAllHSCV($row['ID_VBD']);
            foreach($hscv as $item)
            {
                if($item['MACONGVIEC']!=NULL)
                {    
                $reCongViec = $giaoviecservice->SelectCongViecByMacongviec(
                        $token
                        ,$item['MACONGVIEC']
                );
                $this->congviec = json_decode($reCongViec);
                switch ($this->congviec->data[0]->TRANGTHAI) {
                            case 1:
                                echo "Đang xử lý</br>";
                                break;
                            case 2:
                                echo "Từ chối</br>";
                                break;
                            case 3:
                                echo "Đã xử lý</br>";
                                break;
                            case 4:
                                echo "Chưa hoàn thành</br>";
                                break;
                            default:
                                echo "Chưa xử lý</br>";
                        }
                }
            }
            ?>
        </td>
	<td valign=top width="20%">
	<?php 
	if($row["ID_HSCV"] != ""){
		//var_dump($row);
		if($row["IS_CHOXULY"]==1){
			echo "Lưu chờ xử lý";
		}else{
			$arr_file_maso = explode(",",$row["FILE_MASO"]);	
			 foreach($arr_file_maso as $arr_file_maso_item){
			 
				if($arr_file_maso_item){
					$arr_maso = explode('~', $arr_file_maso_item);
					if($arr_maso[0] != "")
					{
						echo "<a href='/hscv/File/download?year=".$row['NAM']."&maso=".$arr_maso[0]."'>".$arr_maso[1]." - (".$arr_maso[2].")<br/>";	
					} else {
						echo $arr_maso[1]."<br/>";	
					}
				} else {
					echo $row["KQ_DEXUAT"];
				}	
			}				
		}
		}
	?>
	</td>
	</tr> 
	

<?php 
  $stt++ ; } ?>
 </tbody>

</table>
</body>
<script>print();</script>
</html>
