<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html>
<head>
<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
</head>
<style>

 p.MsoNormal, li.MsoNormal, div.MsoNormal
	{mso-style-unhide:no;
	mso-style-qformat:yes;
	mso-style-parent:"";
	margin-top:0in;
	margin-right:0in;
	margin-bottom:10.0pt;
	margin-left:0in;
	line-height:115%;
	mso-pagination:widow-orphan;
	
	}



</style>
<body>
<FONT  style="font-size: 12pt;">
<table>
	<tr>
		<td nowrap="nowrap" align="center" style="line-height: 16px"><b><?=mb_strtoupper( $this->config->sys_info->company,"utf-8")?></b></td>
		<td width="100%" style="line-height: 16px"></td>
		<td nowrap="nowrap" align="center" style="line-height: 16px"><b>CỘNG HÒA XÃ HỘI CHỦ  NGHĨA VIỆT NAM</b></td>
	</tr>
	<tr>
		<td nowrap="nowrap" align="center" style="line-height: 16px"><b>Tổ Tiếp nhận Và Trả HS</b></td>
		<td width="100%" style="line-height: 16px"></td>
		<td nowrap="nowrap" align="center" style="line-height: 16px"><b>Độc lập – Tự do – Hạnh phúc</b></td>
	</tr>
	<tr>
		<td nowrap="nowrap" align="center" style="line-height: 16px"><b>---------oOo---------</b></td>
		<td width="100%" style="line-height: 16px"></td>
		<td nowrap="nowrap" align="center" style="line-height: 16px"><b>---------oOo---------</b></td>
	</tr>
	
	<tr>
		<td nowrap="nowrap" align="center" style="line-height: 16px">
		<table>
			<tr>
				<td align="right" >Điện thoại:</td>
				<td><?=$this->config->sys_info->phone?></td>
			</tr>	
			<tr>
				<td align="right">Số:</td>
				<td><?=$this->data->SOKYHIEU?></td>
			</tr>	
		</table>
	
		
		</td>
		<td width="100%" style="line-height: 16px"></td>
		<td nowrap="nowrap" align="right" style="line-height: 16px"></td>
	</tr>
</table>
<p align="center"><font style="font-size: 12pt;"><b>BIÊN NHẬN HỒ SƠ</b></font></p>

	
		<p>Nhận của đơn vị:&nbsp;<b><?=$this->data->TENTOCHUCCANHAN?></b>.&nbsp;</p>

	
		<p>Loại hồ sơ:&nbsp;<?=$this->tenloai?></p>
	<table width="100%"  cellpadding="0" cellspacing="0">
		<?php 
	$arr_custom_fields = motcua_hosoModel::CustomfieldsInBN($this->data->ID_LOAIHOSO);
	
	$dem = count($arr_custom_fields);
	if($dem > 0){
		for($i=0;$i<$dem;$i++){
?>
		<tr>
			<td valign="top" nowrap><?=$arr_custom_fields[$i]["NAME_DISPLAY"]?>:&nbsp;</td>
			<td valign="top" width=50%>
<?php 
			$col_value = "";
			eval('$col_value=$this->data->'.$arr_custom_fields[$i]["NAME_COLUMN"].";");
			if($arr_custom_fields[$i]["TYPE"] == "DATE"){
				echo "".implode("/",array_reverse(explode("-",$col_value)))."";
			}else{
				echo "".$col_value."";
			}
?>
			</td>
<?php
			$i++;
?>
			<td valign="top" nowrap><?=$arr_custom_fields[$i]["NAME_DISPLAY"]?>:&nbsp;</td>
			<td valign="top" width=50%>
<?php 
			$col_value = "";
			eval('$col_value=$this->data->'.$arr_custom_fields[$i]["NAME_COLUMN"].";");
			if($arr_custom_fields[$i]["TYPE"] == "DATE"){
				echo "".implode("/",array_reverse(explode("-",$col_value)))."";
			}else{
				echo "".$col_value."";
			}
?>
			</td>
		</tr>
<?php
		}
	}
?>		
		</table>

		<p>Nội dung:&nbsp; <?=$this->data->TRICHYEU?></p>		
	


<p>Hồ sơ gồm có:</p>
<font font-size="10pt">
<?php
if(count($this->nhangom)>0){
	$st=0;
	foreach($this->nhangom as $itemnhangom){
	
?>
	<p class=MsoNormal style='margin-bottom:0in;margin-bottom:.0001pt;line-height:
normal'>&nbsp;&nbsp;&nbsp;&nbsp;<?=$st+1?>.<?=$itemnhangom->TEN_THUTUC?></p>
	
<?php
	
	$st++;
}}
?>
<font>

<p>Nhận lúc :  <?=(($this->data->NHAN_LUC!="")?$this->data->NHAN_LUC ." giờ":"")?> ngày <?=date("d",strtotime($this->data->NGAYNHAN))?> tháng <?=date("m",strtotime($this->data->NGAYNHAN))?> năm <?=date("Y",strtotime($this->data->NGAYNHAN))?></p>

<p>Thời gian nhận kết quả: <?=(($this->data->NHANLAI_LUC!="")?$this->data->NHANLAI_LUC ." giờ":"")?> ngày <?=date("d",strtotime($this->data->NHANLAI_NGAY))?> tháng <?=date("m",strtotime($this->data->NHANLAI_NGAY))?> năm <?=date("Y",strtotime($this->data->NHANLAI_NGAY))?></p>



<table width="100%">
	<tr>
		<td nowrap="nowrap" width="33%" align="center"></td>
		
		<td nowrap="nowrap" width="33%" align="center"></td>
		<td nowrap="nowrap" width="33%" align="center"><i><?=$this->config->sys_info->city?>, ngày <?=date("d")?> tháng <?=date("m")?> năm <?=date("Y")?></i></td>
	</tr>
	<tr>
		<td nowrap="nowrap" width="33%" align="center"><b>Người nộp</b></td>
		
		<td nowrap="nowrap" width="33%" align="center"></td>
		<td nowrap="nowrap" width="33%" align="center"><b>Người tiếp nhận</b></td>
		
	</tr>
	<tr>
		<td nowrap="nowrap" width="33%" align="center">(Ký và ghi rõ họ tên)</td>
		<td nowrap="nowrap" width="33%" align="center"></td>
		<td nowrap="nowrap" width="33%" align="center">(Ký và ghi rõ họ tên)</td>
	</tr>
	<tr>
		<td colspan="3"><br><br><br></td>
	</tr>
	<tr>
		<td nowrap="nowrap" width="33%" align="center"></td>
		
		<td nowrap="nowrap" width="33%"></td>
		<td nowrap="nowrap" width="33%" align="center"><b><?=$this->user->FULLNAME?></b></td>
	</tr>

</table>




</body>
</html>
<script>
window.print();

</script>