<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html>
<head>
<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
<script type="text/javascript" src="/js/common.js"></script>
<script src="/js/validate.js" type="text/javascript"></script>
<script src="/js/validate.js" type="text/javascript"></script>
<link rel="stylesheet" type="text/css" href="/styles/general.css" />
<script type="text/javascript" src="/js/Ajax/AjaxEngine.js"></script>
</head>
<body style="background-color:transparent;margin:0;" onclick="parent.document.getElementById('id_tooltip').style.display='none';parent.document.getElementById('id_tooltip_group').style.display='none'">	
	<div class="markermenu">
		<?php
		$html = "";
		echo mail::ToTree($this->folder,$this->folder[0]['ID_EF_PARENT'],"mail_folder",$html,$this->idfolder);
		?>
	</div>

<p id=lasttext></p>

</body>

</html>
<script>
function folder_click(id_folder){
		window.parent.document.getElementById('right_frame').src="/mailclient/main/maillist/idfolder/"+id_folder;
		window.location = "/mailclient/main/folderlist/idfolder/"+id_folder;
		///alert(1);
}
var iframeElement = window.parent.document.getElementById('folder_frame');
iframeElement.style.height = ""+(document.getElementById("lasttext").offsetTop)+"px";
iframeElement.width = "100%"; 

</script>