
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="en-gb" lang="en-gb" dir="ltr" >
<head>
<meta http-equiv="content-type" content="text/html; charset=utf-8" />
<title>Thông báo</title>
<link rel="stylesheet" href="/styles/login/login.css" type="text/css" />
</head>
<body>

	<div id="content-box">
		<div class="padding">
        	<div class="login" id="element-box">
            	<div class="loginbanner"></div>
                <div class="login-content">		
                    	<p align="center" style="color:#00B2E3;padding-top:60px;font-size:18px;font-family:Arial, Helvetica, sans-serif">HỆ THỐNG ĐANG ĐƯỢC BẢO TRÌ, VUI LÒNG TRỞ LẠI SAU<p>
                </div>
                <div class="login-bottom">
                	<span>Phiên bản 4.0 - Phát triển bởi <a href="http://unitech.vn" target="_blank">Unitech</a></span>
                </div>
				            </div>
		</div>	
	</div>
</body>
</html>
