<?=QLVBDHCommon::useDlgConfirm()?>
<form name=frm method="post" action="/qtht/danhmucnguoidung">
	<table>
		<tr>
			<td align="left" width="100%">
				Lọc:
				<input type="text" name="search" id="search" value="<?php echo htmlspecialchars($this->search); ?>" class="text_area" onchange="document.frm.page.value=1;document.frm.submit();" />
                                <input type="button" style="background: url(/images/hscv-input-bg.png) repeat-x;" onclick="document.frm.submit();" value="Tìm" />
                                <input type="button" style="background: url(/images/hscv-input-bg.png) repeat-x;" onclick="document.frm.page.value=1;document.getElementById('search').value='';document.frm.submit();" value="Làm lại" />
                                <input type="button" style="background: url(/images/hscv-input-bg.png) repeat-x;" onclick="document.frm.action = '/qtht/danhmucnguoidung/dongbo';document.frm.submit();" value="Đồng bộ Ldap"/>
			</td>
			<td nowrap="nowrap" align="right">
			
			<select name=ID_DEP onchange="document.frm.submit();">
			<option value=0>** Tất cả phòng ban **</option>
			<option value=1>** Người dùng mới tạo **</option>
			<?=nguoidungModel::ToDepCombo($this->dep,$this->sel_dep) ?>
			</select>
			<script> document.frm.ID_DEP.value="<?=$this->sel_dep?>"</script>
			</td>
		</tr>
	</table>
	<table class="adminlist">
	<thead>
		<tr>
			<th nowrap style="text-align: center;">#</th>
			<th nowrap style="text-align: center;"><input type=checkbox name=DELALL onclick="SelectAll(this,'DEL')"></th>
			<th width="15%">Tài khoản</th>
			<th width="15%">Họ</th>
			<th width="15%">Tên</th>
			<th width="15%">Phòng ban</th>
			<th width="15%">Nhóm</th>
			<th width="15%">Thư điện tử-ĐT</th>
		</tr>
	</thead>
	<tfoot>
		<tr>
			<td colspan="8">
					<div class="pagination">
						<div class="limit">Hiển thị #
							<select name="limit" id="limit" class="inputbox" size="1" onchange="document.frm.page.value = 1;document.frm.submit();" style="width:60px;">
								<option value="5">5</option>
								<option value="10">10</option>
								<option value="15">15</option>
								<option value="20">20</option>
								<option value="25">25</option>
								<option value="30">30</option>
								<option value="50">50</option>
								<option value="100">100</option>
								<script>
									document.frm.limit.value='<?php echo $this->limit ?>';
								</script>
							</select>
						</div>
						<div style="float:right;"><?php echo $this->showPage;  ?></div>
					</div>
			</td>
		</tr>
	</tfoot>

	<tbody>
<?php
$stt=0;
$i=5;
foreach ($this->data as $row ){
	$stt++;
?>
		<tr class="row<?php echo $i; ?>">
			<td nowrap align="center"><?php echo $stt ?></td>
			<td nowrap align="center">
				<?php if($row['USERNAME']!="administrator"){?>
				<input type=checkbox name=DEL[] value='<?php echo $row['ID_U'] ?>'>
				<?php } ?>
			</td>
			<td nowrap>
				<a href="#" onclick = "ItemClick(<?php echo $row['ID_U'] ?>);">
				<?=$row['ISLEADER']==1?"<b>":""?><?php echo htmlspecialchars($row['USERNAME']) ?>
				</a>
			</td>
			<td  nowrap>
				<a href="#" onclick = "ItemClick(<?php echo $row['ID_U'] ?>);">
				<?php echo htmlspecialchars($row['FIRSTNAME']) ?>
				</a>
			</td>
			<td nowrap>
				<a href="#" onclick = "ItemClick(<?php echo $row['ID_U'] ?>);">
				<?php echo htmlspecialchars($row['LASTNAME']) ?>
				</a>
			</td>
			<td  nowrap>
				<a href="#" onclick = "ItemClick(<?php echo $row['ID_U'] ?>);">
				<?php echo htmlspecialchars($row['DEPNAME']) ?>
				</a>
			</td>
			<td  nowrap>
				<a href="#" onclick = "ItemClick(<?php echo $row['ID_U'] ?>);">
				<?php echo htmlspecialchars($row['GNAME']) ?>
				</a>
			</td>
			<td  nowrap>
				<a href="#" onclick = "ItemClick(<?php echo $row['ID_U'] ?>);">
				<?php echo htmlspecialchars($row['EMAIL']."--".$row['DIENTHOAI']) ?>
				</a>
			</td>
		</tr>
<?php
    $i = (-1+$i)*-1;
}
?>
	</tbody>
</table>
<input type="hidden" name="page" value="<?php echo $this->page; ?>">
</form>
<script>
function inClick(){
	document.frm.action = "/qtht/Indanhba/list";
	document.frm.submit();
}
function DeleteButtonClick(){
	var mess = true;
	mess = validateInput("selone_check","DEL[]","<?=ERR11012001?>");
	if(mess){
		var func_ok = "document.frm.action = '/qtht/danhmucnguoidung/Delete';document.frm.submit();";
		var func_cancel = "";
		displayConfirm("Bạn có muốn xóa người dùng không?","","",func_ok,func_cancel);
			
		/*if(confirm("<?=MSG11012001?>")){
			
		}*/
	}else{
		alert("<?=ERR11012001?>");
	}
}
function AddNewButtonClick(){
	document.frm.action = "/qtht/danhmucnguoidung/input";
	document.frm.submit();
}
function ItemClick(id){
	document.frm.action = "/qtht/danhmucnguoidung/input/id/"+id;
	document.frm.submit();
}
</script>
<script>
    var ftext = document.getElementById('search');
    ftext.focus();
</script>