<table width="50%">
    <tr>
        <td align="middle" colspan="2"><h2>Danh bạ người dùng</h2></td>
    </tr>
    <tr>
        <td>Tên người dùng </td>
        <td><?= $this->data['FIRSTNAME']?>  <?= $this->data['LASTNAME']?></td>
    </tr>
    <tr>
        <td>Mã người dùng </td>
        <td><?= $this->data['ID_U'] ?></td>
    </tr>
     <tr>
        <td>Mã phòng </td>
        <td><?= $this->data['ID_EMP'] ?></td>
    </tr>
    <tr>
        <td>Tên phòng </td>
        <td><?= $this->data['DEPNAME'] ?></td>
    </tr>
    <tr>
        <td>Số máy lẻ</td>
        <td><?= $this->data['PHONE_EXT'] ?></td>
    </tr>
     <tr>
        <td>Email </td>
        <td><?= $this->data['EMAIL'] ?></td>
    </tr>
    <tr>
        <td>Địa chỉ nhà </td>
        <td><?= $this->data['ADDRESS'] ?></td>
    </tr>
    <tr>
        <td>Số điện thoại </td>
        <td><?= $this->data['PHONE'] ?></td>
    </tr>
    
</table>
<script>print()</script>