<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html>
<head>
<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
<script type="text/javascript" src="/js/common.js"></script>
<script src="/js/validate.js" type="text/javascript"></script>
<script type="text/javascript" src="/js/calendar.js"></script>
<script type="text/javascript" src="/js/Ajax/AjaxEngine.js"></script>
<link rel="stylesheet" type="text/css" href="/styles/general.css" />

</head>
<body>
<form name="frm" action="/congviec/noidungyk/save" method="post">
<table>
<tr>
<td nowrap="nowrap" style="color:blue">Nội dung ý kiến
<font color="Red" size="3">*</font></td>
<td> 
<textarea name="CONTENT" cols="72" rows="2"> <?php echo htmlspecialchars($this->content);?></textarea> 
 <span class="box_erro_area" id="ERRCONTENT" > </span>
</td>
</table>

<input type="button" value="Lưu" onclick="SaveButtonClick()">
<input type=hidden name="ID_WORK" value="<?php echo $this->id_work?>">
<input type=hidden name="ID_REMARK" value="<?php echo $this->id ?>">
 
</form>
<p id=lasttext></p>
</body>
</html>

<script>

function resize(){
	var iframeElement = parent.document.getElementById('inputykien<?=$this->id_work?>');
	iframeElement.style.height = "300px";
	iframeElement.width = "100%";
}
resize();
function SaveButtonClick(){

	var err = true;
	   err= err & validateInput("req",document.frm.CONTENT,"Chưa nhập nội dung ý kiến");
	
		if(err==true)
		document.frm.submit();
}

</script>

