<link rel="stylesheet" type="text/css" href="/popupmini/popupmini.css" />
<script src="/jquery/jquery-1.10.2.js"></script>
<script type="text/javascript">
    var jq1102 = jQuery.noConflict(true);
</script>
<form name=frm method=post action='/giaoviec/index/index' onsubmit="document.frm.page.value = 1;document.frm.action = '/giaoviec/index/index';return true;">
<div>
    <table>
        <!--
        <tr>
            <td nowrap="nowrap">Đơn vị giao</td>
            <td nowrap="nowrap">
                <select name="CQLIENTHONG" id="CQLIENTHONG" class="inputbox" size="1" onchange="document.frm.submit();">

                    <?php
                        require_once "giaoviec/models/GiaoViecModel.php";
                        echo GiaoViecModel::WriteDonVi((int)$this->CQLIENTHONG, "-- Chọn tất cả  --");
                    ?>
                </select>

            </td>

        </tr>
        -->
        <tr>
            <td nowrap="nowrap">Số ký hiệu</td>
            <td nowrap="nowrap" >
                <input type=text class=inputbox name=SOKYHIEU value="<?= $this->SOKYHIEU ?>" size=20>
            </td>

        </tr>

        <tr>
            <td nowrap="nowrap" valign=top>Tên nhiệm vụ</td>
            <td nowrap="nowrap" colspan="3">
                <input type=text class=inputbox name=TENCONGVIEC value="<?= $this->TENCONGVIEC ?>" size=50>
            </td>
            <td width="100%"></td>
        </tr>

        <tr>
            <td nowrap="nowrap">Người thực hiện</td>
            <td nowrap="nowrap" >
                <input type=text class=inputbox name=NGUOITHUCHIEN value="<?= $this->NGUOITHUCHIEN ?>" size=20>
            </td>
            <td width="100%"></td>
        </tr>
        
        <tr>
            <td nowrap="nowrap"></td>
            <td nowrap="nowrap" colspan="3">
                <input type=hidden><input type=submit value="Tìm kiếm">
            </td>
            <td width="100%"></td>
        </tr>
        <tr></tr>
    </table>
</div>
<table class="adminlist">
    <thead>
         <tr>
			<th colspan="11">
				<div>
					<div class="limit" style="float:left;">Hiển thị #
						<select name="limit1"  style="width:60px;" id="limit1" class="inputbox" size="1" onchange="
							document.frm.page.value = 1;
							document.frm.limit2.value = document.frm.limit1.value;
							document.frm.action = '/giaoviec/index/index';
							document.frm.submit();
						">
							<option value="5" <?php if($this->limit==5){echo "selected";} ?>>5</option>
							<option value="10" <?php if($this->limit==10){echo "selected";} ?>>10</option>
							<option value="15" <?php if($this->limit==15){echo "selected";} ?>>15</option>
							<option value="20" <?php if($this->limit==20){echo "selected";} ?>>20</option>
							<option value="25" <?php if($this->limit==25){echo "selected";} ?>>25</option>
							<option value="30" <?php if($this->limit==30){echo "selected";} ?>>30</option>
							<option value="30" <?php if($this->limit==35){echo "selected";} ?>>35</option>
							<option value="30" <?php if($this->limit==40){echo "selected";} ?>>40</option>
							<option value="50" <?php if($this->limit==50){echo "selected";} ?>>50</option>
							<option value="100" <?php if($this->limit==100){echo "selected";} ?>>100</option>
						</select>
					</div>
					<div class="limit" style="float:right;"><?php echo $this->showPage; ?></div>
				</div>
			</th>
	</tr>
        <tr>
            <th colspan=9>
                <!-- <a id=trangthai0 href="/giaoviec/index/index/trangthai/0">Chưa tiếp nhận</a> |  -->
                <!-- <a id=trangthai1 href="/giaoviec/index/index/trangthai/1">Đã tiếp nhận</a> |  -->
                <a id=trangthai3 href="/giaoviec/index/index/trangthai/3">Đã hoàn thành</a> | 
                <!-- <a id=trangthai2 href="/giaoviec/index/index/trangthai/2">Từ chối</a> |  -->
                <a id=trangthai4 href="/giaoviec/index/index/trangthai/4">Chưa hoàn thành</a> | 
                <a id="trangthai-1" href="/giaoviec/index/index/trangthai/-1">Tất cả</a></th>
        </tr>
        <tr>
            <th nowrap>STT</th>
            <th nowrap>Văn bản</th>
            <th nowrap>Nhiệm vụ</th>
            <th nowrap>Trạng thái</th>
            <th nowrap>Người xử lý</th>
            <th nowrap>Hạn xử lý </th>
            <th nowrap>Kết quả</th>
            <th nowrap>Xác nhận kết quả</th> 
            <th nowrap>Chức năng</th>
        </tr>
    </thead>

    <tbody>

        <?php
        $stt = 1;
	    $i=0;
        foreach ($this->data as $item) {
            ?>
            <tr class="row<?=$i?><?php if ($item->XACNHANTRANGTHAI == 1) {echo ' dahoanthanh';} ?>"  row="<?=$i?>">
                <td nowrap align=right><?= $stt++ ?></td>
                <td><a href="/vbden/vbden/listall/SOKYHIEU/<?= base64_encode($item->SOKYHIEU) ?>/base64/1"><?php echo $item->SOKYHIEU?> - <?php echo date("d/m/Y", strtotime($item->NGAYBANHANH));?> - <?php echo $item->DONVIGIAO?></a></td>
                <td width=35% valign=top>
                    <strong><?= $item->TENCONGVIEC ?></strong><br>
                    
                    <div style="display:none" id="xuly_action_<?= $item->MACONGVIEC ?>">

                    </div>
                    <div class="groupcontent" id="groupcontent<?= $item->ID_CONGVIECDETAIL ?>" style="display:none;border: 1px solid #CCC"></div>
                </td>
                <td>
                    <?php 
                        if($item->TRANGTHAI == 0){ echo "Chưa tiếp nhận";}
                        if($item->TRANGTHAI == 1){ echo "Đã tiếp nhận và đang xử lý";}
                        if($item->TRANGTHAI == 2){ echo "Từ chối";}
                        if($item->TRANGTHAI == 3){ echo "Đã xử lý";}
                        if($item->TRANGTHAI == 4){ echo "Chưa hoàn thành";}
                    ?>
                </td>
                <td valign=top><?= $item->HOTENNGUOINHAN ?></td>
                <td nowrap  valign=top>
                    <?php 
                        echo date("d/m/Y", strtotime($item->NGAYDUKIENHOANTHANH));
                    ?>
                </td>

               <td align=center valign=top width=10%>
               <?php 
                    require_once 'giaoviec/models/GiaoViecModel.php';
                    $giaoviec = new GiaoViecModel();
                    $giaoviec->ShowFileAll($this->session,$item->ID_CONGVIECDETAIL,$item->ID_VBLIENTHONG_VAO);
                ?>
                </td>
                
                <td>
                    <?php 
                        if($item->XACNHANTRANGTHAI=='1') { echo 'Đã xác nhận hoàn thành';
                        }elseif($item->XACNHANTRANGTHAI=='2') { echo 'Đã xác nhận hoàn thành trễ hạn';
                        }elseif($item->XACNHANTRANGTHAI=='3') { echo 'Đã xác nhận chưa hoàn thành';
                        }else {echo '';}
                    ?>
                </td>

                <td valign=top width=7% >
                        <!-- <a href="javascript:void(0)" onclick="
                            if (jq1102(this).hasClass('selected')) {
                                popupMiniDeselect_cntt($(this));
                            } else {
                                loadDataPopupCapnhattrangthai_cntt('<?= $item->MACONGVIEC ?>', '<?= $item->IDDONVINHAN ?>', '<?= $item->TRANGTHAI ?>');
                                jq1102(this).addClass('selected');
                                jq1102(this).closest('tr').addClass('row2');
                                jq1102('.pop_capnhat_tt').popupMiniSlideFadeToggle();
                            }
                            return false;" class="capnhattrangthai" >Xác nhận kết quả<br></a> -->
                    <a href="/giaoviec/index/xemtiendo/id/<?= $item->ID_CONGVIECDETAIL ?>">Cập nhật tiến độ<br></a>
                    <a href="#" onclick="{SwapIframe(<?= $item->ID_CONGVIECDETAIL?>,'/giaoviec/index/giaonhiemvu/id/<?=$item->ID_CONGVIECDETAIL?>/tencongviec/<?=base64_encode($item->TENCONGVIEC)?>/sokyhieu/<?=base64_encode($item->SOKYHIEU)?>/macongviec/<?= $item->MACONGVIEC ?>');return false;
                     }">Giao nhiệm vụ<br></a>
                     <!-- <a href="/giaoviec/index/capnhattiendo/id/<?= $item->ID_CONGVIECDETAIL ?>">Cập nhật tiến độ<br></a> -->
                </td>
               
            </tr>
            <?php
             $i = (-1+$i)*-1;$i;
        }
        ?>

    </tbody>
    <tfoot>
		<tr>
			<th colspan="11">
				<div class="pagination">
					<div class="limit">Hiển thị #
						<select name="limit2" style="width:60px;" id="limit2" class="inputbox" size="1" onchange="
							document.frm.page.value = 1;
							document.frm.limit1.value = document.frm.limit2.value;
							document.frm.action = '/giaoviec/index/index';
							document.frm.submit();
						">
							<option value="5" <?php if($this->limit==5){echo "selected";} ?>>5</option>
							<option value="10" <?php if($this->limit==10){echo "selected";} ?>>10</option>
							<option value="15" <?php if($this->limit==15){echo "selected";} ?>>15</option>
							<option value="20" <?php if($this->limit==20){echo "selected";} ?>>20</option>
							<option value="25" <?php if($this->limit==25){echo "selected";} ?>>25</option>
							<option value="30" <?php if($this->limit==30){echo "selected";} ?>>30</option>
							<option value="30" <?php if($this->limit==35){echo "selected";} ?>>35</option>
							<option value="30" <?php if($this->limit==40){echo "selected";} ?>>40</option>
							<option value="50" <?php if($this->limit==50){echo "selected";} ?>>50</option>
							<option value="100" <?php if($this->limit==100){echo "selected";} ?>>100</option>
						</select>
					</div>
					<div style="float:right"><?php echo $this->showPage; ?></div>
				</div>
			</th>
		</tr>
	</tfoot>
</table>
<input type="hidden" name="page" value="<?php echo $this->page; ?>">

</form>    
<div class="tuchoipopup pop_tuchoi">
    <form method="post" name="tuchoiform" id="tuchoiform" enctype="multipart/form-data">
        <p>
        <h3> Lý do từ chối:</h3>
        <textarea name="lydo"  id="lydo"></textarea>
        <input type="hidden" name="macongviec" id="macongviec" value="">
        </p>        
        <p>
            </br>
            <button name="capnhat_submit" onclick="sendTuChoiNhiemVu()" id="capnhat_submit">Xác nhận</button> 
            <button  onclick="popupMiniDeselect_tuchoi(jq1102('a.tuchoi.selected'));return false;">Hủy bỏ</button>
        </p>
    </form>
</div>

<div class="capnhattrangthaipopup pop_capnhat_tt">
    <form method="post" name="capnhattrangthaiform" id="capnhattrangthaiform" enctype="multipart/form-data">
        <p>
        <h3> Cập nhật tiến độ:</h3>
        <select id="trangthaixacnhan" name="trangthaixacnhan"  style="width:190px;">
            <option value='0'>--Chọn Trạng Thái--</option>
            <option value="1">Hoàn thành</option>
            <!-- <option value="2">Hoàn thành trễ hạn</option> -->
            <option value="3">Chưa hoàn thành</option>
        </select>
        <h4> Mô tả tiến độ hiện tại:</h4>
        <textarea name="bosungchitiet" id="bosungchitiet" cols="60" rows="5"></textarea>
        <input type="hidden" name="macongviectt" id="macongviectt" value="">
        <input type="hidden" name="donvinhantt" id="donvinhantt" value="">
        </p>        
        <p>
            <font color="red" id="errorCNTT"></font>
            </br>
            <button name="capnhat_submit" onclick="sendCapNhatTrangThai()" id="capnhat_submit">Xác nhận</button> 
            <button  onclick="popupMiniDeselect_cntt(jq1102('a.capnhattrangthai.selected'));
                    return false;">Hủy bỏ</button>
        </p>
    </form>
</div>
<script>
    jq1102(document).ready(function () {
        jq1102("#trangthai<?= $this->trangthai ?>").css("color", "red");
    });
    var TrangThai = new Array("Chưa tiếp nhận", "Đã tiếp nhận", "Từ chối", "Đã hoàn thành");
    function NhiemvuXulyToancoquanClick() {
        document.location = '/giaoviec/index/indexall';
    }
    function tiepNhanGiaoViec(id) {
        if (confirm("Bạn có muốn tiếp nhận công việc này không?")) {
            jq1102.ajax({
                type: "POST",
                url: "/giaoviec/index/tiepnhan",
                data: "id=" + id,
                dataType: "json",
                success: function (data1) {
                    if (data1.error.code == 0) {
                        alert("Tiếp nhận thành công");
                        location.reload();
                    } else {
                        alert("Tiếp nhận lỗi: " + data1.error.message);
                    }
                },
                error: function (request, status, errorThrown) {

                }
            });
        }
    }

    function tuChoiGiaoViec(id) {
        if (confirm("Bạn có muốn từ chối công việc này không?")) {
            jq1102.ajax({
                type: "POST",
                url: "/giaoviec/index/tuchoi",
                data: "id=" + id,
                dataType: "json",
                success: function (data1) {
                    if (data1.error.code == 0) {
                        alert("Từ chối thành công");
                        location.reload();
                    } else {
                        alert("Từ chối lỗi: " + data1.error.message);
                    }
                },
                error: function (request, status, errorThrown) {

                }
            });
        }
    }

    function ShowXulyList(macongviec) {
        jq1102('#xuly_list_' + macongviec).toggle();
        jq1102("#xuly_list_" + macongviec + " tbody").remove();
        jq1102.ajax({
            type: "POST",
            url: "/giaoviec/index/congcong",
            data: "function=selectThamGiaXuLy&macongviec=" + macongviec,
            dataType: "json",
            success: function (data1) {
                for (var i = 0; i < data1.length; i++) {
                    var html = "";
                    html = "<tr><td>" + (i + 1) + "</td>";
                    html += "<td>" + data1[i].DONVINHAN + "</td>";
                    html += "<td>" + (data1[i].LADONVICHINH == 1 ? "Xử lý" : "Phối hợp") + "</td>";
                    html += "<td>" + data1[i].CHUYENVIENTHEODOI + "</td>";
                    var style='';
                    if(data1[i].HOTENNGUOINHAN==null){
                        data1[i].HOTENNGUOINHAN='-';
                        style='style="text-align:center;"'
                    }
                    html += "<td "+style+">" + data1[i].HOTENNGUOINHAN + "</td>";
                    html += "<td>" + TrangThai[data1[i].TRANGTHAI] + (data1[i].TRANGTHAI == 2 ? "<br><i>" + data1[i].LYDOTUCHOI + "</i>" : "") + "</td></tr>";

                    jq1102("#xuly_list_" + macongviec).append(html);
                }
            },
            error: function (request, status, errorThrown) {

            }
        });
    }
    jq1102.fn.popupMiniSlideFadeToggle = function (easing, callback) {
        return this.animate({opacity: 'toggle', height: 'toggle'}, 'fast', easing, callback);
    };
    function popupMiniDeselect_cntt(e) {
        jq1102('.pop_capnhat_tt').popupMiniSlideFadeToggle(function () {
            e.removeClass('selected');
            jq1102('#trangthaixacnhan').val('');
        });
    }
    function loadDataPopupCapnhattrangthai_cntt(macongviectt, donvinhantt, trangthaixacnhan) {
        jq1102('#macongviectt').val(macongviectt);
        jq1102('#donvinhantt').val(donvinhantt);
        if(trangthaixacnhan==3){
            jq1102("#trangthaixacnhan").val(1);
        }else{
            jq1102("#trangthaixacnhan").val(3);
        }
        
    }
    function popupMiniDeselect_tuchoi(e) {
        jq1102('.pop_tuchoi').popupMiniSlideFadeToggle(function () {
            e.closest('tr').removeClass('row2');
            e.removeClass('selected');
            jq1102('#macongviec').val('');
        });
    }
    function loadDataPopupTuchoi(macongviec, lydo) {
        jq1102('#macongviec').val(macongviec);
        jq1102("#lydo").val(lydo);
    }

    function sendTuChoiNhiemVu() {
        jq1102('#errorTUCHOI').html("");
        jq1102.ajax({
            url: '/giaoviec/index/tuchoi',
            data: {
                'macongviec': jq1102('#macongviec').val(),
                'lydo': jq1102('#lydo').val()
            },
            async: false,
            type: 'post',
            cache: false,
            success: function (data) {
                var jsonObj = jq1102.parseJSON(data);
                // if(jsonObj.status == 'true'){
                popupMiniDeselect_cntt(jq1102('a.pop_tuchoi.selected'));
                //jq1102(jq1102('a.pop_capnhat_nv.selected').closest('tr')).find('#nhiemvu_cn').html(jsonObj.tiendo);                   
                return false;
                //}else{
                // jq1102('#errorCNTT').html("Không thể cập nhật :(");
                //}
            }
        });

    }
    function sendCapNhatTrangThai() {
        jq1102('#errorCNTT').html("");
        jq1102.ajax({
            url: '/giaoviec/index/xacnhantrangthai',
            data: {
                'macongviectt': jq1102('#macongviectt').val(),
                'donvinhantt': jq1102('#donvinhantt').val(),
                'trangthaixacnhan': jq1102('#trangthaixacnhan').val(),
                'bosungchitiet': jq1102('#bosungchitiet').val()
            },
            async: false,
            type: 'post',
            cache: false,
            success: function (data) {

            }
        });
    }
    function SwapIframe( id, url ) { 
        for ( var i = 1; i < 11; i++ ) {
            if ( document.getElementById( "groupicon" + i + "_" + id ) ) {
                if ( document.getElementById( "groupicon" + i + "_" + id ).className == "groupiconopen" ) {
                    document.getElementById( "groupcontent" + id ).style.display = "none";
                    document.getElementById( "groupicon" + i + "_" + id ).className = "groupicon";
                    break;
                }
            }
        }
        if ( document.getElementById( 'groupcontent' + id ).style.display == '' ) {
            document.getElementById( 'groupcontent' + id ).style.display = 'none';
        } else {
            document.getElementById( 'groupcontent' + id ).innerHTML = '<iframe style="overflow-x:visible" height=300px width=100% id=iframebutphe' + id + ' allowTransparency=true BORDER=0 scrolling=yes FRAMEBORDER=no src="' + url + '"></iframe>';
            document.getElementById( 'groupcontent' + id ).style.display = '';
        }

    }
</script>