<link rel="stylesheet" type="text/css" href="/popupmini/popupmini.css" />
<script src="/jquery/jquery-1.10.2.js"></script>
<script type="text/javascript">
    var jq1102 = jQuery.noConflict(true);
</script>
<form name=frm method=post action='/giaoviec/index/list' onsubmit="document.frm.page.value = 1;document.frm.action = '/giaoviec/index/list';return true;">
<div style="width: 50%;float:left">
    <table>
        <div>
        <label><b>Ngày giao nhiệm vụ:</b></label>
        <?= QLVBDHCommon::calendarFull($this->fromdate, "fromdate", "fromdate") ?>
        >>
        <?= QLVBDHCommon::calendarFull($this->todate, "todate", "todate") ?>

    </div>
    <div class=clr></div>
    <div>
        <div>
            <?php
            $year = QLVBDHCommon::getYear();
            $d = strtotime($year . "-3-1");
            $d = $d - 86400;
            $str_cuoi2 = date('d/m', $d);
            ?>            
			<label><b>Tháng:</b></label>
            <input type="radio" name='sel_timedis' onclick="setvalueDateD('1/1/<?php echo $year ?>', '31/1/<?php echo $year ?>')">1

            <input type="radio" name='sel_timedis' onclick="setvalueDateD('1/2/<?php echo $year ?>', '<?php echo $str_cuoi2 ?>/<?php echo $year ?>')" >2
            <input type="radio" name='sel_timedis' onclick="setvalueDateD('1/3/<?php echo $year ?>', '31/3/<?php echo $year ?>')">3
            <input type="radio" name='sel_timedis'onclick="setvalueDateD('1/4/<?php echo $year ?>', '30/4/<?php echo $year ?>')" >4
            <input type="radio" name='sel_timedis'onclick="setvalueDateD('1/5/<?php echo $year ?>', '31/5/<?php echo $year ?>')">5
            <input type="radio" name='sel_timedis' onclick="setvalueDateD('1/6/<?php echo $year ?>', '30/6/<?php echo $year ?>')">6
            <input type="radio" name='sel_timedis'onclick="setvalueDateD('1/7/<?php echo $year ?>', '31/7/<?php echo $year ?>')" >7
            <input type="radio" name='sel_timedis'onclick="setvalueDateD('1/8/<?php echo $year ?>', '31/8/<?php echo $year ?>')" >8
            <input type="radio" name='sel_timedis'onclick="setvalueDateD('1/9/<?php echo $year ?>', '30/9/<?php echo $year ?>')">9
            <input type="radio" name='sel_timedis'onclick="setvalueDateD('1/10/<?php echo $year ?>', '31/10/<?php echo $year ?>')">10
            <input type="radio" name='sel_timedis'onclick="setvalueDateD('1/11/<?php echo $year ?>', '30/11/<?php echo $year ?>')">11
            <input type="radio" name='sel_timedis'onclick="setvalueDateD('1/12/<?php echo $year ?>', '31/12/<?php echo $year ?>')">12
        </div>

    </div>
    <div class="clr"></div>
    <div>
        <label><b>Đơn vị:</b></label>
		<select name='sel_donvi[]' id='sel_donvi' multiple style="width:400px" size=10>
		<option value="0">--Tất cả--</option>
		<?php
			foreach($this->dataDonVi as $itemDonVi){
		?>
			<option value="<?php echo $itemDonVi->OrganId?>"><?php echo htmlspecialchars($itemDonVi->OrganName)?></option>
		<?php
			}
		?>
		</select>
   </div> 
    <div class=clr></div>
    <div>
        <br/>
        <input type=submit value="Hiển thị">
    </div>    
    </table>
</div>

 
<div style="width: 50%;float:right;font-weight: bold;">
    <?php
        $nhiemvudagiaotrongthang = 0;
        $nhiemvuketduthangtruoc = 0;
        $nhiemvudagiaohoanthanh = 0;
        $nhiemvudangthuchien = 0;
        $nhiemvuchuathuchien = 0;
        foreach($this->dataReport as $key=>$value){
            $nhiemvudagiaotrongthang+= $value->CNTCONGVIEC;
            $nhiemvudagiaohoanthanh+= $value->CNTDAHOANTHANH;
            $nhiemvudangthuchien+= $value->CNTDANGTRIENKHAI;
            $nhiemvuchuathuchien+= $value->CNTCHUATHUCHIEN;
            $nhiemvuketduthangtruoc+= $value->CNTTHANGTRUOC;
        }
    ?>
    <table>
        <tr>
            <td style=" color: #0ca1e3;font-size: 14px"> TÌNH TRẠNG NHIỆM VỤ THÁNG <?= (int)$this->month  ?> </td>
        </tr>
        <tr>
            <td style="padding:5px;">Tổng số nhiệm vụ đã giao trong tháng: <font color="#3399ff"><?=$nhiemvudagiaotrongthang?></font></td>
        </tr>
        <tr>
            <td style="padding:5px;">Tổng số nhiệm vụ kết dư tháng trước: <font color="#3399ff"><?=$nhiemvuketduthangtruoc?> </font>tỷ lệ <?=(int)($nhiemvuketduthangtruoc/(int)$nhiemvudagiaotrongthang*100)?>%</td>
        </tr>
        <tr>
            <td style="padding:5px;">Tổng số số nhiệm vụ đã thực hiện: <font color="#3399ff"><?=$nhiemvudagiaohoanthanh?></font> đạt tỷ lệ <?=(int)($nhiemvudagiaohoanthanh/(int)$nhiemvudagiaotrongthang*100)?>%</td>
        </tr>
        <tr>
            <td style="padding:5px;">Tổng số số nhiệm vụ đang thực hiện: <font color="#3399ff"><?=$nhiemvudangthuchien?></font> đạt tỷ lệ <?=(int)($nhiemvudangthuchien/(int)$nhiemvudagiaotrongthang*100)?>%</td>
        </tr>
        <tr>
            <td style="padding:5px;">Tổng số nhiệm vụ chưa thực hiện: <font color="#3399ff"><?=$nhiemvuchuathuchien?></font> đạt tỷ lệ <?=(int)($nhiemvuchuathuchien/(int)$nhiemvudagiaotrongthang*100)?>%</td>
        </tr>
       
    </table>
</div>
    <table class=adminlist>
        <tr>
            <td align=center style="font-weight:bold;border: none; font-size: 15px;">SỐ NHIỆM VỤ CỤ THỂ TRONG THÁNG  <?= (int)$this->month  ?></td>
        </tr>
          <tr>
            <td align=center style="font-weight:bold;border: none;">Từ ngày <?= $this->fromdate  ?> đến ngày <?= $this->todate  ?></td>
        </tr>
        
    </table>
      
<table class=adminlist1>
    <thead>
            <tr>
                    <th rowspan=2>TT</th>
                    <th rowspan="2">Cơ quan thực hiện nhiệm vụ</th>
                    <th style="text-align:center" colspan=3>Nhiệm vụ được giao trong tháng</th>
                    <th style="text-align:center" colspan=3>Đã thực hiện</th>
                    <th style="text-align:center" colspan=2>Đang thực hiện</th>
                    <th style="text-align:center" colspan=3>Chưa thực hiện</th>
            </tr>
            <tr>
                <th>Kết dư từ tháng trước</th>
                <th>Nhiệm vụ trong tháng</th>
                <th>Tổng nhiệm vụ giao</th>
                <th>Trước hạn</th>
                <th>Đúng hạn</th>
                <th>Quá hạn</th>
                <th>Trong hạn</th>
                <th>Quá hạn</th>
                <th>Trong hạn</th>
                <th>Quá hạn</th>
            </tr>
           
    </thead>
    <tbody>
        
        
        
        
            <?php
                    $stt=0;
                    foreach($this->dataReport as $itemreport){
            ?>
            <tr>
                    <td align=center><?php echo ++$stt?></td>
                    <td><?php echo $itemreport->TENDONVI?></td>
                    

                    <td align=center>
                        <?php
                        if((int)$itemreport->CNTTHANGTRUOC > 0){
                         ?>
                        <a href="#" onclick="window.parent.document.frm.target = 'reportview';
    window.parent.document.frm.action = '/giaoviec/index/listdetail/REPORTTYPE/10/DONVINHAN/<?php echo $itemreport->DONVINHAN?>';
    window.parent.document.frm.submit();
    return false;"><?php echo $itemreport->CNTTHANGTRUOC?></a>
                        <?php
                        }else
                             echo $itemreport->CNTTHANGTRUOC;
                        ?>
                        
                    </td>

                    <td align=center><a href="#" onclick="window.parent.document.frm.target = 'reportview';
    window.parent.document.frm.action = '/giaoviec/index/listdetail/REPORTTYPE/2/DONVINHAN/<?php echo $itemreport->DONVINHAN?>';
    window.parent.document.frm.submit();
    return false;"><?php echo $itemreport->CNTCONGVIEC?></a></td>
                     <td align=center><?php echo (int)$itemreport->CNTTHANGTRUOC + (int)$itemreport->CNTCONGVIEC ?></td>
                     
                    <td align=center>
                        <?php
                        if((int)$itemreport->CNTXONGTRUOCHAN > 0){
                         ?>
                         <a href="#" onclick="window.parent.document.frm.target = 'reportview';
    window.parent.document.frm.action = '/giaoviec/index/listdetail/REPORTTYPE/4/DONVINHAN/<?php echo $itemreport->DONVINHAN?>';
    window.parent.document.frm.submit();
    return false;"><?php echo $itemreport->CNTXONGTRUOCHAN?></a>
                        <?php
                        }else
                             echo $itemreport->CNTXONGTRUOCHAN;
                        ?>
                        
                        </td>
                    
                    <td align=center>
                        <?php
                        if((int)$itemreport->CNTXONGDUNGHAN > 0){
                         ?>
                         <a href="#" onclick="window.parent.document.frm.target = 'reportview';
    window.parent.document.frm.action = '/giaoviec/index/listdetail/REPORTTYPE/4/DONVINHAN/<?php echo $itemreport->DONVINHAN?>';
    window.parent.document.frm.submit();
    return false;"><?php echo $itemreport->CNTXONGDUNGHAN?></a>
                        <?php
                        }else
                             echo $itemreport->CNTXONGDUNGHAN;
                        ?>
                        
                        
                        
                       </td>
                    
                    
                    <td align=center>
                        <?php
                        if((int)$itemreport->CNTXONGTREHAN > 0){
                         ?>
                        <a href="#" onclick="window.parent.document.frm.target = 'reportview';
    window.parent.document.frm.action = '/giaoviec/index/listdetail/REPORTTYPE/4/DONVINHAN/<?php echo $itemreport->DONVINHAN?>';
    window.parent.document.frm.submit();
    return false;"><?php echo $itemreport->CNTXONGTREHAN?></a>
                        <?php
                        }else
                             echo $itemreport->CNTXONGTREHAN;
                        ?>
                        
                        
                        </td>
                    
                    
                    <td align=center>
                         <?php
                        if((int)$itemreport->CNTDANGTRIENKHAI > 0){
                         ?>
                        <a href="#" onclick="window.parent.document.frm.target = 'reportview';
    window.parent.document.frm.action = '/giaoviec/index/listdetail/REPORTTYPE/8/DONVINHAN/<?php echo $itemreport->DONVINHAN?>';
    window.parent.document.frm.submit();
    return false;"><?php echo $itemreport->CNTDANGTRIENKHAI?></a>
                        <?php
                        }else
                             echo $itemreport->CNTDANGTRIENKHAI;
                        ?>
                        
                       </td>
                    
                    <td align=center>
                         <?php
                        if((int)$itemreport->CNTDANGTRIENKHAITREHAN > 0){
                         ?>
                        <a href="#" onclick="window.parent.document.frm.target = 'reportview';
    window.parent.document.frm.action = '/giaoviec/index/listdetail/REPORTTYPE/8/DONVINHAN/<?php echo $itemreport->DONVINHAN?>';
    window.parent.document.frm.submit();
    return false;"><?php echo $itemreport->CNTDANGTRIENKHAITREHAN?></a>
                        <?php
                        }else
                             echo $itemreport->CNTDANGTRIENKHAITREHAN;
                        ?>
                        
                        
                    </td>
                    
                    
                    <td align=center>
                         <?php
                        if((int)$itemreport->CNTCHUATHUCHIEN > 0){
                         ?>
                        <a href="#" onclick="window.parent.document.frm.target = 'reportview';
    window.parent.document.frm.action = '/giaoviec/index/listdetail/REPORTTYPE/9/DONVINHAN/<?php echo $itemreport->DONVINHAN?>';
    window.parent.document.frm.submit();
    return false;"><?php echo $itemreport->CNTCHUATHUCHIEN?></a>
                        <?php
                        }else
                             echo $itemreport->CNTCHUATHUCHIEN;
                        ?>
                        
                    
                    </td>
                    
                    <td align=center>
                         <?php
                        if((int)$itemreport->CNTCHUATHUCHIENTREHAN > 0){
                         ?>
                        <a href="#" onclick="window.parent.document.frm.target = 'reportview';
    window.parent.document.frm.action = '/giaoviec/index/listdetail/REPORTTYPE/9/DONVINHAN/<?php echo $itemreport->DONVINHAN?>';
    window.parent.document.frm.submit();
    return false;"><?php echo $itemreport->CNTCHUATHUCHIENTREHAN?></a>
                        <?php
                        }else
                             echo $itemreport->CNTCHUATHUCHIENTREHAN;
                        ?>
                        
                        
                    
                    </td>
                    
            </tr>
            <?php
                    }
            ?>
       
    </body>
    <tfoot>
    </tfoot>
</table>

</form>

<script>
function setvalueDateD(value_from, value_to) {
	document.frm.fromdate.value = value_from;
	document.frm.todate.value = value_to;
} 
</script>