<html xmlns:o="urn:schemas-microsoft-com:office:office"
xmlns:x="urn:schemas-microsoft-com:office:excel"
xmlns="http://www.w3.org/TR/REC-html40">

<head>
<meta http-equiv=Content-Type content="text/html; charset=utf-8">
<meta name=ProgId content=Excel.Sheet>
<meta name=Generator content="Microsoft Excel 11">
<link rel=File-List href="ÁDF_files/filelist.xml">
<link rel=Edit-Time-Data href="ÁDF_files/editdata.mso">
<link rel=OLE-Object-Data href="ÁDF_files/oledata.mso">
<!--[if gte mso 9]><xml>
 <o:DocumentProperties>
  <o:Author>User</o:Author>
  <o:LastAuthor>User</o:LastAuthor>
  <o:LastPrinted>2009-12-28T18:35:42Z</o:LastPrinted>
  <o:Created>2009-12-21T17:06:33Z</o:Created>
  <o:LastSaved>2009-12-28T18:35:55Z</o:LastSaved>
  <o:Company>HOME</o:Company>
  <o:Version>11.9999</o:Version>
 </o:DocumentProperties>
</xml><![endif]-->
<style>
<!--table
	{mso-displayed-decimal-separator:"\.";
	mso-displayed-thousand-separator:"\,";}
@page
	{margin:1.0in .25in 1.0in .25in;
	mso-header-margin:.5in;
	mso-footer-margin:.25in;}
tr
	{mso-height-source:auto;}
col
	{mso-width-source:auto;}
br
	{mso-data-placement:same-cell;}
.style0
	{mso-number-format:General;
	text-align:general;
	vertical-align:bottom;
	white-space:nowrap;
	mso-rotate:0;
	mso-background-source:auto;
	mso-pattern:auto;
	color:windowtext;
	font-size:10.0pt;
	font-weight:400;
	font-style:normal;
	text-decoration:none;
	font-family:Arial;
	mso-generic-font-family:auto;
	mso-font-charset:0;
	border:none;
	mso-protection:locked visible;
	mso-style-name:Normal;
	mso-style-id:0;}
td
	{mso-style-parent:style0;
	padding-top:1px;
	padding-right:1px;
	padding-left:1px;
	mso-ignore:padding;
	color:windowtext;
	font-size:10.0pt;
	font-weight:400;
	font-style:normal;
	text-decoration:none;
	font-family:Arial;
	mso-generic-font-family:auto;
	mso-font-charset:0;
	mso-number-format:General;
	text-align:general;
	vertical-align:bottom;
	border:none;
	mso-background-source:auto;
	mso-pattern:auto;
	mso-protection:locked visible;
	white-space:nowrap;
	mso-rotate:0;}
.xl24
	{mso-style-parent:style0;
	font-weight:700;
	font-family:Arial, sans-serif;
	mso-font-charset:0;}
.xl25
	{mso-style-parent:style0;
	vertical-align:middle;}
.xl26
	{mso-style-parent:style0;
	font-weight:700;
	font-family:Arial, sans-serif;
	mso-font-charset:0;
	vertical-align:middle;}
.xl27
	{mso-style-parent:style0;
	font-family:Arial, sans-serif;
	mso-font-charset:0;
	text-align:center;}
.xl28
	{mso-style-parent:style0;
	font-weight:700;
	font-family:Arial, sans-serif;
	mso-font-charset:0;
	text-align:center;}
.xl29
	{mso-style-parent:style0;
	text-align:center;}
.xl30
	{mso-style-parent:style0;
	font-size:14.0pt;
	font-family:Arial, sans-serif;
	mso-font-charset:0;
	text-align:center;}
.xl31
	{mso-style-parent:style0;
	font-weight:700;
	font-family:Arial, sans-serif;
	mso-font-charset:0;
	text-align:center;
	vertical-align:middle;
	border-top:.5pt solid windowtext;
	border-right:none;
	border-bottom:none;
	border-left:.5pt solid windowtext;white-space:normal;}
.xl32
	{mso-style-parent:style0;
	font-weight:700;
	font-family:Arial, sans-serif;
	mso-font-charset:0;
	text-align:center;
	vertical-align:middle;
	border-top:.5pt solid windowtext;
	border-right:.5pt solid windowtext;
	border-bottom:none;
	border-left:none;white-space:normal;}
.xl33
	{mso-style-parent:style0;
	font-weight:700;
	font-family:Arial, sans-serif;
	mso-font-charset:0;
	text-align:center;
	vertical-align:middle;
	border-top:none;
	border-right:none;
	border-bottom:.5pt solid windowtext;
	border-left:.5pt solid windowtext;white-space:normal;}
.xl34
	{mso-style-parent:style0;
	font-weight:700;
	font-family:Arial, sans-serif;
	mso-font-charset:0;
	text-align:center;
	vertical-align:middle;
	border-top:none;
	border-right:.5pt solid windowtext;
	border-bottom:.5pt solid windowtext;
	border-left:none;white-space:normal;}
.xl35
	{mso-style-parent:style0;
	font-weight:700;
	font-family:Arial, sans-serif;
	mso-font-charset:0;
	text-align:center;
	vertical-align:middle;
	border-top:.5pt solid windowtext;
	border-right:.5pt solid black;
	border-bottom:none;
	border-left:none;white-space:normal;}
.xl36
	{mso-style-parent:style0;
	font-weight:700;
	font-family:Arial, sans-serif;
	mso-font-charset:0;
	text-align:center;
	vertical-align:middle;
	border-top:none;
	border-right:.5pt solid black;
	border-bottom:.5pt solid windowtext;
	border-left:none;white-space:normal;}
.xl37
	{mso-style-parent:style0;
	font-weight:700;
	font-family:Arial, sans-serif;
	mso-font-charset:0;
	text-align:center;
	vertical-align:middle;
	border-top:.5pt solid windowtext;
	border-right:none;
	border-bottom:none;
	border-left:.5pt solid black;white-space:normal;}
.xl38
	{mso-style-parent:style0;
	font-weight:700;
	font-family:Arial, sans-serif;
	mso-font-charset:0;
	text-align:center;
	vertical-align:middle;
	border-top:none;
	border-right:none;
	border-bottom:.5pt solid windowtext;
	border-left:.5pt solid black;white-space:normal;}
.xl39
	{mso-style-parent:style0;
	font-weight:700;
	font-family:Arial, sans-serif;
	mso-font-charset:0;
	text-align:left;
	vertical-align:middle;
	border-top:.5pt solid windowtext;
	border-right:none;
	border-bottom:.5pt solid windowtext;
	border-left:.5pt solid windowtext;white-space:normal;}
.xl40
	{mso-style-parent:style0;
	font-weight:700;
	font-family:Arial, sans-serif;
	mso-font-charset:0;
	text-align:left;
	vertical-align:middle;
	border-top:.5pt solid windowtext;
	border-right:none;
	border-bottom:.5pt solid windowtext;
	border-left:none;white-space:normal;}
.xl41
	{mso-style-parent:style0;
	font-weight:700;
	font-family:Arial, sans-serif;
	mso-font-charset:0;
	text-align:left;
	vertical-align:middle;
	border-top:.5pt solid windowtext;
	border-right:.5pt solid black;
	border-bottom:.5pt solid windowtext;
	border-left:none;white-space:normal;}
.xl42
	{mso-style-parent:style0;
	font-family:Arial, sans-serif;
	mso-font-charset:0;
	text-align:center;
	vertical-align:middle;
	border-top:.5pt solid windowtext;
	border-right:none;
	border-bottom:.5pt solid windowtext;
	border-left:.5pt solid windowtext;white-space:normal;}
.xl43
	{mso-style-parent:style0;
	font-family:Arial, sans-serif;
	mso-font-charset:0;
	text-align:center;
	vertical-align:middle;
	border-top:.5pt solid windowtext;
	border-right:.5pt solid black;
	border-bottom:.5pt solid windowtext;
	border-left:none;white-space:normal;}
.xl44
	{mso-style-parent:style0;
	font-family:Arial, sans-serif;
	mso-font-charset:0;
	text-align:center;
	vertical-align:middle;
	border-top:.5pt solid windowtext;
	border-right:none;
	border-bottom:.5pt solid windowtext;
	border-left:.5pt solid black;white-space:normal;}
-->
</style>
<!--[if gte mso 9]><xml>
 <x:ExcelWorkbook>
  <x:ExcelWorksheets>
   <x:ExcelWorksheet>
    <x:Name>Sheet1</x:Name>
    <x:WorksheetOptions>
     <x:Print>
      <x:ValidPrinterInfo/>
      <x:Scale>56</x:Scale>
      <x:HorizontalResolution>600</x:HorizontalResolution>
      <x:VerticalResolution>600</x:VerticalResolution>
     </x:Print>
     <x:PageBreakZoom>60</x:PageBreakZoom>
     <x:Selected/>
     <x:Panes>
      <x:Pane>
       <x:Number>3</x:Number>
       <x:ActiveRow>9</x:ActiveRow>
       <x:ActiveCol>6</x:ActiveCol>
       <x:RangeSelection>$G$10:$H$11</x:RangeSelection>
      </x:Pane>
     </x:Panes>
     <x:ProtectContents>False</x:ProtectContents>
     <x:ProtectObjects>False</x:ProtectObjects>
     <x:ProtectScenarios>False</x:ProtectScenarios>
    </x:WorksheetOptions>
    <x:PageBreaks>
     <x:RowBreaks>
      <x:RowBreak>
       <x:Row>56</x:Row>
       <x:ColEnd>18</x:ColEnd>
      </x:RowBreak>
     </x:RowBreaks>
    </x:PageBreaks>
   </x:ExcelWorksheet>
   <x:ExcelWorksheet>
    <x:Name>Sheet2</x:Name>
    <x:WorksheetOptions>
     <x:ProtectContents>False</x:ProtectContents>
     <x:ProtectObjects>False</x:ProtectObjects>
     <x:ProtectScenarios>False</x:ProtectScenarios>
    </x:WorksheetOptions>
   </x:ExcelWorksheet>
   <x:ExcelWorksheet>
    <x:Name>Sheet3</x:Name>
    <x:WorksheetOptions>
     <x:ProtectContents>False</x:ProtectContents>
     <x:ProtectObjects>False</x:ProtectObjects>
     <x:ProtectScenarios>False</x:ProtectScenarios>
    </x:WorksheetOptions>
   </x:ExcelWorksheet>
  </x:ExcelWorksheets>
  <x:WindowHeight>9180</x:WindowHeight>
  <x:WindowWidth>15510</x:WindowWidth>
  <x:WindowTopX>240</x:WindowTopX>
  <x:WindowTopY>150</x:WindowTopY>
  <x:ProtectStructure>False</x:ProtectStructure>
  <x:ProtectWindows>False</x:ProtectWindows>
 </x:ExcelWorkbook>
 <x:ExcelName>
  <x:Name>Print_Area</x:Name>
  <x:SheetIndex>1</x:SheetIndex>
  <x:Formula>=Sheet1!$A$1:$S$56</x:Formula>
 </x:ExcelName>
</xml><![endif]-->
</head>

<body link=blue vlink=purple>

<table x:str border=0 cellpadding=0 cellspacing=0 width=1283 style='border-collapse:
 collapse;table-layout:fixed;width:962pt'>
 <col width=64 span=5 style='width:48pt'>
 <col width=115 style='mso-width-source:userset;mso-width-alt:4205;width:86pt'>
 <col width=64 span=12 style='width:48pt'>
 <col width=16 style='mso-width-source:userset;mso-width-alt:585;width:12pt'>
 <col width=64 style='width:48pt'>
 <tr height=17 style='height:12.75pt'>
  <td colspan=7 height=17 class=xl27 width=499 style='height:12.75pt;
  width:374pt'><?= mb_strtoupper($this->config->sys_info->unit,"utf-8") ?></td>
  <td width=64 style='width:48pt'></td>

  <td width=64 style='width:48pt'></td>
  <td width=64 style='width:48pt'></td>
  <td colspan=10 class=xl28 width=592 style='width:444pt'>CỘNG HÒA XÃ HỘI CHỦ
  NGHĨA VIỆT NAM</td>
 </tr>
 <tr height=17 style='height:12.75pt'>
  <td colspan=7 height=17 class=xl28 style='height:12.75pt'><?= mb_strtoupper($this->config->sys_info->company,"utf-8") ?></td>
  <td colspan=3 style='mso-ignore:colspan'></td>
  <td colspan=10 class=xl28>Ðộc lập - Tự do - Hạnh phúc</td>

 </tr>
 <tr height=17 style='height:12.75pt'>
  <td height=17 colspan=10 style='height:12.75pt;mso-ignore:colspan'></td>
  <td colspan=10 class=xl29><?=$this->config->sys_info->city?>, ngày <?=date("d")?> tháng <?=date("m")?> năm <?=date("Y")?></td>
 </tr>
 <tr height=34 style='height:25.5pt;mso-xlrowspan:2'>
  <td height=34 colspan=20 style='height:25.5pt;mso-ignore:colspan'></td>
 </tr>

 <tr height=17 style='height:12.75pt'>
  <td height=17 colspan=3 style='height:12.75pt;mso-ignore:colspan'></td>
  <td colspan=13 rowspan=2 class=xl30>THỐNG KÊ VĂN BẢN ĐI</td>
  <td colspan=4 style='mso-ignore:colspan'></td>
 </tr>
 <tr height=17 style='height:12.75pt'>
  <td height=17 colspan=3 style='height:12.75pt;mso-ignore:colspan'></td>
  <td colspan=4 style='mso-ignore:colspan'></td>

 </tr>
 <tr height=17 style='height:12.75pt'>
  <td height=17 colspan=7 style='height:12.75pt;mso-ignore:colspan'></td>
  <td colspan=4 class=xl27><?php echo $this->thu;?></td>
  <td colspan=8 style='mso-ignore:colspan'></td>
 </tr>
 <tr height=17 style='height:12.75pt'>
  <td height=17 colspan=20 style='height:12.75pt;mso-ignore:colspan'></td>

 </tr>
<?php
   require_once 'report/models/ThongkevanbandiModel.php';        
   ?>
 <tr height=38 style='mso-height-source:userset;height:28.5pt'>
  <td height=38 style='height:28.5pt'></td>
  <td class=xl24></td>
  <td colspan=2 rowspan=2 class=xl31 style='border-right:.5pt solid black;
  border-bottom:.5pt solid black'>STT</td>
  <td colspan=2 rowspan=2 class=xl31 style='border-right:.5pt solid black;
  border-bottom:.5pt solid black'>Số/Ký hiệu</td>
  <td colspan=2 rowspan=2 class=xl37 style='border-right:.5pt solid black;
  border-bottom:.5pt solid black'>Ngày ban hành</td>

  <td colspan=2 rowspan=2 class=xl37 style='border-right:.5pt solid black;
  border-bottom:.5pt solid black'>Trích yếu</td>
  <td colspan=2 rowspan=2 class=xl37 style='border-right:.5pt solid black;
  border-bottom:.5pt solid black'>Thông tin VBĐến</td>
  <?php
                    if($this->thongke == 0){
                    ?>
  <td colspan=2 rowspan=2 class=xl37 style='border-right:.5pt solid black;
  border-bottom:.5pt solid black;'>Người xử lý</td>
  <?PHP
                    }
                    ?>
  <td colspan=2 rowspan=2 class=xl37 style='border-right:.5pt solid black;
  border-bottom:.5pt solid black'>Ghi chú</td>
  <td colspan=2 class=xl24 style='mso-ignore:colspan'></td>
  <td colspan=2 style='mso-ignore:colspan'></td>
 </tr>

 <tr height=44 style='mso-height-source:userset;height:33.0pt'>
  <td height=44 style='height:33.0pt'></td>
  <td class=xl24></td>
  <td colspan=2 class=xl24 style='mso-ignore:colspan'></td>
  <td colspan=2 style='mso-ignore:colspan'></td>
 </tr>
 <?php                
                    foreach($this->data as $dataGroup){
                    $paramData=array(
                        'fromdate'=>$this->fromdate,
                        'todate'=>$this->todate,
                        'year'=>$this->year,                        
                        'id_svb'=>$this->sel_svb,
                        'id_lvb'=>$this->sel_lvb                        
                    );
                    if($this->thongke == 0){
                        $paramData['id_dep']=$dataGroup['ID_DEP'];
                    }else{
                        $paramData['id_u']=$dataGroup['ID_U'];
                    }
                    $dataRows=ThongkevanbandiModel::getDataThongKeVanBanDi($paramData);
                ?>
 <tr height=30 style='mso-height-source:userset;height:22.5pt'>
  <td height=30 style='height:22.5pt'></td>
  <td class=xl24></td>

  <?php
    if($this->thongke == 0){
    ?>
    <td colspan=14 class=xl39 style='border-right:.5pt solid black'><?php echo $dataGroup['NAME'].'('.count($dataRows).')';?></td>
    <?php
    }else{
    ?>
    <td colspan=12 class=xl39 style='border-right:.5pt solid black'><?php echo $dataGroup['FIRSTNAME'].' '.$dataGroup['LASTNAME'].' ('.count($dataRows).') - '.$dataGroup['NAME'];?></td>
    
    <?php
    }
    ?>
    <td colspan=2 class=xl24 style='mso-ignore:colspan'></td>
  <td colspan=2 style='mso-ignore:colspan'></td>
 </tr>
 <?php 
                    $stt=1;
                    foreach($dataRows as $row){
                    ?>
 <tr height=34 style='mso-height-source:userset;height:25.5pt'>
  <td height=34 style='height:25.5pt'></td>
  <td class=xl24></td>
  <td colspan=2 class=xl42 style='border-right:.5pt solid black' x:num><?php echo $stt; ?></td>

  <td colspan=2 class=xl44 style='border-right:.5pt solid black;border-left:
  none'><?php echo $row['SOKYHIEU'];?></td>
  <td colspan=2 class=xl44 style='border-right:.5pt solid black;border-left:
  none' ><?php echo QLVBDHCommon::MysqlDateToVnDate($row["NGAYBANHANH"])?></td>
  <td colspan=2 class=xl44 style='border-right:.5pt solid black;border-left:
  none;word-wrap:break-word' ><?php echo $row['TRICHYEU']?></td>
  <td colspan=2 class=xl44 style='border-right:.5pt solid black;border-left:
  none;word-wrap:break-word' ><?php
                            if($row['SOKYHIEU_VBDEN']!=null && $row['SOKYHIEU_VBDEN']!=''){
                                echo $row['SOKYHIEU_VBDEN'].' ngày ';
                                echo QLVBDHCommon::MysqlDateToVnDate($row['NGAYBANHANH_VBDEN']).' của ';
                                echo $row['NAME_COQUANBANHANH_VBDEN'];
                            }
                            ?></td>
  <?php
                        if($this->thongke == 0){
                        ?>
  <td colspan=2 class=xl44 style='border-right:.5pt solid black;border-left:
  none;word-wrap:break-word' ><?php echo $row['FIRSTNAME'].' '.$row['LASTNAME']?></td>
  <?php
                        }
                        ?>
  <td colspan=2 class=xl44 style='border-right:.5pt solid black;border-left:
  none;word-wrap:break-word' ><?php
                            if($row['NGAYHETHAN_VBDEN']!=null && $row['NGAYHETHAN_VBDEN']!=''){
                                $minusTime=strtotime($row['NGAYBANHANH']) - strtotime($row['NGAYHETHAN_VBDEN']);
                                if($minusTime>0){
                                    echo 'Trễ hạn';
                                }
                                if($minusTime==0){
                                    echo 'Đúng hạn';
                                }
                                if($minusTime<0){
                                    echo 'Sớm hạn';
                                }
                            }
                            ?></td>

  <td colspan=2 class=xl24 style='mso-ignore:colspan'></td>
  <td colspan=2 style='mso-ignore:colspan'></td>
 </tr>
                    <?php                
                    $stt++;
                    }
                }
                ?>
 <tr height=68 style='height:51.0pt;mso-xlrowspan:4'>
  <td height=68 colspan=20 style='height:51.0pt;mso-ignore:colspan'></td>
 </tr>
 <tr height=26 style='mso-height-source:userset;height:19.5pt'>
  <td height=26 colspan=12 style='height:19.5pt;mso-ignore:colspan'></td>
  <td colspan=3 class=xl25 style='mso-ignore:colspan'></td>

  <td colspan=5 style='mso-ignore:colspan'></td>
 </tr>
 <tr height=68 style='height:51.0pt;mso-xlrowspan:4'>
  <td height=68 colspan=20 style='height:51.0pt;mso-ignore:colspan'></td>
 </tr>
 <tr height=25 style='mso-height-source:userset;height:18.75pt'>
  <td height=25 colspan=11 style='height:18.75pt;mso-ignore:colspan'></td>
  <td colspan=5 class=xl26 style='mso-ignore:colspan'></td>
  <td colspan=4 style='mso-ignore:colspan'></td>

 </tr>
 <tr height=21 style='mso-height-source:userset;height:15.75pt'>
  <td height=21 colspan=20 style='height:15.75pt;mso-ignore:colspan'></td>
 </tr>
 <![if supportMisalignedColumns]>
 <tr height=0 style='display:none'>
  <td width=64 style='width:48pt'></td>
  <td width=64 style='width:48pt'></td>
  <td width=64 style='width:48pt'></td>

  <td width=64 style='width:48pt'></td>
  <td width=64 style='width:48pt'></td>
  <td width=115 style='width:86pt'></td>
  <td width=64 style='width:48pt'></td>
  <td width=64 style='width:48pt'></td>
  <td width=64 style='width:48pt'></td>
  <td width=64 style='width:48pt'></td>
  <td width=64 style='width:48pt'></td>
  <td width=64 style='width:48pt'></td>

  <td width=64 style='width:48pt'></td>
  <td width=64 style='width:48pt'></td>
  <td width=64 style='width:48pt'></td>
  <td width=64 style='width:48pt'></td>
  <td width=64 style='width:48pt'></td>
  <td width=64 style='width:48pt'></td>
  <td width=16 style='width:12pt'></td>
  <td width=64 style='width:48pt'></td>
 </tr>

 <![endif]>
</table>

</body>

</html>
<script>print();</script>