<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html>
<head>
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8"/>
    <script type="text/javascript" src="/js/common.js"></script>
    <script src="/js/validate.js" type="text/javascript"></script>
    <script src="/js/validate.js" type="text/javascript"></script>
    <script type="text/javascript" src=<?php echo $this->baseUrl() . "/js/Json/Base64.js" ?>></script>
    <script type="text/javascript" src=<?php echo $this->baseUrl() . "/js/Json/json2.js" ?>></script>
    <script type="text/javascript" src=<?php echo $this->baseUrl() . "/js/Json/json_parse.js" ?>></script>
    <script type="text/javascript" src=<?php echo $this->baseUrl() . "/js/Ajax/AjaxEngine.js" ?>></script>
    <link rel="stylesheet" type="text/css" href="/styles/general.css"/>
    <link rel=Stylesheet href=stylesheet.css>
</head>
<body style="background-color:transparent">
<h3><?php echo $this->thu; ?></h3>
<?php
    require_once 'report/models/ThongkevanbandiModel.php';
?>
<table class=adminlist width="100%">
    <thead>
    <tr>
        <th>STT</th>
        <th>Số/Ký hiệu</th>
        <th>Ngày ban hành</th>
        <th>Trích yếu</th>
        <th>Thông tin VBĐến</th>
        <?php
            if ( $this->thongke == 0 ) {
                ?>
                <th>Người xử lý</th>
                <?php
            }
        ?>
        <th>Ghi chú</th>
    </tr>
    </thead>
    <tbody>
    <?php
        foreach ( $this->data as $dataGroup ) {
            $paramData = array('fromdate' => $this->fromdate, 'todate' => $this->todate, 'year' => $this->year, 'id_svb' => $this->sel_svb, 'id_lvb' => $this->sel_lvb);
            if ( $this->thongke == 0 ) {
                $paramData['id_dep'] = $dataGroup['ID_DEP'];
            } else {
                $paramData['id_u'] = $dataGroup['ID_U'];
            }
            $dataRows = ThongkevanbandiModel::getDataThongKeVanBanDi($paramData);
            ?>
            <tr>
                <!-- 1/7/2016 - update by hoangnm - begin -->
                <?php
                    if ( $this->thongke == 0 ) {
                        ?>
                        <td colspan="7"><b><?php echo $dataGroup['NAME'] . '(' . count($dataRows) . ')'; ?></b></td>
                        <?php
                    } else {
                        ?>
                        <td colspan="6"><b><?php echo $dataGroup['FIRSTNAME'] . ' ' . $dataGroup['LASTNAME'] . ' (' . count($dataRows) . ') - ' . $dataGroup['NAME']; ?></b></td>
                        <?php
                    }
                ?>
                <!-- 1/7/2016 - update by hoangnm - end -->
            </tr>
            <?php
            $stt = 1;
            foreach ( $dataRows as $row ) {
              //  var_dump($row);
                ?>
                <tr>
                    <td><?php echo $stt; ?></td>
                    <td><?php echo $row['SOKYHIEU']; ?></td>
                    <td><?php echo QLVBDHCommon::MysqlDateToVnDate($row["NGAYBANHANH"]) ?></td>
                    <td><?php echo $row['TRICHYEU'] ?></td>
                    <td>
                        <?php
                            if ( $row['SOKYHIEU_VBDEN'] != NULL && $row['SOKYHIEU_VBDEN'] != '' ) {
                                echo $row['SOKYHIEU_VBDEN'] . ' ngày ';
                                echo QLVBDHCommon::MysqlDateToVnDate($row['NGAYBANHANH_VBDEN']) . ' của ';
                                echo $row['NAME_COQUANBANHANH_VBDEN'];
                            }
                        ?>
                    </td>
                    <?php
                        if ( $this->thongke == 0 ) {
                            ?>
                            <td><?php echo $row['FIRSTNAME'] . ' ' . $row['LASTNAME'] ?></td>
                            <?php
                        }
                    ?>
                    <td>
                        <?php
                            if ( $row['NGAYHETHAN_VBDEN'] != NULL && $row['NGAYHETHAN_VBDEN'] != '' ) {
                                $minusTime = strtotime($row['NGAYBANHANH']) - strtotime($row['NGAYHETHAN_VBDEN']);
                                if ( $minusTime > 0 ) {
                                    echo 'Trễ hạn';
                                }
                                if ( $minusTime == 0 ) {
                                    echo 'Đúng hạn';
                                }
                                if ( $minusTime < 0 ) {
                                    echo 'Sớm hạn';
                                }
                            }
                        ?>
                    </td>
                </tr>
                <?php
                $stt++;
            }
        }
    ?>
    </tbody>
    <tfoot>
    </tfoot>
</table>
<p id=lasttext></p>
</body>
</html>
<script>
    function resize() {
        try {
            var iframeElement = window.parent.document.getElementById( 'reportview' );
            iframeElement.style.height = "" + (document.getElementById( "lasttext" ).offsetTop) + "px";
            iframeElement.width = "100%";
            setTimeout( "resize()", 1000 );
        } catch ( ex ) {
        }
    }
    resize();
</script>

