<?php
    require_once('qtht/models/DepartmentsModel.php');
    require_once 'qtht/models/sovanbanModel.php';
    require_once 'qtht/models/LoaiVanBanModel.php';
    require_once 'report/models/ThongkevanbandiModel.php';
    $data_departs = DepartmentsModel::getAll();
?>
<form name=frm method="POST" target="reportview">
    <div>
        <label><b>Chọn năm thống kê:</b></label>
        <?php
            $year = new qtht_year();
            echo $year->ToCombo("year", "");
        ?>
    </div>
    <div class=clr></div>
    <div>
        <label><b>Ngày bắt đầu:</b></label>
        <?= QLVBDHCommon::calendar($this->fromdate, "fromdate", "fromdate") ?>
        >>
        <?= QLVBDHCommon::calendar($this->todate, "todate", "todate") ?>
    </div>
    <div class=clr></div>
    <div>
        <label><b>Tháng:</b></label> <input type="radio" name='sel_timedis' onclick="setvalueDateD('1/1','31/1')">1
        <?php
            $year = QLVBDHCommon::getYear();
            $d = strtotime($year . "-3-1");
            $d = $d - 86400;
            $str_cuoi2 = date('d/m', $d);
        ?>
        <input type="radio" name='sel_timedis' onclick="setvalueDateD('1/2','<?php echo $str_cuoi2 ?>')">2
        <input type="radio" name='sel_timedis' onclick="setvalueDateD('1/3','31/3')">3
        <input type="radio" name='sel_timedis' onclick="setvalueDateD('1/4','30/4')">4
        <input type="radio" name='sel_timedis' onclick="setvalueDateD('1/5','31/5')">5
        <input type="radio" name='sel_timedis' onclick="setvalueDateD('1/6','30/6')">6
        <input type="radio" name='sel_timedis' onclick="setvalueDateD('1/7','31/7')">7
        <input type="radio" name='sel_timedis' onclick="setvalueDateD('1/8','31/8')">8
        <input type="radio" name='sel_timedis' onclick="setvalueDateD('1/9','30/9')">9
        <input type="radio" name='sel_timedis' onclick="setvalueDateD('1/10','31/10')">10
        <input type="radio" name='sel_timedis' onclick="setvalueDateD('1/11','30/11')">11
        <input type="radio" name='sel_timedis' onclick="setvalueDateD('1/12','31/12')">12
    </div>
    <div class=clr></div>
    <div>
        <label><b>Quí:</b></label> <input type="radio" name='sel_timedis' onclick="setvalueDateD('1/1','31/3')">I
        <input type="radio" name='sel_timedis' onclick="setvalueDateD('1/4','30/6')">II
        <input type="radio" name='sel_timedis' onclick="setvalueDateD('1/7','30/9')">III
        <input type="radio" name='sel_timedis' onclick="setvalueDateD('1/10','31/12')">IV
    </div>
    <div class=clr></div>
    <div>
        <label><b>Năm:</b></label> <input type="radio" name='sel_timedis' onclick="setvalueDateD('1/1','31/12')">
    </div>
    <div class=clr></div>
    <div>
        <label><b>Thống kê theo:</b></label>
        <input type="radio" name='thongke' value="0" checked="true" onclick="checkCaNhan()">Phòng ban
        <input type="radio" name='thongke' value="1" onclick="checkCaNhan()">Từng cá nhân
    </div>
    <div class=clr></div>
    <br/>

    <div id="phongban">
        <label><b>Chọn phòng ban:</b></label> <select name="sel_pb[]" id="sel_lvb" multiple="multiple" size=5>
            <option value=0>[Tất cả phòng ban]</option>
            <?php
                $user = Zend_Registry::get('auth')->getIdentity();
                DepartmentsModel::toComboNameWithSel($this->sel_pb);
            ?>
        </select>
    </div>
    <div id="canhan">
        <label><b>Chọn Người:</b></label>
        <?php
            echo ThongkevanbandiModel::writeSelectDepartmentMultiUserH('sel_dep_canhan', 'sel_canhan');
        ?>
    </div>
    <br/>

    <div class=clr></div>
    <div style="float:left">
        <label><b>Sổ văn bản:</b></label> <select name="sel_svb" id="sel_svb">
            <option value=0>[Chọn tất cả]</option>
            <?php sovanbanModel::toComboNameWithDep(1); ?>
        </select>
    </div>
    <div class=clr></div>
    <div style="float:left">
        <label><b>Loại văn bản:</b></label> <select name="sel_lvb" id="sel_lvb">
            <option value="0">--- Tất cả loại văn bản ---</option>
            <?php LoaiVanBanModel::toComboName(); ?>
        </select>
    </div>
    <input type=hidden id=h_isexel name=h_isexel value=0>

    <div class=clr></div>
    <input type="button" title="Hiện thị báo cáo" style="background: url('/images/hscv-input-bg.png') repeat-x;"
           onclick="
            document.frm.target='reportview';
            document.frm.h_isexel.value = 0;
            document.frm.action='/report/thongkevanbandi/indextkview';
            document.frm.submit();
            return false;" value="Hiển thị">

    <input type="button" title="Xuất excel" style="background: url(/images/hscv-input-bg.png) repeat-x;"
           onclick="
            document.frm.target='reportview';
            document.frm.h_isexel.value = 1;
            document.frm.action='/report/thongkevanbandi/indextkviewexcel';
            document.frm.submit();
            return false;" value="Xuất ra Exel">

    <input type="button" title="In báo cáo" style="background: url(/images/hscv-input-bg.png) repeat-x;"
           onclick="
            document.frm.target='_blank';
            document.frm.h_isexel.value = 0;
            document.frm.action = '/report/thongkevanbandi/indextkview/is_in/1';
            document.frm.submit();
            return false;" value="In báo cáo">

</form>
<iframe style="overflow-x:visible" allowTransparency=true BORDER=0 scrolling=no FRAMEBORDER=no
        id="reportview" name="reportview">
</iframe>
<script>
    var arr_user = new Array();
    function setvalueDateD( value_from, value_to ) {
        document.frm.fromdate.value = value_from;
        document.frm.todate.value = value_to;
    }
    function checkCaNhan() {
        if ( document.frm.thongke.value == 1 ) {
            document.getElementById( 'canhan' ).style.display = "";
            document.getElementById( 'phongban' ).style.display = "none";
        } else {
            document.getElementById( 'canhan' ).style.display = "none";
            document.getElementById( 'phongban' ).style.display = "";
        }
    }
    checkCaNhan();
</script>