<?= QLVBDHCommon::useDlgConfirm() ?>
<form name=frm method="post" action="/giamsatgiaoviec/danhmucloaicongviec/index">    
    <table class="adminlist">
        <thead>
            <tr>
                <th nowrap style="text-align: center;">#</th>
                <th nowrap><input type=checkbox name=DELALL onclick="SelectAll(this, 'DEL')"></th>
                <th width="15%">Tên loại công việc giao</th>
                <th width="15%">Mã</th>
            </tr>
        </thead>
        <tbody>
            <?php
            $stt = 0;
            foreach ($this->data as $row) {
                $stt++;
                ?>
                <tr>
                    <td nowrap align="center"><?php echo $stt ?></td>
                    <td nowrap align="center">
                        <input type=checkbox name=DEL[] value='<?php echo $row['ID_LCV'] ?>'>
                    </td>                    
                    <td nowrap align="left" width="100%"> <a href="#" onclick = "ItemClick(<?php echo $row['ID_LCV'] ?>);"><?=$row['NAME']?></a></td>
                    <td nowrap align="center"><?=$row['CODE']?></td>                    
                </tr>
            <?php
                $i = (-1 + $i) * -1;
            }
            ?>
        </tbody>
        <tfoot>
            <tr>
                <td colspan="8">
                    <div class="pagination">
                        <div class="limit">Hiển thị #
                            <select name="limit" id="limit" class="inputbox" size="1" onchange="document.frm.page.value = 1;
                                    document.frm.submit();" style="width:60px;">
                                <option value="5">5</option>
                                <option value="10">10</option>
                                <option value="15">15</option>
                                <option value="20">20</option>
                                <option value="25">25</option>
                                <option value="30">30</option>
                                <option value="40">40</option>                                
                                <option value="50">50</option>
                                <option value="100">100</option>
                                <script>
                                    document.frm.limit.value = '<?php echo $this->limit ?>';
                                </script>
                            </select>
                        </div>
                        <div style="float:right;"><?php echo $this->showPage; ?></div>
                    </div>
                </td>
            </tr>
        </tfoot>
    </table>
    <input type="hidden" name="page" value="<?php echo $this->page; ?>">
</form>
<script>
    function DongBoButtonClick() {
        document.frm.action = "/giamsatgiaoviec/danhmucloaicongviec/dongbo";
        document.frm.submit();
    }
    function BackButtonClick(){
        window.location.href="/";
    }
    function DeleteButtonClick(){
        var ln = 0;
        var arr = document.getElementsByName('DEL[]');
        for (var i = 0; i < arr.length; i++){
            if (arr[i].checked == true){
                ln = 1;
            }
        }
        if (ln == 1){
            var func_ok = "document.frm.action='/giamsatgiaoviec/danhmucloaicongviec/delete';document.frm.method='post';document.frm.submit();";
            var func_cancel = "";
            displayConfirm("Bạn có muốn xóa không?", "", "", func_ok, func_cancel);
        }else{
            alert("Bạn phải chọn một loại công việc giao việc để xóa!");
        }
    }

    function AddNewButtonClick() {
        document.frm.action = "/giamsatgiaoviec/danhmucloaicongviec/input";
        document.frm.method = "post";
        document.frm.submit();
    }
    function ItemClick(id) {
        document.frm.action = "/giamsatgiaoviec/danhmucloaicongviec/input/idLCV/" + id;
        document.frm.method = "post";
        document.frm.submit();
    }
    function TimLai() {
        document.frm.search.value = "";
        document.frm.action = "/giamsatgiaoviec/danhmucloaicongviec/index";
        document.frm.submit();
    }
</script>