<html xmlns:o="urn:schemas-microsoft-com:office:office"
xmlns:x="urn:schemas-microsoft-com:office:excel"
xmlns="http://www.w3.org/TR/REC-html40">

<head>
<meta http-equiv=Content-Type content="text/html; charset=utf-8">
<meta name=ProgId content=Excel.Sheet>
<meta name=Generator content="Microsoft Excel 11">
<link rel=File-List href="ytrew_files/filelist.xml">
<link rel=Edit-Time-Data href="ytrew_files/editdata.mso">
<link rel=OLE-Object-Data href="ytrew_files/oledata.mso">
<!--[if gte mso 9]><xml>
 <o:DocumentProperties>
  <o:Author>nguyennd</o:Author>
  <o:LastAuthor>User</o:LastAuthor>
  <o:Created>2009-08-25T14:43:47Z</o:Created>
  <o:LastSaved>2009-11-17T09:38:07Z</o:LastSaved>
  <o:Company>Hewlett-Packard</o:Company>
  <o:Version>11.9999</o:Version>
 </o:DocumentProperties>
</xml><![endif]-->
<style>
<!--table
	{mso-displayed-decimal-separator:"\.";
	mso-displayed-thousand-separator:"\,";}
@page
	{margin:.2in .2in .2in .2in;
	mso-header-margin:.2in;
	mso-footer-margin:.2in;
	mso-page-orientation:landscape;}
.font9
	{color:red;
	font-size:12.0pt;
	font-weight:400;
	font-style:italic;
	text-decoration:none;
	font-family:"Times New Roman", serif;
	mso-font-charset:0;}
tr
	{mso-height-source:auto;}
col
	{mso-width-source:auto;}
br
	{mso-data-placement:same-cell;}
.style0
	{mso-number-format:General;
	text-align:general;
	vertical-align:bottom;
	white-space:nowrap;
	mso-rotate:0;
	mso-background-source:auto;
	mso-pattern:auto;
	color:windowtext;
	font-size:10.0pt;
	font-weight:400;
	font-style:normal;
	text-decoration:none;
	font-family:Arial;
	mso-generic-font-family:auto;
	mso-font-charset:0;
	border:none;
	mso-protection:locked visible;
	mso-style-name:Normal;
	mso-style-id:0;}
td
	{mso-style-parent:style0;
	padding-top:1px;
	padding-right:1px;
	padding-left:1px;
	mso-ignore:padding;
	color:windowtext;
	font-size:10.0pt;
	font-weight:400;
	font-style:normal;
	text-decoration:none;
	font-family:Arial;
	mso-generic-font-family:auto;
	mso-font-charset:0;
	mso-number-format:General;
	text-align:general;
	vertical-align:bottom;
	border:none;
	mso-background-source:auto;
	mso-pattern:auto;
	mso-protection:locked visible;
	white-space:nowrap;
	mso-rotate:0;}
.xl24
	{mso-style-parent:style0;
	font-size:12.0pt;
	font-family:"Times New Roman", serif;
	mso-font-charset:0;}
.xl25
	{mso-style-parent:style0;
	font-size:12.0pt;
	font-weight:700;
	font-family:"Times New Roman", serif;
	mso-font-charset:0;
	text-align:center;
	vertical-align:top;
	border-top:none;
	border-right:.5pt solid windowtext;
	border-bottom:.5pt solid windowtext;
	border-left:.5pt solid windowtext;
	background:silver;
	mso-pattern:auto none;
	white-space:normal;}
.xl26
	{mso-style-parent:style0;
	font-size:12.0pt;
	font-weight:700;
	font-family:"Times New Roman", serif;
	mso-font-charset:0;
	text-align:center;
	vertical-align:top;
	border-top:none;
	border-right:.5pt solid windowtext;
	border-bottom:.5pt solid windowtext;
	border-left:none;
	background:silver;
	mso-pattern:auto none;
	white-space:normal;}
.xl27
	{mso-style-parent:style0;
	font-size:12.0pt;
	font-family:"Times New Roman", serif;
	mso-font-charset:0;
	text-align:center;
	vertical-align:middle;
	border-top:none;
	border-right:.5pt solid windowtext;
	border-bottom:.5pt solid windowtext;
	border-left:.5pt solid windowtext;
	white-space:normal;}
.xl28
	{mso-style-parent:style0;
	font-size:12.0pt;
	font-family:"Times New Roman", serif;
	mso-font-charset:0;
	mso-number-format:"\@";
	text-align:center;
	vertical-align:middle;
	border-top:none;
	border-right:.5pt solid windowtext;
	border-bottom:.5pt solid windowtext;
	border-left:none;
	white-space:normal;}
.xl29
	{mso-style-parent:style0;
	font-size:12.0pt;
	font-family:"Times New Roman", serif;
	mso-font-charset:0;
	text-align:center;}
.xl30
	{mso-style-parent:style0;
	font-size:12.0pt;
	font-weight:700;
	font-family:"Times New Roman", serif;
	mso-font-charset:0;
	text-align:center;}
.xl31
	{mso-style-parent:style0;
	font-size:12.0pt;
	font-weight:700;
	text-decoration:underline;
	text-underline-style:single;
	font-family:"Times New Roman", serif;
	mso-font-charset:0;
	text-align:center;}
.xl32
	{mso-style-parent:style0;
	font-size:12.0pt;
	font-style:italic;
	font-family:"Times New Roman", serif;
	mso-font-charset:0;
	text-align:center;}
-->
</style>
<!--[if gte mso 9]><xml>
 <x:ExcelWorkbook>
  <x:ExcelWorksheets>
   <x:ExcelWorksheet>
    <x:Name>Sheet1</x:Name>
    <x:WorksheetOptions>
     <x:DefaultRowHeight>315</x:DefaultRowHeight>
     <x:Print>
      <x:ValidPrinterInfo/>
      <x:PaperSizeIndex>9</x:PaperSizeIndex>
      <x:Scale>44</x:Scale>
      <x:HorizontalResolution>600</x:HorizontalResolution>
      <x:VerticalResolution>600</x:VerticalResolution>
     </x:Print>
     <x:PageBreakZoom>60</x:PageBreakZoom>
     <x:Selected/>
     <x:Panes>
      <x:Pane>
       <x:Number>3</x:Number>
       <x:ActiveRow>7</x:ActiveRow>
       <x:ActiveCol>3</x:ActiveCol>
      </x:Pane>
     </x:Panes>
     <x:ProtectContents>False</x:ProtectContents>
     <x:ProtectObjects>False</x:ProtectObjects>
     <x:ProtectScenarios>False</x:ProtectScenarios>
    </x:WorksheetOptions>
   </x:ExcelWorksheet>
   <x:ExcelWorksheet>
    <x:Name>Sheet2</x:Name>
    <x:WorksheetOptions>
     <x:ProtectContents>False</x:ProtectContents>
     <x:ProtectObjects>False</x:ProtectObjects>
     <x:ProtectScenarios>False</x:ProtectScenarios>
    </x:WorksheetOptions>
   </x:ExcelWorksheet>
   <x:ExcelWorksheet>
    <x:Name>Sheet3</x:Name>
    <x:WorksheetOptions>
     <x:ProtectContents>False</x:ProtectContents>
     <x:ProtectObjects>False</x:ProtectObjects>
     <x:ProtectScenarios>False</x:ProtectScenarios>
    </x:WorksheetOptions>
   </x:ExcelWorksheet>
  </x:ExcelWorksheets>
  <x:WindowHeight>12240</x:WindowHeight>
  <x:WindowWidth>15315</x:WindowWidth>
  <x:WindowTopX>885</x:WindowTopX>
  <x:WindowTopY>-135</x:WindowTopY>
  <x:ProtectStructure>False</x:ProtectStructure>
  <x:ProtectWindows>False</x:ProtectWindows>
 </x:ExcelWorkbook>
 <x:ExcelName>
  <x:Name>Print_Area</x:Name>
  <x:SheetIndex>1</x:SheetIndex>
  <x:Formula>=Sheet1!$A$1:$J$9</x:Formula>
 </x:ExcelName>
</xml><![endif]-->
</head>

<body link=blue vlink=purple class=xl24>

<table x:str border=0 cellpadding=0 cellspacing=0 width=1531 style='border-collapse:
 collapse;table-layout:fixed;width:1150pt'>
 <col class=xl24 width=49 style='mso-width-source:userset;mso-width-alt:1792;
 width:37pt'>
 <col class=xl24 width=277 style='mso-width-source:userset;mso-width-alt:10130;
 width:208pt'>
 <col class=xl24 width=106 style='mso-width-source:userset;mso-width-alt:3876;
 width:80pt'>
 <col class=xl24 width=215 style='mso-width-source:userset;mso-width-alt:7862;
 width:161pt'>
 <col class=xl24 width=196 style='mso-width-source:userset;mso-width-alt:7168;
 width:147pt'>
 <col class=xl24 width=141 style='mso-width-source:userset;mso-width-alt:5156;
 width:106pt'>
 <col class=xl24 width=184 style='mso-width-source:userset;mso-width-alt:6729;
 width:138pt'>
 <col class=xl24 width=114 style='mso-width-source:userset;mso-width-alt:4169;
 width:86pt'>

 <col class=xl24 width=100 style='mso-width-source:userset;mso-width-alt:3657;
 width:75pt'>
 <col class=xl24 width=149 style='mso-width-source:userset;mso-width-alt:5449;
 width:112pt'>
 <col class=xl24 width=139 style='mso-width-source:userset;mso-width-alt:5083;
 width:104pt'>
 <col class=xl24 width=125 style='mso-width-source:userset;mso-width-alt:4571;
 width:94pt'>
 <col class=xl24 width=131 style='mso-width-source:userset;mso-width-alt:4790;
 width:98pt'>
 <tr height=21 style='height:15.75pt'>
  <td colspan=3 height=21 class=xl29 width=432 style='height:15.75pt;
  width:325pt'><a name="Print_Area"><?= mb_strtoupper($this->config->sys_info->unit,"utf-8") ?></td>
  <td class=xl24 width=215 style='width:161pt'></td>

  <td colspan=3 class=xl30 width=521 style='width:391pt'>CỘNG HÒA XÃ HỘI CHỦ
  NGHĨA VIỆT NAM</td>
  <td class=xl24 width=114 style='width:86pt'></td>
  <td class=xl24 width=100 style='width:75pt'></td>
  <td class=xl24 width=149 style='width:112pt'></td>
 </tr>
 <tr height=21 style='height:15.75pt'>
 <td colspan=3 height=21 class=xl30 style='height:15.75pt'> <?= mb_strtoupper($this->config->sys_info->company,"utf-8") ?></td>
 
  <td colspan=6 class=xl31>Ðộc lập - Tự do - Hạnh phúc</td>

  <td class=xl24></td>
 </tr>
 <tr height=21 style='height:15.75pt'>
  <td height=21 colspan=3 class=xl24 style='height:15.75pt;mso-ignore:colspan'></td>
  <td colspan=6 class=xl32><?=$this->config->sys_info->city?>, ngày <?=date("d")?> tháng <?=date("m")?> năm <?=date("Y")?></td>
  <td class=xl24></td>
 </tr>
 <tr height=21 style='height:15.75pt'>

  <td height=21 colspan=10 class=xl24 style='height:15.75pt;mso-ignore:colspan'></td>
 </tr>
 <tr height=21 style='height:15.75pt'>
  <td colspan=7 height=21 class=xl30 style='height:15.75pt'>BÁO CÁO TÌNH HÌNH
  XỬ LÝ CÔNG VIỆC</td>
  <td colspan=3 class=xl24 style='mso-ignore:colspan'></td>
 </tr>
 <tr height=21 style='height:15.75pt'>
  <td colspan=7 height=21 class=xl32 style='height:15.75pt'><?php echo $this->thu;?> NĂM <?=date("Y")?></td>

  <td colspan=3 class=xl24 style='mso-ignore:colspan'></td>
 </tr>
 <tr height=21 style='height:15.75pt'>
  <td height=21 colspan=10 class=xl24 style='height:15.75pt;mso-ignore:colspan'></td>
 </tr>
 <tr height=21 style='height:15.75pt'>
  <td height=21 class=xl25 width=49 style='height:15.75pt;width:37pt'>Stt</td>
  <td class=xl26 width=277 style='width:208pt'>Tên công việc</td>

  <td class=xl26 width=106 style='width:80pt'>Ngày tạo</td>
  <td class=xl26 width=215 style='width:161pt'>Người yêu cầu</td>
  <td class=xl26 width=196 style='width:147pt'>Người xử lý</td>
  <td class=xl26 width=141 style='width:106pt'>Hạn xử lý</td>
  <td class=xl26 width=184 style='width:138pt'>Trạng thái</td>
  <td colspan=3 class=xl24 style='mso-ignore:colspan'></td>

 </tr>
<?php
		foreach($this->data as $congviecitem){
			$stt++;
	?>
 <tr height=45 style='mso-height-source:userset;height:33.75pt'>
  <td height=45 class=xl27 width=49 style='height:33.75pt;width:37pt' x:num><?=$stt?></td>
  <td class=xl28 width=277 style='width:208pt'><?=htmlspecialchars($congviecitem['NAME'])?></td>
  <td class=xl28 width=106 style='width:80pt'><?=QLVBDHCommon::MysqlDateToVnDate($congviecitem['NGAYTAO'])?></td>
  <td class=xl28 width=215 style='width:161pt'><?=htmlspecialchars($congviecitem['NAMENGUOIYEUCAU'])?></td>
  <td class=xl28 width=196 style='width:147pt'><?=htmlspecialchars($congviecitem['NAMENGUOIXULY'])?></td>

  <td class=xl28 width=141 style='width:106pt'><?=QLVBDHCommon::createTextHanXuLy($congviecitem['HANXULY'])?></td>
  <td class=xl28 width=184 style='width:138pt'><?php
				if($congviecitem['IS_THEODOI']==1){
					echo "Lưu tham khảo";
				}else if($congviecitem['IS_FINISH']==0){
					echo "Đang xử lý";
					$tre = QLVBDHCommon::getTreHan($congviecitem['DATESEND'],$congviecitem['HANXULY']);
					echo QLVBDHCommon::trehantostr($tre);
				}else{
					echo "Đã xử lý";
				}
			?></td>
  <td colspan=3 class=xl24 style='mso-ignore:colspan'></td>
 </tr>
<?php } ?>
 <tr height=21 style='height:15.75pt'>
  <td height=21 colspan=10 class=xl24 style='height:15.75pt;mso-ignore:colspan'></td>
 </tr>

 <tr height=21 style='height:15.75pt'>
  <td colspan=3 height=21 class=xl30 style='height:15.75pt'>Người nhận hồ sơ</td>
  <td colspan=7 class=xl30>Người bàn giao hồ sơ</td>
 </tr>
 <tr height=21 style='height:15.75pt'>
  <td height=21 colspan=10 class=xl24 style='height:15.75pt;mso-ignore:colspan'></td>
 </tr>
 <tr height=21 style='height:15.75pt'>

  <td height=21 colspan=10 class=xl24 style='height:15.75pt;mso-ignore:colspan'></td>
 </tr>
 <tr height=21 style='height:15.75pt'>
  <td height=21 colspan=10 class=xl24 style='height:15.75pt;mso-ignore:colspan'></td>
 </tr>
 <tr height=21 style='height:15.75pt'>
  <td colspan=3 height=21 class=xl29 style='height:15.75pt'></td>
  <td colspan=7 class=xl29><?=Zend_Registry::get("auth")->getIdentity()->FULLNAME?></td>

 </tr>
 <![if supportMisalignedColumns]>
 <tr height=0 style='display:none'>
  <td width=49 style='width:37pt'></td>
  <td width=277 style='width:208pt'></td>
  <td width=106 style='width:80pt'></td>
  <td width=215 style='width:161pt'></td>
  <td width=196 style='width:147pt'></td>
  <td width=141 style='width:106pt'></td>

  <td width=184 style='width:138pt'></td>
  <td width=114 style='width:86pt'></td>
  <td width=100 style='width:75pt'></td>
  <td width=149 style='width:112pt'></td>
 </tr>
 <![endif]>
</table>

</body>

</html>

<script>print();</script>