<?php require_once('qtht/models/DepartmentsModel.php');
$data_departs = DepartmentsModel::getAll();
?>
<form name=frm method="POST" target="reportview">
	<div>
		<label><b>Ngày bắt đầu:</b></label>
		<?=QLVBDHCommon::calendar($this->fromdate,"fromdate","fromdate") ?>
		>>
		<?=QLVBDHCommon::calendar($this->todate,"todate","todate") ?>
	</div>
	<div class=clr></div>
	<div>
		<label><b>Tháng:</b></label>
		<input type="radio" name='sel_timedis' onclick="setvalueDateD('1/1','31/1')">1
		<?php 
		$year = QLVBDHCommon::getYear();
		$d = strtotime($year."-3-1") ;
		$d = $d - 86400;
		$str_cuoi2 =date('d/m',$d); 
		 ?>
		<input type="radio" name='sel_timedis' onclick="setvalueDateD('1/2','<?php echo $str_cuoi2 ?>')" >2
		<input type="radio" name='sel_timedis' onclick="setvalueDateD('1/3','31/3')">3
		<input type="radio" name='sel_timedis'onclick="setvalueDateD('1/4','30/4')" >4
		<input type="radio" name='sel_timedis'onclick="setvalueDateD('1/5','31/5')">5
		<input type="radio" name='sel_timedis' onclick="setvalueDateD('1/6','30/6')">6
		<input type="radio" name='sel_timedis'onclick="setvalueDateD('1/7','31/7')" >7
		<input type="radio" name='sel_timedis'onclick="setvalueDateD('1/8','31/8')" >8
		<input type="radio" name='sel_timedis'onclick="setvalueDateD('1/9','30/9')">9
		<input type="radio" name='sel_timedis'onclick="setvalueDateD('1/10','31/10')">10
		<input type="radio" name='sel_timedis'onclick="setvalueDateD('1/11','30/11')">11
		<input type="radio" name='sel_timedis'onclick="setvalueDateD('1/12','31/12')">12
	</div>
	<div class=clr></div>
	<div>
		<label><b>Quí:</b></label>
		<input type="radio" name='sel_timedis' onclick="setvalueDateD('1/1','31/3')">I
		<input type="radio" name='sel_timedis' onclick="setvalueDateD('1/4','30/6')">II
		<input type="radio" name='sel_timedis'onclick="setvalueDateD('1/7','30/9')">III
		<input type="radio" name='sel_timedis'onclick="setvalueDateD('1/10','31/12')">IV
	</div>
	<div class=clr></div>
	<div>
		<label><b>Năm:</b></label>
		<input type="radio" name='sel_timedis' onclick="setvalueDateD('1/1','31/12')">
	</div>
	<div class=clr></div>
	<br/>
	<div>
		<label><b>Chọn phòng ban:</b></label>
			<select name="sel_pb[]" id="sel_lvb" multiple="multiple" size=5 onchange="document.getElementById('ID_DEP').value = this.value;FillComboByComboExp1(this,document.getElementById('ID_U'),ARR_ID_U,arr_user);">
				<option value=0>[Tất cả phòng ban]</option>
				<?php 
					$user = Zend_Registry::get('auth')->getIdentity();
					DepartmentsModel::toComboNameWithSel($this->sel_pb);
				?>
			</select>
	</div>
        <div class=clr></div>
	<div>
		<label><b>Người xử lý:</b></label>
		 <?php 
		   echo QLVBDHCommon::writeSelectDepartmentUserWithSelreport('ID_DEP','ID_U')
		 ?>
	</div>
    <div class=clr></div>
	<input type=hidden id=h_isexel name=h_isexel value=0>	
        <br>
<input type="button" title="Hiển thị báo cáo" style="background: url(/images/hscv-input-bg.png) repeat-x;" 
onclick="
document.frm.target='reportview';
document.frm.h_isexel.value = 0;
document.frm.action='/report/XuLyCongviec/inputcongviecview';
document.frm.submit();
return false;" value="Hiển thị">

<input type="button" title="Xuất excel" style="background: url(/images/hscv-input-bg.png) repeat-x;"
onclick="
document.frm.target='reportview';
document.frm.h_isexel.value = 1;
document.frm.action='/report/XuLyCongviec/inputcongviececxel';
document.frm.submit();
return false;" value="Xuất ra Exel">

<input type="button" title="In báo cáo" style="background: url(/images/hscv-input-bg.png) repeat-x;" 
onclick="
document.frm.target='_blank';
document.frm.h_isexel.value = 0;
document.frm.action = '/report/XuLyCongviec/inputcongviececxel';
document.frm.submit();
return false;" value="In báo cáo">

</form>
<iframe style="overflow-x:visible" allowTransparency=true BORDER=0 scrolling=no FRAMEBORDER=no 
 id="reportview" name="reportview">
</iframe>
<script>
var arr_user = new Array();
document.getElementById('ID_DEP').style.display="none";
function setvalueDateD(value_from,value_to){
	document.frm.fromdate.value = value_from;
	document.frm.todate.value = value_to;
}
</script>