<?php require_once 'qtht/models/LoaiVanBanModel.php';?>
<?php if($this->xuat==1){?>
<html xmlns:o="urn:schemas-microsoft-com:office:office"
xmlns:x="urn:schemas-microsoft-com:office:excel"
xmlns="http://www.w3.org/TR/REC-html40">

<head>
<meta http-equiv=Content-Type content="text/html; charset=utf-8">
<meta name=ProgId content=Excel.Sheet>
<meta name=Generator content="Microsoft Excel 11">
<link rel=File-List href="baocaovanbanden-15_files/filelist.xml">
<link rel=Edit-Time-Data href="baocaovanbanden-15_files/editdata.mso">
<link rel=OLE-Object-Data href="baocaovanbanden-15_files/oledata.mso">
<!--[if gte mso 9]><xml>
 <o:DocumentProperties>
  <o:Author>nguyennd</o:Author>
  <o:LastAuthor>User</o:LastAuthor>
  <o:LastPrinted>2010-06-16T02:08:44Z</o:LastPrinted>
  <o:Created>2009-08-25T14:43:47Z</o:Created>
  <o:LastSaved>2010-06-16T02:09:03Z</o:LastSaved>
  <o:Company>Hewlett-Packard</o:Company>
  <o:Version>11.9999</o:Version>
 </o:DocumentProperties>
</xml><![endif]-->
<style>
<!--table
	{mso-displayed-decimal-separator:"\.";
	mso-displayed-thousand-separator:"\,";}
@page
	{margin:.2in .2in .2in .2in;
	mso-header-margin:.2in;
	mso-footer-margin:.2in;
	mso-page-orientation:landscape;
	mso-horizontal-page-align:center;}
tr
	{mso-height-source:auto;}
col
	{mso-width-source:auto;}
br
	{mso-data-placement:same-cell;}
.style0
	{mso-number-format:General;
	text-align:general;
	vertical-align:bottom;
	white-space:nowrap;
	mso-rotate:0;
	mso-background-source:auto;
	mso-pattern:auto;
	color:windowtext;
	font-size:10.0pt;
	font-weight:400;
	font-style:normal;
	text-decoration:none;
	font-family:Arial;
	mso-generic-font-family:auto;
	mso-font-charset:0;
	border:none;
	mso-protection:locked visible;
	mso-style-name:Normal;
	mso-style-id:0;}
td
	{mso-style-parent:style0;
	padding-top:1px;
	padding-right:1px;
	padding-left:1px;
	mso-ignore:padding;
	color:windowtext;
	font-size:10.0pt;
	font-weight:400;
	font-style:normal;
	text-decoration:none;
	font-family:Arial;
	mso-generic-font-family:auto;
	mso-font-charset:0;
	mso-number-format:General;
	text-align:general;
	vertical-align:bottom;
	border:none;
	mso-background-source:auto;
	mso-pattern:auto;
	mso-protection:locked visible;
	white-space:nowrap;
	mso-rotate:0;}
.xl24
	{mso-style-parent:style0;
	font-size:12.0pt;
	font-family:"Times New Roman", serif;
	mso-font-charset:0;}
.xl25
	{mso-style-parent:style0;
	font-size:12.0pt;
	font-weight:700;
	text-decoration:underline;
	text-underline-style:single;
	font-family:"Times New Roman", serif;
	mso-font-charset:0;}
.xl26
	{mso-style-parent:style0;
	font-size:12.0pt;
	font-style:italic;
	font-family:"Times New Roman", serif;
	mso-font-charset:0;}
.xl27
	{mso-style-parent:style0;
	font-size:12.0pt;
	font-weight:700;
	font-family:"Times New Roman", serif;
	mso-font-charset:0;
	text-align:center;
	vertical-align:top;
	border-top:none;
	border-right:.5pt solid windowtext;
	border-bottom:.5pt solid windowtext;
	border-left:none;
	background:silver;
	mso-pattern:auto none;
	white-space:normal;}
.xl28
	{mso-style-parent:style0;
	font-size:12.0pt;
	font-family:"Times New Roman", serif;
	mso-font-charset:0;
	mso-number-format:"\@";
	text-align:center;
	vertical-align:middle;
	border-top:none;
	border-right:.5pt solid windowtext;
	border-bottom:.5pt solid windowtext;
	border-left:.5pt solid windowtext;
	white-space:normal;}
.xl29
	{mso-style-parent:style0;
	font-size:12.0pt;
	font-family:"Times New Roman", serif;
	mso-font-charset:0;
	mso-number-format:"\@";
	text-align:center;
	vertical-align:middle;
	border-top:none;
	border-right:.5pt solid windowtext;
	border-bottom:.5pt solid windowtext;
	border-left:none;
	white-space:normal;}
.xl30
	{mso-style-parent:style0;
	font-size:13.0pt;
	font-weight:700;
	font-family:"Times New Roman", serif;
	mso-font-charset:0;
	text-align:center;
	vertical-align:middle;}
.xl31
	{mso-style-parent:style0;
	font-size:13.0pt;
	font-family:"Times New Roman", serif;
	mso-font-charset:0;
	text-align:center;
	vertical-align:middle;}
.xl32
	{mso-style-parent:style0;
	font-size:12.0pt;
	text-decoration:underline;
	text-underline-style:single;
	font-family:"Times New Roman", serif;
	mso-font-charset:0;
	text-align:center;
	vertical-align:middle;}
.xl33
	{mso-style-parent:style0;
	font-size:13.0pt;
	font-style:italic;
	font-family:"Times New Roman", serif;
	mso-font-charset:0;
	text-align:right;}
.xl34
	{mso-style-parent:style0;
	font-size:13.0pt;
	font-weight:700;
	font-family:"Times New Roman", serif;
	mso-font-charset:0;
	text-align:center;}
.xl35
	{mso-style-parent:style0;
	font-size:13.0pt;
	font-style:italic;
	font-family:"Times New Roman", serif;
	mso-font-charset:0;
	text-align:center;}
.xl355
	{mso-style-parent:style0;
	font-size:13.0pt;
	font-family:"Times New Roman", serif;
	mso-font-charset:0;
	text-align:center;}
.xl36
	{mso-style-parent:style0;
	font-size:12.0pt;
	font-weight:700;
	font-family:"Times New Roman", serif;
	mso-font-charset:0;
	text-align:center;
	vertical-align:middle;
	border-top:.5pt solid windowtext;
	border-right:.5pt solid windowtext;
	border-bottom:none;
	border-left:.5pt solid windowtext;
	background:silver;
	mso-pattern:auto none;
	white-space:normal;}
.xl37
	{mso-style-parent:style0;
	font-size:12.0pt;
	font-weight:700;
	font-family:"Times New Roman", serif;
	mso-font-charset:0;
	text-align:center;
	vertical-align:middle;
	border-top:none;
	border-right:.5pt solid windowtext;
	border-bottom:.5pt solid windowtext;
	border-left:.5pt solid windowtext;
	background:silver;
	mso-pattern:auto none;
	white-space:normal;}
.xl38
	{mso-style-parent:style0;
	font-size:12.0pt;
	font-weight:700;
	font-family:"Times New Roman", serif;
	mso-font-charset:0;
	text-align:center;
	vertical-align:middle;
	border-top:.5pt solid windowtext;
	border-right:none;
	border-bottom:.5pt solid windowtext;
	border-left:.5pt solid windowtext;
	background:silver;
	mso-pattern:auto none;}
.xl39
	{mso-style-parent:style0;
	font-size:12.0pt;
	font-weight:700;
	font-family:"Times New Roman", serif;
	mso-font-charset:0;
	text-align:center;
	vertical-align:middle;
	border-top:.5pt solid windowtext;
	border-right:.5pt solid windowtext;
	border-bottom:.5pt solid windowtext;
	border-left:none;
	background:silver;
	mso-pattern:auto none;}
-->
</style>
<!--[if gte mso 9]><xml>
 <x:ExcelWorkbook>
  <x:ExcelWorksheets>
   <x:ExcelWorksheet>
    <x:Name>Sheet1</x:Name>
    <x:WorksheetOptions>
     <x:DefaultRowHeight>315</x:DefaultRowHeight>
     <x:Print>
      <x:ValidPrinterInfo/>
      <x:PaperSizeIndex>9</x:PaperSizeIndex>
      <x:Scale>80</x:Scale>
      <x:HorizontalResolution>600</x:HorizontalResolution>
      <x:VerticalResolution>600</x:VerticalResolution>
     </x:Print>
     <x:PageBreakZoom>60</x:PageBreakZoom>
     <x:Selected/>
     <x:Panes>
      <x:Pane>
       <x:Number>3</x:Number>
       <x:ActiveRow>9</x:ActiveRow>
      </x:Pane>
     </x:Panes>
     <x:ProtectContents>False</x:ProtectContents>
     <x:ProtectObjects>False</x:ProtectObjects>
     <x:ProtectScenarios>False</x:ProtectScenarios>
    </x:WorksheetOptions>
    <x:PageBreaks>
     <x:ColBreaks>
      <x:ColBreak>
       <x:Column>9</x:Column>
      </x:ColBreak>
     </x:ColBreaks>
    </x:PageBreaks>
   </x:ExcelWorksheet>
   <x:ExcelWorksheet>
    <x:Name>Sheet2</x:Name>
    <x:WorksheetOptions>
     <x:ProtectContents>False</x:ProtectContents>
     <x:ProtectObjects>False</x:ProtectObjects>
     <x:ProtectScenarios>False</x:ProtectScenarios>
    </x:WorksheetOptions>
   </x:ExcelWorksheet>
   <x:ExcelWorksheet>
    <x:Name>Sheet3</x:Name>
    <x:WorksheetOptions>
     <x:ProtectContents>False</x:ProtectContents>
     <x:ProtectObjects>False</x:ProtectObjects>
     <x:ProtectScenarios>False</x:ProtectScenarios>
    </x:WorksheetOptions>
   </x:ExcelWorksheet>
  </x:ExcelWorksheets>
  <x:WindowHeight>12240</x:WindowHeight>
  <x:WindowWidth>15315</x:WindowWidth>
  <x:WindowTopX>885</x:WindowTopX>
  <x:WindowTopY>-135</x:WindowTopY>
  <x:ProtectStructure>False</x:ProtectStructure>
  <x:ProtectWindows>False</x:ProtectWindows>
 </x:ExcelWorkbook>
</xml><![endif]-->

</head>

<body link=blue vlink=purple class=xl24>

<table x:str border=0 cellpadding=0 cellspacing=0 width=1283 style='border-collapse:
 collapse;table-layout:fixed;width:963pt'>
 <col class=xl24 width=55 style='mso-width-source:userset;mso-width-alt:2011;
 width:41pt'>
 <col class=xl24 width=70 style='mso-width-source:userset;mso-width-alt:2560;
 width:53pt'>
 <col class=xl24 width=170 style='mso-width-source:userset;mso-width-alt:6217;
 width:128pt'>
 <col class=xl24 width=162 style='mso-width-source:userset;mso-width-alt:5924;
 width:122pt'>
 <col class=xl24 width=76 style='mso-width-source:userset;mso-width-alt:2779;
 width:57pt'>
 <col class=xl24 width=81 style='mso-width-source:userset;mso-width-alt:2962;
 width:61pt'>
 <col class=xl24 width=275 style='mso-width-source:userset;mso-width-alt:10057;
 width:206pt'>
 <col class=xl24 width=147 style='mso-width-source:userset;mso-width-alt:5376;
 width:110pt'>

 <col class=xl24 width=108 style='mso-width-source:userset;mso-width-alt:3949;
 width:81pt'>
 <col class=xl24 width=139 style='mso-width-source:userset;mso-width-alt:5083;
 width:104pt'>
 <col class=xl24 width=125 style='mso-width-source:userset;mso-width-alt:4571;
 width:94pt'>
 <tr height=25 style='mso-height-source:userset;height:18.75pt'>
  <td height=25 class=xl24 width=55 style='height:18.75pt;width:41pt'></td>
  <td colspan=3 class=xl30 width=402 style='width:303pt'><?= mb_strtoupper($this->config->sys_info->unit,"utf-8") ?></td>
  <td colspan=5 class=xl31 width=687 style='width:515pt'>CỘNG HÒA XÃ HỘI CHỦ
  NGHĨA VIỆT NAM</td>
  <td class=xl24 width=139 style='width:104pt'></td>

 </tr>
 <tr height=25 style='mso-height-source:userset;height:18.75pt'>
  <td height=25 class=xl24 style='height:18.75pt'></td>
  <td colspan=3 class=xl31><?= mb_strtoupper($this->config->sys_info->company,"utf-8") ?><span style='mso-spacerun:yes'> </span></td>
  <td colspan=5 class=xl32>Ðộc lập - Tự do - Hạnh phúc</td>
  <td class=xl25></td>
 </tr>

 <tr height=22 style='height:16.5pt'>
  <td height=22 colspan=3 class=xl24 style='height:16.5pt;mso-ignore:colspan'></td>
  <td class=xl26></td>
  <td colspan=5 class=xl33><?=$this->config->sys_info->city?>, ngày <?=date("d")?> tháng <?=date("m")?> năm <?=date("Y")?></td>
  <td class=xl26></td>
 </tr>
 <tr height=21 style='height:15.75pt'>
  <td height=21 colspan=10 class=xl24 style='height:15.75pt;mso-ignore:colspan'></td>

 </tr>
 <tr height=22 style='height:16.5pt'>
  <td height=22 class=xl24 style='height:16.5pt'></td>
  <td colspan=8 class=xl34>BÁO CÁO VĂN BẢN ĐẾN</td>
  <td class=xl24></td>
 </tr>
 <?php 
	if(count($this->id_lvbs) > 0) { 
	$lvb = htmlspecialchars(LoaiVanBanModel::getArrNameById($this->id_lvbs));
?>
 <tr height=22 style='height:16.5pt'>
  <td height=22 class=xl24 style='height:16.5pt'></td>
  <td colspan=8 class=xl355>Loại Văn Bản: <?= $this->id_lvbs > 0 ? $lvb : 'Tất cả các loại';?></td>
  <td class=xl24></td>
 </tr>
 <?php } ?>
 <tr height=22 style='height:16.5pt'>
  <td height=22 class=xl24 style='height:16.5pt'></td>

  <td colspan=8 class=xl35><?php echo $this->thu;?> năm <?=QLVBDHCommon::getYear();?></td>
  <td class=xl24></td>
 </tr>
 <tr height=21 style='height:15.75pt'>
  <td height=21 colspan=10 class=xl24 style='height:15.75pt;mso-ignore:colspan'></td>
 </tr>
 <tr height=21 style='height:15.75pt'>
  <td rowspan=2 height=42 class=xl36 width=55 style='border-bottom:.5pt solid black;
  height:31.5pt;width:41pt'>Stt</td>
<?php if(count($this->soden) >0) {?>
  <td rowspan=2 class=xl36 width=70 style='border-bottom:.5pt solid black;
  width:53pt'>Số đến</td>
    <?php } ?>
  <?php if(count($this->ngayden) >0) {?>
  <td rowspan=2 class=xl36 width=170 style='border-bottom:.5pt solid black;
  width:128pt'>Ngày đến</td>
    <?php } ?>
  <?php if(count($this->coquanbh) >0) {?>
  <td rowspan=2 class=xl36 width=162 style='border-bottom:.5pt solid black;
  width:122pt'>Cơ quan ban hành</td>
    <?php } ?>
  <td colspan=2 class=xl38 style='border-right:.5pt solid black;border-left:
  none'>Văn bản đến</td>
  <?php if(count($this->trichyeund) >0) {?>
  <td rowspan=2 class=xl36 width=275 style='border-bottom:.5pt solid black;
  width:206pt'>Trích yếu nội dung</td>
    <?php } ?>
  <?php if(count($this->chuyenchoai) >0) {?>
  <td rowspan=2 class=xl36 width=147 style='border-bottom:.5pt solid black;
  width:110pt'>Chuyển cho ai</td>
    <?php } ?>
  <?php if(count($this->ketqua) >0) {?>
  <td rowspan=2 class=xl36 width=108 style='border-bottom:.5pt solid black;
  width:81pt' x:str="Kết quả ">Kết quả<span style='mso-spacerun:yes'> </span></td>
  <td rowspan=2 class=xl36 width=275 style='border-bottom:.5pt solid black;
  width:206pt'>Ghi chú</td>
    <?php } ?>
  <td class=xl24></td>
 </tr>
 <tr height=21 style='height:15.75pt'>
  <td height=21 class=xl27 width=76 style='height:15.75pt;width:57pt'>Số</td>
  <td class=xl27 width=81 style='width:61pt' x:str="Ngày ">Ngày<span
  style='mso-spacerun:yes'> </span></td>

  <td class=xl24></td>
 </tr>
   <?php $stt=1;$ten= VanbandenreportModel::getNguoiXuly();foreach($this->data as $row){ ?>
 <tr height=84 style='height:63.0pt'>

  <td height=84 class=xl28 width=55 style='height:63.0pt;width:41pt'><?=$stt?></td>
 <?php if(count($this->soden) >0) {?>
  <td class=xl28 width=70 style='border-left:none;width:53pt'><?=$row["SODEN"]?></td>
  <?php } ?>
  <?php if(count($this->ngayden) >0) {?>
  <td class=xl29 width=170 style='width:128pt'><?=QLVBDHCommon::MysqlDateToVnDateNoneZero($row["NGAYDEN"])?></td>
  <?php } ?>
  <?php if(count($this->coquanbh) >0) {?>
  <td class=xl29 width=162 style='width:122pt'><?=$row["COQUANBANHANH_TEXT"]?></td>
  <?php } ?>
  <td class=xl29 width=76 style='width:57pt'><?=$row["SOKYHIEU"]?></td>
  <td class=xl29 width=81 style='width:61pt'><?=QLVBDHCommon::MysqlDateToVnDateNoneZero($row["NGAYBANHANH"])?></td>
   <?php if(count($this->trichyeund) >0) {?>
  <td class=xl29 width=275 style='width:206pt'><?=$row["TRICHYEU"]?></td>
  <?php } ?>
  <?php if(count($this->chuyenchoai) >0) {?>
  <td class=xl29 width=147 style='width:110pt'><?php 
 	if($row["IS_KHONGXULY"] == 1)
 		echo "Văn bản không xử lý";
 	else{ 	     
	      $arr_u_xl = explode(",",$row["NAME_U"] );			 
		  foreach($arr_u_xl as $id_user_xl){
		    if((int)$id_user_xl){
		    echo $ten[(int)$id_user_xl]."<br/>"; 
			  }
		  }
		 $arr_u_ph = explode(",",$row["NAME_PH"] );			 
		  foreach($arr_u_ph as $id_user_ph){
		    if((int)$id_user_xl){
		    echo $ten[(int)$id_user_ph]."<br/>"; 
			}
		  }
		 $arr_u_db = explode(",",$row["NAME_DB"] );			 
		  foreach($arr_u_db as $id_user_db){
		  if((int)$id_user_xl){
		    echo $ten[(int)$id_user_db]."<br/>"; 
			}
		  }
	} 
		 ?>
    </td>
	<?php } ?>
	<?php if(count($this->ketqua) >0) {?>
  <td class=xl29 width=108 style='width:81pt'><?php 
	if($row["ID_HSCV"] != ""){		
		$arr_file_maso = explode(",",$row["FILE_MASO"]);	
         foreach($arr_file_maso as $arr_file_maso_item){
		    if($arr_file_maso_item['MASO']){
		echo "<a href='/hscv/File/download?year=".$row['NAM']."&maso=".$arr_file_maso_item['MASO']."'>".$row["SOKYHIEU"]."<br/>";	
		        }else{
			echo $row["KQ_DEXUAT"] ;
			}	
		}				
		}
	?></td>
  <?php } ?>
  <td class=xl29 width=275 style='width:206pt'><?=$row["GHICHU"]?></td>
  <td class=xl24></td>
 </tr>
  <?php $stt++;} ?> 
 <![if supportMisalignedColumns]>
 <tr height=0 style='display:none'>
  <td width=55 style='width:41pt'></td>
  <td width=70 style='width:53pt'></td>
  <td width=170 style='width:128pt'></td>

  <td width=162 style='width:122pt'></td>
  <td width=76 style='width:57pt'></td>
  <td width=81 style='width:61pt'></td>
  <td width=275 style='width:206pt'></td>
  <td width=147 style='width:110pt'></td>
  <td width=108 style='width:81pt'></td>
  <td width=139 style='width:104pt'></td>
 </tr>
 <![endif]>

</table>

</body>

</html>

<?php }else{ ?>
<html xmlns:o="urn:schemas-microsoft-com:office:office"
xmlns:x="urn:schemas-microsoft-com:office:excel"
xmlns="http://www.w3.org/TR/REC-html40">

<head>
<meta http-equiv=Content-Type content="text/html; charset=utf-8">
<meta name=ProgId content=Excel.Sheet>
<meta name=Generator content="Microsoft Excel 11">
<link rel=File-List href="baocaovanbanden-15_files/filelist.xml">
<link rel=Edit-Time-Data href="baocaovanbanden-15_files/editdata.mso">
<link rel=OLE-Object-Data href="baocaovanbanden-15_files/oledata.mso">
<!--[if gte mso 9]><xml>
 <o:DocumentProperties>
  <o:Author>nguyennd</o:Author>
  <o:LastAuthor>User</o:LastAuthor>
  <o:LastPrinted>2010-06-16T02:08:44Z</o:LastPrinted>
  <o:Created>2009-08-25T14:43:47Z</o:Created>
  <o:LastSaved>2010-06-16T02:09:03Z</o:LastSaved>
  <o:Company>Hewlett-Packard</o:Company>
  <o:Version>11.9999</o:Version>
 </o:DocumentProperties>
</xml><![endif]-->
<style>
<!--table
	{mso-displayed-decimal-separator:"\.";
	mso-displayed-thousand-separator:"\,";}
@page
	{margin:.2in .2in .2in .2in;
	mso-header-margin:.2in;
	mso-footer-margin:.2in;
	mso-page-orientation:Portrait;
	mso-horizontal-page-align:center;}
tr
	{mso-height-source:auto;}
col
	{mso-width-source:auto;}
br
	{mso-data-placement:same-cell;}
.style0
	{mso-number-format:General;
	text-align:general;
	vertical-align:bottom;
	white-space:nowrap;
	mso-rotate:0;
	mso-background-source:auto;
	mso-pattern:auto;
	color:windowtext;
	font-size:10.0pt;
	font-weight:400;
	font-style:normal;
	text-decoration:none;
	font-family:Arial;
	mso-generic-font-family:auto;
	mso-font-charset:0;
	border:none;
	mso-protection:locked visible;
	mso-style-name:Normal;
	mso-style-id:0;}
td
	{mso-style-parent:style0;
	padding-top:1px;
	padding-right:1px;
	padding-left:1px;
	mso-ignore:padding;
	color:windowtext;
	font-size:10.0pt;
	font-weight:400;
	font-style:normal;
	text-decoration:none;
	font-family:Arial;
	mso-generic-font-family:auto;
	mso-font-charset:0;
	mso-number-format:General;
	text-align:general;
	vertical-align:bottom;
	border:none;
	mso-background-source:auto;
	mso-pattern:auto;
	mso-protection:locked visible;
	white-space:nowrap;
	mso-rotate:0;}
.xl24
	{mso-style-parent:style0;
	font-size:12.0pt;
	font-family:"Times New Roman", serif;
	mso-font-charset:0;}
.xl25
	{mso-style-parent:style0;
	font-size:12.0pt;
	font-weight:700;
	text-decoration:underline;
	text-underline-style:single;
	font-family:"Times New Roman", serif;
	mso-font-charset:0;}
.xl26
	{mso-style-parent:style0;
	font-size:12.0pt;
	font-style:italic;
	font-family:"Times New Roman", serif;
	mso-font-charset:0;}
.xl27
	{mso-style-parent:style0;
	font-size:12.0pt;
	font-weight:700;
	font-family:"Times New Roman", serif;
	mso-font-charset:0;
	text-align:center;
	vertical-align:top;
	border-top:none;
	border-right:.5pt solid windowtext;
	border-bottom:.5pt solid windowtext;
	border-left:none;
	background:silver;
	mso-pattern:auto none;
	white-space:normal;}
.xl28
	{mso-style-parent:style0;
	font-size:12.0pt;
	font-family:"Times New Roman", serif;
	mso-font-charset:0;
	mso-number-format:"\@";
	text-align:center;
	vertical-align:middle;
	border-top:none;
	border-right:.5pt solid windowtext;
	border-bottom:.5pt solid windowtext;
	border-left:.5pt solid windowtext;
	white-space:normal;}
.xl29
	{mso-style-parent:style0;
	font-size:12.0pt;
	font-family:"Times New Roman", serif;
	mso-font-charset:0;
	mso-number-format:"\@";
	text-align:center;
	vertical-align:middle;
	border-top:none;
	border-right:.5pt solid windowtext;
	border-bottom:.5pt solid windowtext;
	border-left:none;
	white-space:normal;}
.xl30
	{mso-style-parent:style0;
	font-size:13.0pt;
	font-weight:700;
	font-family:"Times New Roman", serif;
	mso-font-charset:0;
	text-align:center;
	vertical-align:middle;}
.xl31
	{mso-style-parent:style0;
	font-size:13.0pt;
	font-family:"Times New Roman", serif;
	mso-font-charset:0;
	text-align:center;
	vertical-align:middle;}
.xl32
	{mso-style-parent:style0;
	font-size:12.0pt;
	text-decoration:underline;
	text-underline-style:single;
	font-family:"Times New Roman", serif;
	mso-font-charset:0;
	text-align:center;
	vertical-align:middle;}
.xl33
	{mso-style-parent:style0;
	font-size:13.0pt;
	font-style:italic;
	font-family:"Times New Roman", serif;
	mso-font-charset:0;
	text-align:right;}
.xl34
	{mso-style-parent:style0;
	font-size:13.0pt;
	font-weight:700;
	font-family:"Times New Roman", serif;
	mso-font-charset:0;
	text-align:center;}
.xl35
	{mso-style-parent:style0;
	font-size:13.0pt;
	font-style:italic;
	font-family:"Times New Roman", serif;
	mso-font-charset:0;
	text-align:center;}
.xl355
	{mso-style-parent:style0;
	font-size:13.0pt;
	font-family:"Times New Roman", serif;
	mso-font-charset:0;
	text-align:center;}
.xl36
	{mso-style-parent:style0;
	font-size:12.0pt;
	font-weight:700;
	font-family:"Times New Roman", serif;
	mso-font-charset:0;
	text-align:center;
	vertical-align:middle;
	border-top:.5pt solid windowtext;
	border-right:.5pt solid windowtext;
	border-bottom:none;
	border-left:.5pt solid windowtext;
	background:silver;
	mso-pattern:auto none;
	white-space:normal;}
.xl37
	{mso-style-parent:style0;
	font-size:12.0pt;
	font-weight:700;
	font-family:"Times New Roman", serif;
	mso-font-charset:0;
	text-align:center;
	vertical-align:middle;
	border-top:none;
	border-right:.5pt solid windowtext;
	border-bottom:.5pt solid windowtext;
	border-left:.5pt solid windowtext;
	background:silver;
	mso-pattern:auto none;
	white-space:normal;}
.xl38
	{mso-style-parent:style0;
	font-size:12.0pt;
	font-weight:700;
	font-family:"Times New Roman", serif;
	mso-font-charset:0;
	text-align:center;
	vertical-align:middle;
	border-top:.5pt solid windowtext;
	border-right:none;
	border-bottom:.5pt solid windowtext;
	border-left:.5pt solid windowtext;
	background:silver;
	mso-pattern:auto none;}
.xl39
	{mso-style-parent:style0;
	font-size:12.0pt;
	font-weight:700;
	font-family:"Times New Roman", serif;
	mso-font-charset:0;
	text-align:center;
	vertical-align:middle;
	border-top:.5pt solid windowtext;
	border-right:.5pt solid windowtext;
	border-bottom:.5pt solid windowtext;
	border-left:none;
	background:silver;
	mso-pattern:auto none;}
-->
</style>
<!--[if gte mso 9]><xml>
 <x:ExcelWorkbook>
  <x:ExcelWorksheets>
   <x:ExcelWorksheet>
    <x:Name>Sheet1</x:Name>
    <x:WorksheetOptions>
     <x:DefaultRowHeight>315</x:DefaultRowHeight>
     <x:Print>
      <x:ValidPrinterInfo/>
      <x:PaperSizeIndex>9</x:PaperSizeIndex>
      <x:Scale>60</x:Scale>
      <x:HorizontalResolution>600</x:HorizontalResolution>
      <x:VerticalResolution>600</x:VerticalResolution>
     </x:Print>
     <x:PageBreakZoom>60</x:PageBreakZoom>
     <x:Selected/>
     <x:Panes>
      <x:Pane>
       <x:Number>3</x:Number>
       <x:ActiveRow>9</x:ActiveRow>
      </x:Pane>
     </x:Panes>
     <x:ProtectContents>False</x:ProtectContents>
     <x:ProtectObjects>False</x:ProtectObjects>
     <x:ProtectScenarios>False</x:ProtectScenarios>
    </x:WorksheetOptions>
    <x:PageBreaks>
     <x:ColBreaks>
      <x:ColBreak>
       <x:Column>9</x:Column>
      </x:ColBreak>
     </x:ColBreaks>
    </x:PageBreaks>
   </x:ExcelWorksheet>
   <x:ExcelWorksheet>
    <x:Name>Sheet2</x:Name>
    <x:WorksheetOptions>
     <x:ProtectContents>False</x:ProtectContents>
     <x:ProtectObjects>False</x:ProtectObjects>
     <x:ProtectScenarios>False</x:ProtectScenarios>
    </x:WorksheetOptions>
   </x:ExcelWorksheet>
   <x:ExcelWorksheet>
    <x:Name>Sheet3</x:Name>
    <x:WorksheetOptions>
     <x:ProtectContents>False</x:ProtectContents>
     <x:ProtectObjects>False</x:ProtectObjects>
     <x:ProtectScenarios>False</x:ProtectScenarios>
    </x:WorksheetOptions>
   </x:ExcelWorksheet>
  </x:ExcelWorksheets>
  <x:WindowHeight>12240</x:WindowHeight>
  <x:WindowWidth>15315</x:WindowWidth>
  <x:WindowTopX>885</x:WindowTopX>
  <x:WindowTopY>-135</x:WindowTopY>
  <x:ProtectStructure>False</x:ProtectStructure>
  <x:ProtectWindows>False</x:ProtectWindows>
 </x:ExcelWorkbook>
</xml><![endif]-->


</head>

<body link=blue vlink=purple class=xl24>

<table x:str border=0 cellpadding=0 cellspacing=0 width=1283 style='border-collapse:
 collapse;table-layout:fixed;width:963pt'>
 <col class=xl24 width=55 style='mso-width-source:userset;mso-width-alt:2011;
 width:41pt'>
 <col class=xl24 width=70 style='mso-width-source:userset;mso-width-alt:2560;
 width:53pt'>
 <col class=xl24 width=170 style='mso-width-source:userset;mso-width-alt:6217;
 width:128pt'>
 <col class=xl24 width=162 style='mso-width-source:userset;mso-width-alt:5924;
 width:122pt'>
 <col class=xl24 width=76 style='mso-width-source:userset;mso-width-alt:2779;
 width:57pt'>
 <col class=xl24 width=81 style='mso-width-source:userset;mso-width-alt:2962;
 width:61pt'>
 <col class=xl24 width=275 style='mso-width-source:userset;mso-width-alt:10057;
 width:206pt'>
 <col class=xl24 width=147 style='mso-width-source:userset;mso-width-alt:5376;
 width:110pt'>

 <col class=xl24 width=108 style='mso-width-source:userset;mso-width-alt:3949;
 width:81pt'>
 <col class=xl24 width=139 style='mso-width-source:userset;mso-width-alt:5083;
 width:104pt'>
 <col class=xl24 width=125 style='mso-width-source:userset;mso-width-alt:4571;
 width:94pt'>
 <tr height=25 style='mso-height-source:userset;height:18.75pt'>
  <td height=25 class=xl24 width=55 style='height:18.75pt;width:41pt'></td>
  <td colspan=3 class=xl30 width=402 style='width:303pt'><?= mb_strtoupper($this->config->sys_info->unit,"utf-8") ?></td>
  <td colspan=5 class=xl31 width=687 style='width:515pt'>CỘNG HÒA XÃ HỘI CHỦ
  NGHĨA VIỆT NAM</td>
  <td class=xl24 width=139 style='width:104pt'></td>

 </tr>
 <tr height=25 style='mso-height-source:userset;height:18.75pt'>
  <td height=25 class=xl24 style='height:18.75pt'></td>
  <td colspan=3 class=xl31><?= mb_strtoupper($this->config->sys_info->company,"utf-8") ?><span style='mso-spacerun:yes'> </span></td>
  <td colspan=5 class=xl32>Ðộc lập - Tự do - Hạnh phúc</td>
  <td class=xl25></td>
 </tr>

 <tr height=22 style='height:16.5pt'>
  <td height=22 colspan=3 class=xl24 style='height:16.5pt;mso-ignore:colspan'></td>
  <td class=xl26></td>
  <td colspan=5 class=xl33><?=$this->config->sys_info->city?>, ngày <?=date("d")?> tháng <?=date("m")?> năm <?=date("Y")?></td>
  <td class=xl26></td>
 </tr>
 <tr height=21 style='height:15.75pt'>
  <td height=21 colspan=10 class=xl24 style='height:15.75pt;mso-ignore:colspan'></td>

 </tr>
 <tr height=22 style='height:16.5pt'>
  <td height=22 class=xl24 style='height:16.5pt'></td>
  <td colspan=8 class=xl34>BÁO CÁO VĂN BẢN ĐẾN</td>
  <td class=xl24></td>
 </tr>
 <?php 
	if(count($this->id_lvbs) > 0) { 
	$lvb = htmlspecialchars(LoaiVanBanModel::getArrNameById($this->id_lvbs));
?>
 <tr height=22 style='height:16.5pt'>
  <td height=22 class=xl24 style='height:16.5pt'></td>
  <td colspan=8 class=xl355>Loại Văn Bản: <?= $this->id_lvbs > 0 ? $lvb : 'Tất cả các loại';?></td>
  <td class=xl24></td>
 </tr>
 <?php } ?>
 <tr height=22 style='height:16.5pt'>
  <td height=22 class=xl24 style='height:16.5pt'></td>

  <td colspan=8 class=xl35><?php echo $this->thu;?> năm <?=QLVBDHCommon::getYear();?></td>
  <td class=xl24></td>
 </tr>
 <tr height=21 style='height:15.75pt'>
  <td height=21 colspan=10 class=xl24 style='height:15.75pt;mso-ignore:colspan'></td>
 </tr>
 <tr height=21 style='height:15.75pt'>
  <td rowspan=2 height=42 class=xl36 width=55 style='border-bottom:.5pt solid black;
  height:31.5pt;width:41pt'>Stt</td>
<?php if(count($this->soden) >0) {?>
  <td rowspan=2 class=xl36 width=70 style='border-bottom:.5pt solid black;
  width:53pt'>Số đến</td>
    <?php } ?>
  <?php if(count($this->ngayden) >0) {?>
  <td rowspan=2 class=xl36 width=170 style='border-bottom:.5pt solid black;
  width:128pt'>Ngày đến</td>
    <?php } ?>
  <?php if(count($this->coquanbh) >0) {?>
  <td rowspan=2 class=xl36 width=162 style='border-bottom:.5pt solid black;
  width:122pt'>Cơ quan ban hành</td>
    <?php } ?>
  <td colspan=2 class=xl38 style='border-right:.5pt solid black;border-left:
  none'>Văn bản đến</td>
  <?php if(count($this->trichyeund) >0) {?>
  <td rowspan=2 class=xl36 width=275 style='border-bottom:.5pt solid black;
  width:206pt'>Trích yếu nội dung</td>
    <?php } ?>
  <?php if(count($this->chuyenchoai) >0) {?>
  <td rowspan=2 class=xl36 width=147 style='border-bottom:.5pt solid black;
  width:110pt'>Chuyển cho ai</td>
    <?php } ?>
  <?php if(count($this->ketqua) >0) {?>
  <td rowspan=2 class=xl36 width=108 style='border-bottom:.5pt solid black;
  width:81pt' x:str="Kết quả ">Kết quả<span style='mso-spacerun:yes'> </span></td>
   <td rowspan=2 class=xl36 width=275 style='border-bottom:.5pt solid black;
  width:206pt'>Ghi chú</td>
    <?php } ?>
  <td class=xl24></td>
 </tr>
 <tr height=21 style='height:15.75pt'>
  <td height=21 class=xl27 width=76 style='height:15.75pt;width:57pt'>Số</td>
  <td class=xl27 width=81 style='width:61pt' x:str="Ngày ">Ngày<span
  style='mso-spacerun:yes'> </span></td>

  <td class=xl24></td>
 </tr>
   <?php 
   
   $stt=1;foreach($this->data as $row){ ?>
 <tr height=84 style='height:63.0pt'>
     
  <td height=84 class=xl28 width=55 style='height:63.0pt;width:41pt'><?=$stt?></td>
 <?php if(count($this->soden) >0) {?>
  <td class=xl28 width=70 style='border-left:none;width:53pt'><?=$row["SODEN"]?></td>
  <?php } ?>
  <?php if(count($this->ngayden) >0) {?>
  <td class=xl29 width=170 style='width:128pt'><?=QLVBDHCommon::MysqlDateToVnDateNoneZero($row["NGAYDEN"])?></td>
  <?php } ?>
  <?php if(count($this->coquanbh) >0) {?>
  <td class=xl29 width=162 style='width:122pt'><?=$row["COQUANBANHANH_TEXT"]?></td>
  <?php } ?>
  <td class=xl29 width=76 style='width:57pt'><?=$row["SOKYHIEU"]?></td>
  <td class=xl29 width=81 style='width:61pt'><?=QLVBDHCommon::MysqlDateToVnDateNoneZero($row["NGAYBANHANH"])?></td>
   <?php if(count($this->trichyeund) >0) {?>
  <td class=xl29 width=275 style='width:206pt'><?=$row["TRICHYEU"]?></td>
  <?php } ?>
  <?php if(count($this->chuyenchoai) >0) {?>
  <td class=xl29 width=147 style='width:110pt'><?php 
 	if($row["IS_KHONGXULY"] == 1)
 		echo "Văn bản không xử lý";
 	else{
 		
		//$idhscvs = VanbandenreportModel::getHscvsByIdVbd($row["ID_VBD"]);
		
		//foreach($idhscvs as $id_hs) - chỗ bị lỗi
//		if($row["ID_HSCV"] != ""){                        
//			echo VanbandenreportModel::getNguoiXulyFromVban($row["ID_HSCV"]);
//			}
                        
                        //lấy từ xuất ngang
                        $ten= VanbandenreportModel::getNguoiXuly();
                        $arr_u_xl = explode(",",$row["NAME_U"] );			 
		  foreach($arr_u_xl as $id_user_xl){
		    if((int)$id_user_xl){
		    echo $ten[(int)$id_user_xl]."<br/>"; 
			  }
		  }
		 $arr_u_ph = explode(",",$row["NAME_PH"] );			 
		  foreach($arr_u_ph as $id_user_ph){
		    if((int)$id_user_xl){
		    echo $ten[(int)$id_user_ph]."<br/>"; 
			}
		  }
		 $arr_u_db = explode(",",$row["NAME_DB"] );			 
		  foreach($arr_u_db as $id_user_db){
		  if((int)$id_user_xl){
		    echo $ten[(int)$id_user_db]."<br/>"; 
			}
		  }
                        
	} ?>
    </td>
	<?php } ?>
	<?php if(count($this->ketqua) >0) {?>
  <td class=xl29 width=108 style='width:81pt'><?php 
 	if($row["ID_HSCV"] != ""){
		
		$list_vbdi = Ad_XulyvanbandenModel::getListVanbandiByIdHSCV($row["ID_HSCV"]);
		if(count($list_vbdi) > 0){
			foreach($list_vbdi as $vbdi){
				echo $vbdi["SOKYHIEU"]."<br/>";
			}
		}else{
			echo $row["KQ_DEXUAT"] ;
		}
		
	} ?></td>
  <?php } ?>
  <td class=xl29 width=275 style='width:206pt'><?=$row["GHICHU"]?></td>
  <td class=xl24></td>
 </tr>
  <?php $stt++;} ?> 
 <![if supportMisalignedColumns]>
 <tr height=0 style='display:none'>
  <td width=55 style='width:41pt'></td>
  <td width=70 style='width:53pt'></td>
  <td width=170 style='width:128pt'></td>

  <td width=162 style='width:122pt'></td>
  <td width=76 style='width:57pt'></td>
  <td width=81 style='width:61pt'></td>
  <td width=275 style='width:206pt'></td>
  <td width=147 style='width:110pt'></td>
  <td width=108 style='width:81pt'></td>
  <td width=139 style='width:104pt'></td>
 </tr>
 <![endif]>

</table>

</body>

</html>
<?php }?>