<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html>
<head>
<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
<script type="text/javascript" src="/js/common.js"></script>
<script src="/js/validate.js" type="text/javascript"></script>
<script src="/js/validate.js" type="text/javascript"></script>
<script type="text/javascript" src=<?php echo $this->baseUrl()."/js/Json/Base64.js"?>></script>
<script type="text/javascript" src=<?php echo $this->baseUrl()."/js/Json/json2.js"?>></script>
<script type="text/javascript" src=<?php echo $this->baseUrl()."/js/Json/json_parse.js"?>></script>
<script type="text/javascript" src=<?php echo $this->baseUrl()."/js/Ajax/AjaxEngine.js"?>></script>
<link rel="stylesheet" type="text/css" href="/styles/general.css" />
<link rel=Stylesheet href=stylesheet.css>
</head>
<body style="background-color:transparent">

    <? $num = count($this->data); 
       if ($num>0) {?>
    <br>
    <div style="color: blue; font-weight: bold">
        SỐ LƯỢNG VĂN BẢN ĐẾN CÓ TRONG DANH SÁCH : <?=$num?>
    </div>
    <br>
    <? } ?>
    
    
<table class=adminlist width="100%">
 <thead>
 	<tr>
	    <th nowrap rowspan=2>Stt</th> 
		<?php if(count($this->soden) >0) {?>
 		<th nowrap rowspan=2>Số đến</th>
		<?php } ?>
		<?php if(count($this->ngayden) >0) {?>
		<th nowrap rowspan=2>Ngày đến</th>
		<?php } ?>
        <?php if(count($this->coquanbh) >0) {?>
 		<th  rowspan=2>Cơ quan ban hành</th>
		<?php } ?>
 		<th nowrap colspan=2 style="text-align:center">Văn bản đến</th>
		<?php if(count($this->trichyeund) >0) {?>
 		<th  rowspan=2 >Trích yếu nội dung</th>
		<?php } ?>
		<!-- <th nowrap rowspan=2>Số lượng</th> -->	
		<?php if(count($this->chuyenchoai) >0) {?>
		<th  rowspan=2>Chuyển cho ai</th>
		<?php } ?>
        <?php if(count($this->ketqua) >0) {?>
		<th  rowspan=2>Kết quả</th>
		<?php } ?>
 		<th  rowspan=2 >Ghi chú</th>
		<!--<th  rowspan=2>Ghi chú</th> -->
 	</tr>
 	<tr>
 		<th nowrap>Số</th>
 		<th nowrap>Ngày</th>
 		
 	</tr>
 </thead>
 <tbody>
<?php require_once 'qtht/models/LoaiVanBanModel.php';
require_once 'qtht/models/CoquanModel.php'; 
require_once 'qtht/models/DepartmentsModel.php';
require_once 'qtht/models/UsersModel.php';
?>
<?php $nguoixuly ; $phongban; $stt=1; 
$num = count($this->data);

foreach($this->data as $row){ 
	
 //dem so cot gion nhau
 //if($stt == 1 || $row['ID_HSCV'] != $this->data[$stt-2]['ID_HSCV']){
 $ten= VanbandenreportModel::getNguoiXuly();
 ?>
	
	<tr>
     <td nowrap valign=top ><?=$stt?></td> 
	<?php if(count($this->soden) >0) {?>
 	<td nowrap valign=top ><?=$row["SODEN"]?></td>
	<?php } ?>
     <?php if(count($this->ngayden) >0) {?>
 	<td nowrap valign=top ><?php echo QLVBDHCommon::MysqlDateToVnDate($row["NGAYDEN"]) ?></td>
	<?php } ?>
     <?php if(count($this->coquanbh) >0) {?>
	<td  width="20%" valign=top ><?=$row["COQUANBANHANH_TEXT"]?> <?php //echo CoquanModel::getNameById($row["ID_CQ"]) ?></td>
    <?php } ?>
 	<td nowrap  valign=top ><?php echo $row["SOKYHIEU"] ?></td>
 	<td nowrap valign=top ><?php echo QLVBDHCommon::MysqlDateToVnDate($row["NGAYBANHANH"]) ?></td>
	<?php if(count($this->trichyeund) >0) {?>
	<td  valign=top width="30%" ><?php echo $row["TRICHYEU"] ?></td>
 	<?php } ?>
	<!--<td nowrap valign=top rowspan=<?php echo $d ?>><?php echo LoaiVanBanModel::getArrNameById($row["ID_LVB"]) ?></td>
 	<td nowrap valign=top rowspan=<?php echo $d ?>><?php echo UsersModel::getEmloyeeNameByIdUser($row["NGUOITAO"]) ?></td>-->
   <!--	<td nowrap ><i><?php echo $row["SOBAN"] ?></i></td>-->  
   	<?php if(count($this->chuyenchoai) >0) {?>
 	<td width="20%">
 	<i><?php 
 	if($row["IS_KHONGXULY"] == 1)
 		echo "Văn bản không xử lý";
 	else{ 	
            $xl= WFEngine::GetProcessLogByObjectId((int)$row['ID_HSCV']);
            $rowsend = $xl[0]['EMPNCNAME'];

            for($j=0;$j<count($xl);$j++){
                    if($j==10){
                    $rowsend .="<br/>" ;
                    $rowsend .=" <br> " ;
                    $rowsend .= $xl[$j]['EMPNCNAME'];

                    }else{
                            if($rowsend != $xl[$j]['EMPNNNAME'])
                            {
                                    //var_dump($xl[$j]);
                                    //exit;
                                    $rowsend .=" <br> " ;
                                    if($xl[$j]["ID_U_EXECUTE"]>0 && $xl[$j]["ID_U_EXECUTE"]!=$xl[$j]["ID_U_NC"]){
                                        $rowsend .= "(". $xl[$j]["EMPEXNAME"]." chuyển giúp) <br>" ;
                                    }
                                    if($xl[$j]['NAME'] == "Chuyển xử lý")
                                          $rowsend .= "<font color=blue>";
                                    $rowsend .= $xl[$j]['EMPNNNAME'];  
                                    
                                    if($xl[$j]['NAME'] == "Chuyển xử lý" )
                                      $rowsend .= "</font>";
                            }
                    }
            }
            $rowsend .=" <br> " ;
            //$rowsend .= $xl[$j-1]['EMPNNNAME'];
						
            ?>
            <i> <?					
                    echo $rowsend;
            ?></i> 
            
            <?php
          
	} 
		 ?>
 		
 	</i></td>
 	<?php } ?>
	<?php if(count($this->ketqua) >0) {?>
	<td valign=top width="20%">
	<?php 
	if($row["ID_HSCV"] != ""){		
		$arr_file_maso = explode(",",$row["FILE_MASO"]);	
         foreach($arr_file_maso as $arr_file_maso_item){
		 
		    if($arr_file_maso_item){
				$arr_maso = explode('~', $arr_file_maso_item);
				if($arr_maso[0] != "")
				{
					echo "<a href='/hscv/File/download?year=".$row['NAM']."&maso=".$arr_maso[0]."'>".$arr_maso[1]." - (".$arr_maso[2].")<br/>";	
				} else {
					echo $arr_maso[1]."<br/>";	
				}
		    } else {
				echo $row["KQ_DEXUAT"];
			}	
		}				
		}
	?>
	</td>
	<?php } ?>
	<td  valign=top width="30%" ><?php echo $row["GHICHU"] ?></td>
	</tr> 
	

<?php 
 /*	
 }
 $nguoixuly .= "<br/>".$row["U_SEND"]."(".$row["NAME_DEP"].")"."--".$row['TR_NAME'];
 //$phongban .="<br/>".$row["NAME_DEP"];
 	
 if($row['ID_HSCV'] != $this->data[$stt]['ID_HSCV']){
 	echo "<td>".$nguoixuly."</td>";
 	//echo "<td>".$phongban."</td>";
 	echo "</tr>";
 	$nguoixuly ="";
 	$phongban = "";
 }

 */
  $stt++ ; } ?>
 </tbody>
 <tfoot >
 </tfoot>
</table>
<p id=lasttext></p>
</body>
</html>
<script>
function resize(){
	try{
	var iframeElement = window.parent.document.getElementById('reportview');
	iframeElement.style.height = ""+(document.getElementById("lasttext").offsetTop)+"px";
	iframeElement.width = "100%";
	setTimeout("resize()",1000);
	}catch(ex){
 }
 }
resize();
</script>