<?php 
require_once('qtht/models/LoaiVanBanModel.php');
require_once('qtht/models/CoQuanModel.php');
?>
<form name="datacdform"  action="/qtht/DanhMucSoVanBan/save" method="post">
<table  class=admintable >
<tbody>
<tr>
<div style="text-align:right;width:100%">
		 Trường có dấu <font color="red">*</font> là bắt buộc nhập 
	</div>
	<td class=key>Tên sổ văn bản<font color="red">*</font> 	
	</td> 
	<td >
		<input type="text" name="name" maxlength="128" size=80 value="<?php echo htmlspecialchars($this->namebefore);?>">		
	</td>
	<td class=error id="ERRname"></td>
	<tr>
	<td class=key>Năm</td> 
	<td >
		<input type="text" name="year" maxlength="128" size=50 value="<?php echo htmlspecialchars($this->yearbefore);?>">
	</td>
	<td class=error id="ERRyear"></td>
	<tr>
	<td class=key>Loại sổ văn bản</td>
	<td>
	<select name="choiceSVB">
	<option value=1>Văn bản đến</option>
	<option value=2>Văn bản đi</option>
	<?php 
		/*if($this->type == 1)
		{
			echo '<option value=1>Văn bản đến</option>';
			echo '<option value=2>Văn bản đi </option>';
		}
		else 
		{
			
			echo '<option value=2>Văn bản đi </option>';
			echo '<option value=1>Văn bản đến</option>';
		}*/
	?>   	
	</select>
	<script>document.datacdform.choiceSVB.value="<?=$this->type?>"</script>
	</td>
	</tr>
	<tr>
	<td class=key>Loại văn bản liên quan</td>
	<td>
	<select name="choiceLVB">
	<option value="0" >--Chọn loại văn bản--</option>
	<?php 
		LoaiVanBanModel::toComboName();
	?>   	
	</select>
	 <script>document.datacdform.choiceLVB.value='<?=(int)$this->id_lvb?>';</script>
	</td>
	<td class=error ></td>
	</tr>
	<tr>
	<td class=key>Cơ quan</td>
	<td>
	<select name="choiceCQ">
	<option value="0" >--Chọn cơ quan--</option>
	<?php 
		CoQuanModel::toComboName(2);
	?>   	
	</select>
	 <script>document.datacdform.choiceCQ.value='<?=(int)$this->id_cq?>';</script>
	</td>
	<td class=error ></td>
	</tr>
	<tr>
	<td class=key>Thuộc phòng</td>
	<td>
	<select name="choiceDEP">
	<option value="0" >--Chọn phòng--</option>
	<?php 
		DepartmentsModel::toComboName();
	?>   	
	</select>
	 <script>document.datacdform.choiceDEP.value='<?=(int)$this->id_dep?>';</script>
	</td>
	<td class=error ></td>
	</tr>
	<tr>
	<td class=key>Đã được sử dụng</td>
	<td>
	<?php
		if($this->activeselect == 1){
			echo '<input type="checkbox" value=1 name="active" checked=checked>';
		}
		else {
			echo '<input type="checkbox" value=1 name="active">';
		}
	?>
	</td>
	<td class=error> </td>
</tr>
</tbody>
</table>

<input type=hidden name="InputIDSVB" value=<?php echo $this->id?> >
<input type=hidden name="limit" value=<?php echo $this->limit?> >
<input type=hidden name="filter_object" value=<?php echo $this->filter_object?> >
<input type=hidden name="search" value=<?php echo $this->search?> >
<input type=hidden name="page" value=<?php echo $this->page?> >

</form>

<script>

function checkFormData(){

	var str = "Bạn phải nhập tên sổ văn bản";
	var strerr = validateInput("required",document.datacdform.name,str);
	if(!strerr){
		document.datacdform.name.focus();
		return false;
	}
	str="Tên của sổ văn bản không được quá 512 ký tự";
	strerr = validateInput("maxlen=512",document.datacdform.name,str);
	if(!strerr){
		
		document.datacdform.name.focus();
		return false;
	}
	str ="Năm sai định dạng";
	strerr = validateInput("year",document.datacdform.year,str);
	if(!strerr){
		
		document.datacdform.year.focus();
		return false;
	}
	return true;
}

function SaveButtonClick(){
	
	if(checkFormData()){
		//document.datacdform.method ="get";
		document.datacdform.submit();
	}
}
function BackButtonClick(){
	document.datacdform.action = '/qtht/danhmucsovanban/index';
	document.datacdform.submit();
}


</script>




















