<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns:v="urn:schemas-microsoft-com:vml"
xmlns:o="urn:schemas-microsoft-com:office:office"
xmlns:w="urn:schemas-microsoft-com:office:word"
xmlns:m="http://schemas.microsoft.com/office/2004/12/omml"
xmlns:st1="urn:schemas-microsoft-com:office:smarttags"
xmlns="http://www.w3.org/TR/REC-html40">

<head>
<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
<meta name=ProgId content=Word.Document>
<meta name=Generator content="Microsoft Word 12">
<meta name=Originator content="Microsoft Word 12">
<link rel=File-List href="capphepxaydung_files/filelist.xml">
<o:SmartTagType namespaceuri="urn:schemas-microsoft-com:office:smarttags"
 name="place"/>
<o:SmartTagType namespaceuri="urn:schemas-microsoft-com:office:smarttags"
 name="country-region"/>

<style>
<!--
 /* Font Definitions */
 @font-face
	{font-family:"Cambria Math";
	panose-1:2 4 5 3 5 4 6 3 2 4;
	mso-font-charset:0;
	mso-generic-font-family:roman;
	mso-font-pitch:variable;
	mso-font-signature:-1610611985 1107304683 0 0 159 0;}
@font-face
	{font-family:"VNtimes new roman";
	mso-font-alt:"Courier New";
	mso-font-charset:0;
	mso-generic-font-family:swiss;
	mso-font-pitch:variable;
	mso-font-signature:3 0 0 0 1 0;}
@font-face
	{font-family:VNarial;
	mso-font-alt:"Courier New";
	mso-font-charset:0;
	mso-generic-font-family:swiss;
	mso-font-pitch:variable;
	mso-font-signature:3 0 0 0 1 0;}
 /* Style Definitions */
 p.MsoNormal, li.MsoNormal, div.MsoNormal
	{mso-style-unhide:no;
	mso-style-qformat:yes;
	mso-style-parent:"";
	margin-top:0in;
	margin-right:0in;
	margin-bottom:10.0pt;
	margin-left:0in;
	line-height:115%;
	mso-pagination:widow-orphan;
	font-size:11.0pt;
	font-family:"Calibri","sans-serif";
	mso-ascii-font-family:Calibri;
	mso-ascii-theme-font:minor-latin;
	mso-fareast-font-family:"Times New Roman";
	mso-fareast-theme-font:minor-fareast;
	mso-hansi-font-family:Calibri;
	mso-hansi-theme-font:minor-latin;
	mso-bidi-font-family:"Times New Roman";
	mso-bidi-theme-font:minor-bidi;}
h1
	{mso-style-unhide:no;
	mso-style-qformat:yes;
	mso-style-link:"Heading 1 Char";
	mso-style-next:Normal;
	margin:0in;
	margin-bottom:.0001pt;
	text-align:center;
	mso-pagination:widow-orphan;
	page-break-after:avoid;
	mso-outline-level:1;
	font-size:12.0pt;
	mso-bidi-font-size:10.0pt;
	font-family:"VNarial","sans-serif";
	mso-fareast-font-family:"Times New Roman";
	mso-bidi-font-family:"Times New Roman";
	mso-font-kerning:0pt;
	font-weight:normal;}
p.MsoHeader, li.MsoHeader, div.MsoHeader
	{mso-style-name:"Header\,h";
	mso-style-unhide:no;
	mso-style-link:"Header Char";
	margin:0in;
	margin-bottom:.0001pt;
	mso-pagination:widow-orphan;
	tab-stops:center 3.0in right 6.0in;
	font-size:14.0pt;
	mso-bidi-font-size:12.0pt;
	font-family:"Times New Roman","serif";
	mso-fareast-font-family:"Times New Roman";}
p.MsoBodyText, li.MsoBodyText, div.MsoBodyText
	{mso-style-unhide:no;
	mso-style-link:"Body Text Char";
	margin:0in;
	margin-bottom:.0001pt;
	mso-pagination:widow-orphan;
	font-size:12.0pt;
	mso-bidi-font-size:10.0pt;
	font-family:"VNarial","sans-serif";
	mso-fareast-font-family:"Times New Roman";
	mso-bidi-font-family:"Times New Roman";}
p.MsoBodyTextIndent, li.MsoBodyTextIndent, div.MsoBodyTextIndent
	{mso-style-unhide:no;
	mso-style-link:"Body Text Indent Char";
	margin:0in;
	margin-bottom:.0001pt;
	text-indent:.25in;
	mso-pagination:widow-orphan;
	font-size:13.0pt;
	mso-bidi-font-size:10.0pt;
	font-family:"VNtimes new roman","sans-serif";
	mso-fareast-font-family:"Times New Roman";
	mso-bidi-font-family:"Times New Roman";}
p.MsoBodyText2, li.MsoBodyText2, div.MsoBodyText2
	{mso-style-unhide:no;
	mso-style-link:"Body Text 2 Char";
	margin:0in;
	margin-bottom:.0001pt;
	text-align:center;
	mso-pagination:widow-orphan;
	font-size:12.0pt;
	mso-bidi-font-size:10.0pt;
	font-family:"VNarial","sans-serif";
	mso-fareast-font-family:"Times New Roman";
	mso-bidi-font-family:"Times New Roman";}
p.MsoPlainText, li.MsoPlainText, div.MsoPlainText
	{mso-style-unhide:no;
	mso-style-link:"Plain Text Char";
	margin:0in;
	margin-bottom:.0001pt;
	mso-pagination:widow-orphan;
	font-size:10.0pt;
	font-family:"Courier New";
	mso-fareast-font-family:"Times New Roman";
	mso-bidi-font-family:"Times New Roman";}
span.Heading1Char
	{mso-style-name:"Heading 1 Char";
	mso-style-unhide:no;
	mso-style-locked:yes;
	mso-style-link:"Heading 1";
	mso-ansi-font-size:12.0pt;
	mso-bidi-font-size:10.0pt;
	font-family:"VNarial","sans-serif";
	mso-ascii-font-family:VNarial;
	mso-fareast-font-family:"Times New Roman";
	mso-hansi-font-family:VNarial;
	mso-bidi-font-family:"Times New Roman";}
span.HeaderChar
	{mso-style-name:"Header Char";
	mso-style-unhide:no;
	mso-style-locked:yes;
	mso-style-link:"Header\,h";
	mso-ansi-font-size:14.0pt;
	mso-bidi-font-size:12.0pt;
	font-family:"Times New Roman","serif";
	mso-ascii-font-family:"Times New Roman";
	mso-fareast-font-family:"Times New Roman";
	mso-hansi-font-family:"Times New Roman";
	mso-bidi-font-family:"Times New Roman";}
span.BodyTextIndentChar
	{mso-style-name:"Body Text Indent Char";
	mso-style-unhide:no;
	mso-style-locked:yes;
	mso-style-link:"Body Text Indent";
	mso-ansi-font-size:13.0pt;
	mso-bidi-font-size:10.0pt;
	font-family:"VNtimes new roman","sans-serif";
	mso-ascii-font-family:"VNtimes new roman";
	mso-fareast-font-family:"Times New Roman";
	mso-hansi-font-family:"VNtimes new roman";
	mso-bidi-font-family:"Times New Roman";}
span.BodyTextChar
	{mso-style-name:"Body Text Char";
	mso-style-unhide:no;
	mso-style-locked:yes;
	mso-style-link:"Body Text";
	mso-ansi-font-size:12.0pt;
	mso-bidi-font-size:10.0pt;
	font-family:"VNarial","sans-serif";
	mso-ascii-font-family:VNarial;
	mso-fareast-font-family:"Times New Roman";
	mso-hansi-font-family:VNarial;
	mso-bidi-font-family:"Times New Roman";}
span.BodyText2Char
	{mso-style-name:"Body Text 2 Char";
	mso-style-unhide:no;
	mso-style-locked:yes;
	mso-style-link:"Body Text 2";
	mso-ansi-font-size:12.0pt;
	mso-bidi-font-size:10.0pt;
	font-family:"VNarial","sans-serif";
	mso-ascii-font-family:VNarial;
	mso-fareast-font-family:"Times New Roman";
	mso-hansi-font-family:VNarial;
	mso-bidi-font-family:"Times New Roman";}
span.PlainTextChar
	{mso-style-name:"Plain Text Char";
	mso-style-unhide:no;
	mso-style-locked:yes;
	mso-style-link:"Plain Text";
	mso-ansi-font-size:10.0pt;
	mso-bidi-font-size:10.0pt;
	font-family:"Courier New";
	mso-ascii-font-family:"Courier New";
	mso-fareast-font-family:"Times New Roman";
	mso-hansi-font-family:"Courier New";
	mso-bidi-font-family:"Times New Roman";}
span.GramE
	{mso-style-name:"";
	mso-gram-e:yes;}
.MsoChpDefault
	{mso-style-type:export-only;
	mso-default-props:yes;
	mso-ascii-font-family:Calibri;
	mso-ascii-theme-font:minor-latin;
	mso-fareast-font-family:"Times New Roman";
	mso-fareast-theme-font:minor-fareast;
	mso-hansi-font-family:Calibri;
	mso-hansi-theme-font:minor-latin;
	mso-bidi-font-family:"Times New Roman";
	mso-bidi-theme-font:minor-bidi;}
.MsoPapDefault
	{mso-style-type:export-only;
	margin-bottom:10.0pt;
	line-height:115%;}
@page Section1
	{size:8.5in 11.0in;
	margin:1.0in 1.0in 1.0in 1.0in;
	mso-header-margin:.5in;
	mso-footer-margin:.5in;
	mso-paper-source:0;}
div.Section1
	{page:Section1;}
-->
</style>
<!--[if gte mso 10]>
<style>
 /* Style Definitions */
 table.MsoNormalTable
	{mso-style-name:"Table Normal";
	mso-tstyle-rowband-size:0;
	mso-tstyle-colband-size:0;
	mso-style-noshow:yes;
	mso-style-priority:99;
	mso-style-qformat:yes;
	mso-style-parent:"";
	mso-padding-alt:0in 5.4pt 0in 5.4pt;
	mso-para-margin-top:0in;
	mso-para-margin-right:0in;
	mso-para-margin-bottom:10.0pt;
	mso-para-margin-left:0in;
	line-height:115%;
	mso-pagination:widow-orphan;
	font-size:11.0pt;
	font-family:"Calibri","sans-serif";
	mso-ascii-font-family:Calibri;
	mso-ascii-theme-font:minor-latin;
	mso-hansi-font-family:Calibri;
	mso-hansi-theme-font:minor-latin;}
</style>
<![endif]--><!--[if gte mso 9]><xml>
 <o:shapedefaults v:ext="edit" spidmax="2050"/>
</xml><![endif]--><!--[if gte mso 9]><xml>
 <o:shapelayout v:ext="edit">
  <o:idmap v:ext="edit" data="1"/>
 </o:shapelayout></xml><![endif]-->
</head>

<body lang=EN-US style='tab-interval:.5in'>
<?php var_dump($this->data); ?>
<div class=Section1>

<h1><b style='mso-bidi-font-weight:normal'><span style='font-size:14.0pt;
mso-bidi-font-size:10.0pt;font-family:"Times New Roman","serif"'>C&#7896;NG HÒA
XÃ H&#7896;I CH&#7910; NGH&#296;A VI&#7878;T <st1:country-region w:st="on"><st1:place
 w:st="on">NAM</st1:place></st1:country-region><o:p></o:p></span></b></h1>

<h1><b style='mso-bidi-font-weight:normal'><u><span style='font-size:14.0pt;
mso-bidi-font-size:10.0pt;font-family:"Times New Roman","serif"'>&#272;&#7897;c
l&#7853;p - T&#7921; do - H&#7841;nh phúc<o:p></o:p></span></u></b></h1>

<p class=MsoNormal align=center style='text-align:center'><span
style='font-family:"Times New Roman","serif"'><o:p>&nbsp;</o:p></span></p>

<p class=MsoNormal align=center style='text-align:center'><b style='mso-bidi-font-weight:
normal'><span style='font-family:"Times New Roman","serif"'>&#272;&#416;N
&#272;&#7872; NGH&#7882; C&#7844;P<o:p></o:p></span></b></p>

<p class=MsoNormal align=center style='text-align:center'><b style='mso-bidi-font-weight:
normal'><span style='font-family:"Times New Roman","serif"'>GI&#7844;Y PHÉP XÂY
D&#7920;NG CÔNG TRÌNH<o:p></o:p></span></b></p>

<p class=MsoNormal align=center style='text-align:center'><span
style='font-family:"Times New Roman","serif"'><o:p>&nbsp;</o:p></span></p>

<p class=MsoNormal align=center style='text-align:center'><span
style='font-family:"Times New Roman","serif"'>Kính g&#7917;i: <b
style='mso-bidi-font-weight:normal'>S&#7903; Giao thông v&#7853;n t&#7843;i
thành ph&#7889; &#272;à N&#7861;ng</b><o:p></o:p></span></p>

<p class=MsoNormal><span style='font-family:"Times New Roman","serif"'><o:p>&nbsp;</o:p></span></p>

<p class=MsoNormal><span style='font-family:"Times New Roman","serif"'><span
style='mso-tab-count:1'>            </span>Tôi tên là:
<b><?=" ".$this->data["TEN_CANHAN"]." "?></b>&#272;i&#7879;n tho&#7841;i
s&#7889;<span class=GramE>:<b><?=" ".$this->data["DIENTHOAI"]." "?></b></span><o:p></o:p></span></p>

<p class=MsoNormal style='tab-stops:35.0pt dotted 6.5in'><span
style='font-family:"Times New Roman","serif"'><span style='mso-tab-count:1'>            </span>&#272;&#7841;i
di&#7879;n (n&#7871;u là c&#417; quan, t&#7893; ch&#7913;c)<span class=GramE>:<b><?=" ".$this->data["TEN_COQUAN"]." "?></b></span><o:p></o:p></span></p>

<p class=MsoNormal style='margin-top:3.0pt;margin-right:0in;margin-bottom:3.0pt;
margin-left:0in;text-indent:35.0pt'><span style='font-family:"Times New Roman","serif"'>&#272;&#7875;
ph&#7909;c v&#7909;
cho<b><?=" ".$this->data["LY_DO"]." "?></b><o:p></o:p></span></p>

<p class=MsoNormal style='margin-top:3.0pt;margin-right:0in;margin-bottom:3.0pt;
margin-left:0in;text-align:justify;text-justify:inter-ideograph;text-indent:
35.0pt'><span style='font-family:"Times New Roman","serif"'>Nay tôi làm
&#273;&#417;n này, kính &#273;&#7873; ngh&#7883; kính &#273;&#7873; ngh&#7883;
S&#7903; Giao thông v&#7853;n t&#7843;i cho phép thi công công
trình<b><?=" ".$this->data["TEN_CONGTRINH"]." "?></b><o:p></o:p></span></p>

<p class=MsoNormal style='margin-top:3.0pt;margin-right:0in;margin-bottom:3.0pt;
margin-left:0in;text-indent:35.0pt'><span style='font-family:"Times New Roman","serif"'>T&#7841;i
v&#7883; trí:<o:p></o:p></span></p>

<p class=MsoNormal style='margin-top:3.0pt;margin-right:0in;margin-bottom:3.0pt;
margin-left:0in;text-indent:35.0pt'><span style='font-family:"Times New Roman","serif"'>T&#7915;
lý trình (nhà s&#7889;)<span class=GramE>:<b><?=" ".$this->data["LY_TRINH_TU"]." "?></b></span>&#273;&#7871;n
lý trình (nhà s&#7889;)<b><?=" ".$this->data["LY_TRINH_DEN"]." "?></b>tuy&#7871;n &#273;&#432;&#7901;ng:<b><?=" ".$this->data["TUYEN_DUONG"]." "?></b><o:p></o:p></span></p>

<p class=MsoNormal style='margin-top:3.0pt;margin-right:0in;margin-bottom:3.0pt;
margin-left:0in;text-align:justify;text-justify:inter-ideograph;text-indent:
35.0pt'><span style='font-family:"Times New Roman","serif"'>Sau khi
&#273;&#432;&#7907;c ch&#7845;p thu&#7853;n cho phép thi công công trình nêu
trên, tôi xin cam k&#7871;t:<o:p></o:p></span></p>

<p class=MsoNormal style='margin-top:3.0pt;margin-right:0in;margin-bottom:3.0pt;
margin-left:0in;text-align:justify;text-justify:inter-ideograph;text-indent:
35.0pt'><span style='font-family:"Times New Roman","serif"'>1. Ch&#7845;p hành
các quy &#273;&#7883;nh hi&#7879;n hành c&#7911;a Nhà n&#432;&#7899;c và c&#7911;a
UBND thành ph&#7889;;<o:p></o:p></span></p>

<p class=MsoNormal style='margin-top:3.0pt;margin-right:0in;margin-bottom:3.0pt;
margin-left:0in;text-align:justify;text-justify:inter-ideograph;text-indent:
35.0pt'><span style='font-family:"Times New Roman","serif"'>2. N&#7897;p ti&#7873;n
chi phí hoàn tr&#7843; v&#7881;a hè, m&#7863;t &#273;&#432;&#7901;ng <span
class=GramE>theo</span> quy &#273;&#7883;nh (n&#7871;u có) và ch&#7883;u trách
nhi&#7879;m qu&#7843;n lý, s&#7917;a ch&#7919;a công trình &#273;ã &#273;&#432;&#7907;c
cho phép thi công (tr&#432;&#7899;c khi s&#7917;a ch&#7919;a ph&#7843;i làm th&#7911;
t&#7909;c c&#7845;p phép theo quy &#273;&#7883;nh hi&#7879;n hành);<o:p></o:p></span></p>

<p class=MsoNormal style='margin-top:3.0pt;margin-right:0in;margin-bottom:3.0pt;
margin-left:0in;text-align:justify;text-justify:inter-ideograph;text-indent:
35.0pt'><span style='font-family:"Times New Roman","serif"'>3. Ch&#7845;p hành
s&#7921; giám sát c&#7911;a &#273;&#417;n v&#7883; qu&#7843;n lý &#273;&#432;&#7901;ng
và n&#7897;p &#273;&#7847;y &#273;&#7911; chi phí giám sát thi công công trình <span
class=GramE>theo</span> quy &#273;&#7883;nh;<o:p></o:p></span></p>

<p class=MsoNormal style='margin-top:3.0pt;margin-right:0in;margin-bottom:3.0pt;
margin-left:0in;text-align:justify;text-justify:inter-ideograph;text-indent:
35.0pt'><span style='font-family:"Times New Roman","serif"'>4. Ch&#7853;m nh&#7845;t
là 30 ngày (ba m&#432;&#417;i ngày) k&#7875; t&#7915; ngày thi công xong tôi s&#7869;
&#273;&#7847;y &#273;&#7911; n&#7897;p h&#7891; s&#417; hoàn công <span
class=GramE>theo</span> &#273;úng quy &#273;&#7883;nh c&#7911;a gi&#7845;y phép
&#273;&#432;&#7907;c c&#7845;p <i>(&#273;&#7889;i v&#7899;i tr&#432;&#7901;ng h&#7907;p
thi công l&#7855;p &#273;&#7863;t công trình ng&#7847;m)</i>;<o:p></o:p></span></p>

<p class=MsoNormal style='margin-top:3.0pt;margin-right:0in;margin-bottom:3.0pt;
margin-left:0in;text-align:justify;text-justify:inter-ideograph;text-indent:
35.0pt'><span style='font-family:"Times New Roman","serif"'>5. Ch&#7883;u m&#7885;i
chi phí trong vi&#7879;c tháo d&#7905;, di chuy&#7875;n công trình &#273;ã l&#7855;p
&#273;&#7863;t và giao tr&#7843; m&#7863;t b&#7857;ng <span class=GramE>theo</span>
&#273;úng th&#7901;i gian yêu c&#7847;u trong tr&#432;&#7901;ng h&#7907;p Nhà
n&#432;&#7899;c có ch&#7911; tr&#432;&#417;ng gi&#7843;i t&#7887;a &#273;&#7875;
nâng c&#7845;p, m&#7903; r&#7897;ng n&#7873;n, m&#7863;t &#273;&#432;&#7901;ng,
v&#7881;a hè, xây d&#7921;ng các công trình công c&#7897;ng (n&#7871;u có).<o:p></o:p></span></p>

<p class=MsoNormal style='margin-top:3.0pt;margin-right:0in;margin-bottom:3.0pt;
margin-left:0in;text-align:justify;text-justify:inter-ideograph;text-indent:
35.0pt'><span style='font-family:"Times New Roman","serif"'>N&#7871;u không th&#7921;c
hi&#7879;n &#273;úng các n&#7897;i dung trên, tôi xin ch&#7883;u hoàn toàn
trách nhi&#7879;m tr&#432;&#7899;c Pháp lu&#7853;t<span class=GramE>./</span>.<o:p></o:p></span></p>

<p class=MsoNormal style='margin-left:35.0pt'><span style='font-family:"Times New Roman","serif"'><o:p>&nbsp;</o:p></span></p>

<p class=MsoNormal style='tab-stops:center 364.0pt'><b style='mso-bidi-font-weight:
normal'><i style='mso-bidi-font-style:normal'><span style='font-family:"Times New Roman","serif"'><span
style='mso-tab-count:1'>                                                                                        </span></span></i></b><i
style='mso-bidi-font-style:normal'><span style='font-family:"Times New Roman","serif"'>&#272;à
N&#7861;ng, <span class=GramE>ngày ........</span> <span class=GramE>tháng</span>..........n&#259;m........<o:p></o:p></span></i></p>

<p class=MsoHeader style='margin-top:5.0pt;margin-right:0in;margin-bottom:5.0pt;
margin-left:0in;tab-stops:center 364.0pt'><span
style='mso-spacerun:yes'>                                                       
</span><span
style='mso-spacerun:yes'>                               </span>Ng&#432;&#7901;i
làm &#273;&#417;n<i style='mso-bidi-font-style:normal'><o:p></o:p></i></p>

<p class=MsoNormal style='margin-top:5.0pt;margin-right:0in;margin-bottom:5.0pt;
margin-left:0in;tab-stops:center 364.0pt'><i style='mso-bidi-font-style:normal'><span
style='font-family:"Times New Roman","serif"'><span style='mso-tab-count:1'>                                                                                       </span>(Ký
tên, ghi rõ h&#7885; và tên, &#273;óng d&#7845;u n&#7871;u có)<o:p></o:p></span></i></p>

<p class=MsoNormal style='margin-top:5.0pt;margin-right:0in;margin-bottom:5.0pt;
margin-left:0in;tab-stops:center 364.0pt'><span style='font-family:"Times New Roman","serif";
mso-bidi-font-style:italic'><o:p>&nbsp;</o:p></span></p>


<p class=MsoNormal><span style='font-family:"Times New Roman","serif"'><o:p>&nbsp;</o:p></span></p>

</div>
<p id=lasttext1></p>

</body>

</html>
<script>
function resize(){
	try{
		//alert("aa");
	var iframeElement = parent.document.getElementById('iframebutphe<?=$this->ID_FR?>');
	iframeElement.style.height = ""+ (document.getElementById("lasttext1").offsetTop) +"px";
	iframeElement.width = "100%"; 
	setTimeout("resize()",1000);
	}catch(ex){
	}
}

setTimeout("resize()",1000);
</script>