<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html>
<head>
<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
<script type="text/javascript" src="/js/common.js"></script>
<script src="/js/validate.js" type="text/javascript"></script>
<script src="/js/validate.js" type="text/javascript"></script>
<script language="javascript" type="text/javascript" src="/js/vgca/base64.js"></script>
<script language="javascript" type="text/javascript" src="/js/vgca/vgcaplugin.js"></script>

<link rel="stylesheet" type="text/css" href="/styles/general.css" />
</head>
<body style="background-color:transparent">
<link rel="stylesheet" type="text/css" href="/styles/general.css" />

	<script type="text/javascript">
            function SignCallBack(sender, rv) {
                var received_msg = JSON.parse(rv);
                            if(received_msg.Status == 0){
                                    document.getElementById("_signature").value = received_msg.Signature;
                            }else{
                                    alert("Ký số không thành công:" + received_msg.Status +":"+ received_msg.Error);
                            }
            }

            function exc_sign_msg(sender) {
                var s1 = Base64.encode(document.getElementById("_plain_text").value);
                vgca_sign_msg(sender, s1, SignCallBack);
            }

            function VerifyCallBack(rv) {

            }

            function exc_verify_msg() {
                var s1 = Base64.encode(document.getElementById("_plain_text").value);
                var s2 = document.getElementById("_signature").value;

                            var prms = {};
                prms["Base64Content"] = s1;
                prms["Signature"] = s2;

                var json_prms = JSON.stringify(prms);

                vgca_verify_msg(json_prms, VerifyCallBack);
                return false;
            }

            function VerifyPDFCallBack(rv) {

            }

            function exc_verify_pdf(sessionid, filename) {
                var prms = {};
                prms["SessionId"] = sessionid;
                prms["FileName"] = filename;

                var json_prms = JSON.stringify(prms);

                vgca_verify_pdf(json_prms, VerifyPDFCallBack);
            }

            function SignFileCallBack(rv) {
                
                var received_msg = JSON.parse(rv);
            
                if (received_msg.Status == 0) {
                    
                   document.frmUpload.submit();
                    
                } else {
                   // document.frmUpload.submit();
                //console.log(received_msg);
                    //document.getElementById("_signature").value = received_msg.Message;
                }
            }

                    //metadata có kiểu List<KeyValue> 
                    //KeyValue là class { string Key; string Value; }
            function exc_sign_file(sessionid, filename, metadata) {
                var prms = {};
                
                prms["SessionId"] = sessionid;
                prms["FileName"] = filename;
                prms["MetaData"] = metadata;
                prms["FileUploadHandler"] = "<?php echo url()?>/chukyso/chukyso/save/?enableDragAndDrop=<?php echo $this->enableDragAndDrop?>&type=<?php echo $this->type?>&year=<?php echo $this->year?>&idObject=<?php echo $this->idObject?>&iddiv=idFileDinhKem&isTemp=<?php echo $this->isTemp?>&pdf=<?php echo $this->pdf?>&is_nogetcontent=<?php echo $this->is_nogetcontent?>";
                
                var json_prms = JSON.stringify(prms);
                //console.log(json_prms);
              
                vgca_sign_file(json_prms, SignFileCallBack);
                //alert(vgca_sign_file);
            }
        </script>
        <?php
        function url(){
            if(isset($_SERVER['HTTPS'])){
                $protocol = ($_SERVER['HTTPS'] && $_SERVER['HTTPS'] != "off") ? "https" : "http";
            }
            else{
                $protocol = 'http';
            }
            return $protocol . "://" . $_SERVER['HTTP_HOST'];
        }
        ?>
<form name=frmUpload enctype="multipart/form-data" action="/chukyso/chukyso/viewLoad" method="post" target="tftemp<?php echo $this->idObject?>">
        <input type="hidden" name="MAX_FILE_SIZE" value="100000000" />
       
	<table width=100% class="admintable" border=0>
		<tr>
			<td nowrap class=key>Chọn tệp (kèm chữ ký)</td>
			<td nowrap><!-- Gọi hàm ký số tệp PDF trên máy tính-->
                            <button type="button" id="_SignOfflineFile"  onclick="exc_sign_file('', '', '');">Chọn Tệp</button></td>
		</tr>
	</table>
	<input type="hidden" name="enableDragAndDrop" value=<?php echo $this->enableDragAndDrop?> >
	<input type="hidden" name="idObject" value=<?php echo $this->idObject?> >
	<input type="hidden" name="isTemp" value=<?php echo $this->isTemp?>>
	<input type="hidden" name="year" value=<?php echo $this->year?>>
	<input type="hidden" name="iddiv" value=<?php echo $this->iddiv?>>
	<input type="hidden" name="type" value=<?php echo $this->type?>>
	<input type="hidden" name="from" value=<?php echo $this->from?>>
	<input type="hidden" name="pdf" value="<?php echo $this->pdf?>">
	<input type="hidden" name="is_nogetcontent" value="<?php echo $this->is_nogetcontent?>">
	
</form>
<p id=lasttext></p>
</body>
</html>
<script>
function SaveButtonClick(){
	
}
var iframeElement = window.parent.document.getElementById('tftemp<?php echo $this->idObject?>');
iframeElement.style.height = ""+(document.getElementById("lasttext").offsetTop+10)+"px";
iframeElement.width = "100%"; 
</script>
