<script	type="text/javascript" src="/js/Ajax/AjaxEngine.js"></script>
<?php
require_once 'vanbansaoy/models/vanbansaoyModel.php';
$auth = Zend_Registry::get('auth');
$data_session = $auth->getIdentity();
$id_u =$data_session->ID_U;
?>
<form name=frm method=post action="/vanbansaoy/index/list">
<table>
	<tr>
			<td align="right"> <b>Tên văn bản sao y: </b></td>
			<td>
			<input type="text" name="search"
			id="search" value="<?php echo htmlspecialchars($this->search); ?>"
			class="text_area"
			onchange="document.frm.page.value=1;document.frm.submit();" style=" width:200px"/>
			<button onclick="document.frm.submit();">Tìm</button>
			</td>	
	</tr>
</table>

<table class="adminlist">
	<thead>
		<tr>
			<th colspan="4">
			<div>
			<div class="limit" style="float: left;">Hiển thị<select
				name="limit1" style="width: 60px;" id="limit1" class="inputbox"
				size="1"
				onchange="
							document.frm.page.value = 1;
							document.frm.limit2.value = document.frm.limit1.value;
							document.frm.action = '/vanbansaoy/index/list';
							document.frm.submit();
						">
				<option value="5" <?php if($this->limit==5){echo "selected";} ?>>5</option>
				<option value="10" <?php if($this->limit==10){echo "selected";} ?>>10</option>
				<option value="15" <?php if($this->limit==15){echo "selected";} ?>>15</option>
				<option value="20" <?php if($this->limit==20){echo "selected";} ?>>20</option>
				<option value="25" <?php if($this->limit==25){echo "selected";} ?>>25</option>
				<option value="30" <?php if($this->limit==30){echo "selected";} ?>>30</option>
                                <option value="35" <?php if($this->limit==35){echo "selected";} ?>>35</option>
                                <option value="40" <?php if($this->limit==40){echo "selected";} ?>>40</option>
				<option value="50" <?php if($this->limit==50){echo "selected";} ?>>50</option>
				<option value="100" <?php if($this->limit==100){echo "selected";} ?>>100</option>
			</select></div>
			<div class="limit" style="float: right;"><?php echo $this->showPage; ?></div>
			</div>
			</th>
		</tr>
		<tr>
			<th nowrap="nowrap">Stt</th>
			<th nowrap valign="top">
                           <input type=checkbox name=CHECKALL onclick="SelectAll(this,'CHECK')">
			<th width="100%">Yêu cầu sao y</th>
                        <th></th>
			
		</tr>
	</thead>

	<tfoot>
		<tr>
			<th colspan="4">
			<div class="pagination">
			<div class="limit">Hiển thị<select name="limit2"
				style="width: 60px;" id="limit2" class="inputbox" size="1"
				onchange="
							document.frm.page.value = 1;
							document.frm.limit1.value = document.frm.limit2.value;
							document.frm.action = '/vanbansaoy/index/list';
							document.frm.submit();
						">
				<option value="5" <?php if($this->limit==5){echo "selected";} ?>>5</option>
				<option value="10" <?php if($this->limit==10){echo "selected";} ?>>10</option>
				<option value="15" <?php if($this->limit==15){echo "selected";} ?>>15</option>
				<option value="20" <?php if($this->limit==20){echo "selected";} ?>>20</option>
				<option value="25" <?php if($this->limit==25){echo "selected";} ?>>25</option>
				<option value="30" <?php if($this->limit==30){echo "selected";} ?>>30</option>
                                <option value="35" <?php if($this->limit==35){echo "selected";} ?>>35</option>
                                <option value="40" <?php if($this->limit==40){echo "selected";} ?>>40</option>
				<option value="50" <?php if($this->limit==50){echo "selected";} ?>>50</option>
				<option value="100" <?php if($this->limit==100){echo "selected";} ?>>100</option>
			</select></div>
			<div style="float: right"><?php echo $this->showPage; ?></div>
			</div>
			</th>
		</tr>
	</tfoot>

	<tbody>
	<?php  if(count($this->data)<=0) {
		echo "<tr><td colspan='4'> Không tìm thấy văn bản sao y nào</td></tr>";
	}else {

	 $stt=1 ;foreach ($this->data as $row){
	  $row['KYHIEUVANBANSAOY'] = QLVBDHCommon::highlightWords($row['KYHIEUVANBANSAOY'],$this->search);
	 	?>
		<tr>
			<td valign="top"><?=$stt ?></td>
			<td valign="top">
                            <input type=checkbox name=CHECK[] value='<?php echo $row['ID_VBSY'] ?>'></td>
			<td valign="top">

<!--                        vb den hay vb nhan , add image tuong ung-->
			<div><?php $user = Zend_Registry::get('auth')->getIdentity(); 
			if(($user->ID_U == $row["NGUOITAO"])||($user->ID_U == $row["NGUOIDENGHI"])){
				?> <img id='guidi_<?=$row['ID_VBSY'] ?>'
				src='/images/arrow_left.png'> <?php }else{?> <img
				id='guiden_<?=$row['ID_VBSY'] ?>' src='/images/arrow_right.png'><?}?>
                                <a name="id_<?=$row["ID_VBSY"]?>"> </a> <?=$row["KYHIEUVANBANSAOY"] ?>
                                <?php if($row["ISFINISHED"]==1) { ?> <font color="blue">- Đã phê duyệt</font> <? }
                            else { ?> <font color="red">- đang chờ phê duyệt</font> <? } ?>
                                <?php
			$user = Zend_Registry::get('auth')->getIdentity();
			//đk set image - vb mới 
				if(vanbansaoyModel::isUserReceive($row["ID_VBSY"],$user->ID_U) == 0
				||$user->ID_U == $row["NGUOITAO"]&& $row["ISNEW"]==1
				){?> <img id='image_new_<?=$row['ID_VBSY'] ?>' src='/images/moi.gif'>
				<?php } ?> 
                        </div>						                        
<!--			<div class="clr"></div>-->
			<div>
			<ul class="chitiethscv">
				<li id=groupicon1_<?=$row["ID_VBSY"]?>><img
					src="/images/icon_chitiet.jpg" border="0" hspace="5"> <a
					href='javascript:
			{SwapDiv(<?=$row["ID_VBSY"]?>,"/vanbansaoy/index/detail?ID_VBSY=<?=$row["ID_VBSY"]?>",1);
			 
		     updateImageNew(<?php echo '"image_new_'.$row["ID_VBSY"].'"'?>,<?=$row["ID_VBSY"]?>,<?=$row["NGUOITAO"]==$id_u?1:0?>);
		     }
		     '>Chi tiết</a></li>                                
								
			</ul>
			</div>
			</td>
			<td nowrap="nowrap" valign="top">		        
                         <a
				href="/vanbansaoy/index/in/ID_VBSY/<?php echo $row['ID_VBSY']?>">In văn bản sao y</a>
                        </td>
                        </td>

		</tr>
		<tr>
			<td colspan="4">
			<div class="groupcontent" id="groupcontent<?=$row["ID_VBSY"]?>"
				style="display: none; border: 1px"></div>
			</td>
		</tr>

		<?php $stt++;}
	}
	?>
	</tbody>
</table>
<input type="hidden" name="page" value="<?php echo $this->page; ?>"></form>
<script>
	//function clickDetail(id,tab){
		//var url ="/vanbansaoy/index/detail?ID_VBSY="+id;
		//document.getElementById("groupcontent_"+id).innerHTML="<img src='/images/loading.gif' width='16' height='16' border='0'></img<img src='/images/loading.gif' width='16' height='16' border='0'></img><img src='/images/loading.gif' width='16' height='16' border='0'></img><img src='/images/loading.gif' width='16' height='16' border='0'></img>";
		//var odiv = document.getElementById("groupcontent_"+id);
		//loadDivFromUrl("groupcontent_"+id,url,1);
		//alert(odiv.innerHTML);
		//if((odiv.innerHTML+'') == '')
		//	loadDivFromUrl("groupcontent_"+id,url,1);
		//else
			
			//odiv.innerHTML = "";

		
	//}
            function indssy()
            {   
                var mess = true;
                mess = validateInput("selone_check","CHECK[]","abc");
                if(mess)
                    {
                         document.frm.action="/vanbansaoy/index/indssy";
                         document.frm.submit();
                    }
                else {
                    alert('Hãy chọn ít nhất 1 văn bản để in');
                }
            }
            function BackButtonClick()
            {
                document.frm.action="/vanbansaoy/index/list";
		document.frm.submit();
            }
            function danhsachsaoy()
            {
                document.frm.action="/vanbansaoy/index/danhsachsaoy";
		document.frm.submit();
            }
		function SwapDiv(id,url,tab){
		for(var i=1;i<11;i++){
			if(document.getElementById("groupicon"+i+"_"+id)){
				if(tab!=i){
					if(document.getElementById("groupicon"+i+"_"+id).className=="groupiconopen"){
						document.getElementById("groupcontent"+id).style.display="none";
						document.getElementById("groupicon"+i+"_"+id).className = "groupicon";
						break;
					}
				}
			}
		}
		if(document.getElementById("groupcontent"+id).style.display==""){
			document.getElementById("groupcontent"+id).style.display="none";
			document.getElementById("groupicon"+tab+"_"+id).className = "groupicon";
		}else{
			document.getElementById("groupcontent"+id).style.display="";
			document.getElementById("groupicon"+tab+"_"+id).className = "groupiconopen";
			document.getElementById("groupcontent"+id).innerHTML="<img src='/images/loading.gif' width='16' height='16' border='0'></img<img src='/images/loading.gif' width='16' height='16' border='0'></img><img src='/images/loading.gif' width='16' height='16' border='0'></img><img src='/images/loading.gif' width='16' height='16' border='0'></img>";
			loadDivFromUrl("groupcontent"+id,url,1);

		}
		//document.getElementById("detailContent_"+id).style.display="none";
	}

	function AddNewButtonClick(){
		//document.URL = "/qtht/DanhMucCoQuan/input";
		document.frm.action="/vanbansaoy/index/input";
		document.frm.method="post";
		document.frm.submit();
		
	}
   
	 function updateImageNew(iddiv,id,is_ngtao){
	    	var oimg = document.getElementById(iddiv);
	    	if(oimg != null){
		    	
	                 
	    		if(oimg.style.display != 'none'){
		    	oimg.style.display = 'none';
		    	
		    	var AE = new AjaxEngine();
				var oXmlHttp = AE.createXMLHttp(); 	
			    			   
				var url = '/vanbansaoy/index/updatedadoc?is_nguoitao='+is_ngtao+'&ID_VBSY='+id+'';
				oXmlHttp.open('post', url , true);
			    oXmlHttp.setRequestHeader("Content-Type", "application/x-www-form-urlencoded");
			    oXmlHttp.onreadystatechange = function () { 
			        if (oXmlHttp.readyState == 4) { 
			        	if (oXmlHttp.status == 200) {             	
			            	//alert(oXmlHttp.responseText);
			        	} else { 
			            	
			            }            
			        } 
			    };  
			    oXmlHttp.send(null);   
	    		}
	    		
	    	}
		    
	    }
	 
	 function DeleteButtonClick()
	 {
	 	var ln = 0;
	 	var arr = document.getElementsByName('DEL[]');
	 	for(var i = 0 ; i < arr.length ;i++ )
	 	{
	 		
	 		if(arr[i].checked == true)
	 		{
	 			ln = 1;
	 			break;
	 		}
	 	}
	 	if(ln == 1)
	 	{
	 		if(confirm("<?php echo "Bạn có muốn xóa không"; ?>")){
	 			//document.URL=
	 			document.frm.action="/vanbansaoy/index/delete";
	 			document.frm.method="post";
	 			document.frm.submit();
	 		}
	 	}
	 	else
	 	{
	 		alert("Bạn phải một dòng chọn để xóa");
	 	}
	 }
  
	     
  function setpheduyet(id){
	 
	  if(confirm( "Chấp nhận đồng ý phê duyệt")){

			//alert(1);
			
		    var AE = new AjaxEngine();
			var oXmlHttp = AE.createXMLHttp(); 		     
			var url = '/vanbansaoy/index/setpheduyet?ID_VBSY='+id;

			oXmlHttp.open('get', url , true);
			oXmlHttp.setRequestHeader("Content-Type", "application/x-www-form-urlencoded");
			  oXmlHttp.onreadystatechange = function () { 
			        if (oXmlHttp.readyState == 4) { 
			        	if (oXmlHttp.status == 200) {             	
			            	
			            	if(oXmlHttp.responseText == 1){
			            		alert("Chấp nhận thành công.");
			            		window.location = "/vanbansaoy/index/list";
     							return;
				            	}
			            	else{
			            		if(oXmlHttp.responseText == 2){
			            			alert("Chấp nhận không thành công.");
				            		                          }
				            	
				            	}
			        	} else { 
			            	
			            }            
			        } 
			    };  
			oXmlHttp.send(null);   
		   
  		}
  	
	  
  }	       

   
   </script>
