<? header("Cache-Control: max-age=600"); ?>
<script src="/js/validate.js" type="text/javascript"></script>
<!-- Khung lọc dữ liệu -->
<div>
<form name=frm action="/lichcttext/index/searchview" method="POST" target="reportview"  >
<div class=clr></div>
<div>
<div>
<label><b>Nội dung tìm kiếm :</b></label>
<input style="width: 25%" type="text" name="noidung" value="<?=$this->noidung?>">
<span class="box_erro_area" id="ERRnoidung"></span>
</div>
<div class=clr></div>     
<div>
<label><b>Trong</b></label>
<select name=TYPE>
        <option value="noidung" selected="selected">Nội Dung</option>
        <option value="thanhphan" >Thành phần</option>
        <option value="diadiem" >Địa điểm</option>
    </select>
</div>    
<div class=clr></div>
<div>
<label><b>Buổi</b></label>
<select name=buoi>
        <option value="0" selected="selected">Tất cả</option>
        <option value="1" >Sáng</option>
        <option value="2" >Chiều</option>
    </select>
</div>    
<div class=clr></div>
<div>
    <label><b>Kiểu lịch công tác</b></label>
    <select name=LCTTYPE onchange="lcttype(this);">        
        <option value="personaltype" selected="selected">Cá nhân</option>
        <option value="deptype">Phòng</option>
        <option value="corptype">Cơ quan</option>
    </select>    
</div>
<div class=clr></div>
<? global $auth;
   $user = $auth->GetIdentity();
   $isleader = $user->ISLEADER;
//   print_r($user);
$actid = ResourceUserModel::getActionByUrl("lichcttext","index","savep");
if(ResourceUserModel::isAcionAlowed($user->USERNAME,$actid[0]) && $isleader>0){			?>
<div id="personaltype" style="display: ">
<label><b>Chọn người</b></label>    
<?=QLVBDHCommon::writeSelectDepartmentUserWithSelAndAction("ID_DEP","ID_U",$this->ID_U,1)?>
<script>document.frm.ID_DEP.value="<?=$this->ID_DEP?>";
FillComboByComboWithSel(document.frm.ID_DEP,document.getElementById("ID_U"),ARR_ID_U,<?=$this->ID_U?>);
</script>    
</div>
<? } else {?>
<div id="personaltype" style="display: ">
<input type="hidden" name="ID_U" value="<?=$this->ID_U?>">
<input type="hidden" name="ID_DEP" value="<?=$this->ID_DEP?>">
</div>
<? } ?>
<div class=clr></div>
<? 
$actid = ResourceUserModel::getActionByUrl("lichcttext","index","saved");
if(ResourceUserModel::isAcionAlowed($user->USERNAME,$actid[0]) && $user->ID_DEP == $this->ID_DEP && $isleader>0){
?>
<div id="deptype" style="display: none">
<label><b>Chọn phòng</b></label>    
<select name=ID_DEP2>
<?php foreach($this->dep as $dep){?>
<option value=<?=$dep['ID_DEP']?> <?=$user->ID_DEP==$dep['ID_DEP']?"selected=selected":""?>><?=str_repeat("--",$dep['LEVEL']-1)?><?=$dep['NAME']?></option>
<?php } ?>
</select>    
</div>
<? } else {?>
<div id="deptype" style="display: none">    
<input type="hidden" name=ID_DEP2 value="<?=$user->ID_DEP?>">
</div>
<? } ?>
<div class=clr></div>
<label><b>Từ:</b></label>
<?=QLVBDHCommon::calendar($this->fromdate,"fromdate","fromdate") ?>
<script> function ChangeDate(){
	document.getElementById('time').value ="";        
}  </script>
>>
<?=QLVBDHCommon::calendar($this->todate,"todate","todate") ?>
<script> function ChangeDate(){
	document.getElementById('time').value ="";
	}</script>
</div>
<div class=clr></div>
<div>

<label>Tháng</label>
<input type="radio" name='sel_timedis' onclick="setvalueDateD('1/1','31/1')">1
<?php 
$year = QLVBDHCommon::getYear();
$d = strtotime($year."-3-1") ;
$d = $d - 86400;
$str_cuoi2 =date('d/m',$d); 
 ?>
<input type="radio" name='sel_timedis' onclick="setvalueDateD('1/2','<?php echo $str_cuoi2 ?>')" >2
<input type="radio" name='sel_timedis' onclick="setvalueDateD('1/3','31/3')">3
<input type="radio" name='sel_timedis'onclick="setvalueDateD('1/4','30/4')" >4
<input type="radio" name='sel_timedis'onclick="setvalueDateD('1/5','31/5')">5
<input type="radio" name='sel_timedis' onclick="setvalueDateD('1/6','30/6')">6
<input type="radio" name='sel_timedis'onclick="setvalueDateD('1/7','31/7')" >7
<input type="radio" name='sel_timedis'onclick="setvalueDateD('1/8','31/8')" >8
<input type="radio" name='sel_timedis'onclick="setvalueDateD('1/9','30/9')">9
<input type="radio" name='sel_timedis'onclick="setvalueDateD('1/10','31/10')">10
<input type="radio" name='sel_timedis'onclick="setvalueDateD('1/11','30/11')">11
<input type="radio" name='sel_timedis'onclick="setvalueDateD('1/12','31/12')">12
</div>
<div class=clr></div>
<div>
<label>Quí:</label>
<input type="radio" name='sel_timedis' onclick="setvalueDateD('1/1','31/3')">I
<input type="radio" name='sel_timedis' onclick="setvalueDateD('1/4','30/6')">II
<input type="radio" name='sel_timedis'onclick="setvalueDateD('1/7','30/9')">III
<input type="radio" name='sel_timedis'onclick="setvalueDateD('1/10','31/12')">IV
</div>
<div class=clr></div>

<div>
<label>Năm:</label>
<input type="radio" name='sel_timedis' onclick="setvalueDateD('1/1','31/12')">
</div>
<div class=clr></div>
<div>
    <label><b>Sắp xếp nội dung:</b></label>
    <select name=SORTTYPE>
        <option value="ASC">Tăng dần</option>
        <option value="DESC" >Giảm dần</option>
    </select>
</div>
<div class="clr"></div>
<div>
<label><b></b></label>
<input type="button" title="Tìm kiếm nội dung lịch công tác" style="background: url(/images/hscv-input-bg.png) repeat-x;" 
onclick="searchsubmit();
return false;" value="Tìm kiếm">
</div>
<div class="clr"></div>
<input type=hidden id=time name=time value="">
</form>

</div>
<div class="clr"></div>
<iframe style="overflow-x:visible" allowTransparency=true BORDER=0 scrolling=no FRAMEBORDER=no id="reportview" name="reportview" >
</iframe>

<script>
var arr_user = new Array();
function setvalueDateD(value_from,value_to){
	document.frm.fromdate.value = value_from;
	document.frm.todate.value = value_to;
}
 function order(sxtrichyeu)
 {
     alert(sctrichyeu);
     document.frm.submit();
 }
 function lcttype(val) {
//     alert(val.value);
     if (val.value=='personaltype') {
         document.getElementById('personaltype').style.display = "";
         document.getElementById('deptype').style.display = "none";
     }
     else
     if (val.value=='deptype') {
         document.getElementById('personaltype').style.display = "none";
         document.getElementById('deptype').style.display = "";
     }
     else
     if (val.value=='corptype') {
         document.getElementById('personaltype').style.display = "none";
         document.getElementById('deptype').style.display = "none";
     }
 }
 function checkFormData() {
     var str="Nội dung tìm kiếm tối thiểu 4 ký tự";
     var strerr = validateInput("minlen=4",document.frm.noidung,str);
	if(!strerr){		
		document.frm.noidung.focus();
		return false;
	}     
	return true;
 }
 function searchsubmit() {
     if (checkFormData()) {
         document.frm.target='reportview';
         document.frm.action = '/lichcttext/index/searchview';
         document.frm.submit();
     }
 }
</script>