<?php
$weekday = array("Chủ nhật","Thứ hai","Thứ ba","Thứ tư","Thứ năm","Thứ sáu","Thứ bảy");
?>
<html xmlns:v="urn:schemas-microsoft-com:vml"
xmlns:o="urn:schemas-microsoft-com:office:office"
xmlns:x="urn:schemas-microsoft-com:office:excel"
xmlns="http://www.w3.org/TR/REC-html40">

<head>
<meta http-equiv=Content-Type content="text/html; charset=utf-8">
<meta name=ProgId content=Excel.Sheet>
<meta name=Generator content="Microsoft Excel 12">
<link rel=File-List href="Book1_files/filelist.xml">
<!--[if !mso]>
<style>
v\:* {behavior:url(#default#VML);}
o\:* {behavior:url(#default#VML);}
x\:* {behavior:url(#default#VML);}
.shape {behavior:url(#default#VML);}
</style>
<![endif]-->
<style id="Book1_32500_Styles">
<!--table
	{mso-displayed-decimal-separator:"\.";
	mso-displayed-thousand-separator:"\,";}
.font532500
	{color:black;
	font-size:13.0pt;
	font-weight:400;
	font-style:normal;
	text-decoration:none;
	font-family:"Times New Roman", serif;
	mso-font-charset:0;}
.xl6332500
	{padding:0px;
	mso-ignore:padding;
	color:black;
	font-size:18.0pt;
	font-weight:700;
	font-style:normal;
	text-decoration:none;
	font-family:"Times New Roman", serif;
	mso-font-charset:0;
	mso-number-format:General;
	text-align:center;
	vertical-align:bottom;
	mso-background-source:auto;
	mso-pattern:auto;
	white-space:normal;}
.xl6432500
	{padding:0px;
	mso-ignore:padding;
	color:black;
	font-size:13.0pt;
	font-weight:400;
	font-style:normal;
	text-decoration:none;
	font-family:"Times New Roman", serif;
	mso-font-charset:0;
	mso-number-format:General;
	text-align:center;
	vertical-align:bottom;
	mso-background-source:auto;
	mso-pattern:auto;
	white-space:nowrap;}
.xl6532500
	{padding:0px;
	mso-ignore:padding;
	color:black;
	font-size:13.0pt;
	font-weight:400;
	font-style:normal;
	text-decoration:none;
	font-family:"Times New Roman", serif;
	mso-font-charset:0;
	mso-number-format:General;
	text-align:general;
	vertical-align:bottom;
	mso-background-source:auto;
	mso-pattern:auto;
	white-space:nowrap;}
.xl6632500
	{padding:0px;
	mso-ignore:padding;
	color:black;
	font-size:13.0pt;
	font-weight:700;
	font-style:normal;
	text-decoration:none;
	font-family:"Times New Roman", serif;
	mso-font-charset:0;
	mso-number-format:General;
	text-align:center;
	vertical-align:bottom;
	mso-background-source:auto;
	mso-pattern:auto;
	white-space:nowrap;}
.xl6732500
	{padding:0px;
	mso-ignore:padding;
	color:black;
	font-size:13.0pt;
	font-weight:400;
	font-style:normal;
	text-decoration:none;
	font-family:"Times New Roman", serif;
	mso-font-charset:0;
	mso-number-format:General;
	text-align:center;
	vertical-align:bottom;
	mso-background-source:auto;
	mso-pattern:auto;
	white-space:normal;}
.xl6832500
	{padding:0px;
	mso-ignore:padding;
	color:black;
	font-size:13.0pt;
	font-weight:400;
	font-style:italic;
	text-decoration:none;
	font-family:"Times New Roman", serif;
	mso-font-charset:0;
	mso-number-format:General;
	text-align:center;
	vertical-align:bottom;
	mso-background-source:auto;
	mso-pattern:auto;
	white-space:nowrap;}
.xl6932500
	{padding:0px;
	mso-ignore:padding;
	color:black;
	font-size:13.0pt;
	font-weight:700;
	font-style:normal;
	text-decoration:none;
	font-family:"Times New Roman", serif;
	mso-font-charset:0;
	mso-number-format:General;
	text-align:general;
	vertical-align:bottom;
	border-top:.5pt solid windowtext;
	border-right:.5pt solid windowtext;
	border-bottom:none;
	border-left:.5pt solid windowtext;
	mso-background-source:auto;
	mso-pattern:auto;
	white-space:nowrap;}
.xl7032500
	{padding:0px;
	mso-ignore:padding;
	color:black;
	font-size:13.0pt;
	font-weight:700;
	font-style:normal;
	text-decoration:none;
	font-family:"Times New Roman", serif;
	mso-font-charset:0;
	mso-number-format:General;
	text-align:general;
	vertical-align:bottom;
	border-top:.5pt solid windowtext;
	border-right:.5pt solid windowtext;
	border-bottom:.5pt solid windowtext;
	border-left:none;
	mso-background-source:auto;
	mso-pattern:auto;
	white-space:normal;}
.xl7132500
	{padding:0px;
	mso-ignore:padding;
	color:black;
	font-size:13.0pt;
	font-weight:400;
	font-style:normal;
	text-decoration:none;
	font-family:"Times New Roman", serif;
	mso-font-charset:0;
	mso-number-format:General;
	text-align:left;
	vertical-align:top;
	border:.5pt solid windowtext;
	mso-background-source:auto;
	mso-pattern:auto;
	white-space:normal;}
.xl7232500
	{padding:0px;
	mso-ignore:padding;
	color:black;
	font-size:13.0pt;
	font-weight:700;
	font-style:normal;
	text-decoration:none;
	font-family:"Times New Roman", serif;
	mso-font-charset:0;
	mso-number-format:"dd\\-mmm";
	text-align:general;
	vertical-align:bottom;
	border-top:none;
	border-right:.5pt solid windowtext;
	border-bottom:.5pt solid windowtext;
	border-left:.5pt solid windowtext;
	mso-background-source:auto;
	mso-pattern:auto;
	white-space:nowrap;}
.xl7332500
	{padding:0px;
	mso-ignore:padding;
	color:black;
	font-size:13.0pt;
	font-weight:700;
	font-style:normal;
	text-decoration:none;
	font-family:"Times New Roman", serif;
	mso-font-charset:0;
	mso-number-format:General;
	text-align:general;
	vertical-align:bottom;
	border-top:.5pt solid windowtext;
	border-right:.5pt solid windowtext;
	border-bottom:.5pt solid windowtext;
	border-left:none;
	background:#CFCFCF;
	mso-pattern:black none;
	white-space:normal;}
.xl7432500
	{padding:0px;
	mso-ignore:padding;
	color:black;
	font-size:13.0pt;
	font-weight:700;
	font-style:normal;
	text-decoration:none;
	font-family:"Times New Roman", serif;
	mso-font-charset:0;
	mso-number-format:General;
	text-align:left;
	vertical-align:bottom;
	mso-background-source:auto;
	mso-pattern:auto;
	white-space:nowrap;}
.xl7532500
	{padding:0px;
	mso-ignore:padding;
	color:black;
	font-size:13.0pt;
	font-weight:400;
	font-style:normal;
	text-decoration:underline;
	text-underline-style:single;
	font-family:"Times New Roman", serif;
	mso-font-charset:0;
	mso-number-format:General;
	text-align:left;
	vertical-align:bottom;
	mso-background-source:auto;
	mso-pattern:auto;
	white-space:normal;}
.xl7632500
	{padding:0px;
	mso-ignore:padding;
	color:black;
	font-size:13.0pt;
	font-weight:700;
	font-style:normal;
	text-decoration:none;
	font-family:"Times New Roman", serif;
	mso-font-charset:0;
	mso-number-format:General;
	text-align:general;
	vertical-align:top;
	mso-background-source:auto;
	mso-pattern:auto;
	white-space:nowrap;}
.xl7732500
	{padding:0px;
	mso-ignore:padding;
	color:black;
	font-size:13.0pt;
	font-weight:700;
	font-style:normal;
	text-decoration:none;
	font-family:"Times New Roman", serif;
	mso-font-charset:0;
	mso-number-format:General;
	text-align:center;
	vertical-align:top;
	mso-background-source:auto;
	mso-pattern:auto;
	white-space:nowrap;}
.xl7832500
	{padding:0px;
	mso-ignore:padding;
	color:black;
	font-size:13.0pt;
	font-weight:400;
	font-style:normal;
	text-decoration:none;
	font-family:"Times New Roman", serif;
	mso-font-charset:0;
	mso-number-format:General;
	text-align:left;
	vertical-align:bottom;
	mso-background-source:auto;
	mso-pattern:auto;
	white-space:normal;}
.xl7932500
	{padding:0px;
	mso-ignore:padding;
	color:black;
	font-size:13.0pt;
	font-weight:400;
	font-style:normal;
	text-decoration:none;
	font-family:"Times New Roman", serif;
	mso-font-charset:0;
	mso-number-format:General;
	text-align:general;
	vertical-align:middle;
	border-top:.5pt solid windowtext;
	border-right:.5pt solid windowtext;
	border-bottom:none;
	border-left:.5pt solid windowtext;
	background:#CFCFCF;
	mso-pattern:black none;
	white-space:normal;}
.xl8032500
	{padding:0px;
	mso-ignore:padding;
	color:black;
	font-size:13.0pt;
	font-weight:400;
	font-style:normal;
	text-decoration:none;
	font-family:"Times New Roman", serif;
	mso-font-charset:0;
	mso-number-format:General;
	text-align:general;
	vertical-align:middle;
	border:.5pt solid windowtext;
	background:#CFCFCF;
	mso-pattern:black none;
	white-space:normal;}
.xl8132500
	{padding:0px;
	mso-ignore:padding;
	color:black;
	font-size:13.0pt;
	font-weight:700;
	font-style:normal;
	text-decoration:none;
	font-family:"Times New Roman", serif;
	mso-font-charset:0;
	mso-number-format:General;
	text-align:center;
	vertical-align:middle;
	border:.5pt solid windowtext;
	background:#CFCFCF;
	mso-pattern:black none;
	white-space:normal;}
-->
</style>
</head>

<body>
<!--[if !excel]>&nbsp;&nbsp;<![endif]-->
<!--The following information was generated by Microsoft Office Excel's Publish
as Web Page wizard.-->
<!--If the same item is republished from Excel, all information between the DIV
tags will be replaced.-->
<!----------------------------->
<!--START OF OUTPUT FROM EXCEL PUBLISH AS WEB PAGE WIZARD -->
<!----------------------------->

<div id="Book1_32500" align=center x:publishsource="Excel">

<table border=0 cellpadding=0 cellspacing=0 width=882 class=xl6532500
 style='border-collapse:collapse;table-layout:fixed;width:664pt'>
 <col class=xl6532500 width=62 style='mso-width-source:userset;mso-width-alt:
 2267;width:47pt'>
 <col class=xl6532500 width=15 style='mso-width-source:userset;mso-width-alt:
 548;width:11pt'>
 <col class=xl6532500 width=118 span=2 style='mso-width-source:userset;
 mso-width-alt:4315;width:89pt'>
 <col class=xl6532500 width=29 style='mso-width-source:userset;mso-width-alt:
 1060;width:22pt'>
 <col class=xl6532500 width=25 style='mso-width-source:userset;mso-width-alt:
 914;width:19pt'>
 <col class=xl6532500 width=67 style='mso-width-source:userset;mso-width-alt:
 2450;width:50pt'>
 <col class=xl6532500 width=143 style='mso-width-source:userset;mso-width-alt:
 5229;width:107pt'>
 <col class=xl6532500 width=114 style='mso-width-source:userset;mso-width-alt:
 4169;width:86pt'>
 <col class=xl6532500 width=54 style='mso-width-source:userset;mso-width-alt:
 1974;width:41pt'>
 <col class=xl6532500 width=137 style='mso-width-source:userset;mso-width-alt:
 5010;width:103pt'>
 <tr height=22 style='height:16.5pt'>
  <td colspan=4 height=22 class=xl6432500 width=313 style='height:16.5pt;
  width:236pt'><?=$this->config->sys_info->unit?></td>
  <td class=xl6432500 width=29 style='width:22pt'></td>
  <td class=xl6432500 width=25 style='width:19pt'></td>
  <td class=xl6532500 width=67 style='width:50pt'></td>
  <td colspan=4 class=xl6632500 width=448 style='width:337pt'>CỘNG HÒA XÃ HỘI
  CHỦ NGHĨA VIỆT NAM</td>
 </tr>
 <tr height=22 style='height:16.5pt'>
  <td colspan=4 height=22 class=xl6632500 style='height:16.5pt'><?=$this->config->sys_info->company?></td>
  <td class=xl6632500></td>
  <td class=xl6632500></td>
  <td class=xl6532500></td>
  <td colspan=4 class=xl6632500>Độc lập - Tự do - Hạnh phúc</td>
 </tr>
 <tr height=22 style='height:16.5pt'>
  <td colspan=4 height=22 class=xl6432500 style='height:16.5pt'>--------------------------</td>
  <td class=xl6432500></td>
  <td class=xl6432500></td>
  <td class=xl6532500></td>
  <td colspan=4 class=xl6432500>--------------------------</td>
 </tr>
 <tr height=22 style='height:16.5pt'>
  <td height=22 class=xl6432500 style='height:16.5pt'></td>
  <td class=xl6732500 width=15 style='width:11pt'></td>
  <td class=xl6532500></td>
  <td class=xl6532500></td>
  <td class=xl6532500></td>
  <td class=xl6532500></td>
  <td class=xl6532500></td>
  <td colspan=4 class=xl6832500><?=$this->config->sys_info->city?>, ngày <?=date("d")?> tháng <?=date("m")?> năm <?=date("Y")?></td>
 </tr>
 <tr height=62 style='mso-height-source:userset;height:46.5pt'>
  <td colspan=11 height=62 class=xl6332500 width=882 style='height:46.5pt;
  width:664pt'>LỊCH CÔNG TÁC TUẦN <?=substr($this->week,4,2)?></td>
 </tr>
 <tr height=48 style='mso-height-source:userset;height:36.0pt'>
  <td colspan=11 height=48 class=xl6732500 width=882 style='height:36.0pt;
  width:664pt'>(Từ ngày <?=$this->begindate?> đến ngày <?=$this->enddate?>)</td>
 </tr>
 <tr height=44 style='height:33.0pt'>
  <td colspan=2 height=44 class=xl7932500 width=77 style='border-bottom:.5pt solid black;
  height:33.0pt;width:58pt'>&nbsp;</td>
  <td class=xl8132500 width=118 style='border-left:none;width:89pt'>Thời gian</td>
  <td colspan=4 class=xl8132500 width=239 style='border-left:none;width:180pt'>Nội
  dung công việc</td>
  <td class=xl8132500 width=143 style='border-left:none;width:107pt'>Chủ trì</td>
  <td class=xl8132500 width=114 style='border-left:none;width:86pt'>Thành phần</td>
  <td class=xl8132500 width=54 style='border-left:none;width:41pt'>Địa điểm</td>
  <td class=xl8132500 width=137 style='border-left:none;width:103pt'>Đơn vị
  chuẩn bị</td>
 </tr>
 <?php
 for($i=0;$i<7;$i++){
	 $rowspanall = (count($this->data[$i][1])>0?count($this->data[$i][1]):1) + (count($this->data[$i][2])>0?count($this->data[$i][2]):1);
 ?>
 <tr height=22 style='height:16.5pt'>
  <td height=22 class=xl6932500 style='height:16.5pt;border-bottom:1px' rowspan=<?=$rowspanall?>>
	<?=$weekday[$this->data[$i][0][0]]?><br>&nbsp;<?=$this->data[$i][0][1]?>
  </td>
  <td class=xl7032500 width=15 style='border-top:none;width:11pt' rowspan=<?=(count($this->data[$i][1])>0?count($this->data[$i][1]):1)?>>S</td>
  <td class=xl7132500 width=118 style='border-top:none;border-left:none;
  width:89pt'>&nbsp;<?=$this->data[$i][1][0]['THOIGIAN']?></td>
  <td colspan=4 class=xl7132500 width=239 style='border-left:none;width:180pt'>&nbsp;<?=$this->data[$i][1][0]['NOIDUNG']?></td>
  <td class=xl7132500 width=143 style='border-top:none;border-left:none;
  width:107pt'>&nbsp;<?=$this->data[$i][1][0]['CHUTRI']?></td>
  <td class=xl7132500 width=114 style='border-top:none;border-left:none;
  width:86pt'>&nbsp;<?=$this->data[$i][1][0]['THANHPHAN']?></td>
  <td class=xl7132500 width=54 style='border-top:none;border-left:none;
  width:41pt'>&nbsp;<?=$this->data[$i][1][0]['DIADIEM']?></td>
  <td class=xl7132500 width=137 style='border-top:none;border-left:none;
  width:103pt'>&nbsp;<?=$this->data[$i][1][0]['GHICHU']?></td>
 </tr>
 <?php
	for($j=1;$j<count($this->data[$i][1]);$j++){
 ?>
<tr height=22 style='height:16.5pt'>
  <td class=xl7132500 width=118 style='border-top:none;border-left:none;
  width:89pt'>&nbsp;<?=$this->data[$i][1][$j]['THOIGIAN']?></td>
  <td colspan=4 class=xl7132500 width=239 style='border-left:none;width:180pt'>&nbsp;<?=$this->data[$i][1][$j]['NOIDUNG']?></td>
  <td class=xl7132500 width=143 style='border-top:none;border-left:none;
  width:107pt'>&nbsp;<?=$this->data[$i][1][$j]['CHUTRI']?></td>
  <td class=xl7132500 width=114 style='border-top:none;border-left:none;
  width:86pt'>&nbsp;<?=$this->data[$i][1][$j]['THANHPHAN']?></td>
  <td class=xl7132500 width=54 style='border-top:none;border-left:none;
  width:41pt'>&nbsp;<?=$this->data[$i][1][$j]['DIADIEM']?></td>
  <td class=xl7132500 width=137 style='border-top:none;border-left:none;
  width:103pt'>&nbsp;<?=$this->data[$i][1][$j]['GHICHU']?></td>
 </tr>
 <?php
	}
 ?>
 <tr height=22 style='height:16.5pt'>
  <td class=xl7332500 width=15 style='border-top:none;width:11pt' rowspan=<?=(count($this->data[$i][2])>0?count($this->data[$i][2]):1)?>>C</td>
  <td class=xl7132500 width=118 style='border-top:none;border-left:none;
  width:89pt'>&nbsp;<?=$this->data[$i][2][0]['THOIGIAN']?></td>
  <td colspan=4 class=xl7132500 width=239 style='border-left:none;width:180pt'>&nbsp;<?=$this->data[$i][2][0]['NOIDUNG']?></td>
  <td class=xl7132500 width=143 style='border-top:none;border-left:none;
  width:107pt'>&nbsp;<?=$this->data[$i][2][0]['CHUTRI']?></td>
  <td class=xl7132500 width=114 style='border-top:none;border-left:none;
  width:86pt'>&nbsp;<?=$this->data[$i][2][0]['THANHPHAN']?></td>
  <td class=xl7132500 width=54 style='border-top:none;border-left:none;
  width:41pt'>&nbsp;<?=$this->data[$i][2][0]['DIADIEM']?></td>
  <td class=xl7132500 width=137 style='border-top:none;border-left:none;
  width:103pt'>&nbsp;<?=$this->data[$i][2][0]['GHICHU']?></td>
 </tr>
  <?php
	for($j=1;$j<count($this->data[$i][2]);$j++){
 ?>
<tr height=22 style='height:16.5pt'>
  <td class=xl7132500 width=118 style='border-top:none;border-left:none;
  width:89pt'>&nbsp;<?=$this->data[$i][2][0]['THOIGIAN']?></td>
  <td colspan=4 class=xl7132500 width=239 style='border-left:none;width:180pt'>&nbsp;<?=$this->data[$i][2][0]['NOIDUNG']?></td>
  <td class=xl7132500 width=143 style='border-top:none;border-left:none;
  width:107pt'>&nbsp;<?=$this->data[$i][2][0]['CHUTRI']?></td>
  <td class=xl7132500 width=114 style='border-top:none;border-left:none;
  width:86pt'>&nbsp;<?=$this->data[$i][2][0]['THANHPHAN']?></td>
  <td class=xl7132500 width=54 style='border-top:none;border-left:none;
  width:41pt'>&nbsp;<?=$this->data[$i][2][0]['DIADIEM']?></td>
  <td class=xl7132500 width=137 style='border-top:none;border-left:none;
  width:103pt'>&nbsp;<?=$this->data[$i][2][0]['GHICHU']?></td>
 </tr>
 <?php
	}
 ?>
 <?php
 }
 ?>
 <tr height=22 style='height:16.5pt'>
  <td colspan=11 height=22 class=xl7432500 style='height:16.5pt'>Lịch công tác
  dự kiến tuần tới <?=substr($this->week,4,2)+1?><font class="font532500">:<?=nl2br(htmlspecialchars($this->DUKIEN))?></font></td>
 </tr>
 <tr height=22 style='height:16.5pt'>
  <td colspan=3 height=22 class=xl7532500 width=195 style='height:16.5pt;
  width:147pt'>Nơi gởi:</td>
  <td class=xl7532500 width=118 style='width:89pt'></td>
  <td class=xl7532500 width=29 style='width:22pt'></td>
  <td class=xl7532500 width=25 style='width:19pt'></td>
  <td class=xl6532500></td>
  <td class=xl7632500></td>
  <td colspan=3 class=xl7732500><?=$this->config->sys_info->company?></td>
 </tr>
 <tr height=22 style='height:16.5pt'>
  <td colspan=3 height=22 class=xl7832500 width=195 style='height:16.5pt;
  width:147pt'><?=nl2br(htmlspecialchars(str_replace("\\n","\r\n",$this->config->lct->noinhan)))?></td>
  <td class=xl7832500 width=118 style='width:89pt'></td>
  <td class=xl7832500 width=29 style='width:22pt'></td>
  <td class=xl7832500 width=25 style='width:19pt'></td>
  <td class=xl6532500></td>
  <td class=xl6532500></td>
  <td class=xl6532500></td>
  <td class=xl6532500></td>
  <td class=xl7632500></td>
 </tr>
 <tr height=22 style='height:16.5pt'>
  <td colspan=3 height=22 class=xl7832500 width=195 style='height:16.5pt;
  width:147pt'></td>
  <td class=xl7832500 width=118 style='width:89pt'></td>
  <td class=xl7832500 width=29 style='width:22pt'></td>
  <td class=xl7832500 width=25 style='width:19pt'></td>
  <td class=xl6532500></td>
  <td class=xl6532500></td>
  <td class=xl6532500></td>
  <td class=xl6532500></td>
  <td class=xl7632500></td>
 </tr>
 <tr height=22 style='height:16.5pt'>
  <td colspan=3 height=22 class=xl7832500 width=195 style='height:16.5pt;
  width:147pt'></td>
  <td class=xl7832500 width=118 style='width:89pt'></td>
  <td class=xl7832500 width=29 style='width:22pt'></td>
  <td class=xl7832500 width=25 style='width:19pt'></td>
  <td class=xl6532500></td>
  <td class=xl6532500></td>
  <td class=xl6532500></td>
  <td class=xl6532500></td>
  <td class=xl7632500></td>
 </tr>
 <tr height=22 style='height:16.5pt'>
  <td colspan=3 height=22 class=xl7832500 width=195 style='height:16.5pt;
  width:147pt'></td>
  <td class=xl7832500 width=118 style='width:89pt'></td>
  <td class=xl7832500 width=29 style='width:22pt'></td>
  <td class=xl7832500 width=25 style='width:19pt'></td>
  <td class=xl6532500></td>
  <td class=xl6532500></td>
  <td class=xl6532500></td>
  <td class=xl6532500></td>
  <td class=xl7632500></td>
 </tr>
 <![if supportMisalignedColumns]>
 <tr height=0 style='display:none'>
  <td width=62 style='width:47pt'></td>
  <td width=15 style='width:11pt'></td>
  <td width=118 style='width:89pt'></td>
  <td width=118 style='width:89pt'></td>
  <td width=29 style='width:22pt'></td>
  <td width=25 style='width:19pt'></td>
  <td width=67 style='width:50pt'></td>
  <td width=143 style='width:107pt'></td>
  <td width=114 style='width:86pt'></td>
  <td width=54 style='width:41pt'></td>
  <td width=137 style='width:103pt'></td>
 </tr>
 <![endif]>
</table>

</div>


<!----------------------------->
<!--END OF OUTPUT FROM EXCEL PUBLISH AS WEB PAGE WIZARD-->
<!----------------------------->
</body>

</html>
