<?php
$weekday = array("Chủ nhật","Thứ hai","Thứ ba","Thứ tư","Thứ năm","Thứ sáu","Thứ bảy");
?>
<html xmlns:v="urn:schemas-microsoft-com:vml"
xmlns:o="urn:schemas-microsoft-com:office:office"
xmlns:x="urn:schemas-microsoft-com:office:excel"
xmlns="http://www.w3.org/TR/REC-html40">
 
<head>
<meta http-equiv=Content-Type content="text/html; charset=utf-8">
<meta name=ProgId content=Excel.Sheet>
<meta name=Generator content="Microsoft Excel 11">
<link rel=File-List href="dd_files/filelist.xml">
<link rel=Edit-Time-Data href="dd_files/editdata.mso">
<link rel=OLE-Object-Data href="dd_files/oledata.mso">
<!--[if !mso]>
<style>
v\:* {behavior:url(#default#VML);}
o\:* {behavior:url(#default#VML);}
x\:* {behavior:url(#default#VML);}
.shape {behavior:url(#default#VML);}
</style>
<![endif]--><!--[if gte mso 9]><xml>
 <o:DocumentProperties>
  <o:Author>admin</o:Author>
  <o:LastAuthor>admin</o:LastAuthor>
  <o:LastPrinted>2012-07-04T06:47:35Z</o:LastPrinted>
  <o:Created>2012-07-03T06:46:41Z</o:Created>
  <o:LastSaved>2012-07-04T06:58:04Z</o:LastSaved>
  <o:Version>11.9999</o:Version>
 </o:DocumentProperties>
</xml><![endif]-->
<style> 
<!--table
	{mso-displayed-decimal-separator:"\.";
	mso-displayed-thousand-separator:"\,";}
@page
	{margin:.39in .17in .39in .14in;
	mso-header-margin:.28in;
	mso-footer-margin:.28in;
	mso-page-orientation:landscape;
	mso-horizontal-page-align:center;}
tr
	{mso-height-source:auto;}
col
	{mso-width-source:auto;}
br
	{mso-data-placement:same-cell;}
.style0
	{mso-number-format:General;
	text-align:general;
	vertical-align:bottom;
	white-space:nowrap;
	mso-rotate:0;
	mso-background-source:auto;
	mso-pattern:auto;
	color:windowtext;
	font-size:10.0pt;
	font-weight:400;
	font-style:normal;
	text-decoration:none;
	font-family:Arial;
	mso-generic-font-family:auto;
	mso-font-charset:0;
	border:none;
	mso-protection:locked visible;
	mso-style-name:Normal;
	mso-style-id:0;}
td
	{mso-style-parent:style0;
	padding:0px;
	mso-ignore:padding;
	color:windowtext;
	font-size:10.0pt;
	font-weight:400;
	font-style:normal;
	text-decoration:none;
	font-family:Arial;
	mso-generic-font-family:auto;
	mso-font-charset:0;
	mso-number-format:General;
	text-align:general;
	vertical-align:bottom;
	border:none;
	mso-background-source:auto;
	mso-pattern:auto;
	mso-protection:locked visible;
	white-space:nowrap;
	mso-rotate:0;}
.xl65
	{mso-style-parent:style0;
	font-family:"Times New Roman", serif;
	mso-font-charset:0;}
.xl66
	{mso-style-parent:style0;
	font-size:13.0pt;
	font-family:"Times New Roman", serif;
	mso-font-charset:0;}
.xl67
	{mso-style-parent:style0;
	font-size:13.0pt;
	font-family:"Times New Roman", serif;
	mso-font-charset:0;
	text-align:center;}
.xl68
	{mso-style-parent:style0;
	font-size:13.0pt;
	font-weight:700;
	font-family:"Times New Roman", serif;
	mso-font-charset:0;}
.xl69
	{mso-style-parent:style0;
	font-size:13.0pt;
	font-style:italic;
	font-family:"Times New Roman", serif;
	mso-font-charset:0;}
.xl70
	{mso-style-parent:style0;
	font-size:20.0pt;
	font-family:"Times New Roman", serif;
	mso-font-charset:0;}
.xl71
	{mso-style-parent:style0;
	font-size:13.0pt;
	font-family:"Times New Roman", serif;
	mso-font-charset:0;
	text-align:center;
	vertical-align:middle;
	border-top:none;
	border-right:.5pt solid windowtext;
	border-bottom:.5pt solid windowtext;
	border-left:none;
	background:silver;
	mso-pattern:auto none;}
.xl72
	{mso-style-parent:style0;
	font-size:13.0pt;
	font-family:"Times New Roman", serif;
	mso-font-charset:0;
	text-align:center;
	vertical-align:middle;
	border-top:none;
	border-right:.5pt solid windowtext;
	border-bottom:.5pt solid windowtext;
	border-left:none;}
.xl73
	{mso-style-parent:style0;
	font-size:13.0pt;
	font-family:"Times New Roman", serif;
	mso-font-charset:0;
	text-align:center;
	vertical-align:middle;
	border-top:none;
	border-right:.5pt solid windowtext;
	border-bottom:.5pt solid windowtext;
	border-left:.5pt solid windowtext;}
.xl74
	{mso-style-parent:style0;
	font-size:11.0pt;
	font-weight:700;
	font-family:"Times New Roman", serif;
	mso-font-charset:0;
	text-align:center;
	vertical-align:middle;
	border-top:.5pt solid windowtext;
	border-right:.5pt solid windowtext;
	border-bottom:none;
	border-left:.5pt solid windowtext;
	white-space:normal;}
.xl75
	{mso-style-parent:style0;
	font-size:11.0pt;
	font-weight:700;
	font-family:"Times New Roman", serif;
	mso-font-charset:0;
	text-align:center;
	vertical-align:middle;
	border-top:none;
	border-right:.5pt solid windowtext;
	border-bottom:.5pt solid windowtext;
	border-left:.5pt solid windowtext;
	white-space:normal;}
.xl76
	{mso-style-parent:style0;
	font-size:11.0pt;
	font-family:"Times New Roman", serif;
	mso-font-charset:0;
	vertical-align:middle;
	border-top:.5pt solid windowtext;
	border-right:none;
	border-bottom:.5pt solid windowtext;
	border-left:.5pt solid windowtext;
	white-space:normal;}
.xl77
	{mso-style-parent:style0;
	font-size:11.0pt;
	font-family:"Times New Roman", serif;
	mso-font-charset:0;
	vertical-align:middle;
	border-top:.5pt solid windowtext;
	border-right:none;
	border-bottom:.5pt solid windowtext;
	border-left:none;
	white-space:normal;}
.xl78
	{mso-style-parent:style0;
	font-size:11.0pt;
	font-family:"Times New Roman", serif;
	mso-font-charset:0;
	vertical-align:middle;
	border-top:.5pt solid windowtext;
	border-right:.5pt solid windowtext;
	border-bottom:.5pt solid windowtext;
	border-left:none;
	white-space:normal;}
.xl79
	{mso-style-parent:style0;
	font-size:11.0pt;
	font-weight:700;
	font-family:"Times New Roman", serif;
	mso-font-charset:0;
	text-align:center;
	vertical-align:middle;
	border-top:none;
	border-right:.5pt solid windowtext;
	border-bottom:none;
	border-left:.5pt solid windowtext;
	white-space:normal;}
.xl80
	{mso-style-parent:style0;
	font-size:11.0pt;
	font-weight:700;
	font-family:"Times New Roman", serif;
	mso-font-charset:0;
	text-align:center;
	vertical-align:middle;
	border-top:.5pt solid windowtext;
	border-right:none;
	border-bottom:.5pt solid windowtext;
	border-left:.5pt solid windowtext;
	background:gray;
	mso-pattern:auto none;}
.xl81
	{mso-style-parent:style0;
	font-size:11.0pt;
	font-weight:700;
	font-family:"Times New Roman", serif;
	mso-font-charset:0;
	text-align:center;
	vertical-align:middle;
	border-top:.5pt solid windowtext;
	border-right:.5pt solid windowtext;
	border-bottom:.5pt solid windowtext;
	border-left:none;
	background:gray;
	mso-pattern:auto none;}
.xl82
	{mso-style-parent:style0;
	font-size:11.0pt;
	font-weight:700;
	font-family:"Times New Roman", serif;
	mso-font-charset:0;
	text-align:center;
	vertical-align:middle;
	border-top:.5pt solid windowtext;
	border-right:none;
	border-bottom:.5pt solid windowtext;
	border-left:none;
	background:gray;
	mso-pattern:auto none;}
.xl83
	{mso-style-parent:style0;
	font-size:13.0pt;
	font-weight:700;
	font-family:"Times New Roman", serif;
	mso-font-charset:0;
	text-align:center;}
.xl84
	{mso-style-parent:style0;
	font-size:11.0pt;
	font-style:italic;
	font-family:"Times New Roman", serif;
	mso-font-charset:0;
	text-align:right;}
.xl85
	{mso-style-parent:style0;
	font-size:18.0pt;
	font-family:"Times New Roman", serif;
	mso-font-charset:0;
	text-align:center;}
-->
</style>
<!--[if gte mso 9]><xml>
 <x:ExcelWorkbook>
  <x:ExcelWorksheets>
   <x:ExcelWorksheet>
    <x:Name>Sheet1</x:Name>
    <x:WorksheetOptions>
     <x:Print>
      <x:ValidPrinterInfo/>
      <x:PaperSizeIndex>9</x:PaperSizeIndex>
      <x:Scale>92</x:Scale>
      <x:HorizontalResolution>600</x:HorizontalResolution>
      <x:VerticalResolution>600</x:VerticalResolution>
     </x:Print>
     <x:PageBreakZoom>60</x:PageBreakZoom>
     <x:Selected/>
     <x:TopRowVisible>6</x:TopRowVisible>
     <x:Panes>
      <x:Pane>
       <x:Number>3</x:Number>
       <x:ActiveRow>10</x:ActiveRow>
       <x:ActiveCol>3</x:ActiveCol>
       <x:RangeSelection>$D$11:$G$11</x:RangeSelection>
      </x:Pane>
     </x:Panes>
     <x:ProtectContents>False</x:ProtectContents>
     <x:ProtectObjects>False</x:ProtectObjects>
     <x:ProtectScenarios>False</x:ProtectScenarios>
    </x:WorksheetOptions>
   </x:ExcelWorksheet>
   <x:ExcelWorksheet>
    <x:Name>Sheet2</x:Name>
    <x:WorksheetOptions>
     <x:ProtectContents>False</x:ProtectContents>
     <x:ProtectObjects>False</x:ProtectObjects>
     <x:ProtectScenarios>False</x:ProtectScenarios>
    </x:WorksheetOptions>
   </x:ExcelWorksheet>
   <x:ExcelWorksheet>
    <x:Name>Sheet3</x:Name>
    <x:WorksheetOptions>
     <x:ProtectContents>False</x:ProtectContents>
     <x:ProtectObjects>False</x:ProtectObjects>
     <x:ProtectScenarios>False</x:ProtectScenarios>
    </x:WorksheetOptions>
   </x:ExcelWorksheet>
  </x:ExcelWorksheets>
  <x:WindowHeight>9015</x:WindowHeight>
  <x:WindowWidth>18195</x:WindowWidth>
  <x:WindowTopX>240</x:WindowTopX>
  <x:WindowTopY>90</x:WindowTopY>
  <x:ProtectStructure>False</x:ProtectStructure>
  <x:ProtectWindows>False</x:ProtectWindows>
 </x:ExcelWorkbook>
 <x:ExcelName>
  <x:Name>Print_Area</x:Name>
  <x:SheetIndex>1</x:SheetIndex>
  <x:Formula>=Sheet1!$B$1:$P$21</x:Formula>
 </x:ExcelName>
</xml><![endif]--><!--[if gte mso 9]><xml>
 <o:shapedefaults v:ext="edit" spidmax="2049"/>
</xml><![endif]--><!--[if gte mso 9]><xml>
 <o:shapelayout v:ext="edit">
  <o:idmap v:ext="edit" data="1"/>
 </o:shapelayout></xml><![endif]-->
</head>
 
<body link=blue vlink=purple class=xl65>
 
<table x:str border=0 cellpadding=0 cellspacing=0 width=1157 style='border-collapse:
 collapse;table-layout:fixed;width:871pt'>
 <col class=xl65 width=31 style='mso-width-source:userset;mso-width-alt:1133;
 width:23pt'>
 <col class=xl65 width=64 style='width:48pt'>
 <col class=xl65 width=22 style='mso-width-source:userset;mso-width-alt:804;
 width:17pt'>
 <col class=xl65 width=64 style='width:48pt'>
 <col class=xl65 width=74 style='mso-width-source:userset;mso-width-alt:2706;
 width:56pt'>
 <col class=xl65 width=69 style='mso-width-source:userset;mso-width-alt:2523;
 width:52pt'>
 <col class=xl65 width=147 style='mso-width-source:userset;mso-width-alt:5376;
 width:110pt'>
 <col class=xl65 width=94 style='mso-width-source:userset;mso-width-alt:3437;
 width:71pt'>
 <col class=xl65 width=62 style='mso-width-source:userset;mso-width-alt:2267;
 width:47pt'>
 <col class=xl65 width=42 style='mso-width-source:userset;mso-width-alt:1536;
 width:32pt'>
 <col class=xl65 width=81 style='mso-width-source:userset;mso-width-alt:2962;
 width:61pt'>
 <col class=xl65 width=72 style='mso-width-source:userset;mso-width-alt:2633;
 width:54pt'>
 <col class=xl65 width=52 style='mso-width-source:userset;mso-width-alt:1901;
 width:39pt'>
 <col class=xl65 width=62 style='mso-width-source:userset;mso-width-alt:2267;
 width:47pt'>
 <col class=xl65 width=59 style='mso-width-source:userset;mso-width-alt:2157;
 width:44pt'>
 <col class=xl65 width=98 style='mso-width-source:userset;mso-width-alt:3584;
 width:74pt'>
 <col class=xl65 width=64 style='width:48pt'>
 <tr height=22 style='height:16.5pt'>
  <td height=22 class=xl66 width=31 style='height:16.5pt;width:23pt'></td>
  <td colspan=5 class=xl67 width=293 style='width:221pt'><a name="Print_Area"><?=$this->config->sys_info->unit?></a></td>
  <td class=xl65 width=147 style='width:110pt'></td>
  <td class=xl65 width=94 style='width:71pt'></td>
  <td class=xl65 width=62 style='width:47pt'></td>
  <td colspan=7 class=xl83 width=466 style='width:351pt'>CỘNG HÒA XÃ
  HỘI CHỦ NGHĨA VIỆT NAM</td>
  <td class=xl68 width=64 style='width:48pt'></td>
 </tr>
 <tr height=22 style='height:16.5pt'>
  <td height=22 class=xl66 style='height:16.5pt'></td>
  <td colspan=5 class=xl83><?=$this->config->sys_info->company?></td>
  <td colspan=3 class=xl65 style='mso-ignore:colspan'></td>
  <td colspan=7 height=22 width=466 style='height:16.5pt;width:351pt'
  align=left valign=top><!--[if gte vml 1]><v:line id="Line_x0020_4" o:spid="_x0000_s1030"
   style='position:absolute;z-index:2;visibility:visible' from="116.25pt,16.5pt"
   to="235.5pt,16.5pt"/><![endif]--><![if !vml]><span style='mso-ignore:vglayout;
  position:absolute;z-index:2;margin-left:154px;margin-top:21px;width:161px;
  height:2px'><img width=161 height=2 src="dd_files/image001.gif" v:shapes="Line_x0020_4"></span><![endif]><span
  style='mso-ignore:vglayout2'>
  <table cellpadding=0 cellspacing=0>
   <tr>
    <td colspan=7 height=22 class=xl83 width=466 style='height:16.5pt;
    width:351pt'>Độc lập - Tự do - Hạnh phúc</td>
   </tr>
  </table>
  </span></td>
  <td class=xl68></td>
 </tr>
 <tr height=29 style='mso-height-source:userset;height:21.75pt'>
  <td height=29 class=xl66 style='height:21.75pt'></td>
  <td align=left valign=top><!--[if gte vml 1]><v:line id="Line_x0020_3"
   o:spid="_x0000_s1029" style='position:absolute;z-index:1;visibility:visible'
   from="48pt,3pt" to="168.75pt,3pt">
   <x:ClientData ObjectType="Line">
    <x:Anchor>
     1, 66, 2, 4, 5, 1, 2, 4</x:Anchor>
   </x:ClientData>
  </v:line><![endif]--><![if !vml]><span style='mso-ignore:vglayout;position:
  absolute;z-index:1;margin-left:63px;margin-top:3px;width:163px;height:2px'><img
  width=163 height=2 src="dd_files/image002.gif" v:shapes="Line_x0020_3"></span><![endif]><span
  style='mso-ignore:vglayout2'>
  <table cellpadding=0 cellspacing=0>
   <tr>
    <td height=29 class=xl66 width=64 style='height:21.75pt;width:48pt'></td>
   </tr>
  </table>
  </span></td>
  <td colspan=3 class=xl66 style='mso-ignore:colspan'></td>
  <td colspan=4 class=xl65 style='mso-ignore:colspan'></td>
  <td colspan=7 class=xl84><?=$this->config->sys_info->city?>, ngày <?=date("d")?> tháng <?=date("m")?> năm <?=date("Y")?></td>
  <td class=xl69></td>
 </tr>
 <tr height=22 style='height:16.5pt'>
  <td height=22 class=xl66 style='height:16.5pt'></td>
  <td class=xl67></td>
  <td class=xl66></td>
  <td colspan=14 class=xl65 style='mso-ignore:colspan'></td>
 </tr>
 <tr height=35 style='height:26.25pt'>
  <td height=35 colspan=4 class=xl65 style='height:26.25pt;mso-ignore:colspan'></td>
  <td class=xl70></td>
  <td colspan=7 class=xl85>LỊCH CÔNG TÁC TUẦN <?=substr($this->week,4,2)?></td>
  <td colspan=5 class=xl65 style='mso-ignore:colspan'></td>
 </tr>
 <tr height=22 style='height:16.5pt'>
  <td height=22 colspan=5 class=xl65 style='height:16.5pt;mso-ignore:colspan'></td>
  <td colspan=7 class=xl67>(Từ ngày <?=$this->begindate?> đến ngày <?=$this->enddate?>)</td>
  <td colspan=5 class=xl65 style='mso-ignore:colspan'></td>
 </tr>
 <tr height=17 style='height:12.75pt'>
  <td height=17 colspan=17 class=xl65 style='height:12.75pt;mso-ignore:colspan'></td>
 </tr>
 <tr height=31 style='mso-height-source:userset;height:23.25pt'>
  <td height=31 class=xl65 style='height:23.25pt'></td>
  <td colspan=2 class=xl80 style='border-right:.5pt solid black'>Thời gian</td>
  <td colspan=4 class=xl80 style='border-right:.5pt solid black;border-left:
  none'>Nội dung</td>
  <td colspan=3 class=xl80 style='border-right:.5pt solid black;border-left:
  none'>Thành phần</td>
  <td colspan=3 class=xl80 style='border-right:.5pt solid black;border-left:
  none'>Địa điểm</td>
  <td colspan=3 class=xl80 style='border-right:.5pt solid black;border-left:
  none'>Ghi chú</td>
  <td class=xl65></td>
 </tr>

 <?php
 for($i=0;$i<7;$i++){
	 $rowspanall = (count($this->data[$i][1])>0?count($this->data[$i][1]):1) + (count($this->data[$i][2])>0?count($this->data[$i][2]):1);
 ?>
 <tr height=29 style='mso-height-source:userset;height:21.75pt'>
  <td height=29 class=xl65 style='height:21.75pt'></td>
  <td rowspan=2 class=xl79 width=64 style='border-bottom:.5pt solid black;
  width:48pt' rowspan=<?=$rowspanall?>><?=$weekday[$this->data[$i][0][0]]?><br>&nbsp;<?=$this->data[$i][0][1]?></td>
  <td class=xl73 style='border-left:none' rowspan=<?=(count($this->data[$i][1])>0?count($this->data[$i][1]):1)?>>S</td>
  <td colspan=4 class=xl76 width=354 style='border-right:.5pt solid black;
  border-left:none;width:266pt'><?=$this->data[$i][1][0]['NOIDUNG']?></td>
  <td colspan=3 class=xl76 width=198 style='border-right:.5pt solid black;
  border-left:none;width:150pt'><?=$this->data[$i][1][0]['THANHPHAN']?></td>
  <td colspan=3 class=xl76 width=205 style='border-right:.5pt solid black;
  border-left:none;width:154pt'><?=$this->data[$i][1][0]['DIADIEM']?></td>
  <td colspan=3 class=xl76 width=219 style='border-right:.5pt solid black;
  border-left:none;width:165pt'><?=$this->data[$i][1][0]['GHICHU']?></td>
  <td class=xl65></td>
 </tr>

  <?php
	for($j=1;$j<count($this->data[$i][1]);$j++){
 ?>
 <tr height=29 style='mso-height-source:userset;height:21.75pt'>
  <td height=29 class=xl65 style='height:21.75pt'></td>
 <td colspan=4 class=xl76 width=354 style='border-right:.5pt solid black;
  border-left:none;width:266pt'><?=$this->data[$i][1][0]['NOIDUNG']?></td>
  <td colspan=3 class=xl76 width=198 style='border-right:.5pt solid black;
  border-left:none;width:150pt'><?=$this->data[$i][1][0]['THANHPHAN']?></td>
  <td colspan=3 class=xl76 width=205 style='border-right:.5pt solid black;
  border-left:none;width:154pt'><?=$this->data[$i][1][0]['DIADIEM']?></td>
  <td colspan=3 class=xl76 width=219 style='border-right:.5pt solid black;
  border-left:none;width:165pt'><?=$this->data[$i][1][0]['GHICHU']?></td>
  <td class=xl65></td>
 </tr>
 <?php
	}
 ?>

 <tr height=26 style='mso-height-source:userset;height:19.5pt'>
  <td height=26 class=xl65 style='height:19.5pt'></td>
  <td class=xl71 rowspan=<?=(count($this->data[$i][2])>0?count($this->data[$i][2]):1)?>>C</td>
  <td colspan=4 class=xl76 width=354 style='border-right:.5pt solid black;
  border-left:none;width:266pt'><?=$this->data[$i][2][0]['NOIDUNG']?></td>
  <td colspan=3 class=xl76 width=198 style='border-right:.5pt solid black;
  border-left:none;width:150pt'><?=$this->data[$i][2][0]['THANHPHAN']?></td>
  <td colspan=3 class=xl76 width=205 style='border-right:.5pt solid black;
  border-left:none;width:154pt'><?=$this->data[$i][2][0]['DIADIEM']?></td>
  <td colspan=3 class=xl76 width=219 style='border-right:.5pt solid black;
  border-left:none;width:165pt'><?=$this->data[$i][2][0]['GHICHU']?></td>
  <td class=xl65></td>
 </tr>

 <?php
	for($j=1;$j<count($this->data[$i][2]);$j++){
 ?>
  <tr height=26 style='mso-height-source:userset;height:19.5pt'>
  <td height=26 class=xl65 style='height:19.5pt'></td>
 <td colspan=4 class=xl76 width=354 style='border-right:.5pt solid black;
  border-left:none;width:266pt'><?=$this->data[$i][2][0]['NOIDUNG']?></td>
  <td colspan=3 class=xl76 width=198 style='border-right:.5pt solid black;
  border-left:none;width:150pt'><?=$this->data[$i][2][0]['THANHPHAN']?></td>
  <td colspan=3 class=xl76 width=205 style='border-right:.5pt solid black;
  border-left:none;width:154pt'><?=$this->data[$i][2][0]['DIADIEM']?></td>
  <td colspan=3 class=xl76 width=219 style='border-right:.5pt solid black;
  border-left:none;width:165pt'><?=$this->data[$i][2][0]['GHICHU']?></td>
  <td class=xl65></td>
  </tr>
 <?php
  }
 ?>
 <?php
 }
 ?> 
 <![if supportMisalignedColumns]>
 <tr height=0 style='display:none'>
  <td width=31 style='width:23pt'></td>
  <td width=64 style='width:48pt'></td>
  <td width=22 style='width:17pt'></td>
  <td width=64 style='width:48pt'></td>
  <td width=74 style='width:56pt'></td>
  <td width=69 style='width:52pt'></td>
  <td width=147 style='width:110pt'></td>
  <td width=94 style='width:71pt'></td>
  <td width=62 style='width:47pt'></td>
  <td width=42 style='width:32pt'></td>
  <td width=81 style='width:61pt'></td>
  <td width=72 style='width:54pt'></td>
  <td width=52 style='width:39pt'></td>
  <td width=62 style='width:47pt'></td>
  <td width=59 style='width:44pt'></td>
  <td width=98 style='width:74pt'></td>
  <td width=64 style='width:48pt'></td>
 </tr>
 <![endif]>
</table>
 
</body>
 
</html>

