<table class=adminlist>
	<thead>
		<tr>
			<th nowrap="nowrap">STT</th>
			<th width="100%">File hướng dẫn</th>
		</tr>
	</thead>
	<tbody>
		
		<tr>
			<td nowrap="nowrap">1</td>
			<td width="100%"><a href="/images/VBDH_LanhDaoCoQuan.pdf" target="_blank">Hướng dẫn sử dụng dành cho Lãnh đạo cơ quan</a></td>
		</tr>
		<tr>
			<td nowrap="nowrap">2</td>
			<td width="100%"><a href="/images/VBDH_LanhDaoPhong.pdf" target="_blank">Hướng dẫn sử dụng dành cho Lãnh đạo phòng</a></td>
		</tr>
		<tr>
			<td nowrap="nowrap">3</td>
			<td width="100%"><a href="/images/VBDH_ChuyenVien.pdf" target="_blank">Hướng dẫn sử dụng dành cho Chuyên viên</a></td>
		</tr>
		<tr>
			<td nowrap="nowrap">4</td>
			<td width="100%"><a href="/images/VBDH_VanThu.pdf" target="_blank">Hướng dẫn sử dụng dành cho Văn thư</a></td>
		</tr>
		<tr>
			<td nowrap="nowrap">5</td>
			<td width="100%"><a href="/images/CaseStudy.pdf" target="_blank">Tài liệu hướng dẫn thực hành</a></td>
		</tr>
		<tr>
			<td nowrap="nowrap">6</td>
			<td width="100%"><a href="/images/VBDH_QuanTriHeThong.pdf" target="_blank">Hướng dẫn sử dụng dành cho QTHT</a></td>
		</tr>
		
		<tr>
			<td nowrap="nowrap">7</td>
			<td width="100%"><a href="/images/Huong dan cai dat - UniSpace.pdf" target="_blank">Hướng dẫn cài đặt QLVBDH</a></td>
		</tr>
                
                <tr>
			<td nowrap="nowrap">8</td>
			<td width="100%"><a href="/images/VBDH_Huong dan cai dat Alert.pdf" target="_blank">Hướng dẫn cài đặt Alert</a></td>
		</tr>
                
                <tr>
			<td nowrap="nowrap">9</td>
			<td width="100%"><a href="/images/VBDH_TroubleShooting.pdf" target="_blank">Hướng dẫn xử lý các lỗi thường gặp</a></td>
		</tr>
                
                <tr>
			<td nowrap="nowrap">10</td>
			<td width="100%"><a href="/images/Cam nang cho So Nganh_Chuyenvien.pdf" target="_blank">Cẩm nang dành cho chuyên viên</a></td>
		</tr>
                
                <tr>
			<td nowrap="nowrap">11</td>
			<td width="100%"><a href="/images/Cam nang cho So Nganh_Lanhdaocoquan.pdf" target="_blank">Cẩm nang dành cho Lãnh đạo cơ quan </a></td>
		</tr>
                
                <tr>
			<td nowrap="nowrap">12</td>
			<td width="100%"><a href="/images/Cam nang cho So Nganh_Lanhdaophong,van phong.pdf" target="_blank">Cẩm nang dành cho Lãnh đạo văn phòng/Lãnh đạo phòng</a></td>
		</tr>     
            
        <tr>
			<td nowrap="nowrap">13</td>
			<td width="100%"><a href="/images/Cam nang cho So Nganh_Vanthu.pdf" target="_blank">Cẩm nang dành cho Văn thư</a></td>
		</tr>
   		
        <tr>
			<td nowrap="nowrap">15</td>
			<td width="100%"><a href="/images/QLVBDH_Setup.exe" target="_blank">File cài đặt trao đổi, thông báo, nhắc nhở</a></td>
		</tr>

		<tr>
			<td nowrap="nowrap">16</td>
			<td width="100%"><a href="/images/2003.exe" target="_blank">File cài đặt addin cho Word 2003</a></td>
		</tr>
		<tr>
			<td nowrap="nowrap">17</td>
			<td width="100%"><a href="/images/2007.exe" target="_blank">File cài đặt addin cho Word 2007</a></td>
		</tr>
		
			<tr>
			<td nowrap="nowrap">18</td>
			<td width="100%"><a href="http://qlvb.ubnd.binhthuan.gov.vn/images/CKS_Binhthuan.pdf" target="_blank">Hướng dẫn sử dụng chữ ký số</a></td>
		</tr>
		<tr>
			<td nowrap="nowrap">19</td>
			<td width="100%"><a href="http://qlvb.ubnd.binhthuan.gov.vn/images/VGCASignServiceSetup_v1.0.0.msi" target="_blank">Bộ cài đặt ứng dụng chữ ký số</a></td>
		</tr>
		<tr>
			<td nowrap="nowrap">20</td>
			<td width="100%"><a href="http://qlvb.ubnd.binhthuan.gov.vn/images/QLVBDH_NHIEMVU.pdf" target="_blank">Hướng dẫn sử dụng Quản lý nhiệm vụ </a></td>
		</tr>
	</tbody>
</table>
