<script type="text/javascript" src="/js/calendar.js"></script>
<link rel="stylesheet" type="text/css" href="/chosen/chosen.css" />
<script src="/jquery/jquery-1.10.2.js"></script>
<script src="/chosen/chosen.jquery.js"></script>
<script type="text/javascript">
var jq1102 = jQuery.noConflict( true );
</script>
<form name=frm action="/report/getinfo/reportview" method="POST" target="reportview">
<div class=clr></div>
<div>
<label><b>Ngày nhận:</b></label>
<?=QLVBDHCommon::calendar($this->fromdate,"fromdate","fromdate") ?>
>>
<?=QLVBDHCommon::calendar($this->todate,"todate","todate") ?>

</div>

<div class=clr></div>
<div>
<div>
<label><b>Tháng:</b></label>
<input type="radio" name='sel_timedis' onclick="setvalueDateD('1/1','31/1')">1
<?php 
$year = QLVBDHCommon::getYear();
$d = strtotime($year."-3-1") ;
$d = $d - 86400;
$str_cuoi2 =date('d/m',$d); 
 ?>
<input type="radio" name='sel_timedis' onclick="setvalueDateD('1/2','<?php echo $str_cuoi2 ?>')" >2
<input type="radio" name='sel_timedis' onclick="setvalueDateD('1/3','31/3')">3
<input type="radio" name='sel_timedis'onclick="setvalueDateD('1/4','30/4')" >4
<input type="radio" name='sel_timedis'onclick="setvalueDateD('1/5','31/5')">5
<input type="radio" name='sel_timedis' onclick="setvalueDateD('1/6','30/6')">6
<input type="radio" name='sel_timedis'onclick="setvalueDateD('1/7','31/7')" >7
<input type="radio" name='sel_timedis'onclick="setvalueDateD('1/8','31/8')" >8
<input type="radio" name='sel_timedis'onclick="setvalueDateD('1/9','30/9')">9
<input type="radio" name='sel_timedis'onclick="setvalueDateD('1/10','31/10')">10
<input type="radio" name='sel_timedis'onclick="setvalueDateD('1/11','30/11')">11
<input type="radio" name='sel_timedis'onclick="setvalueDateD('1/12','31/12')">12
</div>
<div class=clr></div>
<div>
<label><b>Quí:</b></label>
<input type="radio" name='sel_timedis' onclick="setvalueDateD('1/1','31/3')">I
<input type="radio" name='sel_timedis' onclick="setvalueDateD('1/4','30/6')">II
<input type="radio" name='sel_timedis'onclick="setvalueDateD('1/7','30/9')">III
<input type="radio" name='sel_timedis'onclick="setvalueDateD('1/10','31/12')">IV
</div>
<div class=clr></div>
<div>
<label><b>Năm:</b></label>
<input type="radio" name='sel_timedis' onclick="setvalueDateD('1/1','31/12')">
</div>
<div class=clr></div>
<div>
<label><b>Văn bản liên thông:</b></label>
<input type="checkbox" name="IS_LIENTHONG" value="1" />
</div>
<div class=clr></div>
<div>
<label><b>Cơ quan trong tỉnh:</b></label>
<?php
	require_once("qtht/models/CoQuanModel.php");
        echo "<select name='ID_CQ' id='ID_CQ' style='width:400px'>";
        echo "<option value=0>[Chọn tất cả]</option>";
        echo CoQuanModel::toComboNameCQLT();
        echo "</select>"
?>
</div>
<div class=clr></div>
<div>
<label></label>
<input type="button" value="Hiển thị" onclick="getinfo(),document.frm.target='reportview'">
<input type="button" value="Xuất excel" onclick="xuatexcel(),document.frm.target='reportview'">
</div>
<div class="clr"></div>
<input type=hidden id=h_isexel name=h_isexel value=0>
<div>
</div>
</form>
<iframe style="overflow-x:visible" allowTransparency=true BORDER=0 scrolling=no FRAMEBORDER=no 
id="reportview" 
name="reportview" >
</iframe>
<script>    
jq1102('#ID_CQ').chosen({
    placeholder_text_multiple:" ",
    no_results_text:"Không tìm thấy kết quả"
});
function setvalueDateD(value_from,value_to){
    document.frm.fromdate.value = value_from;
    document.frm.todate.value = value_to;
}
function getinfo()
{
    document.frm.h_isexel.value = 0;    
    document.frm.action = '/report/getinfo/reportview';
    document.frm.submit();
}
function xuatexcel()
{
    document.frm.h_isexel.value = 1;    
    document.frm.action = '/report/getinfo/reportviewexcel';
    document.frm.submit();
}
</script>
