<?php if($this->xuat==1) {?>
<html xmlns:v="urn:schemas-microsoft-com:vml"
xmlns:o="urn:schemas-microsoft-com:office:office"
xmlns:x="urn:schemas-microsoft-com:office:excel"
xmlns="http://www.w3.org/TR/REC-html40">

<head>
<meta http-equiv=Content-Type content="text/html; charset=utf-8">
<meta name=ProgId content=Excel.Sheet>
<meta name=Generator content="Microsoft Excel 11">
<link rel=File-List href="baocaovanbanden%201%20_files/filelist.xml">
<link rel=Edit-Time-Data href="baocaovanbanden%201%20_files/editdata.mso">
<link rel=OLE-Object-Data href="baocaovanbanden%201%20_files/oledata.mso">
<!--[if gte mso 9]><xml>
 <o:DocumentProperties>
  <o:Author>nguyennd</o:Author>
  <o:LastAuthor>User</o:LastAuthor>
  <o:LastPrinted>2009-12-24T23:53:13Z</o:LastPrinted>
  <o:Created>2009-08-25T14:43:47Z</o:Created>
  <o:LastSaved>2009-12-24T23:53:38Z</o:LastSaved>
  <o:Company>Hewlett-Packard</o:Company>
  <o:Version>11.9999</o:Version>
 </o:DocumentProperties>
</xml><![endif]-->
<style>
<!--table
	{mso-displayed-decimal-separator:"\.";
	mso-displayed-thousand-separator:"\,";}
@page
	{margin:.2in 1.44in .2in .2in;
	mso-header-margin:.2in;
	mso-footer-margin:.2in;
	mso-page-orientation:landscape;}
tr
	{mso-height-source:auto;}
col
	{mso-width-source:auto;}
br
	{mso-data-placement:same-cell;}
.style0
	{mso-number-format:General;
	text-align:general;
	vertical-align:bottom;
	white-space:nowrap;
	mso-rotate:0;
	mso-background-source:auto;
	mso-pattern:auto;
	color:windowtext;
	font-size:10.0pt;
	font-weight:400;
	font-style:normal;
	text-decoration:none;
	font-family:Arial;
	mso-generic-font-family:auto;
	mso-font-charset:0;
	border:none;
	mso-protection:locked visible;
	mso-style-name:Normal;
	mso-style-id:0;}
td
	{mso-style-parent:style0;
	padding-top:1px;
	padding-right:1px;
	padding-left:1px;
	mso-ignore:padding;
	color:windowtext;
	font-size:10.0pt;
	font-weight:400;
	font-style:normal;
	text-decoration:none;
	font-family:Arial;
	mso-generic-font-family:auto;
	mso-font-charset:0;
	mso-number-format:General;
	text-align:general;
	vertical-align:bottom;
	border:none;
	mso-background-source:auto;
	mso-pattern:auto;
	mso-protection:locked visible;
	white-space:nowrap;
	mso-rotate:0;}
.xl24
	{mso-style-parent:style0;
	font-size:12.0pt;
	font-family:"Times New Roman", serif;
	mso-font-charset:0;}
.xl25
	{mso-style-parent:style0;
	font-size:12.0pt;
	font-weight:700;
	font-family:"Times New Roman", serif;
	mso-font-charset:0;}
.xl26
	{mso-style-parent:style0;
	font-size:12.0pt;
	font-style:italic;
	font-family:"Times New Roman", serif;
	mso-font-charset:0;}
.xl27
	{mso-style-parent:style0;
	font-size:12.0pt;
	font-weight:700;
	font-family:"Times New Roman", serif;
	mso-font-charset:0;
	text-align:center;
	vertical-align:top;
	border:.5pt solid windowtext;
	background:silver;
	mso-pattern:auto none;
	white-space:normal;}
.xl28
	{mso-style-parent:style0;
	font-size:12.0pt;
	font-weight:700;
	font-family:"Times New Roman", serif;
	mso-font-charset:0;
	text-align:center;
	vertical-align:top;
	border-top:none;
	border-right:.5pt solid windowtext;
	border-bottom:.5pt solid windowtext;
	border-left:.5pt solid windowtext;
	background:silver;
	mso-pattern:auto none;
	white-space:normal;}
.xl29
	{mso-style-parent:style0;
	font-size:12.0pt;
	font-weight:700;
	font-family:"Times New Roman", serif;
	mso-font-charset:0;
	text-align:center;
	vertical-align:top;
	border-top:none;
	border-right:.5pt solid windowtext;
	border-bottom:.5pt solid windowtext;
	border-left:none;
	background:silver;
	mso-pattern:auto none;
	white-space:normal;}
.xl30
	{mso-style-parent:style0;
	font-size:12.0pt;
	font-family:"Times New Roman", serif;
	mso-font-charset:0;
	text-align:center;
	vertical-align:middle;
	border-top:none;
	border-right:.5pt solid windowtext;
	border-bottom:.5pt solid windowtext;
	border-left:.5pt solid windowtext;
	white-space:normal;}
.xl31
	{mso-style-parent:style0;
	font-size:12.0pt;
	font-family:"Times New Roman", serif;
	mso-font-charset:0;
	mso-number-format:"\@";
	text-align:center;
	vertical-align:middle;
	border-top:none;
	border-right:.5pt solid windowtext;
	border-bottom:.5pt solid windowtext;
	border-left:none;
	white-space:normal;}
.xl32
	{mso-style-parent:style0;
	font-size:12.0pt;
	font-family:"Times New Roman", serif;
	mso-font-charset:0;
	mso-number-format:"\@";
	text-align:center;
	vertical-align:middle;
	border-top:none;
	border-right:.5pt solid windowtext;
	border-bottom:.5pt solid windowtext;
	border-left:none;
	white-space:normal;}
.xl33
	{mso-style-parent:style0;
	color:red;
	font-size:12.0pt;
	font-family:"Times New Roman", serif;
	mso-font-charset:0;
	mso-number-format:"\@";
	text-align:center;
	vertical-align:middle;
	border-top:none;
	border-right:.5pt solid windowtext;
	border-bottom:.5pt solid windowtext;
	border-left:none;
	white-space:normal;}
.xl34
	{mso-style-parent:style0;
	font-size:12.0pt;
	font-family:"Times New Roman", serif;
	mso-font-charset:0;
	text-align:center;}
.xl35
	{mso-style-parent:style0;
	font-size:12.0pt;
	font-weight:700;
	font-family:"Times New Roman", serif;
	mso-font-charset:0;
	text-align:center;}
.xl36
	{mso-style-parent:style0;
	font-size:12.0pt;
	font-weight:700;
	text-decoration:underline;
	text-underline-style:single;
	font-family:"Times New Roman", serif;
	mso-font-charset:0;
	text-align:center;}
.xl37
	{mso-style-parent:style0;
	font-size:12.0pt;
	font-style:italic;
	font-family:"Times New Roman", serif;
	mso-font-charset:0;
	text-align:center;}
.xl38
	{mso-style-parent:style0;
	font-size:12.0pt;
	font-weight:700;
	font-family:"Times New Roman", serif;
	mso-font-charset:0;
	text-align:center;
	vertical-align:top;
	border-top:.5pt solid windowtext;
	border-right:none;
	border-bottom:.5pt solid windowtext;
	border-left:none;
	background:silver;
	mso-pattern:auto none;
	white-space:normal;}
.xl39
	{mso-style-parent:style0;
	font-size:12.0pt;
	font-weight:700;
	font-family:"Times New Roman", serif;
	mso-font-charset:0;
	text-align:center;
	vertical-align:top;
	border-top:.5pt solid windowtext;
	border-right:none;
	border-bottom:.5pt solid windowtext;
	border-left:.5pt solid windowtext;
	background:silver;
	mso-pattern:auto none;
	white-space:normal;}
.xl40
	{mso-style-parent:style0;
	font-size:12.0pt;
	font-weight:700;
	font-family:"Times New Roman", serif;
	mso-font-charset:0;
	text-align:center;
	vertical-align:top;
	border-top:.5pt solid windowtext;
	border-right:.5pt solid black;
	border-bottom:.5pt solid windowtext;
	border-left:none;
	background:silver;
	mso-pattern:auto none;
	white-space:normal;}
.xl41
	{mso-style-parent:style0;
	font-size:12.0pt;
	font-weight:700;
	font-family:"Times New Roman", serif;
	mso-font-charset:0;
	text-align:center;
	vertical-align:top;
	border-top:.5pt solid windowtext;
	border-right:none;
	border-bottom:.5pt solid windowtext;
	border-left:.5pt solid black;
	background:silver;
	mso-pattern:auto none;
	white-space:normal;}
-->
</style>
<!--[if gte mso 9]><xml>
 <x:ExcelWorkbook>
  <x:ExcelWorksheets>
   <x:ExcelWorksheet>
    <x:Name>Sheet1</x:Name>
    <x:WorksheetOptions>
     <x:DefaultRowHeight>315</x:DefaultRowHeight>
     <x:Print>
      <x:ValidPrinterInfo/>
      <x:PaperSizeIndex>9</x:PaperSizeIndex>
      <x:Scale>57</x:Scale>
      <x:HorizontalResolution>600</x:HorizontalResolution>
      <x:VerticalResolution>600</x:VerticalResolution>
     </x:Print>
     <x:PageBreakZoom>60</x:PageBreakZoom>
     <x:Selected/>
     <x:Panes>
      <x:Pane>
       <x:Number>3</x:Number>
       <x:ActiveRow>7</x:ActiveRow>
       <x:ActiveCol>1</x:ActiveCol>
       <x:RangeSelection>$B$8:$H$8</x:RangeSelection>
      </x:Pane>
     </x:Panes>
     <x:ProtectContents>False</x:ProtectContents>
     <x:ProtectObjects>False</x:ProtectObjects>
     <x:ProtectScenarios>False</x:ProtectScenarios>
    </x:WorksheetOptions>
    <x:PageBreaks>
     <x:ColBreaks>
      <x:ColBreak>
       <x:Column>11</x:Column>
      </x:ColBreak>
     </x:ColBreaks>
    </x:PageBreaks>
   </x:ExcelWorksheet>
   <x:ExcelWorksheet>
    <x:Name>Sheet2</x:Name>
    <x:WorksheetOptions>
     <x:ProtectContents>False</x:ProtectContents>
     <x:ProtectObjects>False</x:ProtectObjects>
     <x:ProtectScenarios>False</x:ProtectScenarios>
    </x:WorksheetOptions>
   </x:ExcelWorksheet>
   <x:ExcelWorksheet>
    <x:Name>Sheet3</x:Name>
    <x:WorksheetOptions>
     <x:ProtectContents>False</x:ProtectContents>
     <x:ProtectObjects>False</x:ProtectObjects>
     <x:ProtectScenarios>False</x:ProtectScenarios>
    </x:WorksheetOptions>
   </x:ExcelWorksheet>
  </x:ExcelWorksheets>
  <x:WindowHeight>12240</x:WindowHeight>
  <x:WindowWidth>15315</x:WindowWidth>
  <x:WindowTopX>885</x:WindowTopX>
  <x:WindowTopY>-135</x:WindowTopY>
  <x:ProtectStructure>False</x:ProtectStructure>
  <x:ProtectWindows>False</x:ProtectWindows>
 </x:ExcelWorkbook>
 <x:ExcelName>
  <x:Name>Print_Area</x:Name>
  <x:SheetIndex>1</x:SheetIndex>
  <x:Formula>=Sheet1!$A$1:$K$58</x:Formula>
 </x:ExcelName>
</xml><![endif]--><!--[if gte mso 9]><xml>
 <o:shapedefaults v:ext="edit" spidmax="1025"/>
</xml><![endif]-->
</head>

<body link=blue vlink=purple class=xl24>

<table x:str border=0 cellpadding=0 cellspacing=0 width=2179 style='border-collapse:
 collapse;table-layout:fixed;width:1636pt'>
 <col class=xl24 width=81 style='mso-width-source:userset;mso-width-alt:2962;
 width:61pt'>
 <col class=xl24 width=110 style='mso-width-source:userset;mso-width-alt:4022;
 width:83pt'>
 <col class=xl24 width=96 style='mso-width-source:userset;mso-width-alt:3510;
 width:72pt'>
 <col class=xl24 width=177 style='mso-width-source:userset;mso-width-alt:6473;
 width:133pt'>
 <col class=xl24 width=257 style='mso-width-source:userset;mso-width-alt:9398;
 width:193pt'>
 <col class=xl24 width=143 style='mso-width-source:userset;mso-width-alt:5229;
 width:107pt'>
 <col class=xl24 width=161 style='mso-width-source:userset;mso-width-alt:5888;
 width:121pt'>
 <col class=xl24 width=136 style='mso-width-source:userset;mso-width-alt:4973;
 width:102pt'>

 <col class=xl24 width=145 style='mso-width-source:userset;mso-width-alt:5302;
 width:109pt'>
 <col class=xl24 width=140 style='mso-width-source:userset;mso-width-alt:5120;
 width:105pt'>
 <col class=xl24 width=149 style='mso-width-source:userset;mso-width-alt:5449;
 width:112pt'>
 <col class=xl24 width=139 style='mso-width-source:userset;mso-width-alt:5083;
 width:104pt'>
 <col class=xl24 width=125 style='mso-width-source:userset;mso-width-alt:4571;
 width:94pt'>
 <col class=xl24 width=64 span=5 style='width:48pt'>
 <tr height=21 style='height:15.75pt'>
  <td colspan=3 height=21 class=xl34 width=287 style='height:15.75pt;
  width:216pt'><?= mb_strtoupper($this->config->sys_info->unit,"utf-8") ?></td>

  <td colspan=<?php echo (11-(10-($this->xulyvanban + $this->tinhhinhxl)));?> class=xl35 width=1636 style='width:1228pt'>CỘNG HÒA XÃ HỘI CHỦ
  NGHĨA VIỆT NAM</td>
  <td class=xl24 width=64 style='width:48pt'></td>
  <td class=xl24 width=64 style='width:48pt'></td>
  <td class=xl24 width=64 style='width:48pt'></td>
  <td class=xl24 width=64 style='width:48pt'></td>
 </tr>
 <tr height=21 style='height:15.75pt'>
  <td colspan=3 height=21 class=xl35 style='height:15.75pt'><?= mb_strtoupper($this->config->sys_info->company,"utf-8") ?></td>

  <td colspan=<?php echo (11-(10-($this->xulyvanban + $this->tinhhinhxl)));?> class=xl36>Ðộc lập - Tự do - Hạnh phúc</td>
  <td colspan=4 class=xl24 style='mso-ignore:colspan'></td>
 </tr>
 <tr height=21 style='height:15.75pt'>
  <td height=21 colspan=3 class=xl24 style='height:15.75pt;mso-ignore:colspan'></td>
  <td colspan=<?php echo (11-(10-($this->xulyvanban + $this->tinhhinhxl)));?> class=xl37><?=$this->config->sys_info->city?>, ngày <?=date("d")?> tháng <?=date("m")?> năm <?=date("Y")?></td>
  <td colspan=4 class=xl24 style='mso-ignore:colspan'></td>
 </tr>

 <tr height=21 style='height:15.75pt'>
  <td height=21 colspan=18 class=xl24 style='height:15.75pt;mso-ignore:colspan'></td>
 </tr>
 <tr height=21 style='height:15.75pt'>
  <td colspan=<?php echo (10-(10-($this->xulyvanban + $this->tinhhinhxl)));?> height=21 class=xl35 style='height:15.75pt'
  x:str="BÁO CÁO XỬ LÝ VĂN BẢN ĐẾN ">BÁO CÁO XỬ LÝ VĂN BẢN ĐẾN<span
  style='mso-spacerun:yes'> </span></td>
  <td class=xl25></td>
  <td colspan=7 class=xl24 style='mso-ignore:colspan'></td>
 </tr>

 <tr height=21 style='height:15.75pt'>
  <td colspan=<?php echo (10-(10-($this->xulyvanban + $this->tinhhinhxl)));?> height=21 class=xl37 style='height:15.75pt'><?php echo $this->thu;?> NĂM <?=QLVBDHCommon::getYear()?></td>
  <td class=xl26></td>
  <td colspan=7 class=xl24 style='mso-ignore:colspan'></td>
 </tr>
 <tr height=21 style='height:15.75pt'>
  <td height=21 colspan=18 class=xl24 style='height:15.75pt;mso-ignore:colspan'></td>
 </tr>

 <tr height=28 style='mso-height-source:userset;height:21.0pt'>
  <td height=28 class=xl27 width=81 style='height:21.0pt;width:61pt'>STT</td>
  <td colspan=<?php echo $this->xulyvanban;?> class=xl39 width=1080 style='border-right:.5pt solid black;
  border-left:none;width:811pt'>Xử lý văn bản đến</td>
  <td colspan=<?php echo $this->tinhhinhxl+1;?> class=xl41 width=434 style='border-right:.5pt solid black;
  border-left:none;width:326pt'>Tình hình xử lý</td>
  <td colspan=7 class=xl24 style='mso-ignore:colspan'></td>
 </tr>
 <tr height=21 style='height:15.75pt'>

  <td height=21 class=xl28 width=81 style='height:15.75pt;width:61pt'>&nbsp;</td>
   <?php if(count($this->soden) >0){?>
  <td class=xl29 width=110 style='width:83pt'>Số đến</td>
  <?php }?>
  <?php if(count($this->soto) >0){?>
  <td class=xl29 width=96 style='width:72pt'>Số tờ</td>
  <?php }?>
  <?php if(count($this->coquanbh) >0){?>
  <td class=xl29 width=177 style='width:133pt'>Cơ quan ban hành</td>
  <?php }?>
    <?php if(count($this->trichyeu) >0){?>
  <td class=xl29 width=257 style='width:193pt'>Trích yếu</td>
  <?php }?>
  <?php if(count($this->ngayden) >0){?>
  <td class=xl29 width=143 style='width:107pt'>Ngày đến</td>
  <?php }?>
   <?php if(count($this->nguoiky) >0){?>
  <td class=xl29 width=161 style='width:121pt'>Người ký</td>
  <?php }?>
  <?php if(count($this->sokh) >0){?>
  <td class=xl29 width=136 style='width:102pt'>Số ký hiệu</td>
  <?php }?>
  <?php if(count($this->nguoixl) >0){?>
  <td class=xl29 width=145 style='width:109pt'>Luồng luân chuyển</td>
  <?php }?>
  <?php if(count($this->trangthai) >0){?>
  <td class=xl29 width=140 style='width:105pt'>Trạng thái</td>
  <?php }?>
  
   <?php if(count($this->nguoixl) > 0){?>
  <td class=xl29 width=145 style='width:109pt'>Chuyên viên trình ký</td>
  <?php }?>
  
    <?php if(count($this->ketquaxl) >0){?>
  <td class=xl29 width=149 style='width:112pt'>Kết quả xử lý</td>
  <?php }?>
  <td colspan=7 class=xl24 style='mso-ignore:colspan'></td>

 </tr>
  <?php $stt=1;foreach($this->data as $item){ ?>
 <tr height=63 style='height:47.25pt'>
  <td height=63 class=xl30 width=81 style='height:47.25pt;width:61pt' x:num><?=$stt?></td>
  <?php if(count($this->soden) >0){?>
  <td class=xl31 width=110 style='width:83pt'><?=$item["SODEN"]?></td>
  <?php }?>
  <?php if(count($this->soto) >0){?>
  <td class=xl31 width=96 style='width:72pt'><?=$item["SOTO"]?></td>
  <?php }?>
  <?php if(count($this->coquanbh) >0){?>
  <td class=xl31 width=177 style='width:133pt'><?=$item["COQUANBANHANH_TEXT"]?></td>
  <?php }?>
  <?php if(count($this->trichyeu) >0){?>
  <td class=xl31 width=257 style='width:193pt'><?=$item["TRICHYEU"]?></td>
  <?php }?>
   <?php if(count($this->ngayden) >0){?>
  <td class=xl31 width=143 style='width:107pt'><?=QLVBDHCommon::MysqlDateToVnDate($item["NGAYDEN"])?></td>
  <?php }?>
    <?php if(count($this->nguoiky) >0){?>
  <td class=xl31 width=161 style='width:121pt'><?=$item["NGUOIKY"]?></td>
  <?php }?>
    <?php if(count($this->sokh) >0){?>
  <td class=xl31 width=136 style='width:102pt'><?=$item["SOKYHIEU"]?></td>
  <?php }?>
  <?php if(count($this->nguoixl) >0){?>
  <td class=xl32 width=145 style='width:109pt'><?php 
			
  /*
                        $arr_u_xl = explode(",",$item["NAME_U"] );	
			
			$ii = 0;
			foreach( $arr_u_xl as $id_user_xl){
				if($ii == 0 && $item["IS_FINISH"]!=1 )
					echo "<font color=blue>";
				echo UsersModel::getEmloyeeNameByIdUser((int)$id_user_xl);
				if($ii == 0 && $item["IS_FINISH"]!=1 )
					echo "</font>";
				echo "<br>";
				$ii++;
				
			}
   */
  
            $xl= WFEngine::GetProcessLogByObjectId((int)$item['ID_HSCV']);
            $rowsend = $xl[0]['EMPNCNAME'];
            for($j=0;$j<count($xl);$j++){
                    if($j==10){
                    $rowsend .="<br/>" ;
                    $rowsend .=" <br> " ;
                    $rowsend .= $xl[$j]['EMPNCNAME'];

                    }else{
                            if($rowsend != $xl[$j]['EMPNCNAME'])
                            {
                                    $rowsend .=" <br> " ;
                                    if($xl[$j]["ID_U_EXECUTE"]>0 && $xl[$j]["ID_U_EXECUTE"]!=$xl[$j]["ID_U_NC"]){
                                        $rowsend .= "(". $xl[$j]["EMPEXNAME"]." chuyển giúp) <br>" ;
                                    }
                                    if($xl[$j]['NAME'] == "Chuyển xử lý")
                                          $rowsend .= "<font color=blue>";
                                    $rowsend .= $xl[$j]['EMPNNNAME'];  
                                    
                                    if($xl[$j]['NAME'] == "Chuyển xử lý" )
                                      $rowsend .= "</font>";
                            }
                    }
            }
            $rowsend .=" <br> " ;
            //$rowsend .= $xl[$j-1]['EMPNNNAME'];
						
            ?>
            <i> <?					
                    echo $rowsend;
            ?></i>
      
		<br>
    </td>
	<?php }?>
	<?php if(count($this->trangthai) >0){?>
  <td class=xl33 width=140 style='width:105pt'><?php 
		if($item["ID_HSCV"]=="")
		{
			if($item["IS_KHONGXULY"] == 1)
					echo "văn bản không xử lý";
		}
		else if($item["IS_THEODOI"]==1){
			echo "Đang lưu theo dõi";
		}else{
		if($item["IS_FINISH"]==1){
			echo "Đã kết thúc";
		}else{
		
		$dis_hour = QLVBDHCommon::getTreHan($item["DATESEND"],$item["HANXULY"]);
				if($dis_hour > 0){
					
					if($this->id_u == $item_luanchuyen["ID_U_RECEIVE"])
						echo '<font color="Red">đang xử lý (trễ '. (int)($dis_hour/8) .' ngày '.($dis_hour%8).' giờ)</font>';
					else 
						echo 'đang xử lý (trễ '. (int)($dis_hour/8) .' ngày '.($dis_hour%8).' giờ)';
				}
				else{ 
					$con = 0- $dis_hour;
					echo 'đang xử lý (còn '. (int)($con/8) .' ngày '.($con%8).' giờ)';
				}
		}}
		?></td>
  <?php }?>
  
  <?php if(count($this->nguoixl) > 0){?>
     <td class=xl32 width=145 style='width:109pt'><?php 
			$arr_u_xl = explode(",",$item["NAME_U"] );	
			
			$ii = 0;
			foreach( $arr_u_xl as $id_user_xl){
				if($ii == 0 && $item["IS_FINISH"]!=1 )
					echo "<font color=blue>";
				echo UsersModel::getEmloyeeNameByIdUser((int)$id_user_xl);
				if($ii == 0 && $item["IS_FINISH"]!=1 )
					echo "</font>";
				echo "<br>";
				$ii++;
				
			}
		?><br>
    </td>
  <?php }?>
  
  <?php if(count($this->ketquaxl) >0){?>

  <td class=xl31 width=149 style='width:112pt'><?php
		if($item["ID_HSCV"] != "")	{
			$list_vbdi = Ad_XulyvanbandenModel::getListVanbandiByIdHSCV($item["ID_HSCV"]);
			if(count($list_vbdi) > 0){
				//if($item["IS_FINISH"] == 1)
					//$ktxuly_ravbdi++;
				//else
					//$dangxuly_ravbdi++;
				foreach($list_vbdi as $vbdi){
					echo  $vbdi["SOKYHIEU"]."<br/>";
				}
			}
			
			if($item["IS_THEODOI"]==1){
				echo $item["KQ_DEXUAT"];
			}
			
		}


	?><br>
    </td>
	<?php }?>
  
  <td colspan=7 class=xl24 style='mso-ignore:colspan'></td>
 </tr>
 <?php $stt++;} ?>
 <tr height=21 style='height:15.75pt'>
  <td height=21 colspan=18 class=xl24 style='height:15.75pt;mso-ignore:colspan'></td>
 </tr>

 <tr height=21 style='height:15.75pt'>
  <td height=21 colspan=18 class=xl24 style='height:15.75pt;mso-ignore:colspan'></td>
 </tr>
 <tr height=21 style='height:15.75pt'>
  <td height=21 colspan=18 class=xl24 style='height:15.75pt;mso-ignore:colspan'></td>
 </tr>
 <tr height=21 style='height:15.75pt'>
  <td height=21 colspan=4 class=xl24 style='height:15.75pt;mso-ignore:colspan'></td>
  <td class=xl25></td>

  <td colspan=2 class=xl24 style='mso-ignore:colspan'></td>
  <td colspan=11 class=xl26 style='mso-ignore:colspan'></td>
 </tr>
 <![if supportMisalignedColumns]>
 <tr height=0 style='display:none'>
  <td width=81 style='width:61pt'></td>
  <td width=110 style='width:83pt'></td>
  <td width=96 style='width:72pt'></td>
  <td width=177 style='width:133pt'></td>

  <td width=257 style='width:193pt'></td>
  <td width=143 style='width:107pt'></td>
  <td width=161 style='width:121pt'></td>
  <td width=136 style='width:102pt'></td>
  <td width=145 style='width:109pt'></td>
  <td width=140 style='width:105pt'></td>
  <td width=149 style='width:112pt'></td>
  <td width=139 style='width:104pt'></td>
  <td width=125 style='width:94pt'></td>

  <td width=64 style='width:48pt'></td>
  <td width=64 style='width:48pt'></td>
  <td width=64 style='width:48pt'></td>
  <td width=64 style='width:48pt'></td>
  <td width=64 style='width:48pt'></td>
 </tr>
 <![endif]>
</table>

</body>

</html>
<script>print();</script>

<?php }else{ ?>

 <html xmlns:v="urn:schemas-microsoft-com:vml"
xmlns:o="urn:schemas-microsoft-com:office:office"
xmlns:x="urn:schemas-microsoft-com:office:excel"
xmlns="http://www.w3.org/TR/REC-html40">

<head>
<meta http-equiv=Content-Type content="text/html; charset=utf-8">
<meta name=ProgId content=Excel.Sheet>
<meta name=Generator content="Microsoft Excel 11">
<link rel=File-List href="baocaovanbanden%201%20_files/filelist.xml">
<link rel=Edit-Time-Data href="baocaovanbanden%201%20_files/editdata.mso">
<link rel=OLE-Object-Data href="baocaovanbanden%201%20_files/oledata.mso">
<!--[if gte mso 9]><xml>
 <o:DocumentProperties>
  <o:Author>nguyennd</o:Author>
  <o:LastAuthor>User</o:LastAuthor>
  <o:LastPrinted>2009-12-24T23:53:13Z</o:LastPrinted>
  <o:Created>2009-08-25T14:43:47Z</o:Created>
  <o:LastSaved>2009-12-24T23:53:38Z</o:LastSaved>
  <o:Company>Hewlett-Packard</o:Company>
  <o:Version>11.9999</o:Version>
 </o:DocumentProperties>
</xml><![endif]-->
<style>
<!--table
	{mso-displayed-decimal-separator:"\.";
	mso-displayed-thousand-separator:"\,";}
@page
	{margin:.2in 1.44in .2in .2in;
	mso-header-margin:.2in;
	mso-footer-margin:.2in;
	}
tr
	{mso-height-source:auto;}
col
	{mso-width-source:auto;}
br
	{mso-data-placement:same-cell;}
.style0
	{mso-number-format:General;
	text-align:general;
	vertical-align:bottom;
	white-space:nowrap;
	mso-rotate:0;
	mso-background-source:auto;
	mso-pattern:auto;
	color:windowtext;
	font-size:10.0pt;
	font-weight:400;
	font-style:normal;
	text-decoration:none;
	font-family:Arial;
	mso-generic-font-family:auto;
	mso-font-charset:0;
	border:none;
	mso-protection:locked visible;
	mso-style-name:Normal;
	mso-style-id:0;}
td
	{mso-style-parent:style0;
	padding-top:1px;
	padding-right:1px;
	padding-left:1px;
	mso-ignore:padding;
	color:windowtext;
	font-size:10.0pt;
	font-weight:400;
	font-style:normal;
	text-decoration:none;
	font-family:Arial;
	mso-generic-font-family:auto;
	mso-font-charset:0;
	mso-number-format:General;
	text-align:general;
	vertical-align:bottom;
	border:none;
	mso-background-source:auto;
	mso-pattern:auto;
	mso-protection:locked visible;
	white-space:nowrap;
	mso-rotate:0;}
.xl24
	{mso-style-parent:style0;
	font-size:12.0pt;
	font-family:"Times New Roman", serif;
	mso-font-charset:0;}
.xl25
	{mso-style-parent:style0;
	font-size:12.0pt;
	font-weight:700;
	font-family:"Times New Roman", serif;
	mso-font-charset:0;}
.xl26
	{mso-style-parent:style0;
	font-size:12.0pt;
	font-style:italic;
	font-family:"Times New Roman", serif;
	mso-font-charset:0;}
.xl27
	{mso-style-parent:style0;
	font-size:12.0pt;
	font-weight:700;
	font-family:"Times New Roman", serif;
	mso-font-charset:0;
	text-align:center;
	vertical-align:top;
	border:.5pt solid windowtext;
	background:silver;
	mso-pattern:auto none;
	white-space:normal;}
.xl28
	{mso-style-parent:style0;
	font-size:12.0pt;
	font-weight:700;
	font-family:"Times New Roman", serif;
	mso-font-charset:0;
	text-align:center;
	vertical-align:top;
	border-top:none;
	border-right:.5pt solid windowtext;
	border-bottom:.5pt solid windowtext;
	border-left:.5pt solid windowtext;
	background:silver;
	mso-pattern:auto none;
	white-space:normal;}
.xl29
	{mso-style-parent:style0;
	font-size:12.0pt;
	font-weight:700;
	font-family:"Times New Roman", serif;
	mso-font-charset:0;
	text-align:center;
	vertical-align:top;
	border-top:none;
	border-right:.5pt solid windowtext;
	border-bottom:.5pt solid windowtext;
	border-left:none;
	background:silver;
	mso-pattern:auto none;
	white-space:normal;}
.xl30
	{mso-style-parent:style0;
	font-size:12.0pt;
	font-family:"Times New Roman", serif;
	mso-font-charset:0;
	text-align:center;
	vertical-align:middle;
	border-top:none;
	border-right:.5pt solid windowtext;
	border-bottom:.5pt solid windowtext;
	border-left:.5pt solid windowtext;
	white-space:normal;}
.xl31
	{mso-style-parent:style0;
	font-size:12.0pt;
	font-family:"Times New Roman", serif;
	mso-font-charset:0;
	mso-number-format:"\@";
	text-align:center;
	vertical-align:middle;
	border-top:none;
	border-right:.5pt solid windowtext;
	border-bottom:.5pt solid windowtext;
	border-left:none;
	white-space:normal;}
.xl32
	{mso-style-parent:style0;
	font-size:12.0pt;
	font-family:"Times New Roman", serif;
	mso-font-charset:0;
	mso-number-format:"\@";
	text-align:center;
	vertical-align:middle;
	border-top:none;
	border-right:.5pt solid windowtext;
	border-bottom:.5pt solid windowtext;
	border-left:none;
	white-space:normal;}
.xl33
	{mso-style-parent:style0;
	color:red;
	font-size:12.0pt;
	font-family:"Times New Roman", serif;
	mso-font-charset:0;
	mso-number-format:"\@";
	text-align:center;
	vertical-align:middle;
	border-top:none;
	border-right:.5pt solid windowtext;
	border-bottom:.5pt solid windowtext;
	border-left:none;
	white-space:normal;}
.xl34
	{mso-style-parent:style0;
	font-size:12.0pt;
	font-family:"Times New Roman", serif;
	mso-font-charset:0;
	text-align:center;}
.xl35
	{mso-style-parent:style0;
	font-size:12.0pt;
	font-weight:700;
	font-family:"Times New Roman", serif;
	mso-font-charset:0;
	text-align:center;}
.xl36
	{mso-style-parent:style0;
	font-size:12.0pt;
	font-weight:700;
	text-decoration:underline;
	text-underline-style:single;
	font-family:"Times New Roman", serif;
	mso-font-charset:0;
	text-align:center;}
.xl37
	{mso-style-parent:style0;
	font-size:12.0pt;
	font-style:italic;
	font-family:"Times New Roman", serif;
	mso-font-charset:0;
	text-align:center;}
.xl38
	{mso-style-parent:style0;
	font-size:12.0pt;
	font-weight:700;
	font-family:"Times New Roman", serif;
	mso-font-charset:0;
	text-align:center;
	vertical-align:top;
	border-top:.5pt solid windowtext;
	border-right:none;
	border-bottom:.5pt solid windowtext;
	border-left:none;
	background:silver;
	mso-pattern:auto none;
	white-space:normal;}
.xl39
	{mso-style-parent:style0;
	font-size:12.0pt;
	font-weight:700;
	font-family:"Times New Roman", serif;
	mso-font-charset:0;
	text-align:center;
	vertical-align:top;
	border-top:.5pt solid windowtext;
	border-right:none;
	border-bottom:.5pt solid windowtext;
	border-left:.5pt solid windowtext;
	background:silver;
	mso-pattern:auto none;
	white-space:normal;}
.xl40
	{mso-style-parent:style0;
	font-size:12.0pt;
	font-weight:700;
	font-family:"Times New Roman", serif;
	mso-font-charset:0;
	text-align:center;
	vertical-align:top;
	border-top:.5pt solid windowtext;
	border-right:.5pt solid black;
	border-bottom:.5pt solid windowtext;
	border-left:none;
	background:silver;
	mso-pattern:auto none;
	white-space:normal;}
.xl41
	{mso-style-parent:style0;
	font-size:12.0pt;
	font-weight:700;
	font-family:"Times New Roman", serif;
	mso-font-charset:0;
	text-align:center;
	vertical-align:top;
	border-top:.5pt solid windowtext;
	border-right:none;
	border-bottom:.5pt solid windowtext;
	border-left:.5pt solid black;
	background:silver;
	mso-pattern:auto none;
	white-space:normal;}
-->
</style>
<!--[if gte mso 9]><xml>
 <x:ExcelWorkbook>
  <x:ExcelWorksheets>
   <x:ExcelWorksheet>
    <x:Name>Sheet1</x:Name>
    <x:WorksheetOptions>
     <x:DefaultRowHeight>315</x:DefaultRowHeight>
     <x:Print>
      <x:ValidPrinterInfo/>
      <x:PaperSizeIndex>9</x:PaperSizeIndex>
      <x:Scale>37</x:Scale>
      <x:HorizontalResolution>600</x:HorizontalResolution>
      <x:VerticalResolution>600</x:VerticalResolution>
     </x:Print>
     <x:PageBreakZoom>60</x:PageBreakZoom>
     <x:Selected/>
     <x:Panes>
      <x:Pane>
       <x:Number>3</x:Number>
       <x:ActiveRow>7</x:ActiveRow>
       <x:ActiveCol>1</x:ActiveCol>
       <x:RangeSelection>$B$8:$H$8</x:RangeSelection>
      </x:Pane>
     </x:Panes>
     <x:ProtectContents>False</x:ProtectContents>
     <x:ProtectObjects>False</x:ProtectObjects>
     <x:ProtectScenarios>False</x:ProtectScenarios>
    </x:WorksheetOptions>
    <x:PageBreaks>
     <x:ColBreaks>
      <x:ColBreak>
       <x:Column>11</x:Column>
      </x:ColBreak>
     </x:ColBreaks>
    </x:PageBreaks>
   </x:ExcelWorksheet>
   <x:ExcelWorksheet>
    <x:Name>Sheet2</x:Name>
    <x:WorksheetOptions>
     <x:ProtectContents>False</x:ProtectContents>
     <x:ProtectObjects>False</x:ProtectObjects>
     <x:ProtectScenarios>False</x:ProtectScenarios>
    </x:WorksheetOptions>
   </x:ExcelWorksheet>
   <x:ExcelWorksheet>
    <x:Name>Sheet3</x:Name>
    <x:WorksheetOptions>
     <x:ProtectContents>False</x:ProtectContents>
     <x:ProtectObjects>False</x:ProtectObjects>
     <x:ProtectScenarios>False</x:ProtectScenarios>
    </x:WorksheetOptions>
   </x:ExcelWorksheet>
  </x:ExcelWorksheets>
  <x:WindowHeight>12240</x:WindowHeight>
  <x:WindowWidth>15315</x:WindowWidth>
  <x:WindowTopX>885</x:WindowTopX>
  <x:WindowTopY>-135</x:WindowTopY>
  <x:ProtectStructure>False</x:ProtectStructure>
  <x:ProtectWindows>False</x:ProtectWindows>
 </x:ExcelWorkbook>
 <x:ExcelName>
  <x:Name>Print_Area</x:Name>
  <x:SheetIndex>1</x:SheetIndex>
  <x:Formula>=Sheet1!$A$1:$K$58</x:Formula>
 </x:ExcelName>
</xml><![endif]--><!--[if gte mso 9]><xml>
 <o:shapedefaults v:ext="edit" spidmax="1025"/>
</xml><![endif]-->
</head>

<body link=blue vlink=purple class=xl24>

<table x:str border=0 cellpadding=0 cellspacing=0 width=2179 style='border-collapse:
 collapse;table-layout:fixed;width:1636pt'>
 <col class=xl24 width=81 style='mso-width-source:userset;mso-width-alt:2962;
 width:61pt'>
 <col class=xl24 width=110 style='mso-width-source:userset;mso-width-alt:4022;
 width:83pt'>
 <col class=xl24 width=96 style='mso-width-source:userset;mso-width-alt:3510;
 width:72pt'>
 <col class=xl24 width=177 style='mso-width-source:userset;mso-width-alt:6473;
 width:133pt'>
 <col class=xl24 width=257 style='mso-width-source:userset;mso-width-alt:9398;
 width:193pt'>
 <col class=xl24 width=143 style='mso-width-source:userset;mso-width-alt:5229;
 width:107pt'>
 <col class=xl24 width=161 style='mso-width-source:userset;mso-width-alt:5888;
 width:121pt'>
 <col class=xl24 width=136 style='mso-width-source:userset;mso-width-alt:4973;
 width:102pt'>

 <col class=xl24 width=145 style='mso-width-source:userset;mso-width-alt:5302;
 width:109pt'>
 <col class=xl24 width=140 style='mso-width-source:userset;mso-width-alt:5120;
 width:105pt'>
 <col class=xl24 width=149 style='mso-width-source:userset;mso-width-alt:5449;
 width:112pt'>
 <col class=xl24 width=139 style='mso-width-source:userset;mso-width-alt:5083;
 width:104pt'>
 <col class=xl24 width=125 style='mso-width-source:userset;mso-width-alt:4571;
 width:94pt'>
 <col class=xl24 width=64 span=5 style='width:48pt'>
 <tr height=21 style='height:15.75pt'>
  <td colspan=3 height=21 class=xl34 width=287 style='height:15.75pt;
  width:216pt'><?= mb_strtoupper($this->config->sys_info->unit,"utf-8") ?></td>

  <td colspan=<?php echo (11-(10-($this->xulyvanban + $this->tinhhinhxl)));?> class=xl35 width=1636 style='width:1228pt'>CỘNG HÒA XÃ HỘI CHỦ
  NGHĨA VIỆT NAM</td>
  <td class=xl24 width=64 style='width:48pt'></td>
  <td class=xl24 width=64 style='width:48pt'></td>
  <td class=xl24 width=64 style='width:48pt'></td>
  <td class=xl24 width=64 style='width:48pt'></td>
 </tr>
 <tr height=21 style='height:15.75pt'>
  <td colspan=3 height=21 class=xl35 style='height:15.75pt'><?= mb_strtoupper($this->config->sys_info->company,"utf-8") ?></td>

  <td colspan=<?php echo (11-(10-($this->xulyvanban + $this->tinhhinhxl)));?> class=xl36>Ðộc lập - Tự do - Hạnh phúc</td>
  <td colspan=4 class=xl24 style='mso-ignore:colspan'></td>
 </tr>
 <tr height=21 style='height:15.75pt'>
  <td height=21 colspan=3 class=xl24 style='height:15.75pt;mso-ignore:colspan'></td>
  <td colspan=<?php echo (11-(10-($this->xulyvanban + $this->tinhhinhxl)));?> class=xl37>Đà Nẵng, ngày 25 tháng 12 năm 2009</td>
  <td colspan=4 class=xl24 style='mso-ignore:colspan'></td>
 </tr>

 <tr height=21 style='height:15.75pt'>
  <td height=21 colspan=18 class=xl24 style='height:15.75pt;mso-ignore:colspan'></td>
 </tr>
 <tr height=21 style='height:15.75pt'>
  <td colspan=<?php echo (10-(10-($this->xulyvanban + $this->tinhhinhxl)));?> height=21 class=xl35 style='height:15.75pt'
  x:str="BÁO CÁO XỬ LÝ VĂN BẢN ĐẾN ">BÁO CÁO XỬ LÝ VĂN BẢN ĐẾN<span
  style='mso-spacerun:yes'> </span></td>
  <td class=xl25></td>
  <td colspan=7 class=xl24 style='mso-ignore:colspan'></td>
 </tr>

 <tr height=21 style='height:15.75pt'>
  <td colspan=<?php echo (10-(10-($this->xulyvanban + $this->tinhhinhxl)));?> height=21 class=xl37 style='height:15.75pt'><?php echo $this->thu;?> NĂM <?=date("Y")?></td>
  <td class=xl26></td>
  <td colspan=7 class=xl24 style='mso-ignore:colspan'></td>
 </tr>
 <tr height=21 style='height:15.75pt'>
  <td height=21 colspan=18 class=xl24 style='height:15.75pt;mso-ignore:colspan'></td>
 </tr>

 <tr height=28 style='mso-height-source:userset;height:21.0pt'>
  <td height=28 class=xl27 width=81 style='height:21.0pt;width:61pt'>STT</td>
  <td colspan=<?php echo $this->xulyvanban;?> class=xl39 width=1080 style='border-right:.5pt solid black;
  border-left:none;width:811pt'>Xử lý văn bản đến</td>
  <td colspan=<?php echo $this->tinhhinhxl;?> class=xl41 width=434 style='border-right:.5pt solid black;
  border-left:none;width:326pt'>Tình hình xử lý</td>
  <td colspan=7 class=xl24 style='mso-ignore:colspan'></td>
 </tr>
 <tr height=21 style='height:15.75pt'>

  <td height=21 class=xl28 width=81 style='height:15.75pt;width:61pt'>&nbsp;</td>
   <?php if(count($this->soden) >0){?>
  <td class=xl29 width=110 style='width:83pt'>Số đến</td>
  <?php }?>
  <?php if(count($this->soto) >0){?>
  <td class=xl29 width=96 style='width:72pt'>Số tờ</td>
  <?php }?>
  <?php if(count($this->coquanbh) >0){?>
  <td class=xl29 width=177 style='width:133pt'>Cơ quan ban hành</td>
  <?php }?>
    <?php if(count($this->trichyeu) >0){?>
  <td class=xl29 width=257 style='width:193pt'>Trích yếu</td>
  <?php }?>
  <?php if(count($this->ngayden) >0){?>
  <td class=xl29 width=143 style='width:107pt'>Ngày đến</td>
  <?php }?>
   <?php if(count($this->nguoiky) >0){?>
  <td class=xl29 width=161 style='width:121pt'>Người ký</td>
  <?php }?>
  <?php if(count($this->sokh) >0){?>
  <td class=xl29 width=136 style='width:102pt'>Số ký hiệu</td>
  <?php }?>
  <?php if(count($this->nguoixl) >0){?>
  <td class=xl29 width=145 style='width:109pt'>Luồng luân chuyển</td>
  <?php }?>
  <?php if(count($this->trangthai) >0){?>
  <td class=xl29 width=140 style='width:105pt'>Trạng thái</td>
  <?php }?>
    <?php if(count($this->ketquaxl) >0){?>
  <td class=xl29 width=149 style='width:112pt'>Kết quả xử lý</td>
  <?php }?>
  <td colspan=7 class=xl24 style='mso-ignore:colspan'></td>

 </tr>
  <?php $stt=1;foreach($this->data as $item){ ?>
 <tr height=63 style='height:47.25pt'>
  <td height=63 class=xl30 width=81 style='height:47.25pt;width:61pt' x:num><?=$stt?></td>
  <?php if(count($this->soden) >0){?>
  <td class=xl31 width=110 style='width:83pt'><?=$item["SODEN"]?></td>
  <?php }?>
  <?php if(count($this->soto) >0){?>
  <td class=xl31 width=96 style='width:72pt'><?=$item["SOTO"]?></td>
  <?php }?>
  <?php if(count($this->coquanbh) >0){?>
  <td class=xl31 width=177 style='width:133pt'><?=$item["COQUANBANHANH_TEXT"]?></td>
  <?php }?>
  <?php if(count($this->trichyeu) >0){?>
  <td class=xl31 width=257 style='width:193pt'><?=$item["TRICHYEU"]?></td>
  <?php }?>
   <?php if(count($this->ngayden) >0){?>
  <td class=xl31 width=143 style='width:107pt'><?=QLVBDHCommon::MysqlDateToVnDate($item["NGAYDEN"])?></td>
  <?php }?>
    <?php if(count($this->nguoiky) >0){?>
  <td class=xl31 width=161 style='width:121pt'><?=$item["NGUOIKY"]?></td>
  <?php }?>
    <?php if(count($this->sokh) >0){?>
  <td class=xl31 width=136 style='width:102pt'><?=$item["SOKYHIEU"]?></td>
  <?php }?>
  <?php if(count($this->nguoixl) >0){?>
  <td class=xl32 width=145 style='width:109pt'><?php 
			/*
                        $arr_u_xl = explode(",",$item["NAME_U"] );	
			
			$ii = 0;
			foreach( $arr_u_xl as $id_user_xl){
				if($ii == 0 && $item["IS_FINISH"]!=1 )
					echo "<font color=blue>";
				echo UsersModel::getEmloyeeNameByIdUser((int)$id_user_xl);
				if($ii == 0 && $item["IS_FINISH"]!=1 )
					echo "</font>";
				echo "<br>";
				$ii++;
				
			}
                         */
                        $xl= WFEngine::GetProcessLogByObjectId((int)$item['ID_HSCV']);
                        $rowsend = $xl[0]['EMPNCNAME'];
                        for($j=0;$j<count($xl);$j++){
                                if($j==10){
                                $rowsend .="<br/>" ;
                                $rowsend .=" <br> " ;
                                $rowsend .= $xl[$j]['EMPNCNAME'];

                                }else{
                                        if($rowsend != $xl[$j]['EMPNCNAME'])
                                        {
                                                $rowsend .=" <br> " ;
                                    if($xl[$j]["ID_U_EXECUTE"]>0 && $xl[$j]["ID_U_EXECUTE"]!=$xl[$j]["ID_U_NC"]){
                                        $rowsend .= "(". $xl[$j]["EMPEXNAME"]." chuyển giúp) <br>" ;
                                    }
                                    if($xl[$j]['NAME'] == "Chuyển xử lý")
                                          $rowsend .= "<font color=blue>";
                                    $rowsend .= $xl[$j]['EMPNNNAME'];  
                                    
                                    if($xl[$j]['NAME'] == "Chuyển xử lý" )
                                      $rowsend .= "</font>";
                                        }
                                }
                        }
                        $rowsend .=" <br> " ;
                       // $rowsend .= $xl[$j-1]['EMPNNNAME'];

                        ?>
                        <i> <?					
                                echo $rowsend;
                        ?></i> 
		<br>
    </td>
	<?php }?>
	<?php if(count($this->trangthai) >0){?>
  <td class=xl33 width=140 style='width:105pt'><?php 
		if($item["ID_HSCV"]=="")
		{
			if($item["IS_KHONGXULY"] == 1)
					echo "văn bản không xử lý";
		}
		else if($item["IS_THEODOI"]==1){
			echo "Đang lưu theo dõi";
		}else{
		if($item["IS_FINISH"]==1){
			echo "Đã kết thúc";
		}else{
		
		$dis_hour = QLVBDHCommon::getTreHan($item["DATESEND"],$item["HANXULY"]);
				if($dis_hour > 0){
					
					if($this->id_u == $item_luanchuyen["ID_U_RECEIVE"])
						echo '<font color="Red">đang xử lý (trễ '. (int)($dis_hour/8) .' ngày '.($dis_hour%8).' giờ)</font>';
					else 
						echo 'đang xử lý (trễ '. (int)($dis_hour/8) .' ngày '.($dis_hour%8).' giờ)';
				}
				else{ 
					$con = 0- $dis_hour;
					echo 'đang xử lý (còn '. (int)($con/8) .' ngày '.($con%8).' giờ)';
				}
		}}
		?></td>
  <?php }?>
  
  <?php if(count($this->cvtrinhki) > 0){?>
  <td class=xl32 width=145 style='width:109pt'><?php 
			$arr_u_xl = explode(",",$item["NAME_U"] );	
			
			$ii = 0;
			foreach( $arr_u_xl as $id_user_xl){
				if($ii == 0 && $item["IS_FINISH"]!=1 )
					echo "<font color=blue>";
				echo UsersModel::getEmloyeeNameByIdUser((int)$id_user_xl);
				if($ii == 0 && $item["IS_FINISH"]!=1 )
					echo "</font>";
				echo "<br>";
				$ii++;
				
			}
		?><br>
    </td>
	<?php }?>
  
  <?php if(count($this->ketquaxl) >0){?>

  <td class=xl31 width=149 style='width:112pt'><?php
		if($item["ID_HSCV"] != "")	{
			$list_vbdi = Ad_XulyvanbandenModel::getListVanbandiByIdHSCV($item["ID_HSCV"]);
			if(count($list_vbdi) > 0){
				//if($item["IS_FINISH"] == 1)
					//$ktxuly_ravbdi++;
				//else
					//$dangxuly_ravbdi++;
				foreach($list_vbdi as $vbdi){
					echo  $vbdi["SOKYHIEU"]."<br/>";
				}
			}
			
			if($item["IS_THEODOI"]==1){
				echo $item["KQ_DEXUAT"];
			}
			
		}


	?><br>
    </td>
	<?php }?>
  <td colspan=7 class=xl24 style='mso-ignore:colspan'></td>
 </tr>
 <?php $stt++;} ?>
 <tr height=21 style='height:15.75pt'>
  <td height=21 colspan=18 class=xl24 style='height:15.75pt;mso-ignore:colspan'></td>
 </tr>

 <tr height=21 style='height:15.75pt'>
  <td height=21 colspan=18 class=xl24 style='height:15.75pt;mso-ignore:colspan'></td>
 </tr>
 <tr height=21 style='height:15.75pt'>
  <td height=21 colspan=18 class=xl24 style='height:15.75pt;mso-ignore:colspan'></td>
 </tr>
 <tr height=21 style='height:15.75pt'>
  <td height=21 colspan=4 class=xl24 style='height:15.75pt;mso-ignore:colspan'></td>
  <td class=xl25></td>

  <td colspan=2 class=xl24 style='mso-ignore:colspan'></td>
  <td colspan=11 class=xl26 style='mso-ignore:colspan'></td>
 </tr>
 <![if supportMisalignedColumns]>
 <tr height=0 style='display:none'>
  <td width=81 style='width:61pt'></td>
  <td width=110 style='width:83pt'></td>
  <td width=96 style='width:72pt'></td>
  <td width=177 style='width:133pt'></td>

  <td width=257 style='width:193pt'></td>
  <td width=143 style='width:107pt'></td>
  <td width=161 style='width:121pt'></td>
  <td width=136 style='width:102pt'></td>
  <td width=145 style='width:109pt'></td>
  <td width=140 style='width:105pt'></td>
  <td width=149 style='width:112pt'></td>
  <td width=139 style='width:104pt'></td>
  <td width=125 style='width:94pt'></td>

  <td width=64 style='width:48pt'></td>
  <td width=64 style='width:48pt'></td>
  <td width=64 style='width:48pt'></td>
  <td width=64 style='width:48pt'></td>
  <td width=64 style='width:48pt'></td>
 </tr>
 <![endif]>
</table>

</body>

</html>
<script>print();</script>
<?php }?>