<?php
	require_once 'Common/FileDinhKem.php';
?>
<script type="text/javascript" src=<?php echo $this->baseUrl()."/js/Json/Base64.js"?>></script>
<script type="text/javascript" src=<?php echo $this->baseUrl()."/js/Json/json2.js"?>></script>
<script type="text/javascript" src=<?php echo $this->baseUrl()."/js/Json/json_parse.js"?>></script>
<script type="text/javascript" src=<?php echo $this->baseUrl()."/js/Json/json_parse_state.js"?>></script>
<script type="text/javascript" src=<?php echo $this->baseUrl()."/js/Ajax/AjaxEngine.js"?>></script>
<script type="text/javascript" src="/js/dlg_confirm.js"></script>

<?=QLVBDHCommon::useDlgConfirm()?>
<form name=frm method=post>
    <input type="hidden" name ="hscv_trehan" value="<?= $this->hscv_trehan ?>" />
    <input type="hidden" name="OBJECT_CXL" value="<?=$this->object_cxl;?>" />

<table class=adminlist>
	<thead>
		<tr>
			<th colspan="3">
				<div>
					<div class="limit" style="float:left;">Hiển thị #
						<select name="limit1"  style="width:60px;" id="limit1" class="inputbox" size="1" onchange="
							document.frm.page.value = 1;
							document.frm.limit2.value = document.frm.limit1.value;
							document.frm.action = '/hscv/Tinhhinhxuly/hscvchoxuly';
							document.frm.submit();
						">
							<option value="5" <?php if($this->limit==5){echo "selected";} ?>>5</option>
							<option value="10" <?php if($this->limit==10){echo "selected";} ?>>10</option>
							<option value="15" <?php if($this->limit==15){echo "selected";} ?>>15</option>
							<option value="20" <?php if($this->limit==20){echo "selected";} ?>>20</option>
							<option value="25" <?php if($this->limit==25){echo "selected";} ?>>25</option>
							<option value="30" <?php if($this->limit==30){echo "selected";} ?>>30</option>
							<option value="35" <?php if($this->limit==35){echo "selected";} ?>>35</option>
							<option value="40" <?php if($this->limit==40){echo "selected";} ?>>40</option>
							<option value="50" <?php if($this->limit==50){echo "selected";} ?>>50</option>
							<option value="100" <?php if($this->limit==100){echo "selected";} ?>>100</option>
						</select>
					</div>
					<div class="limit" style="float:right;"><?php echo $this->showPage; ?></div>
				</div>
			</th>
		</tr>
		<tr>
			<th nowrap="nowrap">
				#
			</th>
			<th width="100%">
				Tên công việc
			</th>
                        <th></th>
		</tr>
	</thead>
	<tfoot>
		<tr>
			<th colspan="3">
				<div class="pagination">
					<div class="limit">Hiển thị #
						<select name="limit2" style="width:60px;" id="limit2" class="inputbox" size="1" onchange="
							document.frm.page.value = 1;
							document.frm.limit1.value = document.frm.limit2.value;
							document.frm.action = '/hscv/Tinhhinhxuly/hscvchoxuly';
							document.frm.submit();
						">
							<option value="5" <?php if($this->limit==5){echo "selected";} ?>>5</option>
							<option value="10" <?php if($this->limit==10){echo "selected";} ?>>10</option>
							<option value="15" <?php if($this->limit==15){echo "selected";} ?>>15</option>
							<option value="20" <?php if($this->limit==20){echo "selected";} ?>>20</option>
							<option value="25" <?php if($this->limit==25){echo "selected";} ?>>25</option>
							<option value="30" <?php if($this->limit==30){echo "selected";} ?>>30</option>
							<option value="35" <?php if($this->limit==35){echo "selected";} ?>>35</option>
							<option value="40" <?php if($this->limit==40){echo "selected";} ?>>40</option>
							<option value="50" <?php if($this->limit==50){echo "selected";} ?>>50</option>
							<option value="100" <?php if($this->limit==100){echo "selected";} ?>>100</option>
						</select>
					</div>
					<div style="float:right"><?php echo $this->showPage; ?></div>
				</div>
			</th>
		</tr>
	</tfoot>
	<tbody>
<?php
	if(count($this->data)<=0){
		echo "<tr><td colspan='4'>Không tìm thấy hồ sơ công việc nào</ td></tr>";
	}else{
	$stt=($this->page-1)*$this->limit;
	$i=0;
	foreach($this->data as $row){
	$row['NAME'] = $this->INNAME==1?QLVBDHCommon::highlightWords($row['NAME'],$this->NAME):$row['NAME'];
		$stt++;
?>
		<tr class="row<?=$this->idhscv==$row['ID_HSCV']?"2":$i?>">
			<td valign="top" rowspan="2"><a name="hscv<?=$row['ID_HSCV']?>"></a><?=$stt?></td>
			<td valign="top" colspan="2">
				<?php
					if($row["ALIAS"]=="VBD"){
						echo "<img src='/images/icon_vbden.jpg'>";
						$vbden = $this->vbden->findByHscv($row['ID_HSCV']);
						//var_dump($vbden);
					}else if($row["ALIAS"]=="VBSOANTHAO"){
						echo "<img src='/images/icon_soanthaovb.jpg'>";
					}else if($row["ALIAS"]=="MOTCUA"){
						echo "<img src='/images/icon_motcua.jpg'>";
					}
				?>
				<?php if($row["ALIAS"]=="VBD"){
					$vbdeninfo = $this->vbden->find($vbden['ID_VBD'])->current();
					echo "<b>".$vbdeninfo->SOKYHIEU." - ".QLVBDHCommon::MysqlDateToVnDate($vbdeninfo->NGAYBANHANH)." - ".$vbdeninfo->COQUANBANHANH_TEXT."</b><br>";
				}?>
				<?=$row['NAME']?>
			</td>
		</tr>
		<tr class="row<?=$this->idhscv==$row['ID_HSCV']?"2":$i?>">
			<td colspan="2">
				<div>
					<ul class="chitiethscv">
					<?php if(QLVBDHCommon::TabHscv(1,$row["ID_LOAIHSCV"])==1){ ?>
						<li id=groupicon1_<?=$row["ID_HSCV"]?>>
							<img src="/images/icon_chitiet.jpg" border="0" hspace="5" >
							<a href='javascript:SwapDiv(<?=$row["ID_HSCV"]?>,"/vbden/vbden/detail/type/<?=$row["ID_LOAIHSCV"]?>/id/<?=$row["ID_HSCV"]?>/year/<?=$this->realyear?><?=$disable?>",1)'>Chi tiết</a>
						</li>
					<?php } ?>
					<?php if(QLVBDHCommon::TabHscv(6,$row["ID_LOAIHSCV"])==1){ ?>
					<li id=groupicon6_<?=$row["ID_HSCV"]?>>
						<img src="/images/icon_luanchuyen.jpg" border="0" hspace="5" >
                                                <!-- thangtba sửa url bên dưới -->
                                                <?php
                                                        $id_choxl=0;
                                                        foreach ($this->dataYkien as $itemsYkien){
                                                            if ($itemsYkien['ID_HSCV_CHOXL'] == $row["ID_HSCV"]) {
                                                                $id_choxl = $row["ID_HSCV"];
                                                            }
                                                        }
                                                ?>
                                                <!--end thangtba sửa url bên dưới -->
						<a href='javascript:SwapDiv(<?=$row["ID_HSCV"]?>,"/hscv/hscv/way/id/<?=$row["ID_HSCV"]?>/year/<?=$this->realyear?>/type/<?=$row["ID_LOAIHSCV"]?><?=$disable?><?=$id_choxl!=0?"/id_dxcxl/$id_choxl":""?>",6)'>Luân chuyển</a>
					</li>
					<?php } ?>
					<?php if(QLVBDHCommon::TabHscv(5,$row["ID_LOAIHSCV"])==1){ ?>
					<li id=groupicon5_<?=$row["ID_HSCV"]?>>
						<img src="/images/icon_duthao.jpg" border="0" hspace="5" >
						<a href='javascript:SwapDiv(<?=$row["ID_HSCV"]?>,"/hscv/VanBanDuThao/index/year/<?=$this->realyear?>/iddivParent/groupcontent<?=$row["ID_HSCV"]?>/idHSCV/<?=$row["ID_HSCV"]?><?=$disable?>",5)'>Dự thảo</a>
					</li>
					<?php } ?>
					<?php if(QLVBDHCommon::TabHscv(8,$row["ID_LOAIHSCV"])==1){ ?>
					<li id=groupicon8_<?=$row["ID_HSCV"]?>>
						<img src="/images/icon_vanbanlienquan.jpg" border="0" hspace="5" >
						<a href='javascript:SwapDiv(<?=$row["ID_HSCV"]?>,"/hscv/hscv/bosung/year/<?=$this->realyear?>/iddivParent/groupcontent<?=$row["ID_HSCV"]?>/id/<?=$row["ID_HSCV"]?><?=$disable?>",8)'>Bổ sung hồ sơ</a>
					</li>
					<?php } ?>
					<?php if(QLVBDHCommon::TabHscv(2,$row["ID_LOAIHSCV"])==1){ ?>
					<li id=groupicon2_<?=$row["ID_HSCV"]?>>
						<img src="/images/icon_butphe.jpg" border="0" hspace="5" >
						<a href='javascript:SwapDiv(<?=$row["ID_HSCV"]?>,"/hscv/hscv/viewbutphe/id/<?=$row["ID_HSCV"]?>/year/<?=$this->realyear?><?=$disable?>",2)'>Bút phê</a>
					</li>
					<?php } ?>
					<?php if(QLVBDHCommon::TabHscv(3,$row["ID_LOAIHSCV"])==1){ ?>
					<li id=groupicon3_<?=$row["ID_HSCV"]?>>
						<img src="/images/icon_phoihop.gif" border="0" hspace="5" >
						<a href='javascript:SwapDiv(<?=$row["ID_HSCV"]?>,"/hscv/phoihop/index/idhscv/<?=$row["ID_HSCV"]?>/year/<?=$this->realyear?><?=strtoupper($this->code)=="PHOIHOP"?"":$disable?>",3)'>Phối hợp</a>
					</li>
					<?php } ?>
					<?php if(QLVBDHCommon::TabHscv(4,$row["ID_LOAIHSCV"])==1){ ?>
					<li id=groupicon4_<?=$row["ID_HSCV"]?>>
						<img src="/images/icon_files.jpg" border="0" hspace="5" >
						<a href='javascript:SwapDiv(<?=$row["ID_HSCV"]?>,"/hscv/file/index/iddiv/groupcontent<?=$row["ID_HSCV"]?>/idObject/<?=$row["ID_LOAIHSCV"]==1?$vbden['ID_VBD']:$row["ID_HSCV"]?>/is_new/0/year/<?=$this->realyear?>/type/<?=$row["ID_LOAIHSCV"]==1?"3":"1"?><?=$disablefile?>",4)'>Đính kèm</a>
					</li>
					<?php } ?>
					<?php if(QLVBDHCommon::TabHscv(7,$row["ID_LOAIHSCV"])==1){ ?>
					<li id=groupicon7_<?=$row["ID_HSCV"]?>>
						<img src="/images/icon_vanbanlienquan.jpg" border="0" hspace="5" >
						<a href='javascript:SwapDiv(<?=$row["ID_HSCV"]?>,"/hscv/vanbanlienquan/index/year/<?=$this->realyear?>/iddivParent/groupcontent<?=$row["ID_HSCV"]?>/idHSCV/<?=$row["ID_HSCV"]?><?=$disable?>",7)'>VB liên quan</a>
					</li>
					<?php } ?>
					<?php if($this->id_thumuc>1){ ?>
					<li id=groupicon9_<?=$row["ID_HSCV"]?>>
						<img src="/images/icon_vanbanlienquan.jpg" border="0" hspace="5" >
						<a href='javascript:SwapDiv(<?=$row["ID_HSCV"]?>,"/hscv/hscv/viewresult/iddivParent/groupcontent<?=$row["ID_HSCV"]?>/id/<?=$row["ID_HSCV"]?>",9)'>Kết quả</a>
					</li>
					<?php } ?>
					</ul>
				</div>
				<div class="groupcontent" id="groupcontent<?=$row["ID_HSCV"]?>" style="display:none;background: #ffffff; border: 1px solid #ccc;"></div>
			</td>
		</tr>
<?php
		$i = (-1+$i)*-1;	
	}
}
?>
	</tbody>
</table>
<input type="hidden" name="page" value="<?php echo $this->page; ?>">

</form>
<script>
	function SwapDiv(id,url,tab){
		for(var i=1;i<11;i++){
			if(document.getElementById("groupicon"+i+"_"+id)){
				if(tab!=i){
					if(document.getElementById("groupicon"+i+"_"+id).className=="groupiconopen"){
						document.getElementById("groupcontent"+id).style.display="none";
						document.getElementById("groupicon"+i+"_"+id).className = "groupicon";
						break;
					}
				}
			}
		}
		if(document.getElementById("groupcontent"+id).style.display==""){
			document.getElementById("groupcontent"+id).style.display="none";
			document.getElementById("groupicon"+tab+"_"+id).className = "groupicon";
		}else{
			document.getElementById("groupcontent"+id).style.display="";
			document.getElementById("groupicon"+tab+"_"+id).className = "groupiconopen";
			document.getElementById("groupcontent"+id).innerHTML="<img src='/images/loading.gif' width='16' height='16' border='0'></img<img src='/images/loading.gif' width='16' height='16' border='0'></img><img src='/images/loading.gif' width='16' height='16' border='0'></img><img src='/images/loading.gif' width='16' height='16' border='0'></img>";
			loadDivFromUrl("groupcontent"+id,url,1);

	}
	}
	function SwapIframe(id,url){
		for(var i=1;i<11;i++){
			if(document.getElementById("groupicon"+i+"_"+id)){
				if(document.getElementById("groupicon"+i+"_"+id).className=="groupiconopen"){
					document.getElementById("groupcontent"+id).style.display="none";
					document.getElementById("groupicon"+i+"_"+id).className = "groupicon";
					break;
				}
			}
		}
		if(document.getElementById('groupcontent'+id).style.display == ''){
			document.getElementById('groupcontent'+id).style.display = 'none';
		}else{
			document.getElementById('groupcontent'+id).innerHTML = '<iframe style="overflow-x:visible" height=0 id=iframebutphe'+id+' allowTransparency=true BORDER=0 scrolling=no FRAMEBORDER=no src="'+url+'"></iframe>';
			document.getElementById('groupcontent'+id).style.display = '';
		}
	}
	function Swap(id,url){
		if(document.getElementById(id).style.display==""){
			document.getElementById(id).style.display="none";
			document.getElementById("groupicon"+id).className = "groupicon";
		}else{
			document.getElementById(id).style.display="";
			document.getElementById("groupicon"+id).className = "groupiconopen";
			loadDivFromUrl(id,url,1);
		}
	}

	function xulylai(ID_LUUCXL){
		
		var func_yes = "execfunction('hscv','hscv','phuchoiluuchoxuly','id/"+ID_LUUCXL+"');";
		var func_cancel = "";
		
		displayConfirm("Bạn có muốn tiếp tục xử lý công việc này không?","","",func_yes,func_cancel);
		
			

	}

    function BackButtonClick(){
	document.frm.action = '/default';
	document.frm.submit();
    }   
</script>
