<?php 
require_once('qtht/models/DepartmentsModel.php');
$data_departs = DepartmentsModel::getAll();
?>
<script type="text/javascript" src="/js/calendar.js"></script>
<script src="/jquery/jquery-1.10.2.js" type="text/javascript" ></script>
<script type="text/javascript">
    var jq1102 = jQuery.noConflict( true );
</script>
<form name=frm action="/giamsatgiaoviec/baocao/baocaochitietgiaoviecnoiboview" method="POST" target="reportview">
    <div class=clr></div>
    <div>
        <label><b>Ngày giao việc:</b></label>
        <?= QLVBDHCommon::calendar($this->fromdate, "fromdate", "fromdate") ?>
        >>
        <?= QLVBDHCommon::calendar($this->todate, "todate", "todate") ?>

    </div>

    <div class=clr></div>
    <div>
        <div>
            <label><b>Tháng:</b></label>
            <input type="radio" name='sel_timedis' onclick="setvalueDateD('1/1', '31/1')">1
            <?php
            $year = QLVBDHCommon::getYear();
            $d = strtotime($year . "-3-1");
            $d = $d - 86400;
            $str_cuoi2 = date('d/m', $d);
            ?>
            <input type="radio" name='sel_timedis' onclick="setvalueDateD('1/2', '<?php echo $str_cuoi2 ?>')" >2
            <input type="radio" name='sel_timedis' onclick="setvalueDateD('1/3', '31/3')">3
            <input type="radio" name='sel_timedis'onclick="setvalueDateD('1/4', '30/4')" >4
            <input type="radio" name='sel_timedis'onclick="setvalueDateD('1/5', '31/5')">5
            <input type="radio" name='sel_timedis' onclick="setvalueDateD('1/6', '30/6')">6
            <input type="radio" name='sel_timedis'onclick="setvalueDateD('1/7', '31/7')" >7
            <input type="radio" name='sel_timedis'onclick="setvalueDateD('1/8', '31/8')" >8
            <input type="radio" name='sel_timedis'onclick="setvalueDateD('1/9', '30/9')">9
            <input type="radio" name='sel_timedis'onclick="setvalueDateD('1/10', '31/10')">10
            <input type="radio" name='sel_timedis'onclick="setvalueDateD('1/11', '30/11')">11
            <input type="radio" name='sel_timedis'onclick="setvalueDateD('1/12', '31/12')">12
        </div>
        <div class=clr></div>
        <div>
            <label><b>Quí:</b></label>
            <input type="radio" name='sel_timedis' onclick="setvalueDateD('1/1', '31/3')">I
            <input type="radio" name='sel_timedis' onclick="setvalueDateD('1/4', '30/6')">II
            <input type="radio" name='sel_timedis'onclick="setvalueDateD('1/7', '30/9')">III
            <input type="radio" name='sel_timedis'onclick="setvalueDateD('1/10', '31/12')">IV
        </div>
        <div class=clr></div>
        <div>
            <label><b>Năm:</b></label>
            <input type="radio" name='sel_timedis' onclick="setvalueDateD('1/1', '31/12')">
        </div>
    </div>
     <div class=clr></div>
    <div>
        <label><b>Người xử lý:</b></label>
        <select name="sel_pb" id="sel_pb" onchange="document.getElementById('ID_DEP').value = this.value;FillComboByComboExp1(this,document.getElementById('ID_U'),ARR_ID_U,arr_user);">
            <option value=0>[Tất cả phòng ban]</option>
            <?php
            $user = Zend_Registry::get('auth')->getIdentity();
            DepartmentsModel::toComboNameWithSel($this->sel_pb);
            ?>
        </select>
        </br>
        <?php 
            echo QLVBDHCommon::writeSelectDepartmentUserWithSelreport('ID_DEP','ID_U');
        ?>        
    </div>     
    <div class=clr></div>
    <div>
        <label><b>Loại công việc giao:</b></label>
        <select name="sel_nhomcv[]" id="sel_nhomcv" multiple="multiple" size=3>
            <option value=0 selected="true">[Tất cả nhóm công việc]</option>
            <?php
            foreach($this->dataloaicongviec as $itemloaicongviec){
            ?>
            <option value="<?=$itemloaicongviec['CODE'] ?>" <?=$this->data["LOAICV_GIAOVIEC"]==$itemloaicongviec['CODE']?'selected':''?>><?=$itemloaicongviec['NAME'] ?></option>
            <?php
            }
            ?>
        </select>
    </div>
    <div class=clr></div>
    <div>
        <label><b>Tình hình xử lý:</b></label>
        <select name="sel_tinhhinh" id="sel_tinhhinh">
            <option value="0">Đang xử lý</option>
            <option value="1">Đã hoàn thành</option>
        </select>
    </div>
    <div class="clr"></div>
    <div style="display:none">
        <label><b>Trạng thái:</b></label>
        <select name="sel_trangthai[]" id="sel_trangthai" multiple="true">
            <option value="0" gdata="0">Đúng hạn</option>
            <option value="1" gdata="0">Sớm hạn</option>
            <option value="2" gdata="0">Trễ hạn</option>
            <option value="3" gdata="1">Chưa đến hạn</option>
            <option value="4" gdata="1">Quá hạn</option>
        </select>
    </div>
    <div class="clr"></div>
    <div style="display:none">
        <label><b>Lịch sử tiến độ:</b></label>
        <input checked="true" value="1" type="checkbox" name="ck_tiendo" id="ck_tiendo">
    </div>
    <div class="clr"></div>
    <input type=hidden id=h_isexel name=h_isexel value=0>
    <div>
        <br/>
        <input type="button" title="Hiển thị báo cáo" value="Hiển thị" onclick="document.frm.target = 'reportview';
                document.frm.h_isexel.value = 0;
                document.frm.action = '/giamsatgiaoviec/baocao/baocaochitietgiaoviecnoiboview';
                document.frm.submit();
                return false;" style="background: url(/images/hscv-input-bg.png) repeat-x;" >
        <input type="button" title="Xuất excel" value="Xuất Excel" onclick="document.frm.target = 'reportview';
                document.frm.h_isexel.value = 1;
                document.frm.action = '/giamsatgiaoviec/baocao/baocaochitietgiaoviecnoiboview/is_in/1';
                document.frm.submit();
                return false;" style="background: url(/images/hscv-input-bg.png) repeat-x;" >
        <input type="button" title="In báo cáo" value="In báo cáo" onclick="document.frm.target = '_blank';
                document.frm.h_isexel.value = 0;
                document.frm.action = '/giamsatgiaoviec/baocao/baocaochitietgiaoviecnoiboview/is_in/1';
                document.frm.submit();
                return false;" style="background: url(/images/hscv-input-bg.png) repeat-x;" >
    </div>
</form>
<iframe  style="overflow-x:visible" allowTransparency=true BORDER=0 scrolling=no FRAMEBORDER=no 
         id="reportview" 
         name="reportview" >
</iframe>
<script>
    var arr_user = new Array();
    document.getElementById('ID_DEP').style.display="none";
    function setvalueDateD(value_from, value_to) {
        document.frm.fromdate.value = value_from;
        document.frm.todate.value = value_to;
    }
    
    jq1102('select[name=sel_tinhhinh]').change(function () {
        var value = jq1102(this).val();
        jq1102('#sel_trangthai  option').each(function() {
            if(jq1102(this).attr('gdata') == value){                
                jq1102(this).show();
            }else{
               jq1102(this).removeAttr('selected');
               jq1102(this).hide(); 
            }
        });
    });
    jq1102('select[name=sel_tinhhinh]').trigger('change');
</script>
