<html xmlns:v="urn:schemas-microsoft-com:vml"
xmlns:o="urn:schemas-microsoft-com:office:office"
xmlns:x="urn:schemas-microsoft-com:office:excel"
xmlns="http://www.w3.org/TR/REC-html40">

<head>
<meta http-equiv=Content-Type content="text/html; charset=utf-8">
<meta name=ProgId content=Excel.Sheet>
<meta name=Generator content="Microsoft Excel 15">
<style>
<!--table
	{mso-displayed-decimal-separator:"\.";
	mso-displayed-thousand-separator:"\,";}
@page
	{margin:.75in .7in .75in .7in;
	mso-header-margin:.3in;
	mso-footer-margin:.3in;}
-->
tr
	{mso-height-source:auto;}
col
	{mso-width-source:auto;}
br
	{mso-data-placement:same-cell;}
.style0
	{mso-number-format:General;
	text-align:general;
	vertical-align:bottom;
	white-space:nowrap;
	mso-rotate:0;
	mso-background-source:auto;
	mso-pattern:auto;
	color:black;
	font-size:11.0pt;
	font-weight:400;
	font-style:normal;
	text-decoration:none;
	font-family:Calibri, sans-serif;
	mso-font-charset:0;
	border:none;
	mso-protection:locked visible;
	mso-style-name:Normal;
	mso-style-id:0;}
td
	{mso-style-parent:style0;
	padding-top:1px;
	padding-right:1px;
	padding-left:1px;
	mso-ignore:padding;
	color:black;
	font-size:11.0pt;
	font-weight:400;
	font-style:normal;
	text-decoration:none;
	font-family:Calibri, sans-serif;
	mso-font-charset:0;
	mso-number-format:General;
	text-align:general;
	vertical-align:bottom;
	border:none;
	mso-background-source:auto;
	mso-pattern:auto;
	mso-protection:locked visible;
	white-space:nowrap;
	mso-rotate:0;}
.xl65
	{mso-style-parent:style0;
	text-align:center;
	vertical-align:middle;
	white-space:normal;}
.xl66
	{mso-style-parent:style0;
	font-weight:700;
	text-align:center;
	vertical-align:middle;
	white-space:normal;}
.xl67
	{mso-style-parent:style0;
	font-weight:700;
	text-align:center;
	vertical-align:middle;
	border:.5pt solid windowtext;
	white-space:normal;}
.xl68
	{mso-style-parent:style0;
	color:#161616;
	font-size:14.0pt;
	font-weight:700;
	text-align:center;
	vertical-align:middle;
	white-space:normal;}
.xl69
	{mso-style-parent:style0;
	text-align:center;
	vertical-align:middle;
	border-top:.5pt solid windowtext;
	border-right:none;
	border-bottom:.5pt solid windowtext;
	border-left:.5pt solid windowtext;
	white-space:normal;}
.xl70
	{mso-style-parent:style0;
	text-align:center;
	vertical-align:middle;
	border-top:.5pt solid windowtext;
	border-right:none;
	border-bottom:.5pt solid windowtext;
	border-left:none;
	white-space:normal;}
.xl71
	{mso-style-parent:style0;
	text-align:center;
	vertical-align:middle;
	border-top:.5pt solid windowtext;
	border-right:.5pt solid windowtext;
	border-bottom:.5pt solid windowtext;
	border-left:none;
	white-space:normal;}
.xl72
	{mso-style-parent:style0;
	text-align:center;
	vertical-align:middle;
	border:.5pt solid windowtext;
	white-space:normal;}

</style>
</head>

<body link="#0563C1" vlink="#954F72" class=xl65>

<table border=0 cellpadding=0 cellspacing=0 width=1226 style='border-collapse:
 collapse;table-layout:fixed;width:920pt'>
 <col class=xl65 width=31 style='mso-width-source:userset;mso-width-alt:1133;
 width:23pt'>
 <col class=xl65 width=109 style='mso-width-source:userset;mso-width-alt:3986;
 width:82pt'>
 <col class=xl65 width=98 style='mso-width-source:userset;mso-width-alt:3584;
 width:74pt'>
 <col class=xl65 width=96 style='mso-width-source:userset;mso-width-alt:3510;
 width:72pt'>
 <col class=xl65 width=100 style='mso-width-source:userset;mso-width-alt:3657;
 width:75pt'>
 <col class=xl65 width=111 style='mso-width-source:userset;mso-width-alt:4059;
 width:83pt'>
 <col class=xl65 width=112 style='mso-width-source:userset;mso-width-alt:4096;
 width:84pt'>
 <col class=xl65 width=109 style='mso-width-source:userset;mso-width-alt:3986;
 width:82pt'>
 <col class=xl65 width=79 style='mso-width-source:userset;mso-width-alt:2889;
 width:59pt'>
 <col class=xl65 width=82 style='mso-width-source:userset;mso-width-alt:2998;
 width:62pt'>
 <col class=xl65 width=107 style='mso-width-source:userset;mso-width-alt:3913;
 width:80pt'>
 <col class=xl65 width=64 span=3 style='width:48pt'>
 <tr height=20 style='height:15.0pt'>
  <td height=20 class=xl65 width=31 style='height:15.0pt;width:23pt'></td>
  <td class=xl65 width=109 style='width:82pt'></td>
  <td class=xl65 width=98 style='width:74pt'></td>
  <td class=xl65 width=96 style='width:72pt'></td>
  <td class=xl65 width=100 style='width:75pt'></td>
  <td class=xl65 width=111 style='width:83pt'></td>
  <td class=xl65 width=112 style='width:84pt'></td>
  <td class=xl65 width=109 style='width:82pt'></td>
  <td class=xl65 width=79 style='width:59pt'></td>
  <td class=xl65 width=82 style='width:62pt'></td>
  <td class=xl65 width=107 style='width:80pt'></td>
  <td class=xl65 width=64 style='width:48pt'></td>
  <td class=xl65 width=64 style='width:48pt'></td>
  <td class=xl65 width=64 style='width:48pt'></td>
 </tr>
 <tr height=20 style='height:15.0pt'>
  <td height=20 class=xl65 width=31 style='height:15.0pt;width:23pt'></td>
  <td class=xl65 width=109 style='width:82pt'></td>
  <td class=xl65 width=98 style='width:74pt'></td>
  <td class=xl65 width=96 style='width:72pt'></td>
  <td class=xl65 width=100 style='width:75pt'></td>
  <td class=xl65 width=111 style='width:83pt'></td>
  <td class=xl65 width=112 style='width:84pt'></td>
  <td class=xl65 width=109 style='width:82pt'></td>
  <td class=xl65 width=79 style='width:59pt'></td>
  <td class=xl65 width=82 style='width:62pt'></td>
  <td class=xl65 width=107 style='width:80pt'></td>
  <td class=xl65 width=64 style='width:48pt'></td>
  <td class=xl65 width=64 style='width:48pt'></td>
  <td class=xl65 width=64 style='width:48pt'></td>
 </tr>
     <?php
require_once 'giamsatgiaoviec/models/BaoCaoModel.php';
?>
 <tr class=xl66 height=20 style='mso-height-source:userset;height:15.0pt'>
  <td colspan=14 height=20 class=xl68 width=1226 style='height:15.0pt;
  width:920pt'>BÁO CÁO QUẢN TRỊ VIỆC NỘI BỘ</td>
 </tr>
 <tr height=20 style='height:15.0pt'>
  <td colspan=14 height=20 class=xl65 width=1226 style='height:15.0pt;
  width:920pt'>(<?=$this->thu?>)</td>
 </tr>
 <tr height=20 style='height:15.0pt'>
  <td height=20 class=xl65 width=31 style='height:15.0pt;width:23pt'></td>
  <td class=xl65 width=109 style='width:82pt'></td>
  <td class=xl65 width=98 style='width:74pt'></td>
  <td class=xl65 width=96 style='width:72pt'></td>
  <td class=xl65 width=100 style='width:75pt'></td>
  <td class=xl65 width=111 style='width:83pt'></td>
  <td class=xl65 width=112 style='width:84pt'></td>
  <td class=xl65 width=109 style='width:82pt'></td>
  <td class=xl65 width=79 style='width:59pt'></td>
  <td class=xl65 width=82 style='width:62pt'></td>
  <td class=xl65 width=107 style='width:80pt'></td>
  <td class=xl65 width=64 style='width:48pt'></td>
  <td class=xl65 width=64 style='width:48pt'></td>
  <td class=xl65 width=64 style='width:48pt'></td>
 </tr>
 <tr height=60 style='height:45.0pt'>
  <td height=60 class=xl67 width=31 style='height:45.0pt;width:23pt'>TT</td>
  <td class=xl67 width=109 style='border-left:none;width:82pt'>Tên công việc</td>
  <td class=xl67 width=98 style='border-left:none;width:74pt'>Vb đến/Căn cứ</td>
  <td class=xl67 width=96 style='border-left:none;width:72pt'>Ngày đến/giao</td>
  <td class=xl67 width=100 style='border-left:none;width:75pt'>Thủ tục nội
  bộ<span style='mso-spacerun:yes'> </span></td>
  <td class=xl67 width=111 style='border-left:none;width:83pt'>Phòng thực hiện</td>
  <td class=xl67 width=112 style='border-left:none;width:84pt'>Người thực hiện</td>
  <td class=xl67 width=109 style='border-left:none;width:82pt'>Phòng phối
  hợp<span style='mso-spacerun:yes'> </span></td>
  <td class=xl67 width=79 style='border-left:none;width:59pt'>Tiến độ (%)</td>
  <td class=xl67 width=82 style='border-left:none;width:62pt'>Ngày cập
  nhật/hoàn thành</td>
  <td class=xl67 width=107 style='border-left:none;width:80pt'>Mô tả tiến độ (2
  dòng mô tả tiến độ mới nhất)</td>
  <td class=xl67 width=64 style='border-left:none;width:48pt'>Thời hạn</td>
  <td class=xl67 width=64 style='border-left:none;width:48pt'>Tình hình xử lý</td>
  <td class=xl67 width=64 style='border-left:none;width:48pt'>Trạng thái</td>
 </tr> 
     <?php
        $fromdateQuery=$this->params['fromdate'].'/'.$this->year;
        $todateQuery=$this->params['todate'].'/'.$this->year;
        
        $baoCaoModel =new BaoCaoModel();
        if(isset($this->params['ID_U']) && is_array($this->params['ID_U'])){
            if(in_array(1,$this->params['ID_U'])){
                $this->params['ID_U']= $baoCaoModel->getAllUserByDep($this->params['sel_pb']);
            }
            if(in_array(0,$this->params['sel_nhomcv'])){
                $ncvArr = array();
                foreach ($this->dataloaicongviec as $itemlcv){
                    array_push($ncvArr, $itemlcv['CODE']);
                }
                $this->params['sel_nhomcv'] =$ncvArr;
            }
            $dataReport = $baoCaoModel->baoCaoChiTietDonVi($this->params['sel_nhomcv'],$this->params['ID_U'],$this->params['sel_tinhhinh'],$this->params['sel_trangthai'],$fromdateQuery,$todateQuery);
            $stt =0;            
            foreach($this->params['sel_nhomcv'] as $itemnhom){
                $check =false;
                foreach($dataReport as $itemReport){ 
                    if($itemnhom == $itemReport['LOAICV_GIAOVIEC']){
                        $stt++;
                        if($check!=true){
                            ?>
     
     <tr height=20 style='height:15.0pt'>
  <td height=20 class=xl72 width=31 style='height:15.0pt;border-top:none;
  width:23pt'>&nbsp;</td>
  <td colspan=13 class=xl69 width=1195 style='border-right:.5pt solid black;
  border-left:none;width:897pt'><?= $itemReport['LOAICVNAME_GIAOVIEC'] ?></td>
 </tr>
     <?php
                            $check =true;
                        }
                        ?>
 <tr height=20 style='height:15.0pt'>
  <td height=20 class=xl72 width=31 style='height:15.0pt;border-top:none;
  width:23pt'><?=$stt ?></td>  
  <td class=xl72 width=98 style='border-top:none;border-left:none;width:74pt'><?=$itemReport['NHIEMVU'] ?></td>
  <td class=xl72 width=96 style='border-top:none;border-left:none;width:72pt'><?=$itemReport['SOKYHIEU'].'-'.$itemReport['TRICHYEU'] ?></td>
  <td class=xl72 width=100 style='border-top:none;border-left:none;width:75pt'><?=$itemReport['NGAYDEN'] ?></td>
  <td class=xl72 width=111 style='border-top:none;border-left:none;width:83pt'>&nbsp;</td>
  <td class=xl72 width=112 style='border-top:none;border-left:none;width:84pt'><?php
                                $nguoixuly = json_decode($itemReport['ID_U_XULYGIAOVIEC']);
                                foreach($nguoixuly as $itemNguoiXuLy){
                                    echo $baoCaoModel->getDepOfNguoiXuLy($itemNguoiXuLy).'</br>';
                                }
                                ?></td>
  <td class=xl72 width=109 style='border-top:none;border-left:none;width:82pt'><?php
                                foreach($nguoixuly as $itemNguoiXuLy){
                                    echo UsersModel::getEmloyeeNameByIdUser($itemNguoiXuLy).'</br>';
                                }
                            ?></td>
  <td class=xl72 width=79 style='border-top:none;border-left:none;width:59pt'><?php
                                $nguoiphoihop = json_decode($itemReport['ID_U_PHOIHOPGIAOVIEC']);
                                foreach($nguoiphoihop as $itemNguoiPhoiHop){
                                    echo $baoCaoModel->getDepOfNguoiXuLy($itemNguoiPhoiHop).'</br>';
                                }
                            ?></td>
  <?php
                            $dataTienDo = $baoCaoModel->getMoTaTienDo($itemReport['ID_HSCV']);
                            ?>
  <td class=xl72 width=82 style='border-top:none;border-left:none;width:62pt'><?=$itemReport['TIENDO_GIAOVIEC']?></td>
  <td class=xl72 width=107 style='border-top:none;border-left:none;width:80pt'><?=$dataTienDo[0]['NGAYCAPNHAT']?></td>
  <td class=xl72 width=64 style='border-top:none;border-left:none;width:48pt'><?php
                            foreach($dataTienDo as $itemdataTienDo){
                                echo $itemdataTienDo['TIENDO'].'-'.$itemdataTienDo['MOTA'].'</br>';
                            }
                            ?></td>
  <td class=xl72 width=64 style='border-top:none;border-left:none;width:48pt'>&nbsp;</td>
  <td class=xl72 width=64 style='border-top:none;border-left:none;width:48pt'><?=$itemReport['TIENDO_GIAOVIEC'] >=100?"Đã hoàn thành":'Đang xử lý'?></td>
  <td class=xl72 width=109 style='border-top:none;border-left:none;width:82pt'></td>
 </tr><?php
                    }
                }
            }
        } 
        ?>
 <![if supportMisalignedColumns]>
 <tr height=0 style='display:none'>
  <td width=31 style='width:23pt'></td>
  <td width=109 style='width:82pt'></td>
  <td width=98 style='width:74pt'></td>
  <td width=96 style='width:72pt'></td>
  <td width=100 style='width:75pt'></td>
  <td width=111 style='width:83pt'></td>
  <td width=112 style='width:84pt'></td>
  <td width=109 style='width:82pt'></td>
  <td width=79 style='width:59pt'></td>
  <td width=82 style='width:62pt'></td>
  <td width=107 style='width:80pt'></td>
  <td width=64 style='width:48pt'></td>
  <td width=64 style='width:48pt'></td>
  <td width=64 style='width:48pt'></td>
 </tr>
 <![endif]>
</table>

</body>

</html>
