<?php 
require_once('qtht/models/DepartmentsModel.php');
$data_departs = DepartmentsModel::getAll();
?>
<script type="text/javascript" src="/js/calendar.js"></script>
<script src="/jquery/jquery-1.10.2.js" type="text/javascript" ></script>
<script type="text/javascript">
    var jq1102 = jQuery.noConflict( true );
</script>
<form name=frm action="/giamsatgiaoviec/baocao/thongkeview" method="POST" target="reportview">
    <div class=clr></div>
    <div>
        <label><b>Ngày giao việc:</b></label>
        <?= QLVBDHCommon::calendar($this->fromdate, "fromdate", "fromdate") ?>
        >>
        <?= QLVBDHCommon::calendar($this->todate, "todate", "todate") ?>

    </div>

    <div class=clr></div>
    <div>
        <div>
            <label><b>Tháng:</b></label>
            <input type="radio" name='sel_timedis' onclick="setvalueDateD('1/1', '31/1')">1
            <?php
            $year = QLVBDHCommon::getYear();
            $d = strtotime($year . "-3-1");
            $d = $d - 86400;
            $str_cuoi2 = date('d/m', $d);
            ?>
            <input type="radio" name='sel_timedis' onclick="setvalueDateD('1/2', '<?php echo $str_cuoi2 ?>')" >2
            <input type="radio" name='sel_timedis' onclick="setvalueDateD('1/3', '31/3')">3
            <input type="radio" name='sel_timedis'onclick="setvalueDateD('1/4', '30/4')" >4
            <input type="radio" name='sel_timedis'onclick="setvalueDateD('1/5', '31/5')">5
            <input type="radio" name='sel_timedis' onclick="setvalueDateD('1/6', '30/6')">6
            <input type="radio" name='sel_timedis'onclick="setvalueDateD('1/7', '31/7')" >7
            <input type="radio" name='sel_timedis'onclick="setvalueDateD('1/8', '31/8')" >8
            <input type="radio" name='sel_timedis'onclick="setvalueDateD('1/9', '30/9')">9
            <input type="radio" name='sel_timedis'onclick="setvalueDateD('1/10', '31/10')">10
            <input type="radio" name='sel_timedis'onclick="setvalueDateD('1/11', '30/11')">11
            <input type="radio" name='sel_timedis'onclick="setvalueDateD('1/12', '31/12')">12
        </div>
        <div class=clr></div>
        <div>
            <label><b>Quí:</b></label>
            <input type="radio" name='sel_timedis' onclick="setvalueDateD('1/1', '31/3')">I
            <input type="radio" name='sel_timedis' onclick="setvalueDateD('1/4', '30/6')">II
            <input type="radio" name='sel_timedis'onclick="setvalueDateD('1/7', '30/9')">III
            <input type="radio" name='sel_timedis'onclick="setvalueDateD('1/10', '31/12')">IV
        </div>
        <div class=clr></div>
        <div>
            <label><b>Năm:</b></label>
            <input type="radio" name='sel_timedis' onclick="setvalueDateD('1/1', '31/12')">
        </div>
    </div>
    <div class=clr></div>
     <div>
        <label><b>Đơn vị:</b></label>
        <select name="sel_donvi[]" id="sel_donvi" onchange="" multiple="">
            <option value=0>[Tất cả đơn vị]</option>
            <?php
            require_once("hscv/models/coquanlienthongModel.php");
            $data_cqlt = coquanlienthongModel::getDataCQLienThong();
            foreach($data_cqlt as $itemcq){
            ?>
                <option value="<?=$itemcq['CODE']?>"><?=$itemcq['NAME']?></option>
            <?php
            }
            ?>
        </select>              
    </div>
    <div class=clr></div>
    <input type=hidden id=h_isexel name=h_isexel value=0>
    <div>
        <br/>
        <input type="button" title="Hiển thị báo cáo" value="Hiển thị" onclick="document.frm.target = 'reportview';
                document.frm.h_isexel.value = 0;
                document.frm.action = '/giamsatgiaoviec/baocao/thongkeview';
                document.frm.submit();
                return false;" style="background: url(/images/hscv-input-bg.png) repeat-x;" >
        <input type="button" title="Xuất excel" value="Xuất Excel" onclick="document.frm.target = 'reportview';
                document.frm.h_isexel.value = 1;
                document.frm.action = '/giamsatgiaoviec/baocao/thongkeview/is_in/1';
                document.frm.submit();
                return false;" style="background: url(/images/hscv-input-bg.png) repeat-x;" >
        <input type="button" title="In báo cáo" value="In báo cáo" onclick="document.frm.target = '_blank';
                document.frm.h_isexel.value = 0;
                document.frm.action = '/giamsatgiaoviec/baocao/thongkeview/is_in/1';
                document.frm.submit();
                return false;" style="background: url(/images/hscv-input-bg.png) repeat-x;" >
    </div>
    <div class=clr></div>
</form>
<iframe  style="overflow-x:visible" allowTransparency=true BORDER=0 scrolling=no FRAMEBORDER=no 
         id="reportview" 
         name="reportview" >
</iframe>
<script>   
    function setvalueDateD(value_from, value_to) {
        document.frm.fromdate.value = value_from;
        document.frm.todate.value = value_to;
    }    
</script>
