<html xmlns:o="urn:schemas-microsoft-com:office:office"
xmlns:x="urn:schemas-microsoft-com:office:excel"
xmlns="http://www.w3.org/TR/REC-html40">

<head>
<meta http-equiv=Content-Type content="text/html; charset=utf-8">
<meta name=ProgId content=Excel.Sheet>
<meta name=Generator content="Microsoft Excel 14">
<link rel=File-List href="abc2_files/filelist.xml">
<style id="abc_18935_Styles">
<!--table
	{mso-displayed-decimal-separator:"\.";
	mso-displayed-thousand-separator:"\,";}
.xl6518935
	{padding-top:1px;
	padding-right:1px;
	padding-left:1px;
	mso-ignore:padding;
	color:windowtext;
	font-size:12.0pt;
	font-weight:400;
	font-style:normal;
	text-decoration:none;
	font-family:"Times New Roman", serif;
	mso-font-charset:0;
	mso-number-format:General;
	text-align:general;
	vertical-align:bottom;
	mso-background-source:auto;
	mso-pattern:auto;
	white-space:nowrap;}
.xl6618935
	{padding-top:1px;
	padding-right:1px;
	padding-left:1px;
	mso-ignore:padding;
	color:windowtext;
	font-size:12.0pt;
	font-weight:700;
	font-style:normal;
	text-decoration:none;
	font-family:"Times New Roman", serif;
	mso-font-charset:0;
	mso-number-format:General;
	text-align:general;
	vertical-align:bottom;
	mso-background-source:auto;
	mso-pattern:auto;
	white-space:nowrap;}
.xl6718935
	{padding-top:1px;
	padding-right:1px;
	padding-left:1px;
	mso-ignore:padding;
	color:windowtext;
	font-size:12.0pt;
	font-weight:400;
	font-style:italic;
	text-decoration:none;
	font-family:"Times New Roman", serif;
	mso-font-charset:0;
	mso-number-format:General;
	text-align:general;
	vertical-align:bottom;
	mso-background-source:auto;
	mso-pattern:auto;
	white-space:nowrap;}
.xl6818935
	{padding-top:1px;
	padding-right:1px;
	padding-left:1px;
	mso-ignore:padding;
	color:windowtext;
	font-size:12.0pt;
	font-weight:700;
	font-style:normal;
	text-decoration:none;
	font-family:"Times New Roman", serif;
	mso-font-charset:0;
	mso-number-format:General;
	text-align:center;
	vertical-align:top;
	border:.5pt solid windowtext;
	background:silver;
	mso-pattern:black none;
	white-space:normal;}
.xl6918935
	{padding-top:1px;
	padding-right:1px;
	padding-left:1px;
	mso-ignore:padding;
	color:windowtext;
	font-size:12.0pt;
	font-weight:400;
	font-style:normal;
	text-decoration:none;
	font-family:"Times New Roman", serif;
	mso-font-charset:0;
	mso-number-format:General;
	text-align:center;
	vertical-align:bottom;
	mso-background-source:auto;
	mso-pattern:auto;
	white-space:nowrap;}
.xl7018935
	{padding-top:1px;
	padding-right:1px;
	padding-left:1px;
	mso-ignore:padding;
	color:windowtext;
	font-size:12.0pt;
	font-weight:700;
	font-style:normal;
	text-decoration:none;
	font-family:"Times New Roman", serif;
	mso-font-charset:0;
	mso-number-format:General;
	text-align:center;
	vertical-align:bottom;
	mso-background-source:auto;
	mso-pattern:auto;
	white-space:nowrap;}
.xl7118935
	{padding-top:1px;
	padding-right:1px;
	padding-left:1px;
	mso-ignore:padding;
	color:windowtext;
	font-size:12.0pt;
	font-weight:700;
	font-style:normal;
	text-decoration:underline;
	text-underline-style:single;
	font-family:"Times New Roman", serif;
	mso-font-charset:0;
	mso-number-format:General;
	text-align:center;
	vertical-align:bottom;
	mso-background-source:auto;
	mso-pattern:auto;
	white-space:nowrap;}
.xl7218935
	{padding-top:1px;
	padding-right:1px;
	padding-left:1px;
	mso-ignore:padding;
	color:windowtext;
	font-size:12.0pt;
	font-weight:400;
	font-style:italic;
	text-decoration:none;
	font-family:"Times New Roman", serif;
	mso-font-charset:0;
	mso-number-format:General;
	text-align:center;
	vertical-align:bottom;
	mso-background-source:auto;
	mso-pattern:auto;
	white-space:nowrap;}
.xl7318935
	{padding-top:1px;
	padding-right:1px;
	padding-left:1px;
	mso-ignore:padding;
	color:windowtext;
	font-size:12.0pt;
	font-weight:400;
	font-style:normal;
	text-decoration:none;
	font-family:"Times New Roman", serif;
	mso-font-charset:0;
	mso-number-format:General;
	text-align:center;
	vertical-align:middle;
	border:.5pt solid windowtext;
	mso-background-source:auto;
	mso-pattern:auto;
	white-space:normal;}
.xl7418935
	{padding-top:1px;
	padding-right:1px;
	padding-left:1px;
	mso-ignore:padding;
	color:windowtext;
	font-size:12.0pt;
	font-weight:400;
	font-style:normal;
	text-decoration:none;
	font-family:"Times New Roman", serif;
	mso-font-charset:0;
	mso-number-format:"\@";
	text-align:left;
	vertical-align:middle;
	border:.5pt solid windowtext;
	mso-background-source:auto;
	mso-pattern:auto;
	white-space:normal;}
.xl7518935
	{padding-top:1px;
	padding-right:1px;
	padding-left:1px;
	mso-ignore:padding;
	color:blue;
	font-size:10.0pt;
	font-weight:400;
	font-style:normal;
	text-decoration:underline;
	text-underline-style:single;
	font-family:Arial;
	mso-generic-font-family:auto;
	mso-font-charset:0;
	mso-number-format:"\@";
	text-align:left;
	vertical-align:middle;
	border:.5pt solid windowtext;
	mso-background-source:auto;
	mso-pattern:auto;
	white-space:normal;}
.xl7618935
	{padding-top:1px;
	padding-right:1px;
	padding-left:1px;
	mso-ignore:padding;
	color:windowtext;
	font-size:12.0pt;
	font-weight:700;
	font-style:normal;
	text-decoration:none;
	font-family:"Times New Roman", serif;
	mso-font-charset:0;
	mso-number-format:General;
	text-align:left;
	vertical-align:middle;
	border-top:.5pt solid windowtext;
	border-right:none;
	border-bottom:.5pt solid windowtext;
	border-left:.5pt solid windowtext;
	mso-background-source:auto;
	mso-pattern:auto;
	white-space:normal;}
.xl7718935
	{padding-top:1px;
	padding-right:1px;
	padding-left:1px;
	mso-ignore:padding;
	color:windowtext;
	font-size:12.0pt;
	font-weight:700;
	font-style:normal;
	text-decoration:none;
	font-family:"Times New Roman", serif;
	mso-font-charset:0;
	mso-number-format:General;
	text-align:left;
	vertical-align:middle;
	border-top:.5pt solid windowtext;
	border-right:none;
	border-bottom:.5pt solid windowtext;
	border-left:none;
	mso-background-source:auto;
	mso-pattern:auto;
	white-space:normal;}
.xl7818935
	{padding-top:1px;
	padding-right:1px;
	padding-left:1px;
	mso-ignore:padding;
	color:windowtext;
	font-size:12.0pt;
	font-weight:700;
	font-style:normal;
	text-decoration:none;
	font-family:"Times New Roman", serif;
	mso-font-charset:0;
	mso-number-format:General;
	text-align:left;
	vertical-align:middle;
	border-top:.5pt solid windowtext;
	border-right:.5pt solid windowtext;
	border-bottom:.5pt solid windowtext;
	border-left:none;
	mso-background-source:auto;
	mso-pattern:auto;
	white-space:normal;}
-->
</style>
</head>

<body>
<!--[if !excel]>&nbsp;&nbsp;<![endif]-->
<!--The following information was generated by Microsoft Excel's Publish as Web
Page wizard.-->
<!--If the same item is republished from Excel, all information between the DIV
tags will be replaced.-->
<!----------------------------->
<!--START OF OUTPUT FROM EXCEL PUBLISH AS WEB PAGE WIZARD -->
<!----------------------------->

<div id="abc_18935" align=center x:publishsource="Excel">

<table border=0 cellpadding=0 cellspacing=0 width=1388 class=xl6518935
 style='border-collapse:collapse;table-layout:fixed;width:1043pt'>
 <col class=xl6518935 width=66 style='mso-width-source:userset;mso-width-alt:
 2413;width:50pt'>
 <col class=xl6518935 width=261 style='mso-width-source:userset;mso-width-alt:
 9545;width:196pt'>
 <col class=xl6518935 width=197 style='mso-width-source:userset;mso-width-alt:
 7204;width:148pt'>
 <col class=xl6518935 width=177 style='mso-width-source:userset;mso-width-alt:
 6473;width:133pt'>
 <col class=xl6518935 width=242 style='mso-width-source:userset;mso-width-alt:
 8850;width:182pt'>
 <col class=xl6518935 width=125 style='mso-width-source:userset;mso-width-alt:
 4571;width:94pt'>
 <col class=xl6518935 width=64 span=5 style='width:48pt'>
 <tr height=21 style='height:15.75pt'>
  <td colspan=2 height=21 class=xl6918935 width=327 style='height:15.75pt;
  width:246pt'><a name="RANGE!A1:E9"><?=$this->config->sys_info->unit?></a></td>
  <td class=xl6518935 width=197 style='width:148pt'></td>
  <td colspan=2 class=xl7018935 width=419 style='width:315pt'>CỘNG HÒA XÃ HỘI
  CHỦ NGHĨA VIỆT NAM</td>
  <td class=xl6518935 width=125 style='width:94pt'></td>
  <td class=xl6518935 width=64 style='width:48pt'></td>
  <td class=xl6518935 width=64 style='width:48pt'></td>
  <td class=xl6518935 width=64 style='width:48pt'></td>
  <td class=xl6518935 width=64 style='width:48pt'></td>
  <td class=xl6518935 width=64 style='width:48pt'></td>
 </tr>
 <tr height=21 style='height:15.75pt'>
  <td colspan=2 height=21 class=xl7018935 style='height:15.75pt'><?=$this->config->sys_info->company?></td>
  <td class=xl6618935></td>
  <td colspan=2 class=xl7118935>Ðộc lập - Tự do - Hạnh phúc</td>
  <td class=xl6518935></td>
  <td class=xl6518935></td>
  <td class=xl6518935></td>
  <td class=xl6518935></td>
  <td class=xl6518935></td>
  <td class=xl6518935></td>
 </tr>
 <tr height=21 style='height:15.75pt'>
  <td height=21 class=xl6518935 style='height:15.75pt'></td>
  <td class=xl6518935></td>
  <td class=xl6518935></td>
  <td colspan=2 class=xl7218935><?=$this->config->sys_info->city?>, ngày <?=date('d')?> tháng <?=date('m')?> năm <?=date('Y')?></td>
  <td class=xl6518935></td>
  <td class=xl6518935></td>
  <td class=xl6518935></td>
  <td class=xl6518935></td>
  <td class=xl6518935></td>
  <td class=xl6518935></td>
 </tr>
 <tr height=21 style='height:15.75pt'>
  <td height=21 class=xl6518935 style='height:15.75pt'></td>
  <td class=xl6518935></td>
  <td class=xl6518935></td>
  <td class=xl6518935></td>
  <td class=xl6518935></td>
  <td class=xl6518935></td>
  <td class=xl6518935></td>
  <td class=xl6518935></td>
  <td class=xl6518935></td>
  <td class=xl6518935></td>
  <td class=xl6518935></td>
 </tr>
 <tr height=21 style='height:15.75pt'>
  <td colspan=5 height=21 class=xl7018935 style='height:15.75pt'>DANH BẠ ĐIỆN
  THOẠI NỘI BỘ</td>
  <td class=xl6518935></td>
  <td class=xl6518935></td>
  <td class=xl6518935></td>
  <td class=xl6518935></td>
  <td class=xl6518935></td>
  <td class=xl6518935></td>
 </tr>
 <tr height=21 style='height:15.75pt'>
  <td height=21 class=xl6518935 style='height:15.75pt'></td>
  <td class=xl6518935></td>
  <td class=xl6518935></td>
  <td class=xl6518935></td>
  <td class=xl6518935></td>
  <td class=xl6518935></td>
  <td class=xl6518935></td>
  <td class=xl6518935></td>
  <td class=xl6518935></td>
  <td class=xl6518935></td>
  <td class=xl6518935></td>
 </tr>
 <tr height=21 style='height:15.75pt'>
  <td height=21 class=xl6818935 width=66 style='height:15.75pt;width:50pt'>STT</td>
  <td class=xl6818935 width=261 style='border-left:none;width:196pt'>HỌ VÀ TÊN</td>
  <td class=xl6818935 width=197 style='border-left:none;width:148pt'>CHỨC DANH</td>
  <td class=xl6818935 width=177 style='border-left:none;width:133pt'>ĐIỆN THOẠI</td>
  <td class=xl6818935 width=242 style='border-left:none;width:182pt'>EMAIL</td>
  <td class=xl6518935></td>
  <td class=xl6518935></td>
  <td class=xl6518935></td>
  <td class=xl6518935></td>
  <td class=xl6518935></td>
  <td class=xl6518935></td>
 </tr>
  <?php 
 $tenpb='';
 for($i=0;$i<count($this->data);$i++)
    {
		if($this->data[$i]['DEPNAME']!=$tenpb)
       {
	?>
 <tr height=21 style='height:15.75pt'>
  <td colspan=5 height=21 class=xl7618935 width=943 style='border-right:.5pt solid black;
  height:15.75pt;width:709pt'><?=$this->data[$i]['DEPNAME']?></td>
  <td class=xl6518935></td>
  <td class=xl6518935></td>
  <td class=xl6518935></td>
  <td class=xl6518935></td>
  <td class=xl6518935></td>
  <td class=xl6518935></td>
 </tr>
<?php } ?>
 <tr height=21 style='height:15.75pt'>
  <td height=21 class=xl7318935 width=66 style='height:15.75pt;border-top:none;
  width:50pt'><?php echo $i+1; ?></td>
  <td class=xl7418935 width=261 style='border-top:none;border-left:none;
  width:196pt'><?php echo $this->data[$i]['FIRSTNAME'].' '.$this->data[$i]['LASTNAME'] ?></td>
  <td class=xl7418935 width=197 style='border-top:none;border-left:none;
  width:148pt'><?php if($this->data[$i]['NAME']== '') echo ' '; else echo $this->data[$i]['NAME'] ?></td>
  <td class=xl7418935 width=177 style='border-top:none;border-left:none;
  width:133pt'><?php if($this->data[$i]['PHONE']== '') echo ' '; else echo $this->data[$i]['PHONE']  ?></td>
  <td class=xl7518935 width=242 style='border-top:none;border-left:none;
  width:182pt'><a href="mailto:anv@unitech.vn" target="_parent"><?php if($this->data[$i]['EMAIL']== '') echo ' '; else echo $this->data[$i]['EMAIL'] ?></a></td>
  <td class=xl6518935></td>
  <td class=xl6518935></td>
  <td class=xl6518935></td>
  <td class=xl6518935></td>
  <td class=xl6518935></td>
  <td class=xl6518935></td>
 </tr>
 <?php
$tenpb=$this->data[$i]['DEPNAME']; 
 } ?>
 <tr height=21 style='height:15.75pt'>
  <td height=21 class=xl6518935 style='height:15.75pt'></td>
  <td class=xl6518935></td>
  <td class=xl6518935></td>
  <td class=xl6518935></td>
  <td class=xl6518935></td>
  <td class=xl6518935></td>
  <td class=xl6518935></td>
  <td class=xl6518935></td>
  <td class=xl6518935></td>
  <td class=xl6518935></td>
  <td class=xl6518935></td>
 </tr>
 <tr height=21 style='height:15.75pt'>
  <td height=21 class=xl6518935 style='height:15.75pt'></td>
  <td class=xl6518935></td>
  <td class=xl6518935></td>
  <td class=xl6518935></td>
  <td class=xl6518935></td>
  <td class=xl6518935></td>
  <td class=xl6518935></td>
  <td class=xl6518935></td>
  <td class=xl6518935></td>
  <td class=xl6518935></td>
  <td class=xl6518935></td>
 </tr>
 <tr height=21 style='height:15.75pt'>
  <td height=21 class=xl6518935 style='height:15.75pt'></td>
  <td class=xl6518935></td>
  <td class=xl6518935></td>
  <td class=xl6518935></td>
  <td class=xl6518935></td>
  <td class=xl6518935></td>
  <td class=xl6518935></td>
  <td class=xl6518935></td>
  <td class=xl6518935></td>
  <td class=xl6518935></td>
  <td class=xl6518935></td>
 </tr>
 <tr height=21 style='height:15.75pt'>
  <td height=21 class=xl6518935 style='height:15.75pt'></td>
  <td class=xl6518935></td>
  <td class=xl6518935></td>
  <td class=xl6518935></td>
  <td class=xl6618935></td>
  <td class=xl6718935></td>
  <td class=xl6718935></td>
  <td class=xl6718935></td>
  <td class=xl6718935></td>
  <td class=xl6718935></td>
  <td class=xl6718935></td>
 </tr>
 <![if supportMisalignedColumns]>
 <tr height=0 style='display:none'>
  <td width=66 style='width:50pt'></td>
  <td width=261 style='width:196pt'></td>
  <td width=197 style='width:148pt'></td>
  <td width=177 style='width:133pt'></td>
  <td width=242 style='width:182pt'></td>
  <td width=125 style='width:94pt'></td>
  <td width=64 style='width:48pt'></td>
  <td width=64 style='width:48pt'></td>
  <td width=64 style='width:48pt'></td>
  <td width=64 style='width:48pt'></td>
  <td width=64 style='width:48pt'></td>
 </tr>
 <![endif]>
</table>

</div>


<!----------------------------->
<!--END OF OUTPUT FROM EXCEL PUBLISH AS WEB PAGE WIZARD-->
<!----------------------------->
</body>

</html>
